### ISSUE TITLE
Author Avatar Doesn't Work On Buddypress Pages

### ISSUE THREAD

**Issue by zachkinsey** [elementor/elementor#8740]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor Author Avatar doesn't work on Buddypress generated pages.

Here's an example of an Elementor Image widget within an Elementor header template using the 'dynamic' feature to pull in the author avatar, but it's not showing on the buddypress generated page and only shows a default avatar/gravatar: http://prntscr.com/ompa80

Here's an example of an Elementor widget within Elementor an Elementor header template using the 'dynamic' feature to pull in the author avatar, and it's showing on the Elementor generated page: http://prntscr.com/ompaq9

## Steps to reproduce
- Create an Elementor header template 
- Add an image widget to the header and use the 'dynamic' feature to pull in the author avatar.
- Save the header so that it's across your entire site and shows only for logged in people.
- Go to a Buddypress generated page and release your avatar isn't showing and only some default one is and be sad.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: mariadb.org binary distribution v10.3.16
	PHP Version: 7.3.6-1+0~20190531112546.39+jessie~1.gbp6131b7
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://gaming.klefka.com
	Home URL: https://gaming.klefka.com
	WP Multisite: Yes
	Max Upload Size: 8 MB
	Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Tom Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.3.2
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Admin Columns Pro - Toolset Types
		Version: 1.5.2
		Author: Admin Columns

	Admin Columns Pro - WooCommerce
		Version: 3.3.3
		Author: Admin Columns

	Admin Menu Editor Pro
		Version: 2.9
		Author: Janis Elsts

	AffiliateWP
		Version: 2.3
		Author: Sandhills Development, LLC

	AffiliateWP - Affiliate Area Shortcodes
		Version: 1.1.7
		Author: AffiliateWP, LLC

	AffiliateWP - Affiliate Landing Pages
		Version: 1.0.2
		Author: AffiliateWP, LLC

	AffiliateWP - Leaderboard
		Version: 1.0.2
		Author: Pippin Williamson and Andrew Munro

	AffiliateWP - Lifetime Commissions
		Version: 1.3.2
		Author: AffiliateWP

	AffiliateWP - Pushover Notifications
		Version: 1.0.2
		Author: Chris Klosowski

	AffiliateWP - REST API Extended
		Version: 1.0.4
		Author: AffiliateWP, LLC

	AffiliateWP - Zapier - Automated Tasks
		Version: 1.1.2
		Author: AffiliateWP

	AffiliateWP Affiliate Sign Up Products
		Version: 1.0.1
		Author: Christian Freeman

	AffiliateWP MLM
		Version: 1.1.2
		Author: Christian Freeman

	AffiliateWP Performance Bonuses
		Version: 1.0.4
		Author: Christian Freeman

	AffiliateWP Ranks
		Version: 1.0.3
		Author: Christian Freeman

	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	Autoptimize CriticalCSS.com Power-Up
		Version: 1.16.0
		Author: Deny Dias & Optimizing Matters

	BuddyPress
		Version: 4.4.0
		Author: The BuddyPress Community

	Cache Enabler
		Version: 1.3.4
		Author: KeyCDN

	Code Snippets
		Version: 2.13.3
		Author: Shea Bunge

	Custom Affiliate Addon
		Version: 1.0.5
		Author: wp-developer

	Duplicate Post
		Version: 3.2.3
		Author: Enrico Battocchi

	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Forms
		Version: 1.8.2
		Author: Elementor Forms

	Elementor Pro
		Version: 2.6.1
		Author: Elementor.com

	Essential Addons for Elementor - Pro
		Version: 2.15.0
		Author: WPDeveloper

	Intuitive Custom Post Order
		Version: 3.1.2
		Author: hijiri

	Network Subsite User Registration
		Version: 2.6
		Author: Justin Fletcher

	Really Simple SSL
		Version: 3.2.2
		Author: Rogier Lankhorst, Mark Wolters

	Really Simple SSL pro multisite
		Version: 2.0.22
		Author: Rogier Lankhorst

	Redux Vendor Support
		Version: 1.0.1
		Author: Team Redux

	Remove Email Verification
		Version: 2.4.1
		Author: WPMU DEV

	ShortPixel Image Optimizer
		Version: 4.14.1
		Author: ShortPixel

	ShortyWP
		Version: 3.0.1
		Author: Shorty

	The SEO Framework
		Version: 3.2.4
		Author: Sybre Waaijer

	The SEO Framework - Extension Manager
		Version: 2.0.4
		Author: Sybre Waaijer

	User Upgrade Capability
		Version: 2.4
		Author: Justin Fletcher

	Wicked Folders Pro
		Version: 2.15.2
		Author: Wicked Plugins

	WooCommerce Subscriptions
		Version: 2.2.18
		Author: Prospress Inc.

	WordPress Toolbar Editor
		Version: 1.3
		Author: Janis Elsts

	WP-Optimize Premium - Clean, Compress, Cache
		Version: 3.0.7
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP E-Signature
		Version: 1.5.4.8
		Author: Approve Me

	WP E-Signature - WooCommerce
		Version: 1.5.4.7
		Author: Approve Me

	WP E-Signature Business add-ons
		Version: 1.5.4.7
		Author: Approve Me

	WP Fusion
		Version: 3.24.6
		Author: Very Good Plugins

	WP Offload SES Lite
		Version: 1.2
		Author: Delicious Brains

	Youzer
		Version: 2.3.3
		Author: Youssef Kaine

	Youzer - Activity Reactions
		Version: 1.0.3
		Author: Youssef Kaine

	Youzer - Edit Activity
		Version: 1.0.2
		Author: Youssef Kaine

	Youzer - Profile Completeness
		Version: 1.0.2
		Author: Youssef Kaine

== Network Plugins ==
	Admin Columns Pro
		Version: 4.6.3
		Author: AdminColumns.com

	Admin Columns Pro - BuddyPress
		Version: 1.4
		Author: Admin Columns

	Admin Columns Pro - WooCommerce
		Version: 3.3.3
		Author: Admin Columns

	Admin Menu Editor Pro
		Version: 2.9
		Author: Janis Elsts

	Alter - White Label Wordpress
		Version: 2.3.9
		Author: AcmeeDesign

	Async JavaScript
		Version: 2.19.07.14
		Author: Frank Goossens (futtta)

	Autoptimize CriticalCSS.com Power-Up
		Version: 1.16.0
		Author: Deny Dias & Optimizing Matters

	BP Multi Network
		Version: 1.0.1
		Author: Brajesh Singh

	Duplicate Post
		Version: 3.2.3
		Author: Enrico Battocchi

	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Enable Media Replace
		Version: 3.3.4
		Author: ShortPixel

	Envato Market
		Version: 2.0.1
		Author: Envato

	Insert Headers and Footers
		Version: 1.4.4
		Author: WPBeginner

	Intuitive Custom Post Order
		Version: 3.1.2
		Author: hijiri

	LearnDash Course Grid
		Version: 1.5.5
		Author: LearnDash

	LearnDash LMS
		Version: 3.0.6.1
		Author: LearnDash

	LearnDash WooCommerce Integration
		Version: 1.5.0
		Author: LearnDash

	Network Subsite User Registration
		Version: 2.6
		Author: Justin Fletcher

	Really Simple SSL
		Version: 3.2.2
		Author: Rogier Lankhorst, Mark Wolters

	Really Simple SSL pro multisite
		Version: 2.0.22
		Author: Rogier Lankhorst

	Redis Object Cache
		Version: 1.4.3
		Author: Till Krüss

	Redux Vendor Support
		Version: 1.0.1
		Author: Team Redux

	Remove Email Verification
		Version: 2.4.1
		Author: WPMU DEV

	ShortPixel Image Optimizer
		Version: 4.14.1
		Author: ShortPixel

	The SEO Framework
		Version: 3.2.4
		Author: Sybre Waaijer

	The SEO Framework - Extension Manager
		Version: 2.0.4
		Author: Sybre Waaijer

	UpdraftPlus - Backup/Restore
		Version: 2.16.16.24
		Author: UpdraftPlus.Com, DavidAnderson

	User Upgrade Capability
		Version: 2.4
		Author: Justin Fletcher

	Wicked Folders Pro
		Version: 2.15.2
		Author: Wicked Plugins

	WooCommerce
		Version: 3.6.5
		Author: Automattic

	WordPress Toolbar Editor
		Version: 1.3
		Author: Janis Elsts

	WP-Optimize Premium - Clean, Compress, Cache
		Version: 3.0.7
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Fusion
		Version: 3.24.6
		Author: Very Good Plugins

	WP Offload Media
		Version: 2.2.1
		Author: Delicious Brains

	WP Offload SES Lite
		Version: 1.2
		Author: Delicious Brains

	WP Ultimo
		Version: 1.9.11
		Author: Arindo Duque - NextPress

	Youzer - Profile Completeness
		Version: 1.0.2
		Author: Youssef Kaine

== Must-Use Plugins ==
	functions.php
		Version: 
		Author: 

	Plugin Organizer MU
		Version: 9.6.4
		Author: Jeff Sterup

== Log ==
	: 
PHP: showing 16 of 16PHP: 2019-06-05 04:10:52 [notice X 1720][/home/digit546/public_html/wp-content/plugins/elementor-pro/classes/utils.php::235] Trying to get property of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-09 04:00:12 [error X 148][/home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php::94] Uncaught Error: Call to a member function has_session() on null in /home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php:94
Stack trace:
#0 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): ef_force_non_logged_user_wc_session('')
#1 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/digit546/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(555): do_action('woocommerce_ini...')
#4 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#5 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home/digit546/public_html/wp-settings.php(525): do_action('init')
#8 /home/digit546/public_html/wp-config.php(142): require_once('/home/digit546/...')
#9 /home [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-09 09:16:24 [notice X 4][/home/digit546/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::130] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-12 05:00:12 [error X 1][/home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php::94] Uncaught Error: Call to a member function has_session() on null in /home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php:94
Stack trace:
#0 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): ef_force_non_logged_user_wc_session('')
#1 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/digit546/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(555): do_action('woocommerce_ini...')
#4 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#5 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home/digit546/public_html/wp-settings.php(525): do_action('init')
#8 /home/digit546/public_html/wp-config.php(144): require_once('/home/digit546/...')
#9 /home [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-12 05:30:11 [error X 27][/home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php::94] Uncaught Error: Call to a member function has_session() on null in /home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php:94
Stack trace:
#0 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): ef_force_non_logged_user_wc_session('')
#1 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/digit546/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(555): do_action('woocommerce_ini...')
#4 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#5 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home/digit546/public_html/wp-settings.php(525): do_action('init')
#8 /home/digit546/public_html/wp-config.php(146): require_once('/home/digit546/...')
#9 /home [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-12 19:00:16 [error X 5][/home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php::94] Uncaught Error: Call to a member function has_session() on null in /home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php:94
Stack trace:
#0 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): ef_force_non_logged_user_wc_session('')
#1 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/digit546/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(555): do_action('woocommerce_ini...')
#4 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#5 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home/digit546/public_html/wp-settings.php(525): do_action('init')
#8 /home/digit546/public_html/wp-config.php(148): require_once('/home/digit546/...')
#9 /home [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-12 21:30:12 [error X 1051][/home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php::94] Uncaught Error: Call to a member function has_session() on null in /home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php:94
Stack trace:
#0 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): ef_force_non_logged_user_wc_session('')
#1 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/digit546/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(555): do_action('woocommerce_ini...')
#4 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#5 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home/digit546/public_html/wp-settings.php(525): do_action('init')
#8 /home/digit546/public_html/wp-config.php(151): require_once('/home/digit546/...')
#9 /home [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-15 03:54:09 [notice X 1][/home/digit546/public_html/wp-content/plugins/elementor/includes/elements/column.php::1071] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-04 19:30:28 [error X 1150][/home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php::94] Uncaught Error: Call to a member function has_session() on null in /home/digit546/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php:94
Stack trace:
#0 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): ef_force_non_logged_user_wc_session('')
#1 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/digit546/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(557): do_action('woocommerce_ini...')
#4 /home/digit546/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#5 /home/digit546/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/digit546/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home/digit546/public_html/wp-settings.php(525): do_action('init')
#8 /home/digit546/public_html/wp-config.php(151): require_once('/home/digit546/...')
#9 /home [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-12 04:23:08 [warning X 1][/home/digit546/public_html/wp-content/plugins/elementor/core/files/manager.php::101] unlink(/home/digit546/public_html/wp-content/uploads/sites/35/elementor/css/post-96.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-12 04:23:34 [warning X 1][/home/digit546/public_html/wp-content/plugins/elementor/core/files/manager.php::101] unlink(/home/digit546/public_html/wp-content/uploads/sites/35/elementor/css/post-98.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-12 04:27:11 [notice X 405][/home/digit546/public_html/wp-content/plugins/elementor/includes/widgets/accordion.php::505] Undefined index: icon_active [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-23 18:49:47 [notice X 363][/home/digit546/public_html/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::1248] Undefined index: button_icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-27 10:30:12 [error X 20][/home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php::94] Uncaught Error: Call to a member function has_session() on null in /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-content/plugins/elementor-forms/inc/woocommerce.php:94
Stack trace:
#0 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/class-wp-hook.php(286): ef_force_non_logged_user_wc_session('')
#1 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(557): do_action('woocommerce_ini...')
#4 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#5 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-29 01:55:22 [notice X 14][/home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-content/plugins/elementor-pro/classes/utils.php::226] Trying to get property 'post_author' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-31 01:44:11 [error X 1][/home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-content/plugins/elementor/includes/plugin.php::562] Uncaught Error: Class 'Elementor\Maintenance_Mode' not found in /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-content/plugins/elementor/includes/plugin.php:562
Stack trace:
#0 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-content/plugins/elementor/includes/plugin.php(479): Elementor\Plugin->init_components()
#1 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/class-wp-hook.php(286): Elementor\Plugin->init('')
#2 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-settings.php(525): do_action('init')
#5 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-config.php(160): require_once('/home/305750.cl...')
#6 /home/305750.cloudwaysapps.com/kfsbwfsbgy/public_html/wp-load.php(37): require_once('/home/305750.cl...')
#7 /home/3057 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2019-06-21 19:45:12 [error X 1][https://gaming.klefka.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:83489] Cannot set property \'controls\' of undefined 
JS: 2019-06-21 22:58:35 [error X 2][https://gaming.klefka.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:53511] Cannot read property \'noUiSlider\' of undefined 
JS: 2019-07-26 05:33:18 [error X 2][https://gaming.klefka.com/wp-content/plugins/essential-addons-elementor/assets/js/eael-scripts.js?ver=1.0:2823:26] Cannot read property \'hasOwnProperty\' of undefined 
JS: 2019-07-31 10:21:05 [error X 6][https://gaming.klefka.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.6:7:50661] Blocked a frame with origin \"https://gaming.klefka.com\" from accessing a cross-origin frame. 

Log: showing 15 of 152019-07-04 19:28:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.9',
  'to' => '2.5.11',
)]
2019-07-12 04:23:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-12 04:23:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.11',
  'to' => '2.5.13',
)]
2019-07-12 04:23:08 [info] elementor::elementor_updater Started 
2019-07-12 04:23:08 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-12 04:23:08 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-12 04:23:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-23 18:42:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.1',
  'to' => '2.6.6',
)]
2019-07-23 18:42:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.13',
  'to' => '2.6.0',
)]
2019-07-23 18:42:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.13',
  'to' => '2.6.0',
)]
2019-07-23 18:42:08 [info] elementor::elementor_updater Started 
2019-07-23 18:42:08 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-23 18:42:11 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-23 18:42:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.1',
  'to' => '2.6.6',
)]
2019-07-25 01:53:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.0',
  'to' => '2.6.1',
)]

**Comment by shilo-ey** [comment]
Hi @zachkinsey 


In v2.7 Pro we will add user dynamics to allow this feature.

Thanks

**Comment by zachkinsey** [comment]
Awesome!

Can't wait ^_^

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!
