### ISSUE TITLE
Repeater not refresh when Delete item then Undo

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#8743]
Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Hello team, 
I want to report a bug with Repeater control. [http://prntscr.com/omv0gh](http://prntscr.com/omv0gh)

## Steps to reproduce
1: Create a page & add "Icon List" widget.
2: Delete any list item.
3: Press command + Z

Then undo action, deteted item is back on preview but in panel it not showing.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.7

Feel free to update

Thanks!
