### ISSUE TITLE
Elementor PRO posts add category post

### ISSUE THREAD

**Issue by franzeweb** [elementor/elementor#8747]
Hi I use elementor pro posts function to show the last posts.

I like do add after read more button a string with che category post,

![franz](https://user-images.githubusercontent.com/12543609/62298045-87da1a80-b472-11e9-9853-5aa481aed50c.JPG)

I add the following code in  elementor-pro/modules/posts/skins/skin-base.php

```
protected function render_read_more() {
		if ( ! $this->get_instance_value( 'show_read_more' ) ) {
			return;
		}

		?>
			<a class="elementor-post__read-more" href="<?php echo $this->current_permalink; ?>">
				<?php echo $this->get_instance_value( 'read_more_text' ); ?>
			</a>
			<br/>
		<?php

		// START UPGRADE 
		$current_post_id = get_the_ID(); 
		$categories = wp_get_post_categories($current_post_id);
		$current_id_category = $categories[0];
		$current_link_category = get_category_link($current_id_category);
		$current_color_category = get_term_meta($current_id_category, 'cc_color', true);
		echo "<a class='button_category_hp' href='".$current_link_category."'>";
		echo "<h3 class='category_post_hp' style='background-color:".$current_color_category."'>".get_cat_name($current_id_category)."</h3>";
		echo "</a>"; 
		// STOP UPGRADE

	}
```

How can I insert this code in a different way that will not be lose when the plugin will be updated?

I try to create the same structure with the new file in child template folder

wp-content/themes/hello-theme-child-master/elementor-pro/modules/posts/skins/skin-base.php 

but it doesn't work!!!

Any idea?

**Comment by shilo-ey** [comment]
Hi @franzeweb 

You should use [the proper hook](https://code.elementor.com/hooks/elementor-frontend-element_type-after_render/
) to add your code after the widget has been registered:

```PHP
add_action( 'elementor/frontend/widget/after_render', function( $widget ) {
	if ( 'posts' !== $widget->get_name() ) {
		return;
	}
	// do your stuff after the widget has been rendered.
});
```
