### ISSUE TITLE
Custom Taxonomy Archives are Blank

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8752]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Archives created for custom taxonomies are blank. 

## Steps to reproduce

1. Use Toolset to create a custom post type. 
2. Create a Taxonomy to be used with the custom post type
3. Using the elementor Theme builder, create a new Archive page. 
4. Set the display conditions to include the taxonomy you just created.

Design a layout including an archive title and the archive posts widget. 
Even enter some non-dynamic elements such as a fixed header (not dynamic) and some other elements. 

Try to view a sample term within the taxonomy you just created: Elementor will display a blank page. 

Note: I am aware of the Elementor and Views conflict, so there is no archive set within views. Everything is set up to rely on Elementor. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: 
	Home URL: 
	WP Multisite: Yes
	Max Upload Size: 15 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name:Elementor Hello
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.0.5
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	CAOS for Analytics
		Version: 2.3.5
		Author: Daan van den Bergh

	Elementor
		Version: 2.6.7
		Author: Elementor.com

	Elementor Extras
		Version: 2.1.5
		Author: Namogo

	Elementor Pro
		Version: 2.6.2
		Author: Elementor.com

	Format Price
		Version: 1.0
		Author: TD Labs Ltd.

	Gravity Fieldset for Gravity Forms
		Version: 0.2.1
		Author: Bas van den Wijngaard & Harro Heijboer

	Post Types Order
		Version: 1.9.4.1
		Author: Nsp Code

	Premium Addons for Elementor
		Version: 3.6.1
		Author: Leap13

	Premium Addons PRO
		Version: 1.6.1
		Author: Leap13

	RealtyPress Premium
		Version: 1.7.2
		Author: RealtyPress Team

	Schema Pro
		Version: 1.3.0
		Author: Brainstorm Force

	SEOPress
		Version: 3.6.1.1
		Author: Benjamin Denis

	SEOPress PRO
		Version: 3.6.1.1
		Author: Benjamin Denis

	Slider Revolution
		Version: 5.4.8.3
		Author: ThemePunch

	Toolset Maps
		Version: 1.8.3
		Author: OnTheGoSystems

	Toolset Types
		Version: 3.3.4
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.9.1
		Author: OnTheGoSystems

	Ultimate Addons for Elementor
		Version: 1.15.0
		Author: Brainstorm Force

== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.9
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 7.3
		Author: ServMask

	All-in-One WP Migration Google Drive Extension
		Version: 2.54
		Author: ServMask

	All-in-One WP Migration Multisite Extension
		Version: 3.76
		Author: ServMask

	Cache Enabler
		Version: 1.3.4
		Author: KeyCDN

	Compress JPEG & PNG images
		Version: 3.2.0
		Author: TinyPNG

	Gravity Forms
		Version: 2.4.11
		Author: rocketgenius

	Safe SVG
		Version: 1.9.4
		Author: Daryll Doyle

	Ultimate Branding
		Version: 2.3.0
		Author: WPMU DEV

	User Role Editor Pro
		Version: 4.51.1
		Author: Vladimir Garagulia

	Wordfence Security
		Version: 7.3.6
		Author: Wordfence

	WP-Cron Control
		Version: 0.7.1
		Author: Thorsten Ott, Erick Hitter, Automattic

	WPMU DEV Dashboard
		Version: 4.7.3.1
		Author: WPMU DEV

	WP Ultimo
		Version: 1.10.1
		Author: Arindo Duque - NextPress

== Log ==
	: 
JS: showing 5 of 5JS: 2019-07-08 18:42:27 [error X 1][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:83489] Cannot set property \&#039;controls\&#039; of undefined 
JS: 2019-07-08 22:27:24 [error X 1][/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.16:2:9579] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `uael-gf-styler` got <10> as `sticky_offset` value. Expected array or object.',
)]
JS: 2019-07-10 01:11:51 [error X 1][o/wp-admin/post.php?post=405&action=elementor:2:12] Unexpected token function 
JS: 2019-07-10 18:54:14 [error X 2][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:8507] Cannot read property \&#039;select2\&#039; of undefined 
JS: 2019-08-02 05:31:04 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view547\&quot;) has already been destroyed and cannot be used. 

PHP: showing 2 of 2PHP: 2019-07-08 17:22:47 [notice X 27][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Undefined index: top [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-02 00:24:59 [warning X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/manager.php::101] unlink(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/sites/39/elementor/css/post-545.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102019-08-02 00:24:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Webtemple',
  'from' => '2.5.16',
  'to' => '2.6.7',
)]
2019-08-02 00:24:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.11',
  'to' => '2.6.2',
)]
2019-08-02 00:25:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.11',
  'to' => '2.6.2',
)]
2019-08-02 00:25:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.11',
  'to' => '2.6.2',
)]
2019-08-02 00:25:35 [info] elementor::elementor_updater Started 
2019-08-02 00:25:35 [info] Page Builder/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-08-02 00:25:35 [info] Page Builder/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-08-02 00:25:35 [info] Page Builder/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-08-02 00:25:35 [info] Page Builder/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-08-02 00:25:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.5.16',
  'to' => '2.6.7',
)]

</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by taropaa** [comment]
Update:
The preview shows the correct posts for the query (as set under preview), but the live taxonomy archive page shows the "It seems we can't find what you're looking for." message.

**Comment by taropaa** [comment]
Issue was not elementor related.

When using Archives with Toolset Views you need to make sure that:

1. You do not have an existing Toolset Archive page defined for the term or taxonomy
2. You do not have a Content Template defined for the Custom Post Type to which the taxonomy belongs.

I was aware of #1 but not #2.

**Comment by mattpramschufer** [comment]
Is there any follow up on this?  I am running into the same issue.  You have to be able to create a custom taxonomy archive template AND a custom post type archive template at the same time?  For instance.  I have CPT Books.  Then I have a custom taxonomy called Book Author.  Those two archives will be completely different in terms of design/layout.
