### ISSUE TITLE
Icon Widget - Rotate not working in Tablet & Mobile views

### ISSUE THREAD

**Issue by papplebee** [elementor/elementor#8753]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using an Icon widget, rotating the icon in the editor 'Style' tab does not work in **Tablet** and **Mobile** views. 

The following screenshot shows that the 'rotate' slider is only allowing values from 0 to 100, when it should actually be 0 to 360: [https://prnt.sc/ondiqm](https://prnt.sc/ondiqm)

Also, another screenshot shows that the CSS is being output as pixels, rather than degrees, which obviously isn't correct: [https://prntscr.com/ond9lr](https://prntscr.com/ond9lr).

## Steps to reproduce

- Edit a page with Elementor
- Add an Icon widget to the page
- Choose the icon
- Switch to Tablet or Mobile view
- Attempt to rotate the icon

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.10 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0
	MySQL version: MySQL Community Server (GPL) v5.7.23
	PHP Version: 7.2.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://pineapplewebdesign.wp.localhost
	Home URL: http://pineapplewebdesign.wp.localhost
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Disable Gutenberg
		Version: 1.8.1
		Author: Jeff Starr

	Elementor
		Version: 2.6.7
		Author: Elementor.com

	Elementor Contact Form DB
		Version: 1.4
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 2.6.2
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 1.9.4
		Author: Flexible-Elementor-Panel.com

	GDPR Cookie Compliance
		Version: 2.1.3
		Author: Moove Agency

	Health Check & Troubleshooting
		Version: 1.3.2
		Author: The WordPress.org community

	JetBlocks For Elementor
		Version: 1.1.10.1
		Author: Zemez

	JetElements For Elementor
		Version: 1.15.16
		Author: Zemez

	JetEngine
		Version: 1.4.8
		Author: Zemez

	JetMenu
		Version: 1.5.14
		Author: Zemez

	JetThemeCore
		Version: 1.1.12
		Author: Zemez

	JetTricks
		Version: 1.2.0
		Author: Zemez

	Premium Addons for Elementor
		Version: 3.6.1
		Author: Leap13

	Smart Slider 3
		Version: 3.3.21
		Author: Nextend

	The GDPR Framework
		Version: 1.0.32
		Author: Data443

	Ultimate Addons for Elementor
		Version: 1.14.0
		Author: Brainstorm Force

	Update Theme and Plugins from Zip File
		Version: 1.1.0
		Author: Jeff Sherk

	Webcraftic Disable Admin Notices Individually
		Version: 1.0.6
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	WP-Optimize - Clean, Compress, Cache
		Version: 3.0.10
		Author: David Anderson, Ruhani Rabin, Team Updraft

== Log ==
	: 
JS: showing 1 of 1JS: 2019-07-30 12:18:37 [error X 18][http://pineapplewebdesign.wp.localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.6:7:19756] Cannot read property \'noUiSlider\' of undefined 

Log: showing 2 of 22019-07-30 16:30:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.6',
  'to' => '2.6.7',
)]
2019-07-30 17:22:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.1',
  'to' => '2.6.2',
)]

</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elemento v2.6.8

Feel free to update

Thanks!
