### ISSUE TITLE
Partnership with image store.

### ISSUE THREAD

**Issue by paulfewman** [elementor/elementor#8754]
Marketing / product growth suggestion.

Elementor Pro clients should have possibility to access image stores resources for free or with discount. By image store I mean services like https://stock.adobe.com or https://pixabay.com. For For me as a user of Elementor it will be handy when looking for graphics and for Elementor will get new clients or decreasing churn rate. Collaboration between Elementor and some image stores sound reasonable.

I've seen some like agreements before, f.e. Pluralsight included access to Code School and vice versa. You might have some promo codes package with 1-100% discount to be used in image store. Elementor Pro user might take it from https://my.elementor.com panel.

Your sincerely, Paul Fewman.

**Comment by Aviad-Herman** [comment]
Hi @paulfewman,
I know this ticket is old but thanks you for the suggestion.
It is something we are considering but its not in the near roadmap.
I'm closing this issue but rest assured it's documented.

Keep sharing great ideas!
Aviad
