### ISSUE TITLE
[Feature request] Prepopulate custom user meta fields from the image widget

### ISSUE THREAD

**Issue by vistol** [elementor/elementor#8758]
Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As you know Wordpress is a pain in the backside when referring to author profile pictures. I don't think Gravatar has been a great success. Also, the Wordpress profile picture system is just simply not as flexible as having your own profile picture by adding a new custom user field.  

**Describe the solution you'd like**
I want to be able to drag and drop an image widget from Elementor and, using the Dynamic Content panel, display my custom user field which is basically a profile picture.

**Describe alternatives you've considered**
I've tried to achieve the same result using the Text widget, and I was able to prepopulate the URL of my custom user field, but only shows the URL string, not the actual profile image. You can see a screencast of this here: https://www.loom.com/share/609df218ed804f609fcd2e30a86b59ac

**Comment by bainternet** [comment]
@vistol 	

In Elementor Pro v2.7 we've added a new dynamic to get the user (not just author) profile picture see #7947.

With that, we cover most user profile plugins that hook into user gravatar filters.

Other than that, you can either catch the get_avatar_url filter your self or add your [own dynamic tag](https://developers.elementor.com/dynamic-tags/).

thanks.
