### ISSUE TITLE
Youtube live stream not showing

### ISSUE THREAD

**Issue by aryan5807** [elementor/elementor#8763]
I tried to embed Youtube Live Feed on my homepage, which was made with Elementor. It was working fine while editing but after publishing the changes, the stream didn't show up, there was blank space in place of the player. The stream was available only in Elementor editing window. I use browser caching, is that a problem?

**Comment by shilo-ey** [comment]
Hi @aryan5807 

We can't reproduce your issue, based on the assumption that you are using YouTube's HTML embed code - it should work fine.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
