### ISSUE TITLE
Size of SVG icon in icon list not working

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#8773]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I uploaded an SVG for my icon list. In the icon style tab, the icon size slider has no effect on the size on the icon. It only moves the text.

Same for the alignment. The Icon always stay on the left side of the text.But  I wanted the icon to be on the right side on the text.

The color and hover color works fine.

## Steps to reproduce

1. Add an icon list widget
2. Import an SVG file for the icon
3. Try to adjust the size and the alignment

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

I tried with an icon box, and in that widget, we can adjust the size of an SVG icon and the alignment (text on the left or on the right of the image)

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @vgstef 

Thanks for reporting.
From your description, it sounds like you have inline style inside your SVG files.
Please [visit our docs](https://docs.elementor.com/article/587-enable-svg-support-in-elementor) to learn more about this issue (the elementor style properties are being overridden by the inline ones).

**Comment by vgstef** [comment]
But why does the sizing works with icon box, but not with icon list? It's the same SVG file.

**Comment by shilo-ey** [comment]
Please contact our support, we can't reproduce this issue.

**Comment by Saiok** [comment]
I have the same issue with icon list's icon size. @vgstef did you solve this issue?

**Comment by batsinfotech** [comment]
I have the same issue . i find it is cause of viewbox is set 512 512 but inline css is not working. any solutions 
?

**Comment by manserlandsson** [comment]
I have the same issue, did anyone find a way to solve it?

**Comment by thinksitdo** [comment]
This is still an issue.

**Comment by juanalbertomontoya** [comment]
I have the same issue. did anyone find a way to solve it?

**Comment by thinksitdo** [comment]
Adding an explicit size to the icon in style tab fixed the issue, but elements site cache needed clearing for it to show

**Comment by hax1** [comment]
setting .elementor-icon-list-text {
width: 100% !important;
}

seems to work.
