### ISSUE TITLE
Reopen Events Calendar #7480

### ISSUE THREAD

**Issue by Brink67** [elementor/elementor#8774]
Please reopen the request Events Calendar #7480 https://github.com/elementor/elementor/issues/7480

This is not a dead issue. It is very much needed.

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by get8bit** [comment]
There is a large demand for it! You didn't even leave the thread open long enough to get feedback!

**Comment by get8bit** [comment]
What a shitty excuse for support.
