### ISSUE TITLE
Elementor Custom Positioning Mobile issue

### ISSUE THREAD

**Issue by ihaseebali** [elementor/elementor#8775]
Hi Guys,

I have just upload screenshot and describe problem.
Please take a look on screenshot.

![Screenshot_2](https://user-images.githubusercontent.com/44776647/62442229-514d1a00-b768-11e9-9532-ac5fc4dfb80c.png)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

In your case this is not an issue but natural behavior, the Position control currently is not responsive.

Thanks.
