### ISSUE TITLE
Nav menu active path

### ISSUE THREAD

**Issue by maisiam** [elementor/elementor#8777]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Actually your active menu show a different style only for the active page, not for the entire path that would me more useful. Could you change that and could you explain me how to do it right now?
**Describe the solution you'd like**
Different style for all the path of the active menu item displayed, not only for the item itself.
**Describe alternatives you've considered**

**Additional context**

**Comment by maisiam** [comment]
Until when and if you decide to implement this feature can you kindly tell me how to get to this result already now?

**Comment by shilo-ey** [comment]
Hi @maisiam 
It is unclear from your request what are you trying to achieve. can you please elaborate with concrete examples?

**Comment by maisiam** [comment]
Suppose a website with this hierarchy:


Home
Page 1
	Page 1.1
	Page 1.2
		Page 1.2.1
		Page 1.2.2
		Page 1.2.3
	Page 1.3
Page 2
Page 3
	Page 3.1
		Page 3.1.2
Page 4


Suppose the user is on the page 1.2.2. Currently Elementor allows me to highlight only the active page, not the entire path leading to the active page including the active page, in this example Page 1, Page 1.2 and page 1.2.2.

**Comment by black-eye** [comment]
In other words: highlight also the parent items of the active page.
+1

**Comment by maisiam** [comment]
Yes, all the parents.

**Comment by shimsa** [comment]
+1

**Comment by Jonathlee** [comment]
Currently I have to copy all the CSS and manually add the class name to replicate the default active style.
```
.nav-menu > .current_page_parent > a:after,
.nav-menu > .current-menu-parent > a:after,
.nav-menu > .current-page-ancestor > a:after{}

```

**Comment by shilo-ey** [comment]
Hi @maisiam 

Thanks for your feedback

Elementor uses the WordPress native `wp_nav_menu`, so you can use the hooks and filters provided to add classes as needed and then highlight the items as you wish.

not something that will be controlled via Elementor anytime soon.

thanks.
