### ISSUE TITLE
SVGs with wrong colors

### ISSUE THREAD

**Issue by filipe-q** [elementor/elementor#8779]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When I have two different SVGs that have same classes, they change their colors because of conflicting CSS rules.

## Steps to reproduce
Add any two SVGs that share CSS classes with conflicting rules.

![image](https://user-images.githubusercontent.com/40602689/62480979-20d9a000-b7a9-11e9-8728-ca321212da8b.png)

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.2.31 (Win32) DAV/2 mod_ssl/2.2.31 OpenSSL/1.0.2e mod_fcgid/2.3.9 mod_wsgi/3.4 Python/2.7.6 PHP/7.1.7 mod_perl/2.0.8 Perl/v5.16.3
	MySQL version: MySQL Community Server (GPL) v5.6.34
	PHP Version: 7.1.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://localhost:81/
	Home URL: http://localhost:81/
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive


== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.2
		Author: Elementor.com

```
</details>

**Comment by shilo-ey** [comment]
Hi @filipe-q 

We do not recommend using inline styling in SVG files due to this exact reason. this is the way SVG files and styles works. [read more here](https://docs.elementor.com/article/587-enable-svg-support-in-elementor).

Thanks!
