### ISSUE TITLE
Please change Default Facebook Icon back to the normal one

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8783]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Ever since the new Fontawesome 5 implementation, the default facebook button has been changed to the round version. Not sure what prompted this design decision, but it looks really bad and out of place. 
All other social network icons are simple. Please change the facebook icon used by social sharing and social follow widgets to the Facebook F rather than what it presently became. 

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Hi @taropaa 

Thanks for your feedback.

The change was made by FontAwesome:
v4.7:
![image](https://user-images.githubusercontent.com/45009641/62520505-6c865b00-b836-11e9-906b-12874165e819.png)

v5.9:
![image](https://user-images.githubusercontent.com/45009641/62520495-65f7e380-b836-11e9-9ef0-28cebb37e260.png)


Notice the slug of the icon: `facebook` (without `facebook-f`)

**Comment by taropaa** [comment]
Hi, @shilo-ey I don't think this is resolved. I understand that FontAwesome changed. 
What I requested here is that the elementor widget also be updated, so that visually we are using the same icon. 

The round fb icon looks awful and from a design point of view can't be used. Or, at least allow users t change the icon used based on their preference within the social share widget and social follow widget.

The reality is: 
As the user of Elementor, I did not want to change this icon for my designs, yet now the icon changed to the round version with the Fontawesome 5 upgrade. Design-wise this is not ok and it causes my design to change by itself, unless I choose to never update. 

This is an issue for 2 reasons:
1. The design changes by itself. As soon as I touch another icon on a website, I have to update to FA 5 to keep using icons. At which point that bloody round FB icon takes over. 
2. Once that happens there is no way for me to put back the original facebook icon which was now replaced and does not look like what I initially designed. 

If my initial request was not clear, I can open a new one

**Comment by shilo-ey** [comment]
We will consider changing this.

Thanks for your detailed request.

**Comment by shilo-ey** [comment]
Hi @taropaa 

After an examination of your request, we came to an understanding that this is not possible without a custom shims.js or we risk breaking backwards compatibility.

We appreciate your request.

Thanks

**Comment by teoeugene** [comment]
Can't Elementor have the icon changed to "fab fa-facebook-f" (noticed the -f affix) instead of "fab fa-facebook", aka the round Facebook icon? As the original posted said, it's awkward especially when selecting circle as another shape -a  round icon within another round shape.

**Comment by RichardUUU** [comment]
In Share Buttons, just give us the option to specify the icon so we can get rid of the dreaded double circle.
