### ISSUE TITLE
Pagination for WooCommerce Reviews tab

### ISSUE THREAD

**Issue by Spark3000** [elementor/elementor#8786]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Please add the ability to paginate the Reviews tab for WooCommerce urgently. I have an uncomfortably long list of reviews that a user needs to scroll down to find the review form fields.

**Comment by shilo-ey** [comment]
Hi @Spark3000 

The pagination feature is a native option in WordPress

Go to Settings > Discussion and select the number of comments per page.

![image](https://user-images.githubusercontent.com/45009641/62601794-e849db80-b8fa-11e9-8fa0-3c5ce363c4f2.png)

Thanks!

**Comment by Spark3000** [comment]
Thanks. Sorry.
