### ISSUE TITLE
Dynamic tags not parsed for front end output

### ISSUE THREAD

**Issue by maoxiong** [elementor/elementor#8787]
If using `'frontend_available' => true` in a widget control (to put the value in the `data-settings` variable) the field isn't parsed, so will just show up as blank.

This seems to be linked to line `1197` of `includes/base/controls-stack.php`.

If you change it from:
`$frontend_settings = array_intersect_key( $this->get_active_settings(), array_flip( $this->get_frontend_settings_keys() ) );`
to
`$frontend_settings = array_intersect_key( $this->get_active_settings($this->get_parsed_dynamic_settings(), $this->get_controls()), array_flip( $this->get_frontend_settings_keys() ) );`

It will now correctly parse the dynamic field - but I'm not an expert to know if this is going to screw something else up somewhere....

**Comment by maoxiong** [comment]
This is still an issue in 2.7

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
