### ISSUE TITLE
Post Navigation Widget not displaying Arrows Type any more

### ISSUE THREAD

**Issue by dameer** [elementor/elementor#8788]
I think the problem took place since uploadable icons took place.

So, as the title says, the Post Navigation widget doesn't display the selected arrow style/symbol anymore. Editor and frontend are affected by the problem.

![no-arrow-prev-next-post-navig](https://user-images.githubusercontent.com/1826261/62531806-782c4e80-b843-11e9-8e4b-319a0eb9ee15.png)

**Comment by shilo-ey** [comment]
Hi @dameer 

Make sure the shim.js file (converting FA4 to FA5) is enabled:
Go to Elementor > Settings > Advanced tab > Set "Load Font Awesome 4 Support" option to "Yes" and see if the issue resolves. [learn more here](https://docs.elementor.com/article/584-migration-to-font-awesome-5).

Thanks!

**Comment by dameer** [comment]
YES! That makes the trick. Thanks!

**Comment by needu-australia** [comment]
Yes, that fixed it. Thank you.
