### ISSUE TITLE
Grouping elements

### ISSUE THREAD

**Issue by paaljoachim** [elementor/elementor#879]
Hey

Sometimes we want to create an affect on multiple elements at once and not just the one element. This means for instance creating a white rounded background containing a shadow around multiple elements.

What can be seen in the screenshot:
A heading
accordion with + signs on the right.
Text editor containing a list. This also contains a Background & Border: Color white, Border type none, Border radius 9, Box Shadow with some adjustments.

![screen shot 2016-11-17 at 23 52 37](https://cloud.githubusercontent.com/assets/5323259/20411302/32f6c41a-ad21-11e6-8713-f9e0af74076f.png)

Let say I wanted to have the white background box behind the accordion list. I would not be able to include the title "Sameiets vedtekter og husordensregler" inside this white background. As I can not group elements and have the same single element effect go across multiple elements. Grouping elements means whatever effect you put on one effects them all.

**Comment by ehausen** [comment]
Commenting here with some keywords so people can find this better:
Edit multiple elements
Bulk edit
Select multiple elements

Can we help somehow to make this happen faster?
Would interface mockup help?

**Comment by ehausen** [comment]
Sketch does it with [Shared Styles](https://www.sketchapp.com/learn/documentation/styling/shared-styles/)

**Comment by benhohner** [comment]
Looks like multiple tickets have been merged into this one, but not much discussion has been had since. 

A group select, shared styles, or global styles feature would be incredible. It would completely eliminate my need to go to CSS for styling large numbers of elements across different pages. 

I think this feature would really propel Elementor to #1 builder on the market, if it's not already!

Any thoughts on the topic?

**Comment by ehausen** [comment]
It might be worth to take a look how [Sketch shared styles](https://sketchapp.com/docs/styling/shared-styles/) does it

**Comment by black-eye** [comment]
+1

**Comment by wcyang** [comment]
+1 -- this would be helpful with respect to saving global widgets too. One application for example is where the Elementor Forms right now do not allow for easy pre-text to be given to the person opting in. 

I.e. "Join our newsletter to get..." 
This has to be done with headers and text so being able to group the three elements (header, text, form) would be ideal.

**Comment by gerardreches** [comment]
+1, I'm missing so much this feature.

**Comment by GreenballParis** [comment]
+1 UP select several similar elements to apply a color change to all the titles of a page for example instead of 1 by 1.

**Comment by ZhanArno** [comment]
+1 UP - This feature would greatly simplify the work.
I look forward to it.

**Comment by Olya-Z** [comment]
+1 UP - Great idea! Changing similar elements one by one takes too much time.
This feature is very necessary. The presence of such a function will greatly speed up and simplify the work.

**Comment by ohameiri** [comment]
+1

**Comment by creazy231** [comment]
+1

**Comment by yokiano** [comment]
+1

**Comment by ofmarconi** [comment]
**+1**

**Comment by libbeydesign** [comment]
+1

**Comment by Drew-source** [comment]
+1 This would would be useful to save headers in global that have multiple elements into 1

**Comment by FIJOR** [comment]
+1 this is an essential tool

**Comment by emilaet** [comment]
+1 Been wishing this for 4-5 years now....
You make your own widget out of elements, but have to copy every single element in the widget every single time.
Seems odd there hasn't been any progress in this as many other wordpress builders.

**Comment by Christopher-Hayes** [comment]
They have this in the PlayCanvas editor, makes an enormous difference. It's practically every day that I'm wishing Elementor had something similar.

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Comment by jes-wd** [comment]
@DorShahar while the feature you've added is helpful, it's worth clarifying that you haven't really added the requested feature, only part of it (the simpler part). What was asked for on both this issue and issue #8006 that was referenced on the beta release notes (#16840) was for the ability to edit the settings of the widget. Particularly on this issue, that was the main request, and deleting, copying and duplicating wasn't even mentioned. 

When you aren't accurate about what you've delivered it causes confusion for your users. Bulk editing of widget settings on a page (for instances of widgets that are the same as each other) is still a feature that would be great to see implemented in Elementor at some stage.

**Comment by gerardreches** [comment]
> @DorShahar while the feature you've added is helpful, it's worth clarifying that you haven't really added the requested feature, only part of it (the simpler part). What was asked for on both this issue and issue #8006 that was referenced on the beta release notes (#16840) was for the ability to edit the settings of widgets in bulk. Particularly on this issue, that was the main request, and deleting, copying and duplicating wasn't even mentioned.
> 
> I appreciate that this is a difficult feature to implement, but it doesn't help when you aren't accurate about what you've delivered. It causes confusion for your users. Bulk editing of widget settings on a page (for instances of widgets that are the same as each other) is still a feature that would be great to see implemented in Elementor at some stage.

I agree, the feature isn't complete, it helps in some scenarios but only to bulk copy/delete. We still can't edit the options the selected widgets have in common.

**Comment by zorrillamonsoon** [comment]
this would be OH so helpful LOL. Please do it this year 😅

**Comment by jmessy919** [comment]
Bulk edit is super important. Bakery Builder has several means of bulk applying styles/customizations to its elements and truly, Elementor is the superior editor, so it'd be a shame to not take the bull by the horns on this one especially now that the system is fully implementing more forward-thinking web tech like flexbox containers and templating. Cheers.

**Comment by ofmarconi** [comment]
@DorShahar reopen this thread please.
