### ISSUE TITLE
custom webhook stopped working 

### ISSUE THREAD

**Issue by peacockesq** [elementor/elementor#8792]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Okay, posting here at Support's suggestions. They called me a developer. Hah!

Elementor Pro, Hello theme, child theme in place.
Custom webhook, obtained from here earlier this year, added to functions.php file.
Webhook worked for a while, then stopped at some point in May.

This is a law firm website, so it is VITAL that it work correctly. I'd prefer to use the built-in webhooks function but we never could get it to work so y'all said to add a custom webhook in the functions.php file. If you have suggestions on how to get the email function in forms to work as well, that would be a good backup to webhooks/posting to my CRM.

I've deactivated all plugins, swapped themes, etc. Nothing gets this hooker to hook.

Here is the code (POST URL has been altered for privacy sake).
```PHP
// // A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );
    if ( 'web_intake' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    wp_remote_post( 'https://api.lawmatics.com/v1/forms/FAKENUMBER/submit', [
        'body' => $fields,
    ]);
}, 10, 2 );
```
-->

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.44
	PHP Version: 7.1.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://www.peacockesq.com
	Home URL: https://www.peacockesq.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: hello-elementor child theme
	Version: 1.0
	Author: William Peacock
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.1.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.14
		Author: Elementor.com

	Google Tag Manager for Wordpress
		Version: 1.9.2
		Author: Thomas Geiger

	PageSpeed Ninja
		Version: 0.9.38
		Author: PageSpeed Ninja

	Rank Math SEO
		Version: 1.0.29
		Author: Rank Math

	Webcraftic Robin image optimizer
		Version: 1.4.0
		Author: Webcraftic <wordpress.webraftic@gmail.com>

== Log ==
	: 
Log: showing 20 of 372019-05-29 19:40:07 [info] elementor-pro::elementor_pro_updater Started 
2019-05-29 19:40:07 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-05-29 19:40:12 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-05-29 19:40:12 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-05-29 19:40:17 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-05-29 19:40:17 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-05-29 19:40:22 [info] Elementor Pro/Upgrades - _v_2_5_4_form callback needs to run more 1 times 
2019-05-29 19:40:22 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start (2 of 2, 100%) 
2019-05-29 19:40:30 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-05-29 19:40:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.5.9',
)]
2019-07-03 18:15:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.9',
  'to' => '2.5.11',
)]
2019-07-10 16:23:21 [info] elementor::elementor_updater Started 
2019-07-10 16:23:21 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-10 16:23:21 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-10 16:23:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.0',
)]
2019-07-10 16:23:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.0',
)]
2019-07-12 15:37:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.0',
  'to' => '2.6.1',
)]
2019-07-15 17:58:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.11',
  'to' => '2.5.14',
)]
2019-07-15 17:59:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.1',
  'to' => '2.6.2',
)]
2019-07-18 17:20:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.4',
)]

JS: showing 6 of 6JS: 2019-05-29 20:31:09 [error X 1][https://www.peacockesq.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.5.9:2:42819] Cannot read property \'get\' of undefined 
JS: 2019-07-03 15:43:06 [error X 1][https://www.peacockesq.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:66970] Cannot read property \'getBoundingClientRect\' of null 
JS: 2019-07-03 19:01:23 [error X 7][https://www.peacockesq.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:42004] Cannot read property \'forEach\' of undefined 
JS: 2019-07-15 17:18:25 [error X 1][https://www.peacockesq.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1191\") has already been destroyed and cannot be used. 
JS: 2019-07-15 17:44:44 [error X 1][https://www.peacockesq.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1429\") has already been destroyed and cannot be used. 
JS: 2019-07-15 20:56:47 [error X 1][https://www.peacockesq.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view838\") has already been destroyed and cannot be used. 

				
</details>

**Comment by peacockesq** [comment]
Disregard. Solved myself while solving the email issue.

Apparently, an update along the line wiped out all of my field ID codes. I did uncover a separate bug that I'm posting in a new thread - email feature reports field ID instead of field value in picklists.

**Comment by shilo-ey** [comment]
Hi @peacockesq 

Glad you managed to figure it out :)

Cheers

**Comment by xinnerz** [comment]
Couple of questions on this:
 1) What does the 10, 2 mean at the end
 2) This code is working for me, but strange is also happening, im getting the same record being posted 6 times any idea why this could be happening??

**Comment by johnnny-bravoo** [comment]
@peacockesq - I also need to submit the Elementor form data to LawMatics. I would appreciate it if you please share your modified code (webhook). Thank you.

**Comment by johnnny-bravoo** [comment]
@peacockesq can you please help me how to send form submissions to Lawmatics or share your code, please. The data should be passed in json and define headers too. Here is the link which is similar to what I need. https://intermarketing.merkados.com/customizing-webhook-calls-in-elementor-pro

I even purchased a plugin [Elementor Forms to Lawmatics](https://www.weconnectcode.com/plugin/lawmatics-for-elementor-forms) but it's not authenticating and support is not responding. So, I would be appreciate if you provide a solution, thank you.
