### ISSUE TITLE
form email reports wrong value

### ISSUE THREAD

**Issue by peacockesq** [elementor/elementor#8794]
Elementor/Pro latest versions installed.

Uncovered a bug when setting up email after form submission. Forms are ID'd as below, per the instructions. Email that came in reports the field code, rather than the value, for the picklist "Legal Issue."

![image](https://user-images.githubusercontent.com/47698592/62574805-4cbb5b00-b867-11e9-9436-cc14ac1b6644.png)

![image](https://user-images.githubusercontent.com/47698592/62574970-aae83e00-b867-11e9-8ba1-85c89c1ce34c.png)

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
