### ISSUE TITLE
SVG in Image Widget Not Showing on Firefox

### ISSUE THREAD

**Issue by filipe-q** [elementor/elementor#8796]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When adding SVGs in Image Widgets, they are not shown in Firefox. They are loaded but with 0 Width, due to the Width Property having Auto value. When changed to a specific width like 100px it shows.

## Steps to reproduce

Add an SVG inside Image Widget
Open page on Firefox

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.2.31 (Win32) DAV/2 mod_ssl/2.2.31 OpenSSL/1.0.2e mod_fcgid/2.3.9 mod_wsgi/3.4 Python/2.7.6 PHP/7.1.7 mod_perl/2.0.8 Perl/v5.16.3
	MySQL version: MySQL Community Server (GPL) v5.6.34
	PHP Version: 7.1.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://localhost/
	Home URL: http://localhost/
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Theme
	Version: 1.0.0
	Author: 
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.2
		Author: Elementor.com
```
</details>

**Comment by shilo-ey** [comment]
This is not an issue related directly to Elementor but to Firefox.

From what it seems, if you add width to the image it should be resolved. [see more here](https://stackoverflow.com/questions/25927208/svg-in-img-tag-not-loading-as-image-in-firefox)

**Comment by filipe-q** [comment]
Thanks for your answer, but I don't think this is closed.

First of all, I use Elementor to speed up development time and because of all of the built-in functionalities it has. Telling me to custom code something that Elementor should do by default is not the appropriate answer, in my opinion.

Second of all, isn't this what Cross-Browser Compatibility is about? Making things work the same on all browsers? I believe that's why Elementor loads a specific body class when on Internet Explorer, for example. This means Elementor is focused on Cross-Browser Compatibility issues such as the one I presented.

My img tag has a set width and height, the problem is related to the markup generated by Elementor because the main div (div class="elementor-widget elementor-widget-image") for the Img Tag that Elementor generates does not have a set width or a way to set this in the builder without custom code.

Because of the above reason I ask that you reconsider this problem and your suggested solution.

Thanks, I really love your product.

**Comment by shilo-ey** [comment]
Hi @filipe-q 

I didn't tell you not to use SVG files, but to use them properly - via Icon widget which implements the SVG file inline.

Alternatively, set width to your image (which solves this issue).


Thanks

**Comment by Smokey55** [comment]
Hi @filipe-q,

setting up the image to a fixed width for an adaptive and responsive design is not ideal.
The issue is caused by the image/svg not relating correctly to the link container. My workaround it, was to set the link (`.elementor-widget-image a`) to `display: block`, which made the logo visible on Firefox and still resizable.

I wonder if this could be implemented by default at the widget level - the site logo widget.
