### ISSUE TITLE
Text shadow in slides widget

### ISSUE THREAD

**Issue by NUGGETRY** [elementor/elementor#8800]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Will allow for text shadow to be applied to overlay text in slides widget.
**Describe the solution you'd like**
Same text shadow option made available that is available on other overlay texts.
**Describe alternatives you've considered**
None
**Additional context**

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!
