### ISSUE TITLE
Hamburger Menu on desktop

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#8802]
I would like to use a hamburger menu on all device. This is not possible with the nav menu widget. Would you please implement that?

**Comment by shilo-ey** [comment]
Hi @HelmutGoebel 

You sure can use the hamburger menu on all devices using dropdown option:
![image](https://user-images.githubusercontent.com/45009641/62681007-48a35080-b9c1-11e9-93fa-ad938532ef94.png)

Thanks

**Comment by jonel33** [comment]
It's not possible if you dont have Elementor pro
