### ISSUE TITLE
Elementor document main section element/class inconsistency

### ISSUE THREAD

**Issue by dameer** [elementor/elementor#8803]
I've noticed something really strange. Not sure whether this is on purpose and if true it's kinda silly... OK, this is how any Elementor page is structured (roughly, of course):

```
<body class="...">
    <div class="elementor-location-header..."><div>
    <main class="site-main..."></main>
    </div class="elementor-location-footer..."></div>
</body>
```

However, if you create Single or Archive template for the custom post type, the structure changes to:

```
<body class="...">
    <div class="elementor-location-header..."><div>
    <div class="elementor-location-single..."></div>
    </div class="elementor-location-footer..."></div>
</body>
```

So, if for some reason one is up to style the main section of the site, it won't work across all Elementor templates. For instance...

```
main.site-main {
    /* main section styles */
}
```
Hope it makes sense!

**Comment by bainternet** [comment]
@dameer 	


thanks for the suggestion, But, sadly, this is not something we control, its theme depended and the main comes for your theme.


thanks.

**Comment by dameer** [comment]
I was talking about Single or Archive template created by Elementor. So, there's no chance it's coming from the theme.
Besides, I'm using Hello Elementor theme.

**Comment by ServerDestroyer** [comment]
@dameer  I opened a new issue and will nag them for there neglect and see if that does anything.
    https://github.com/elementor/elementor/issues/11107

**Comment by ServerDestroyer** [comment]
This is the same problem with elomentor.com which uses the same Hello Elementor theme. Is the problem Hello Elementor or is it Elementor its self?
