### ISSUE TITLE
Hide Title not working on mobile devices, only Desktop

### ISSUE THREAD

**Issue by sa1979** [elementor/elementor#8807]
I believe that there is a glitch that needs to be fixed. I am using the Twenty Sixteen Theme. 

I want to Hide Title on all devices, so on Page Setting in Elementor, I clicked Hide Title. I also clicked on Responsive Mode {Mobile} to see that the Title is also hidden. 

The problem is when I look on my phone or developer tools [the title is still there, it's not hidden at all- just for the Desktop version]. It's hidden on Desktop and not mobile....

I need it to be hidden on both. [I don't need hidden columns, I need A hidden title.] 

Currently, I am seeing double Titles on Mobile and Developer Tools.

My site is Blogs.O-Reviews.com

**Comment by shilo-ey** [comment]
Hi @sa1979 

The "Hide Title" option is for the post settings (the post native title).
If you want to hide the title in tablet/desktop/mobile, simply go to Advanced tab in any widget you want to hide (not just column/section) > Responsive section > Hide toggles.

In the editor you won't see the changes until you'll collapse the editors panel.

Thanks.

**Comment by sa1979** [comment]
Thank you Shilo-ey for your response. I used the element inspector and found that the theme was using H2.entry-title, not H1.entry-title. This fixed the issue with the Title on the different platforms. I was trying to remove it from the Blog Posts Page, but I think it needs to stay visible in order to select which Blog Post you want to view.
