### ISSUE TITLE
Wrong sanitizing of "get" parameters in dynamic fields

### ISSUE THREAD

**Issue by studioramix** [elementor/elementor#8809]
To replicate this issue, simply:

1. Add a title or any widget with content that can be dynamic
2. Select  for the dynamic tag "Request Parameter", with the type "Get"
3. Publish and then call the page with a get parameter containing text with quotes or single quote.

This results with slashes behind the quotes (like classic MySQL escaping).

This could be problematic for cases where a name or legit script is passed in such a parameter. 

I assume the ideal and safe handling should be the classic html entities including quotes.
![image](https://user-images.githubusercontent.com/11744255/62718114-ea508f00-ba0d-11e9-8ef9-5b6b937dafc3.png)

**Comment by bainternet** [comment]
@studioramix 

Thanks for taking the time to report this, We are aware of it and its the correct behavior of the Request Param Dynamic tag, Which is there to avoid cases of XSS security issues.

thanks again.
