### ISSUE TITLE
Elementor support for WP Stateless 

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8810]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I would love to be able to deploy Elementor within a distributed environment built on google drive. There is one plugin out there, WP Stateless, that seems to be leading the charge in that field, by allowing the media library to be shipped off-site to a google cloud storage container. 

**Describe the solution you'd like**

I would love to see Elementor add support for WP Stateless. This would open the door for some more serious applications beyond small sites and personal blogs. 

**Describe alternatives you've considered**

No other viable alternatives seem to exist yet...

Not sure if this ties into [https://github.com/elementor/elementor/issues/413](url).

**Comment by pingram3541** [comment]
@taropaa YES!  I'd love to see Elementor embrace the front-end development movement.  With Google's focus on mobile site speed, especially as it relates to ranking, headless CMS is gaining a lot of traction.

I've been playing with Frontity and would love to see Elementor json data paired with React modules that rebuild "efficient" html, eliminating the death by a thousand divs and the slower PHP/xSQL stack.

**Comment by bainternet** [comment]
@taropaa 	
I merged this issue with #413, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

@pingram3541 

The name of the plugin threw me off too :)

Thanks for your feedback!
