### ISSUE TITLE
In single CPT templates native password protection doesnt work

### ISSUE THREAD

**Issue by alfredo49** [elementor/elementor#8812]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

When a custom post type is created and an Elementor template is created for this post type. The WordPress Password Protected option no longer works.

The Elementor template appears to be removing something required to make the password protection work correctly.

## Steps to reproduce

Using CPT-UI.

    1Create CPT.
    2Add new post to CPT.
    3Publish post and set visibility to 'password protected'.
    4View post - you should see the password box.
    5Create Elementor Template - Single - Post / Display Conditions - [CPT name].
    6Save.
    7Go back to the CPT post and view - the password box does not appear.
    8The post is immediately viewable.
    9The post title says "Protected", but no password option was given.

This issue also happens with default wordpress theme (twenty) and all plugins deactivated except elementor

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | (Debian) v5.5.57 |  
PHP Version: | 7.1.29 |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 35M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  


</details>

**Comment by shilo-ey** [comment]
Hi @alfredo49 

Make sure you are using "Elementor Full Width" page template to make sure that `the_content` will be included in your CPT page template.

Waiting for your response.

See more here: #7960

**Comment by alfredo49** [comment]
Hi @shilo-ey 

Im using "Elementor Full Width Structure" in Individual Page Template, if i add "Page Content" Module, password protected is shown but the problem is the rest of the template also is showing, event if you dont put the password

**Comment by bainternet** [comment]
@alfredo49 

This is the correct behavior, WordPress password protection is for "Post Content" and not the whole template, and elementor is aligned with that.

thanks.
