### ISSUE TITLE
background-image = none for tablet and mobile

### ISSUE THREAD

**Issue by mjb2000** [elementor/elementor#8813]
**What problem is your feature request going to solve? Please describe.**
I have a section with a background image set for desktops. I would like to have no background displayed on mobile and tablet.

**Describe the solution you'd like**
At the moment we can chose a different image for these other devices and even remove that different image, but in removing it the desktop image is used since there is no override for tablet or phone.

**Describe alternatives you've considered**
Right now I am overriding the tablet and phone image with a transparent spacer.gif - but it would be nice if there was an option for force the css to be `background-image: none`

**Additional context**
Nope

**Comment by black-eye** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/8265 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
