### ISSUE TITLE
Blog post customization feature request for elementor pro

### ISSUE THREAD

**Issue by dbauer22** [elementor/elementor#8814]
I've been trying to create a magazine/blog/news style website and I've found the Pro Blog Post element to be very limited. I've purchased all of the Elementor 3rd part blog elements and they come closer to achieving what I want, but they are still limited.

Here's what I'm looking for:

> A read more button (not just text)
> Category tags with the ability to change the tag font/style/colors
> Social share icons
> Customizable dividers shapes
> Ability to have the author's picture
> Ability to crop the image into a circle
> Special effects for the images.

Thanks!
P.S. sending people toa 3rd party website with a confusing and frustrating way to have them submit feature requests.

![Posts1](https://user-images.githubusercontent.com/53948471/62794323-09dccb80-ba91-11e9-9758-30b24e30a936.PNG)
![Posts2](https://user-images.githubusercontent.com/53948471/62794324-0a756200-ba91-11e9-8279-545a87dcf3b9.PNG)
![Posts4](https://user-images.githubusercontent.com/53948471/62794325-0a756200-ba91-11e9-919e-c2f0beee7ea4.PNG)
![Posts5](https://user-images.githubusercontent.com/53948471/62794326-0b0df880-ba91-11e9-8667-7e6f59ef1541.PNG)

**Comment by shilo-ey** [comment]
Hi @dbauer22 

We have plans in that direction,

I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
