### ISSUE TITLE
Customizable Newsletter Element

### ISSUE THREAD

**Issue by dbauer22** [elementor/elementor#8815]
We're looking for an email capture element that we can customize with an image as the background.

![Newsletter Elements](https://user-images.githubusercontent.com/53948471/62794578-ae5f0d80-ba91-11e9-8861-e6380342d908.PNG)

**Comment by shilo-ey** [comment]
Hi @dbauer22 

You can create it via Elementor.

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues are not for support.

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
