### ISSUE TITLE
Single 404 triggered doesn't re-write destination URL, which messes up web analytics

### ISSUE THREAD

**Issue by AlbanL74fr** [elementor/elementor#8817]
I made a 404 layout with the theme builder. It's great, except that I noticed that the destination url is unchanged when 404 layout is triggered.

For example, if I target `https://www.my-site.com/alban`, but the is not an existing page on my site, then my 404 layout will be displayed on a page with url with exactly https://www.my-site.com/alban. Now if I have Google Analytics on my site, the pageview event is dispatched no matter the page is found or not. Even worse, I see no way for me to filter these pages out of my analytics (unlike if the destination was re-written into something like `https://www.my-site.com/404?target=https%3A%2F%2Fwww.my-site.com%2F%2Falban` or equivalent). 
Is there a better way to sort this issue out?

**Comment by bainternet** [comment]
@AlbanL74fr 	

This is how 404 pages work.

thanks.
