### ISSUE TITLE
⛔ 🚀 Feature Request: Change padding margin on hover

### ISSUE THREAD

**Issue by Kashyap000010** [elementor/elementor#8819]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
On hover it can add padding and margin to the element so that we can do whatever we want to with the element

**Describe the solution you'd like**
add padding to element on hover so that it can become 3d while hovering.

**Comment by bainternet** [comment]
@Kashyap000010 	

Which element?

**Comment by Kashyap000010** [comment]
Any column any section or any widget of elementor we should be able to
change padding margin of widgets, column or section also we want gradient
button.

**Comment by Kashyap000010** [comment]
Also there should be gradient background to all icons icon box.

**Comment by bainternet** [comment]
Thanks for clarifying,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by yacoalioi** [comment]
+1 This would be awesome to simulate a hover effect on a column with shadow and moving it upwards.

**Comment by fathidevs** [comment]
I found a workaround using "custom CSS" in advanced tap.

`selector:hover {
    margin-top: -50px;
    padding-bottom: 50px;
    transition: all 1s ease-in-out;
    cursor: pointer;
}
`
