### ISSUE TITLE
Custom layout for item in loop

### ISSUE THREAD

**Issue by Kashyap000010** [elementor/elementor#8820]
**What problem is your feature request going to solve? Please describe.**
For custom post type there are limitation for post widget if you can add custom  layout to the post widget than it becomes easy for web designer to loop through elements

**Describe the solution you'd like**
you can add new loop templates in theme builder in that the customer can add the heading or post data however they want to add and on a general page if we can add custom post widget than in post widget there should be custom option to select.

Also please add condition output to elementor widget for single template so if the element has no value than that element will be hidden.

**Comment by shilo-ey** [comment]
I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
