### ISSUE TITLE
Hide Panel & Drag

### ISSUE THREAD

**Issue by LielZ** [elementor/elementor#8821]
There is a bug that if you Hide the side panel, you cannot drag sections anymore, you'll need to refresh the page.

**Comment by shilo-ey** [comment]
Hi @LielZ 

Thanks for your feedback.

This is not a bug but intentional behavior, when you close the panel you're entering "Preview" mode and you cannot drag and drop widgets.

Thanks

**Comment by LielZ** [comment]
@shilo-ey  I know that, When you exit the "Preview Mode" (Show sidebar again) then you cannot drag sections.

**Comment by shilo-ey** [comment]
Thanks,

Sadly we couldn't reproduce this issue.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, In that case, please contact our support.

thanks.
