### ISSUE TITLE
Margin and Padding Boxes

### ISSUE THREAD

**Issue by Flipback8** [elementor/elementor#8827]
in the area of margin and padding, the boxes under the advanced section,  the fields are buggy. 
**### Reproduction Steps**
Make a section and add some margin or padding values and click the **unlink button** and "0"'s will be in the box which you **can't remove** without adding additional values. You need to add a number in front of it so that you can take the zeros out. **The experience is not that great.** 

It would be nice if margins and padding could be controlled in a visual way just like in the oxygen builder or the Divi Builder.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @Flipback8 
Thanks for your feedback.

Generally speaking, this is not a proper issue, but this is the behavior of this control (when you unlink the values, the system doesn't have any default value) to work with.

We are working on a broader solution for this control.

In the meanwhile, I merged this issue with #7739, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
