### ISSUE TITLE
Wordpress elementor text

### ISSUE THREAD

**Issue by Ruben2600** [elementor/elementor#8829]
Hello!

My question about the wordpress elementor plugin are about the text

I have 7 columns with pictures, under that pictures I have set text..

When I look on the mobile version the text doing very weird,,,

Is it possibvle with one code to make the text to points like this: Texttext... ?
Thanks! :)

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
