### ISSUE TITLE
Incorrect display ‘type’ => \Elementor\Controls_Manager::ICONS

### ISSUE THREAD

**Issue by Vladddosss** [elementor/elementor#8830]
Hello.
Create your first widget, there is such a problem.
Wrote code, as in instructions

```
$this->add_control(
      'drozd_image_box_icon',
	[
		'label' => esc_html__( 'Icon', 'drozd' ),
		'type' => \Elementor\Controls_Manager::ICONS,
		'default' => [
			'value' => 'fas fa-star',
			'library' => 'solid',
		],
		'condition' => [
			'drozd_image_box_img_or_icon' => 'icons',
		]
	]
);
```

Output

```
<div class="image">
	<?php
	if ( $settings['drozd_image_box_img_or_icon'] == 'icons' ) {
	echo  \Elementor\Icons_Manager::render_icon( $settings['drozd_image_box_icon'], [ 'aria-hidden' => 'true' ] );
	}
	?>
</div>
```

Icon is displayed, but for some reason with the number 1.
Here’s how to output in HTML.

```
<div class="image">
	<i aria-hidden="true" class="fas fa-reply"></i> 1							
</div>
```

How to remove digit 1 from the output?

Screenshot http://SSMaker.ru/4cdf9a4e/

**Comment by shilo-ey** [comment]
Hi @Vladddosss 

Try removing the `echo` before the `\Elementor\Icons_Manager::render_icon( $settings['drozd_image_box_icon'], [ 'aria-hidden' => 'true' ] );
`

It returns 1 because the function already echos its output.

Thanks

**Comment by Vladddosss** [comment]
Thanks. Helped
