### ISSUE TITLE
How to update controls in Repeater control?

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#8832]
Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello team,

Could you tell me how to update controls in Repeater control?

Thanks.

**Comment by bainternet** [comment]
@steve231293 

Same as you would any other control, for example, here I update the tabs repeater tab title to allow dynamic:
```PHP
add_action( 'elementor/element/tabs/section_tabs/before_section_end', function( $widget, $args ) {
	// First get the repeater control
	$control_data = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $widget->get_unique_name(), 'tabs' );
	if ( is_wp_error( $control_data ) ) {
		return;
	}

	// Then you can access and modify the repeater fields as an array directly
	$control_data['fields']['tab_title']['dynamic'] = [
		'active' => true,
	];

	// And then just update the control in the stack/widget
	$widget->update_control( 'tabs', $control_data );
}, 10, 2 );
```

Hope this helps.

**Comment by steve231293** [comment]
@bainternet Thank you for your comment.

**Comment by rickhelmi** [comment]
Can we have tabs( start_controls_tabs ) as well ?

**Comment by sariyanta** [comment]
> @steve231293
> 
> Same as you would any other control, for example, here I update the tabs repeater tab title to allow dynamic:
> 
> ```
> add_action( 'elementor/element/tabs/section_tabs/before_section_end', function( $widget, $args ) {
> 	// First get the repeater control
> 	$control_data = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $widget->get_unique_name(), 'tabs' );
> 	if ( is_wp_error( $control_data ) ) {
> 		return;
> 	}
> 
> 	// Then you can access and modify the repeater fields as an array directly
> 	$control_data['fields']['tab_title']['dynamic'] = [
> 		'active' => true,
> 	];
> 
> 	// And then just update the control in the stack/widget
> 	$widget->update_control( 'tabs', $control_data );
> }, 10, 2 );
> ```
> 
> Hope this helps.

I'm lost in trying to render the content from the newly added control to the repeater. Is there any way to do this?
