### ISSUE TITLE
icon list icons not visible without link

### ISSUE THREAD

**Issue by codeagencybe** [elementor/elementor#8834]
In the last update, the icons from icon list become invisible if you don't set a link/URL on the element. 

Sometimes you don't need a link in the icon list if you just want to create a bulletpoint list, USP list etc... 
But with the latest updates, the icons are not visible if you leave the URL empty. 

Please screen recording to demo the issue:

https://www.loom.com/share/7e62b30aa89b406c8f453cf87e2c6e22

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
