### ISSUE TITLE
Role Manger - Block editing of Spacer element

### ISSUE THREAD

**Issue by glennpsp** [elementor/elementor#8838]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Role Manager does not limit the user from editing the Spacer elements allowing users to mess up site spacing when all they should be editing is content. I would love to see the ability for their access to be limited to two options. 

1. Text
2. Text and Images

**Describe the solution you'd like**
I would like Role Manager settings with "Access to edit content only" priveledges to not be able to access the Spacer element. White space should not be considered content.

**Describe alternatives you've considered**
Other possibilities to solve this are adding Margin / Padding to emulate the Spacer element but this is ineffective in the long run and requires more effort to create the same effect.

**Additional context**
View of an Editor that is able to edit Spacers
https://www.dropbox.com/s/a37xnt5jb2b1jp7/Screenshot%202019-08-14%2008.43.51.png?dl=0

I would like to see the option to only edit Text. Our site is translated into other languages and often users do not need to nor should they edit the imagery of a site. Just the copy into a different language.

**Comment by bainternet** [comment]
@glennpsp 

Thanks for reporting, but it's working as intended, "Edit Content Only" mode allows you to edit only the content of the widget and in spacer widget, the white space is the widget's content.

if you don't want that simply don't use it and space your elements/sections with margins/paddings which a user with "Edit Content Only" mode will not be able to change.

thanks again.
