### ISSUE TITLE
chrome/firefox

### ISSUE THREAD

**Issue by AliAtaMoussa** [elementor/elementor#8839]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by AliAtaMoussa** [comment]
Hello,

I downloaded the code of the builder and I tried it on "Edge" and it is working, but the drag and drop doesn't work on Chrome and Firefox, is there any issue by that?

Thanks

**Comment by madbradj** [comment]
Please see if you have a problem like this: https://github.com/polylang/polylang/issues/399
