### ISSUE TITLE
Style before / after in advanced menu for ACF

### ISSUE THREAD

**Issue by qwik3r** [elementor/elementor#8840]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I noticed that while using the icon list widget and a dynamic ACF field to populate it, that under the advanced menu you can't style what you put into the before or after fields: https://cl.ly/ae7552070160.  

This is the html output: https://cl.ly/6f6a8d51c829.

It doesn't actually use the css before property to insert content or wrap it in a span or class. 

**Describe the solution you'd like**
Wrap the before / after elements in something to style or add the ability to style it directly in the widget

**Describe alternatives you've considered**

**Comment by lucafagherazzi** [comment]
+1

**Comment by bainternet** [comment]
@qwik3r 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can wrap the before/after text in an HTML element ( like `<span>` ) for example and style via Custom CSS.


Thanks for the feedback.

**Comment by qwik3r** [comment]
> @qwik3r
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> For now, you can wrap the before/after text in an HTML element ( like `<span>` ) for example and style via Custom CSS.
> 
> Thanks for the feedback.

That's what I did, wrap the element, but it's cumbersome to do so.
