### ISSUE TITLE
 Publish new templates button is not working. Display Conditions button is not working.

### ISSUE THREAD

**Issue by fredarend** [elementor/elementor#8843]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Publish button when new models are created does not work, simply button click does not happen.

When they are existing models created with older versions of elementor, the "Display Conditions" button does not work in the same way as Publish.

## Steps to reproduce

Creating a new header model.

1 - Create a header model;
2 - Click publish. Simply nothing happens, the button does not work.

When I change a model created with previous version of elementor, the update works normally, but the "Display Conditions" button doesn't work.

## Screenshots - google chrome console

Display Conditions:
![Display](https://user-images.githubusercontent.com/22778127/63095835-a0523680-bf42-11e9-9545-9f9747681302.PNG)

Publish Button:
![Publish](https://user-images.githubusercontent.com/22778127/63095837-a0523680-bf42-11e9-873f-2607d6ecee08.PNG)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: mariadb.org binary distribution v10.3.16
	PHP Version: 7.3.7-10+bionic
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://157.230.181.69
	Home URL: http://157.230.181.69
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.6.10
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.8
		Author: Elementor.com


== Log ==
	: 
Log: showing 11 of 112019-08-15 09:30:37 [info] elementor::elementor_updater Started 
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start  
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_3_0_widget_image Finished 
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_3_0_template_type Start  
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_3_0_template_type Finished 
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-08-15 09:30:37 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-08-15 09:30:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.1.8',
  'to' => '2.6.8',
)]
2019-08-15 09:30:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.1.8',
  'to' => '2.6.8',
)]

JS: showing 1 of 1JS: 2019-08-15 12:33:23 [error X 5][http://157.230.181.69/wp-admin/post.php?post=7&action=elementor:8:19] Cannot read property \'add\' of undefined 


				
```
</details>

**Comment by bainternet** [comment]
@fredarend 

we can't replicate, also in your active plugins we see only Elementor and display conditions is an Elementor Pro feature. 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
