### ISSUE TITLE
Display related content from CPT

### ISSUE THREAD

**Issue by lv986** [elementor/elementor#8846]
Hi, all the CPT plugins have the ability for related posts. Personally I use toolset. In elementor you can display dynamic content from these CPT, but how can I display content from a related CPT on the single page of a post?

**Comment by free2shout** [comment]
I back this issue. 
I have several CPT's and I need to dynamically display related content from a CPT or another. Exemple: 
CPT's: Organization, Event
Organizations: AAA, BBB, and so on
Events: Event A (organized by AAA), Event B (organized by BBB) and so on
Organization has a template in theme builder and needs to display the Events organized by it. 

How can I do that? Query settings in Posts widgets are not dynamic. The Custom Fields plugin has shortcodes but are not allowed either. 

Thought about creating a user for each organization that will be the author  of each Event. Still, Query>author field is not dynamic.

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
