### ISSUE TITLE
Feature Request: Forms: Integrate with Formidable Forms / Formidable Pro

### ISSUE THREAD

**Issue by prospurring** [elementor/elementor#8850]
## Pre-requisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor and Elementor Pro

## What problem is your feature request going to solve?
I love that Elementor has forms options AND I've already been using Formidable Forms Pro (premium plugin) for forms. One of the best features of Formidable Forms is the ability to display Views on a web page.

For example, if your website offers online classes using LearnDash, and if you ask your users to input their information in a Formidable Form, you can then create a View for a given section of a given class, showing the names of all the other students in the class.

Or, if you're a real estate agent, you could create a form where your prospective customers could input the house that they want to list or that they'd like to view, and Formidable Forms could create a View that you could password protect, so you could see all of the new entries at once. Alternatively, you could input form data yourself and display a View of all the current properties you have listed to end-users.

Formidable Pro offers a number of other features, such as User Registration, Quiz Maker, and Polylang that can be useful for online course creators. Formidable also has an integration with ApproveMe's WP eSignature plugin to create legally binding forms. These features aren't available, to my knowledge, using Elementor's forms.

Adding an integration with Formidable Forms would also allow Elementor to, therefore, integrate with ApproveMe's WP eSignature plugin, so that everyone who has Elementor can create legally binding online agreements and contracts.

## Describe the solution you'd like
I would like to use Elementor to add forms to my WordPress posts and pages and have Elementor style them - while passing the form data to Formidable Forms' functionality on the back-end.

## Describe alternatives you've considered
I'm currently using Formidable Forms outside of Elementor. However, Formidable Forms' strength is their functionality, while their weakness is being able to style the forms and make them look the way you'd like them to, as a designer. Marrying Elementor's ability to design anything with Formidable Forms' functionality would be the best of both worlds for me.

## Additional context
Documentation from Formidable Forms for developers can be found here: [https://formidableforms.com/knowledgebase-category/extend-formidable-forms/](https://formidableforms.com/knowledgebase-category/extend-formidable-forms/).

Thank you so much for considering this request.

**Comment by shilo-ey** [comment]
Hi @prospurring 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

In the meanwhile, you can create a custom form action via our [Forms API](https://developers.elementor.com/forms-api/)

Thanks for the feedback.

**Comment by Deralict** [comment]
+1 Would love this!!!

**Comment by dawinks** [comment]
+1 Would be great!

**Comment by bentalgad** [comment]
+1

**Comment by prospurring** [comment]
An Elementor plugin, called PowerPack Elements has made a Formidable Forms Elementor Widget that allows you to style forms from Formidable. [https://powerpackelements.com/elementor-widgets/formidable-forms/](url)

**Comment by maryannstoll** [comment]
I'm +1 for the integration right in Elementor.

**Comment by nisiwi** [comment]
+1

**Comment by nicmare** [comment]
+1

**Comment by sdep** [comment]
+1
