### ISSUE TITLE
Multiple buttons in Slide widget

### ISSUE THREAD

**Issue by JuweTakeheshi** [elementor/elementor#8851]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've been requested more than once from my clients to have two or three buttons within each slide. I've been telling them that this is not supported on this platform. But they keep sending me examples of other platforms.

**Describe the solution you'd like**
Having the option to add two or three more buttons per slide, would be very useful

**Describe alternatives you've considered**
I've considered installing third-party plugins but I really like to keep my plugins page as clean as possible

**Additional context**
I'm using the latest version of Elementor Pro.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
