### ISSUE TITLE
Remove icon in icon list widget when no dynamic field is present

### ISSUE THREAD

**Issue by qwik3r** [elementor/elementor#8857]
## Prerequisit

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

When using the icon list and attaching it to an ACF, if the field is empty do not show the icon. Currently it shows the icon if field is empty: https://cl.ly/49626c8066c5

Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action. 
-->

## Steps to reproduce

1. Add icon list widget
2. Select an icon
3. Select 'dynamic';
4. Select your custom field (ACF)
5. If the ACF is not filled out it will display blank but icon will persist

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by black-eye** [comment]
+1

**Comment by qwik3r** [comment]
I know it's not suppoorted

> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> Thanks for the feedback.

I know it's not supported, that's the point lol. It's also a BUG not a support request.

**Comment by PermaPain** [comment]
+1 would like to see this implemented

**Comment by qwik3r** [comment]
This should be reopened it's a BUG. Maybe instead of getting "close request" happy you should have read and reproduced the steps first. @bainternet

**Comment by ArnaudKeyen** [comment]
**+1000**

**Comment by collingibson** [comment]
I have run into this so many times. If you could fix this that would be great. Thanks

**Comment by bluubsen** [comment]
bump

Does somebody know a workaround? Thanks

**Comment by kellyrenee814** [comment]
Vote for this, or can you just please make the icon list available with a repeater and icon picker.

**Comment by dmeijide** [comment]
+1

**Comment by dnajcz** [comment]
Hi, you can try this workaround - hide icon on empty item text with jQuery:
1) Put elementor [HTML widget](https://elementor.com/help/html-widget/) into the page just after your icon list or to the end of the page,
2) Put html code inside HTML element:
`<script>jQuery('span.elementor-icon-list-text:empty').parent().hide();</script>`
3) Save the page and try. Done.

**Comment by Kipperlenny** [comment]
@bainternet here is a high demand for it

**Comment by shayanfp** [comment]
+1
It's my problem too and I hope that you fix it.
Thank you @dnajcz , for the jQuery code👌

**Comment by Rosita311** [comment]
+1
This would be a great solutiun, Not only while using ACF fields, but also with JetEngine.

**Comment by govusfi** [comment]
+1 for this! :)

**Comment by JennyPower** [comment]
+1

**Comment by stefanullinger** [comment]
I would need this too. Shame, that Elementor devs are not listening.

**Comment by mayurjobanputra** [comment]
> +1
> 
> Workaround - I've used social icons instead and the following CSS to hide if no URL .elementor-social-icon:not([href]) { display:none; }

This solution from JennyPower worked!

**Comment by canaryninja** [comment]
+1

**Comment by FlourishDesignStudio** [comment]
@rebofel @dnajcz 

Any idea why the snippet that you suggested would stop working? I had it working  on this page: https://slwtnewlisting.wpengine.com/explore-our-wineries/anthonyroadwine/slwt-winery-profile/

Then, it stopped. So, I'm trying to come up with a workaround but I'm struggling. You can see the evolution of the trials on that page if you have a minute to look.

Thanks in advance for your help!

![Screenshot 2023-02-28 100643](https://user-images.githubusercontent.com/116741453/221899299-f6a5b385-f4cd-4efa-b7d9-3405c0beb836.jpg)

**Comment by mb4wdc** [comment]
The icon list with ACF issue is also a problem for me when there's no data to display.

**Comment by portrayaloflife** [comment]
+1

**Comment by JboyJW** [comment]
+1

**Comment by crucialcreative** [comment]
+1 I created a Github account just to say how helpful this would be. Under the link advanced settings where you can specify a fallback value, it would be great to have a "hide if empty" checkbox.

**Comment by itmotions** [comment]
empty element can be hidden with css 
`.elementor-icon-list-item:has(.elementor-icon-list-text:empty) {
  display: none;
}`

**Comment by rebofel** [comment]
@itmotions  Hero, thanks!

**Comment by wishtreedev** [comment]
@dnajcz Thank you buddy 👍
