### ISSUE TITLE
Add advanced rule for popups with forms: show/hide popup based on form sent/not sent

### ISSUE THREAD

**Issue by rathert** [elementor/elementor#8858]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I use a popup template to offer to subscribe to a newsletter. I would like to show the popup als long as a user did not yet send the from and subscribed to the newsletter. Unfortunately, there is no trigger / advanced rule enabling that setup.  

**Describe the solution you'd like**

Ad an advanced rule of this form:
"Hide to users that did send the form contained in the popup"

**Describe alternatives you've considered**

none

**Additional context**

**Comment by bainternet** [comment]
@rathert 

You can do this already if you add a Popup "Action after Submit" to the form and set the "Don't Show Again" to YES.

thanks.

**Comment by rathert** [comment]
@bainternet thanks for the hint. I did that, but it does not work, the popup still appears, even after I submitted the form. I guess the reason is that the setting you recommend only applies to the form, not to the popup (template) that contains the form and that is controlled by its own "triggers" and "advanced rules". Or am I getting something wrong?
