### ISSUE TITLE
Slider Content's Text Editor

### ISSUE THREAD

**Issue by wasduman** [elementor/elementor#8862]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

My clients would like to edit their Texts (Title & Description) in Slider own. But missing feature is a Text Editor. They can't write HTML.

**Comment by bainternet** [comment]
@wasduman 	

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can set that with a custom snippet to change the type of the control. 

ex:

```PHP
<?php
// set slides description as wysiwyg
add_action( 'elementor/element/slides/section_slides/before_section_end', function( $widget, $args ) {
	$slides_control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $widget->get_unique_name(), 'slides' );

	if ( is_wp_error( $slides_control ) ) {
		return;
	}

	$slides_control['fields']['description']['type'] = \Elementor\Controls_Manager::WYSIWYG;

	$widget->update_control( 'slides', $slides_control );
},10 ,2 );
```

Bear in mind, that there could some unknown side effects to this.

Thanks for the feedback.

**Comment by wasduman** [comment]
thanks, it works but there are so many places actually where should have Text editor instead of HTML editor. Elementor should take care better of it.

**Comment by kbradleyg** [comment]
@bainternet 
I've been trying to adapt this code to the description field of the call-to-action-widget by looking at the widget's structure etc. to turn the description field into a WYSIWYG also. But somehow nothing happens. What am I missing here?

`/*
 * Set Elementor > CTA widget description as wysiwyg Text Editor
 */
add_action( 'elementor/element/call-to-action/section_content/before_section_end', function( $widget, $args ) {
	$cta_control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $widget->get_unique_name(), 'call-to-action' );

	if ( is_wp_error( $cta_control ) ) {
		return;
	}

	$cta_control['fields']['description']['type'] = \Elementor\Controls_Manager::WYSIWYG;

	$widget->update_control( 'call-to-action', $cta_control );
},10 ,2 );`

Any help appreciated. Thank you.
