### ISSUE TITLE
Different column gap for desktop/tablet/mobile

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#8863]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I need to set a different column gap depending if I'm on a desktop a tablet of a mobile. On a desktop I want my 3 columns to have large space between them. On a tablet, column content get too narrow with a large gap, so I need to reduce the gap to fit the content.

**Describe the solution you'd like**

Just like other option, I'd like to set different settings depending of the screen size.

**Describe alternatives you've considered**

The only option I found is to keep a small gap for all screen sizes.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by black-eye** [comment]
+1
