### ISSUE TITLE
Elementor Will Not Open. "Failed to execute editor.min.js?ver=2.6.8:32" "Uncaught DOMException: Failed to execute"

### ISSUE THREAD

**Issue by jjjanosik** [elementor/elementor#8864]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by jjjanosik** [comment]
Hello. I am attempting to use Elementor with my website, and it was working well for the first few weeks I was working on my site. However, Elementor is not working anymore. When I press "edit with Elementor", I recieve an Elementor loading page that never finishes loading. I have tried almost all solutions I could find on the internet, and I still cannot fix the problem. I have spent days trying to find a solution, but nothing I do works. Any and all help would be greatly appreciated.
![Elementor Error](https://user-images.githubusercontent.com/54292108/63303024-8a6ea980-c293-11e9-8caa-8186c842f765.PNG)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
