### ISSUE TITLE
Add action not working - Script not getting added by using elementor/editor/before_enqueue_scripts

### ISSUE THREAD

**Issue by latheeshvmv** [elementor/elementor#8866]
## Description

```
add_action( 'elementor/editor/before_enqueue_scripts', [ $this, 'ggowl_run_script' ] );
public function ggowl_run_script(){
      var_dump(plugin_dir_url( __FILE__ ) . 'js/ggowl-elementor.js'); //returns correct
      wp_equeue_script( 'ggowl-elementor', plugin_dir_url( __FILE__ ) . 'js/ggowl-elementor.js', ['jquery','elementor-editor'], '1.0' , true );
    }

```
but this is not working the script is not getting loaded. though the var_dump seems to work. 
but the script is not getting added. 

I have modified  'section' and added some fields there. If I use the WordPress method to load the script above it only works in the frontend, not in the editor. I think I have to load the dependencies. Also requesting better documentation on this and controls. 
Please help

## Steps to reproduce

Just place a script and try to enqueue a script so that it can load js in the editor as well as frontend

**Comment by shilo-ey** [comment]
Hi @latheeshvmv 

It's simply wrong to use `elementor-editor` as a dependency.
Also, jQuery is a dependency of Elementor Editor so there's no need for it.
If you want to be sure Elementor Editor has been loaded, use the `elementor/editor/after_enqueue_scripts` action.

Thanks
