### ISSUE TITLE
Elementor for PHP

### ISSUE THREAD

**Issue by breizhwave** [elementor/elementor#8867]
Hi, I've been using Elementor for Prestashop, provided by [Warehouse Theme](https://github.com/elementor/elementor/issues/7556) : any idea or plan to develop Elementor for PHP in general ? could be a nice tool to use in Laravel packages !!

and also, any plan to make elementor pages less elementor dependent, css wise ? full Bootstrap layout ?

Thanks, just ideas

**Comment by bainternet** [comment]
@breizhwave 	

Thanks for the suggestions,

There are plans, but no real ETA for now.

thanks again.
