### ISSUE TITLE
Navigator Names to HTML Classes

### ISSUE THREAD

**Issue by sambbaron** [elementor/elementor#8871]
I think it may be helpful to have navigator element names converted to html classes. This could support more transparent, semantic development. To avoid naming clashes, the classes could have a prefix, like "navigator-*" or "elementor-name-*".

Here's an example. I have a column with the navigator name of `Right Sidebar`. This would be converted to the html element class of `elementor-name-right-sidebar`.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, you can set the Class yourself for each element.

Thanks for the feedback.
