### ISSUE TITLE
Default Link color for the Elementor Page Builder

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8874]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When using Elementor & Pro, in conjunction with the Hello Elementor Theme, we are stuck with a default pink link. I am not sure where that is coming from or where it is defined, but there is no way for the user to specify another one. 
Adding a custom css rule targeting links will override the color of all link texts to black, including the elementor buttons and other widget buttons.

**Describe the solution you'd like**
Add a global link color in the global options. Perhaps in the same area as the Default Colors.
The default colors and the color palette are also quite vague in terms of what color defines what default color for which item

**Describe alternatives you've considered**
Declaring a CSS link style, but again that overrides any custom styled button link colors.

**Comment by shilo-ey** [comment]
@taropaa 
Thanks for your feedback

We are currently working on a solution for this issue and should be released in the next versions.

I merged this issue with #534, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks!
