### ISSUE TITLE
Add option for imagebox width

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#8877]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I have many imageboxes on a page that are set for inline position. Images and titles aren't all the same size so I need to set a specific width for the imagebox to make it uniform. Unfortunately, there is no option for the whole box width in the widget settings. There's only a slider width for the image.

**Describe the solution you'd like**

I simply want a slider for the box to set the width. This also need to be adjustable for desktop/tablet/mobile.

**Describe alternatives you've considered**

I can set a selector width or max-width in the custom CSS, but that's cumbersome I can't set a different width for mobile.

**Additional context**

**Comment by shilo-ey** [comment]
Hi @vgstef 

You can set `custom` width and set the precise custom width you wish to add to your widget (whether it's an image box or any other widget).

This way, you can control the width of your elements responsively.

Thanks for your feedback!

**Comment by vgstef** [comment]
Thanks for the reply, but that's not working. The custom width is only for the image, not the whole imagebox.

See this example:
![image](https://user-images.githubusercontent.com/5083355/63491650-c9fce780-c485-11e9-8599-b91f4d45bebe.png)

The image is smaller than the text, so that ugly and the imagebox becomes larger than the image width. 

That's why I'd like to reopen this feature request.

**Comment by shilo-ey** [comment]
Go to Advanced tab > Custom Positioning section > Width and set it to `Custom`
