### ISSUE TITLE
Disabling elements

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#8878]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Often, I have to update a website or hide some widgets on a page. I know I can hide a widget for a Desktop/Tablet/Mobile in the Responsive section of the advanced tab. But hiding keeps all the content in the frond end page. So looking at the source code of a page, one can see the content of the hidden widget.

**Describe the solution you'd like**

What I'm looking for is a simple on/off button in each widget where I could enable/disable that widget. This way, it wouldn't be loaded at all by the visitor.

**Describe alternatives you've considered**

For now, I need to cut and paste the element (section or widget) in a different draft page to keep the element for further use.

**Additional context**

**Comment by shilo-ey** [comment]
I merged this issue with #7530, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello @vgstef!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.18.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
