### ISSUE TITLE
Image Carousel Problem

### ISSUE THREAD

**Issue by arnonneder** [elementor/elementor#8879]
I use the image carousel within Elementor. I have three images, and the lightbox feature is on. When I click on an image and turn the lightbox on, the arrows to move between images are working in the back end, but not in the front end- they are grayed out (when I update the page and click view).

URL- https://ootrcomic.com/comics/

I already cleared the cache on my computer, which didn't help.

Any suggestions? Thanks in advance!

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by aFluxx** [comment]
This is because there seems to be a problem with dialog.min.js, which calls a fadeIn function. This is rendering an error. 

Hopefully gets fixed in a next update.

Everywhere where you can set up lightbox feature this issue persists.

**Comment by moonbeetle** [comment]
Stumbled upon this problem just now as well. It's a bug for sure, not fixed it seems. Elementor 2.9.8 + Elementor 2.9.3. The arrows of the image carousel widget work, but if you click on the image to fire up the lightbox, the arrows don't work anymore, so the carousel doesn't work anymore.

**Comment by brunomeloc** [comment]
Hi arnonneder! Yesterday I had the same problem as you. In my case, I use the "ocean WP" theme and this theme already has its own lightbox. What was happening was a conflict between the theme's lightbox and the elementor's lightbox. To solve this, I went to the wordpress panel> theme panel> scripts & styles panel> turn off "lightbox". I hope this solves your problem! Good luck

**Comment by vaucci** [comment]
**SOLUTION IN CSS:** 

.swiper-fade .swiper-slide {pointer-events:initial}
