### ISSUE TITLE
Condition does not work under certain conditions

### ISSUE THREAD

**Issue by wayheming** [elementor/elementor#8881]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello a few versions ago, I noticed that the conditions in my widget do not work, I did not attach any importance to this, I thought it would recover in the future, but the problem did not resolve. I have given below the code of the demo widget using which you can see the problem. I have a select on which the tabs depend, inside the tab, there is another a select on which some fields depend, and everything is in the repeater. Dependencies inside the tab from the second select do not work. If you remove the dependence on the tabs from the first select, everything will work. https://gyazo.com/0911926a1175e2e3fa24e4e2f6619013

Sorry, but I couldn’t correctly insert all the code here, so I uploaded it to Google Drive, here’s the [link](https://drive.google.com/file/d/1_ldWoHyaCS3Lj31IRJj8NArcm_u5-WKY/view?usp=sharing)

**Comment by wayheming** [comment]
up

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
