### ISSUE TITLE
Headlines in text widget

### ISSUE THREAD

**Issue by rolffresh** [elementor/elementor#8886]
If the Heading components are used within the Text Editor widget the styling is different compared to when using the Headline widget.

Settings:
- Custom font uploaded for headlines
- Custom font uploaded for body text
- If inside a text widget the headings are used, it uses the body text font to render the headlines, not the uploaded font for headlines.

**Comment by bainternet** [comment]
@rolffresh 

this is a correct observation, simply how things work. 
In a Heading widget, we have more control to allow individual heading styling, in Text Widget, we have less control over the markup (which can be **anything**) so we can't control the inner style of each element.

thanks.
