### ISSUE TITLE
Bug with Pro 2.6.4

### ISSUE THREAD

**Issue by special4code** [elementor/elementor#8888]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I updated to a new Pro version (2.6.4) I got fatal error with this message (No such file or directory):
**PHP Warning:  unlink(/wp-content/uploads/elementor/css/global.css): No such file or directory in /wp-content/plugins/elementor/core/files/manager.php on line 101**
**PHP Warning:  unlink(wp-content/uploads/elementor/css/post-10800.css): No such file or directory in /wp-content/plugins/elementor/core/files/manager.php on line 101**
**PHP Warning:  unlink(/wp-content/uploads/elementor/css/post-10863.css): No such file or directory in /wp-content/plugins/elementor/core/files/manager.php on line 101**

Also, Elementor free version is 2.6.8

## Steps to reproduce

It is related with **clear_cache()** function.

`foreach ( glob( $path ) as $file_path ) {
			unlink( $file_path );
		}`

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
