### ISSUE TITLE
Menu Cart should include everything, so Cart page is no longer needed

### ISSUE THREAD

**Issue by Stilian1** [elementor/elementor#8890]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Conversions for e-commerce stores are the priority**, and although Elementor is trying, it needs improvement. Right now, the Menu Cart is missing some features.

Here's what it needs:

1. An option to add a Title on the top (i.e. Your Cart)
2. An option to add Quantity buttons (plus, minus) to adjust the amount of products
3. An option to show a coupon field
4. An option to add Shipping, Tax, and Total Price details
5. An option to hide the View Cart button
6. An option to add text above or below the Checkout button
7. An option to set a target price for free shipping and showing the progress in a bar
8. An option to open the Menu Cart whenever a product is added to cart
9. An option to change the text of these elements
10. An option to change the order of these elements

If these features are added in the Menu Cart Widget, I'll be eternally grateful to you, Elementor. It will be the ultimate cart menu for every online store owner who cares for conversions.

Here's an example for you to see it in action:
https://ibb.co/0mLxCcy

Thank you!

PS. As you probably noticed from my list above, **we need options**, and that's why we love Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Ethanmbinns** [comment]
Is there an easy way to hook into the template to add this ourself?

**Comment by TrotiWow** [comment]
> Is there an easy way to hook into the template to add this ourselves?

Any luck with this? I'm also looking for hooks in the template. We can edit the mini-cart.php file from Elementor but it's not a good way of doing this. You will always have to replace the file when you update... :( 
@stylians request is super! Covers all the needs. I Hope the Elementor team will take this into consideration.

**Comment by katiachumakova** [comment]
@stylians this list is perfect, elementor should really look into implementing this, at least some basics like editing quantity in the  mini cart.
