### ISSUE TITLE
I need to import an elementor template into (hardcode) a existing php file (template)

### ISSUE THREAD

**Issue by hasintha** [elementor/elementor#8891]
Hello there

Not an issue but need your support on this.

We've a website that needs to be modified. This site was handed over to us by a another company and has a lot of custom templates. What we need is to import elementor sections into these template. ( The front end ui is not an option)

Is there a way to hardcode our elementor templates directly into a php code.?

Awaiting a favorable response

Best

**Comment by shilo-ey** [comment]
Hi @hasintha 

You can use the template shortcode in your PHP file with `do_shortcode` function.

Thanks

**Comment by hasintha** [comment]
Thanks brother
