### ISSUE TITLE
Exit popup - minimum wait delay

### ISSUE THREAD

**Issue by kangarko** [elementor/elementor#8892]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Is there a way for developers to defer the popup having "exit trigger" on from displaying right away if the user moves their mouse instantly away from the screen?

I am looking for a sort of a "start delay" that would set the minimum time required from the script is loaded till the popup is shown, e.g. 2 seconds.

I am a paying customer.

**Comment by kaisdavis** [comment]
@kangarko Did you end up finding a solution to this?

**Comment by kangarko** [comment]
Custom solution

**Comment by kaisdavis** [comment]
@kangarko I arrived there as well -- thank you!
----
Commenting this for anyone who lands here through Google as well: you want to use JS to impose a delay and trigger the exit intent after that delay, using the native Elementor popup, but bypassing the elementor triggering. I got blocked with cross-browser silliness on that front, and switched to using an off the shelf solution (WisePops).

**Comment by launchthatbrand** [comment]
Create a popup that will load on the whole site. No triggers. Add your fade in and fade out animations directly in the elementor popup settings.

Use this code to trigger the popup on exit intent, once per session, and after a 5 minute delay:

```
<script>
document.addEventListener('DOMContentLoaded', function() {
    var hasBeenFiveMinutes = false;
    var popupTriggered = false;

    // Set a timeout for 5 minutes
    setTimeout(function() {
        hasBeenFiveMinutes = true;
    }, 300000); // 300000 milliseconds = 5 minutes

    // Function to handle exit intent
    function showExitIntentPopup(event) {
			console.log("exit_init")
        if (!popupTriggered && hasBeenFiveMinutes) {
					console.log("load_popup")
            if (event.clientY < 50) { // Adjust sensitivity as needed
                // Trigger the Elementor Popup by its ID, e.g., '13161'
								elementorProFrontend.modules.popup.showPopup( { id: 13161 } );
                popupTriggered = true; // Ensure popup only triggers once
            }
        }
    }

    // Add the event listener for mouse movements
    document.addEventListener('mouseleave', showExitIntentPopup);
});
</script>
```
