### ISSUE TITLE
HELP! IMAGE AND FORM MOVE ON DIFFERENT SCREEN RESOLUTIONS

### ISSUE THREAD

**Issue by naowebdesign** [elementor/elementor#8893]
I'm having an issue when building this landing page. The client would like the form to be permanently fixed in the same shape, two arrows same place for different screen sizes and the image that says "OR" just under the BOOK NOW. I've tried to make all these images absolute but still doesn't work. Could someone give me a piece of advise to make these images and form stay on the place for all screen sizes, please? It is a matter of emergency so please get back to me ASAP guys. Appreciated!
![Screen Shot 2019-08-23 at 21 49 12](https://user-images.githubusercontent.com/54471815/63636615-84990f80-c669-11e9-9e84-cecc5f0c66fd.png)
![Screen Shot 2019-08-23 at 21 49 02](https://user-images.githubusercontent.com/54471815/63636622-895dc380-c669-11e9-8f9a-393567d57575.png)

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
