### ISSUE TITLE
URL fields ACF does not generate the url in the button

### ISSUE THREAD

**Issue by ZambraDesigner** [elementor/elementor#8900]
I created a URL field with ACF but when I try to insert it into a button this doesn't work. The button is not clickable and you do not keep any url.

I attach screenshot
<img width="316" alt="Schermata 2019-08-25 alle 19 13 58" src="https://user-images.githubusercontent.com/47243056/63653490-bbf0e480-c76d-11e9-8e9f-33ccd469b859.png">
<img width="1840" alt="Schermata 2019-08-25 alle 19 21 05" src="https://user-images.githubusercontent.com/47243056/63653491-bbf0e480-c76d-11e9-8fe1-6e3b64fbc417.png">
<img width="1521" alt="Schermata 2019-08-25 alle 19 18 28" src="https://user-images.githubusercontent.com/47243056/63653492-bbf0e480-c76d-11e9-99f2-044c13c86640.png">

**Comment by shilo-ey** [comment]
Hi @ZambraDesigner 

Thanks for reporting.

We managed to reproduce this issue by editing the button after inserting the URL. editing the URL will probably fix the issue manually and locally as a workaround until we will provide a fix.

Thanks!

**Comment by ZambraDesigner** [comment]
> Ciao @ZambraDesigner
> 
> Grazie per aver segnalato.
> 
> Siamo riusciti a riprodurre questo problema modificando il pulsante dopo aver inserito l'URL. la modifica dell'URL probabilmente risolverà il problema manualmente e localmente come soluzione alternativa fino a quando non forniremo una correzione.
> 
> Grazie!

Hi,
what are the steps to solve manually?

Waiting for your official fix

**Comment by shilo-ey** [comment]
Edit the URL placed in the ACF field again and it will work

**Comment by ZambraDesigner** [comment]
> Edit the URL placed in the ACF field again and it will work

I changed the URL but it doesn't work.
Can you make a video to see your steps?

**Comment by ZambraDesigner** [comment]
> Edit the URL placed in the ACF field again and it will work

Are there any news for the fix? I can't bring back your solution. 

@bainternet

**Comment by shilo-ey** [comment]
Hi @ZambraDesigner 

Thanks for your feedback

After some investigation, this issue happens also with the native ACF shortcode.
When accessing the preview mode the `post_id` changes due to `\acf_revisions::acf_validate_post_id` action hook and therefore this is not a bug related to Elementor but how ACF outputs its fields on the WP preview.

Thanks!
