### ISSUE TITLE
Underline Color does not inherit the color of the text when set in typography settings

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#8902]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Underlines in headings do not inherit the color set for the text.

## Steps to reproduce

Set any color other than black for text in the style tab for a heading element. For example blue, hex code #0020b2. Then in typography settings choose underline in the decoration dropdown. The underline is always black and does not inherit the blue of #0020b2.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@jazir5 	

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* System info.


Using the latest Elementor, We can't replicate, 
![bWdMGiV](https://user-images.githubusercontent.com/660572/63684007-94992680-c804-11e9-9c4a-db627f1bc9e3.png)
