### ISSUE TITLE
Social Icons Widget - Hover Options

### ISSUE THREAD

**Issue by edcoyne** [elementor/elementor#8908]
Social Icons Widget - Hover Options

## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
You already have "Official Color" option for "Normal" appearance. That's great!

**Describe the solution you'd like**
You should also include "Official Color" as a "Hover" option (with custom colors for "Normal").

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
