### ISSUE TITLE
A single license for each Wordpress installation.

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#8910]
Hello guys,

I have more than 10 different subjects (health, fashion and beauty, business, investments, music, technology, ...), separated into categories. And I think of putting each subject in different subdomains. But all will be within the same site, same domain, same Wordpress installation.

It's not fair that I have to pay over 10x for Elementor Pro, since it's all the same site.

So I leave the suggestion for you to offer a single Pro license per Wordpress installation (same domain), and only need to have another license if it is different domain.

Thank you,
Rodrigo

**Comment by arielk** [comment]
I'm closing an issue because it's a license issue. Feel free to contact our support for any issue through your account.
