### ISSUE TITLE
Posts Widget - Option to Show Private Posts

### ISSUE THREAD

**Issue by DeathStapler** [elementor/elementor#8927]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have a page that I want site editors to be able to refer to for FAQs, policies, and procedures.  I want it to have a list of posts that are marked as private and in a specific category, which the editors can reference.  I was hoping to use the Posts Widget to accomplish this so that I don't have to manually update the page when I create a new post. However, the Posts Widget only displays Published which are not marked as private.

**Describe the solution you'd like**
I would like to see an option when, maybe a toggle, that would allow the Posts Widget to include Private posts.

**Describe alternatives you've considered**
The only alternative that I have found would be to manually update the page with links to posts.

**Additional context**
An example of the additional option in the Query options.
https://i.imgur.com/ZiQT0aZ.png

**Comment by bainternet** [comment]
@DeathStapler 	

this can be done easily via https://developers.elementor.com/custom-query-filter/

thanks.
