### ISSUE TITLE
PHP hook "elementor/frontend/the_content" filtering more than expected

### ISSUE THREAD

**Issue by northerner** [elementor/elementor#8930]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This is just a question really, and I'm not sure if it is a bug or intended behavior, but we've been told by your support team to post it here as a bug.

One of our Memberful WP plugin users has reported that more of their pages and posts than expected is being restricted when using the Elementor theme builder. On pages where they expect to just see the main page content restricted they also see elements in headers, footers, sidebar etc. restricted too. The sort of content normally shared across all pages of the site.

We use the `elementor/frontend/the_content` filter when we hook into Elementor to restrict content. This ends up filtering out all content added through Elementor. **Is it the intended behavior to filter out all content in the page or should it be just the main post body content?**

The hook:
https://code.elementor.com/php-hooks/#elementorfrontendthe_content

Memberful's current use of the hook:
https://github.com/memberful/memberful-wp/blob/master/wordpress/wp-content/plugins/memberful-wp/src/contrib/elementor.php

Memberful's previous use of the hook:
https://github.com/memberful/memberful-wp/commit/25cfbcdacb5f05fb8bcff2b3e2be8d6638fdd0b7#diff-de9b0bcfd60ae40bd2a7889d6ff5b272

If this sounds like a bug, and not expected behavior, please let me know and I can add steps to reproduce.

## Isolating the problem

- [*] This bug happens with only Elementor plugin active (and Elementor Pro).
- [*] This bug happens with a default WordPress theme active.

**Comment by bainternet** [comment]
@northerner 

In a page designed with elementor templates (Header, Footer, Single, Archive ...) the filter gets fired for each of the template parts in that page so you need to make sure you are only filtering only the main queried post/page content or even better is to add your filter only on the main post to begin with, something like this for example:

```PHP
add_filter( 'elementor/frontend/builder_content_data', function( $data, $post_id ) {
	if ( get_queried_object_id() === $post_id ) {
		add_action( 'elementor/frontend/the_content', 'memberful_wp_protect_content' );
	}
	return $data;
}, 10, 2 );
```

And make sure that you remove that action hook from your `memberful_wp_protect_content` once to avoid infinite loop or re-runs on other elementor template parts down that page.

**Comment by northerner** [comment]
That works great, thanks for the explanation @bainternet.

**Comment by jcbpl** [comment]
Hi there @bainternet, I work with @northerner at Memberful. We updated our plugin back in August to use `builder_content_data` as recommended above, and we also added `remove_filter` to `memberful_wp_protect_content` per that advice: https://github.com/memberful/memberful-wp/blob/29b49e558cefb5462d48b3fc91241e2604a33cfb/wordpress/wp-content/plugins/memberful-wp/src/content_filter.php#L17

We recently discovered that the latter change is causing problems for a mutual customer who's using Elementor Pro's posts template; adding the posts template to a page protected by Memberful causes all of the Elementor templates to be displayed unprotected.

Removing `remove_filter` causes it to work again, but I'm not sure I understand the implications. Could you elaborate on the possible "infinite loop or re-runs on other elementor template parts down that page" that we need to avoid?
