### ISSUE TITLE
Don't close video lightbox when the video is clicked

### ISSUE THREAD

**Issue by swinggraphics** [elementor/elementor#8931]
- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Clicking/tapping on a video usually plays/pauses the video, but when a self-hosted video plays in a lightbox, clicking on it stops the video and closes the lightbox.

**Describe the solution you'd like**
Clicking on a video in a lightbox should play/pause the video; it would not close the lightbox.

This should be considered a bug, because it is contrary to the expected behavior for any user.

**Comment by shilo-ey** [comment]
Hi @swinggraphics 

Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!
