### ISSUE TITLE
Shape Divider - Add shadow

### ISSUE THREAD

**Issue by Nedo21** [elementor/elementor#8933]
The shape divider needs a custom Shadow option.

**Comment by Nedo21** [comment]
YOu can use this CSS to solve the Problem on your own:

.elementor-shape-bottom {
   filter: drop-shadow( -3px -1px 4px rgba(0, 0, 0, .1));
}

**Comment by shilo-ey** [comment]
Glad you managed to work it out

Thanks

**Comment by CringyMonkey** [comment]
Perfect!
