### ISSUE TITLE
Manager::AddSettingsPanel does not work with Elementor 2.7 Beta

### ISSUE THREAD

**Issue by andreasnrb** [elementor/elementor#8936]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.
- [x] The issue still exists against the latest beta version of Elementor.

## Description
I have a custom settings panel in the Elementor plugin. Which is added using 
Elementor\Core\Settings\Manager::AddSettingsPanel. Testing with Elementor 2.7 Beta it is not shown. This is most likely due to changes on how the panels are now rendered using Backbone Marionette (PanelMenuPageView and initGroups: function initGroups() {
)

## Steps to reproduce

* Install the Elementor 2.7 Beta
* Extend Elementor\Core\Settings\Base\Manager
* Extend Elementor\Core\Settings\Base\Model

```
		add_action( 'elementor/init', static function () {
			Manager::add_settings_manager( new CustomSettings() );
		}, 100, 0 );
```
## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @andreasnrb 

Thanks for reporting.

Please report beta issues only in the beta thread.

Thanks
