### ISSUE TITLE
How to create WooCommerce search result page? 

### ISSUE THREAD

**Issue by kcynia85** [elementor/elementor#8937]
HI there,

I can't find anywhere an issue about creating a Woocommerce search result page. 
When I have tried to save the already created Shop page as a search result template.
And now I am trying to search sth using  Search Elementor widget I see default disgusting view not saved a template. 

Thank you in advance for your help.

**Comment by anastk** [comment]
There is no dedicated search function for Woocommerce the search widget is the Wordpress built in search feature and I couldn’t customize it either I am using Elementor Pro it looks like crocoblock has this feature but I prefer to have it built in Elementor...

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/6226 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
