### ISSUE TITLE
Elementor Forms - Update available field map fields after widget saved

### ISSUE THREAD

**Issue by verygoodplugins** [elementor/elementor#8938]
I've created a custom form action for Elementor Forms which has a field map in it. This is all working fine. My problem right now is if new fields are added to the fields map, these aren't reflected in the form action unless the entire form is deleted and re-created.

Here's the code I'm working with:

    $widget->add_control(
        'wpf_fields_map',
        [
            'label' => sprintf( __( '%s Field Mapping', 'elementor-pro' ), wp_fusion()->crm->name ),
            'type' => Fields_Map::CONTROL_TYPE,
            'separator' => 'before',
            'fields' => [
                [
                    'name' => 'remote_id',
                    'type' => Controls_Manager::HIDDEN,
                ],
                [
                    'name' => 'local_id',
                    'type' => Controls_Manager::SELECT,
                ],
            ],
            'default'   => $this->get_fields(),
        ]
    );
     
    // Need to merge in new fields....
     
    $settings = $widget->get_settings();
     
    if ( ! empty( $settings['wpf_fields_map'] ) ) {
     
        $fields         = $this->get_fields();
        $new_fields_map = array_merge( $fields, $settings['wpf_fields_map'] );
        $widget->set_settings( 'wpf_fields_map', $new_fields_map );
     
    }

What I'm trying to do in the second part is use `$widget->set_settings()` to update the saved settings with any newly added fields, but this isn't working.

I looked for a filter that could be used to filter the saved settings after they're loaded from the DB and before they're used to render the control, but couldn't find anything applicable.

Can you point me in the right direction? Thanks.

**Comment by bainternet** [comment]
@verygoodplugins 	

This is not how you should work with the Field Mapping control, this control needs a supporting JS handler that runs on the editor and updates on each change of the form fields repeater (which is how we use it for every one of our actions after submit, that utilize this control), also see this: https://developers.elementor.com/building-a-simple-custom-widget-with-javascript/
to better handle JS in your widget/actions/extensions.

**Comment by verygoodplugins** [comment]
@bainternet 

I do have a JS handler that updates the dropdowns of `local_id`s when the form fields repeater changes. That's all fine. I'm talking about the `remote_id`s.

In your ActiveCampaign action after submit, for example, when the API credentials are updated you make an AJAX request via the `fetchCache` function to get the fields and then update them via `updateFieldsMapping()`. That makes sense as the remote fields are not known when the page is loaded.

In my case the remote fields _are_ already known before the page is loaded, and aren't dependent on any user interaction. 

I could copy the way E Pro does it and add an extra AJAX request to get the data I need, but it goes against design principles to use JavaScript to solve a shortcoming in the PHP.

If you're telling me it _can't_ be done with Elementor, that's fine. I can either attach a filter to `get_post_metadata` on the `_elementor_data` key (overly broad), or add an additional AJAX request (sloppy).

My assumption was that there must be a filter or method somewhere that would let me modify the saved settings for a widget before the control is rendered. Can you tell me if this is the case?

Thanks

**Comment by verygoodplugins** [comment]
Posting a solution here in case anyone else finds it useful.

Since it's not possible to filter Elementor's saved settings, you can hook into `get_post_metadata` to modify the data after it's loaded from the database and before it's used in the builder.

In this example I'm searching for a setting with key `my_custom_setting` and updating its value to "NEW VALUE":

	/**
	 * Loop through saved elements, updating values as necessary
	 *
	 * @access  public
	 * @return  array Elements
	 */

	private function my_parse_elements( $elements ) {

		foreach ( $elements as $i => $element ) {

			if ( isset( $element['settings'] ) && isset( $element['settings']['my_custom_setting'] ) ) {

				$elements[ $i ]['settings']['my_custom_setting'] = 'NEW VALUE;'

			}

			if ( ! empty( $element['elements'] ) ) {

				$elements[ $i ]['elements'] = $this->parse_elements_for_form( $element['elements'] );

			}
		}

		return $elements;

	}

	/**
	 * Update saved data when it's loaded from the DB to modify saved values
	 *
	 * @access  public
	 * @return  null / array Value
	 */

	public function my_update_saved_forms( $value, $object_id, $meta_key, $single ) {

		if ( is_admin() && $meta_key == '_elementor_data' ) {

			// Prevent looping
			remove_filter( 'get_post_metadata', 'my_update_saved_elements', 10, 4 );

			$settings = get_post_meta( $object_id, '_elementor_data', true );

			// Quit if the desired setting isn't found
			if ( false === strpos( $settings, 'my_custom_setting' ) ) {
				return $value;
			}

			$settings = json_decode( $settings, true );

			$settings = my_parse_elements( $settings );

			$value = json_encode( $settings );

		}

		return $value;

	}

	add_filter( 'get_post_metadata', array( $this, 'my_update_saved_elements' ), 10, 4 );

**Comment by helloarpitgshah** [comment]
Hey,

I have tried to add this widget control but it's not working for me. How can you add the JS within your custom plugin code?

It's gives me error for the elementor object

Thanks,
