### ISSUE TITLE
Ability to redirect to any page with Custom Add to Cart widget

### ISSUE THREAD

**Issue by Stilian1** [elementor/elementor#8942]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

It's very limiting to not be able to redirect to a custom page while using the custom add to cart widget. Unless it's possible and I don't know how to do it, because it's a pretty basic feature (and WooCommerce provides that functionality with URLs).

Also, if I don't have checked the redirection to cart option in WooCommerce settings, I noticed upon clicking the custom add to cart button, it redirects to the just added product's page. This is not a great move, since it defeats the purpose of having a custom add to cart button...

So, unless it's for a reason I don't understand, why don't you give the option to set a custom page for redirection after adding something to cart?

**Comment by bainternet** [comment]
@Stilian1 

Like you said:
> WooCommerce provides that functionality with URLs

Which you can still use `https://domain.com/redirect_to/?add-to-cart=product_id`, for example, redirect to checkout page ex:
`https://domain.com/checkout/?add-to-cart=5`

The "Custom Add to product" widget is something else and not a "Custom Add to Cart" URL.

thanks.

**Comment by Stilian1** [comment]
@bainternet 

Hi, 

I think I wasn't clear enough. Here's an example to explain it better:

I'm using the WooCommerce builder to design my store. But I also have landing pages, in which I want to use the Custom Add to Cart widget. Creating buttons with custom add-to-cart URLs is not ideal, because I want to let my users to choose product quantity dynamically. So the quantity field of the button is what I need, really.

Of course, I would also like to set a redirection page because, as I said, I don't want the button to redirect to the product's page (if I don't have the "redirect to cart" option checked in WooCommerce settings, that is).

Does my request make more sense now?
