### ISSUE TITLE
Controls_Manager::SELECT2 not working in Safari with only 1 option

### ISSUE THREAD

**Issue by dudaster** [elementor/elementor#8944]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
 When try using Controls_Manager::SELECT2 with only one option in Safari doesn't want to select the value and no javascript errors occur.

This happens only in safari and only if you have one option. If you have 2 or more it works well.

## Steps to reproduce
If you create a widget and add Controls_Manager::SELECT2 type controler and has only one option, when you go into Elementor Editor with Safari browser, you'll see that the single option cannot be selected.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @dudaster 

Thanks for your feedback,

We are aware of this issue, and it's originated in select2. nothing we control of.

Until they will fix this issue, simply add blank value to overcome this issue.

Thanks!
