### ISSUE TITLE
Is there anyway to call the toggle function via javascript?

### ISSUE THREAD

**Issue by S-Simon** [elementor/elementor#8946]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I'm looking to implement a custom feature where if someone clicks on an image, a specific elementor "Toggle element" activates.

Now I understand you don't do customization but I would appreciate it if you could point me to the right direction in terms of what function could I call or how should I activate the toggle element.

I think it would be beneficial to include things like these in the docs. Would make the plugin even more powerful.

Thank you

**Comment by bainternet** [comment]
A few weeks ago we posted a tutorial about this:

https://developers.elementor.com/building-a-simple-custom-widget-with-javascript/

Hope this helps.
