### ISSUE TITLE
Elementor date format

### ISSUE THREAD

**Issue by mygreenfootprint** [elementor/elementor#8949]
Hi there,
Could someone please assist me in changing the existing default date format for elementor from yyyy/mm/dd over to dd/mm ?

I look forward to your reply.

Kind regards,

Kerry

**Comment by mygreenfootprint** [comment]
Hi there,
Could someone please assist me in changing the existing default date format for elementor from yyyy/mm/dd over to dd/mm ?

I look forward to your reply.

Kind regards,

Kerry

**Comment by shilo-ey** [comment]
Hi @mygreenfootprint 

If you're referring to WordPress native return date format you can find an explanation here: https://wordpress.org/support/article/formatting-date-and-time/

Otherwise, please explain your request better.

Thanks!

**Comment by mygreenfootprint** [comment]
Hi Shilo,

I’m referring to the format of the date picker the elementor form widget
uses. I need for users to only be able to select did/mm and not year.

Kerry

**Comment by shilo-ey** [comment]
Hi Kerry,

The Date time control uses `flatpickr` library and the `picker_options` accepts most if not all of the option that `flatpickr` can accept. here is the docs: flatpickr.js.org/options

You can see similar issue here: https://github.com/elementor/elementor/issues/6610

Thanks

**Comment by kashifmahmood47** [comment]
Hey guys I found another solution to change the date format in Elementor forms. As now Elementor Pro uses Native HTML 5, so you need to follow this new method to make it work

This worked for me: https://www.youtube.com/watch?v=z3Dk0GzXIHA
