### ISSUE TITLE
Bug:  Server Error (403 error) when saving page in editor

### ISSUE THREAD

**Issue by aspengooaa** [elementor/elementor#8952]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

I was editing a Post in Elementor Pro, and kept getting a 'Server Error (403 error)'. I did some searching in the Elementor knowledge base and also using google. Here is a link that I found detailing the many things you could try to solve this problem. (https://docs.elementor.com/article/185-the-update-button-does-not-work)

However, I think I have figured out what was causing this, and it isn't any of the things mentioned in that link. This error occurs when I am using the Text Editor widget, and I enter "Data:" (ignore the quotes). As long as I delete anything that says "data:", I can click the update button and save it. If not, the text editor widget remains grayed out, and I get the Server Error (403 error). 

I contacted Elementor, who requested I post this as a bug report in their Github Repository.

Here are some screen shots:
![Server Error Note Grayed Out text](https://user-images.githubusercontent.com/54754780/64070868-754e2f00-cc32-11e9-9fb2-7f4ba570a673.png)
![Server Error (403)  text view](https://user-images.githubusercontent.com/54754780/64070869-754e2f00-cc32-11e9-9455-0e174eef80a5.png)
![Server error (403 error) when using the word data and colon in elementor](https://user-images.githubusercontent.com/54754780/64070870-754e2f00-cc32-11e9-8427-cbdcdaa43db8.png)
 | 
-- | --

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.
Go into Elementor or Elementor Pro, and add a Text Editor widget. Enter the word data, followed by a colon (no spaces). (Data:) (don't include parentheses). Now click the update button in the lower right corner.  You will get a Server Error (403 error). 
## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
THIS IS SERVER INFORMATION WHEN USING ELEMENTOR (non-pro version)
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.44-86.0
	PHP Version: 7.2.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://yourowntraditions.com
	Home URL: https://yourowntraditions.com
	WP Multisite: No
	Max Upload Size: 250 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: admin2@yourowntraditions.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Sixteen
	Version: 2.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.8
		Author: Elementor.com

== Log ==
	: 

HERE IS THE SYSTEM INFO FROM A SITE USING ELEMENTOR PRO (Note that I did not deactivate the plugins again when running the system report. )

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.44-86.0
	PHP Version: 7.2.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://confidentblogging.com
	Home URL: https://confidentblogging.com
	WP Multisite: No
	Max Upload Size: 250 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: admin@confidentblogging.com
	Debug Mode: Inactive

== Theme ==
	Name: Mesmerize Pro Child Theme
	Version: 1.0.0
	Author: AA
	Child Theme: Yes
	Parent Theme Name: Mesmerize PRO
	Parent Theme Version: 1.6.106
	Parent Theme Author: Horea Radu

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.2
		Author: Automattic

	BackWPup
		Version: 3.6.10
		Author: Inpsyde GmbH

	Elementor
		Version: 2.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.5
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.9
		Author: ExactMetrics

	LiteSpeed Cache
		Version: 2.9.8.5
		Author: LiteSpeed Technologies

	Mailchimp for WordPress
		Version: 4.5.3
		Author: ibericode

	Mesmerize Companion
		Version: 1.6.110
		Author: Horea Radu

	TablePress
		Version: 1.9.2
		Author: Tobias Bäthge

	Wordfence Security
		Version: 7.4.0
		Author: Wordfence

	WP-Optimize - Clean, Compress, Cache
		Version: 3.0.11
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WPForms Lite
		Version: 1.5.5
		Author: WPForms

	Yoast SEO
		Version: 11.9
		Author: Team Yoast

== Log ==
	: 
Log: showing 20 of 302019-07-09 06:26:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.0',
)]
2019-07-09 06:26:46 [info] elementor::elementor_updater Started 
2019-07-09 06:26:46 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-09 06:26:46 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-09 06:26:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.0',
)]
2019-07-11 06:35:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.0',
  'to' => '2.6.1',
)]
2019-07-15 06:19:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.1',
  'to' => '2.6.2',
)]
2019-07-15 11:27:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.8',
  'to' => '2.5.14',
)]
2019-07-18 06:30:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.4',
)]
2019-07-19 06:22:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.4',
  'to' => '2.6.5',
)]
2019-07-23 06:29:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.6.6',
)]
2019-07-23 06:29:09 [info] elementor::elementor_updater Started 
2019-07-23 06:29:09 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-23 06:29:09 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-23 06:29:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.6.6',
)]
2019-07-30 10:23:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.6',
  'to' => '2.6.7',
)]
2019-07-30 10:24:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.14',
  'to' => '2.6.2',
)]
2019-08-07 14:25:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.7',
  'to' => '2.6.8',
)]
2019-08-20 16:17:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.2',
  'to' => '2.6.3',
)]
2019-08-29 15:05:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.3',
  'to' => '2.6.5',
)]

**Comment by bainternet** [comment]
@aspengooaa 

We cant replicate, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by creativekamrul** [comment]
Same issue here. I can fix that. I have tried many ways

**Comment by debihazelden** [comment]
I have a similar problem. The same thing is happening when I have "include:" within my text

**Comment by milon27** [comment]
same issue. in text editor when add color style on text its giving this error.

**Comment by RandevSeneviratne** [comment]
Seems like this issue is still happening. Example page here - https://www.emeraldclinics.com.au/clinical-programs/

Specifically the text " Unmet medical needs of interest include" - we have now had to use a semi-colon instead of a colon to avoid this error which is not ideal.

**Comment by refuogee** [comment]
Same here. If I use the word system followed by brackets ie:
"Incident Registration Information System (an unrivalled...." it breaks, I take system or the brackets out and it works.
How do we fix this I need to create a ton of blog posts and now can't!!

**Comment by refuogee** [comment]
> Same here. If I use the word system followed by brackets ie: "Incident Registration Information System (an unrivalled...." it breaks, I take system or the brackets out and it works. How do we fix this I need to create a ton of blog posts and now can't!!

I put a span around my brackets and it worked.. Might be a possible work around..

**Comment by RandevSeneviratne** [comment]
Any acknowledgement from Elementor on this issue?
