### ISSUE TITLE
Form acceptance text click closes Popup

### ISSUE THREAD

**Issue by parfilov** [elementor/elementor#8956]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
1. If I put the Form widget into the popup the click on the Acceptance text closes the popup.

2. This time, if I have another form NOT in popup, just on page. If I click on acceptance text in popup, there is a mark places to the acceptance of the page form.

Temporary solution: disable close on overlay click. However, the mark in usual form still places when I click on acceptance in popup form.

70 sec. to understand the issue better https://youtu.be/EHEbwwwsabQ

## Steps to reproduce
1. Create form with acceptance on page;
2. Create form with acceptance in popup;
3. Create button and trigger popup with Dynamic feature;
4. View page with form and button, click on button and click on the popup form acceptance.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@parfilov 	

do the acceptance fields have the same name/id in both forms?

**Comment by parfilov** [comment]
@bainternet 
Right! Made different field IDs and both issues disappeared. Thanks!

**Comment by V1ch1** [comment]
Good morning everyone! how can i solve the problem?
