### ISSUE TITLE
Ability to show post view (count) in Meta Box

### ISSUE THREAD

**Issue by moxet** [elementor/elementor#8957]
I am currently working on a newspaper style website in Elementor and came across a feature which is, very, required and can be added/tweaked in next version.

![Screenshot_1](https://user-images.githubusercontent.com/919409/64096685-51decd80-cd73-11e9-894c-3c867421b360.jpg)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
