### ISSUE TITLE
How to get background control value?

### ISSUE THREAD

**Issue by dimative** [elementor/elementor#8959]
Hello guys. I need to get background field value. 
I try to get value but can't get success. Please help me. 

Field snippet:
```
$this->add_group_control(
			Group_Control_Background::get_type(),
			[
				'name'      => 'accordion_title_background',
				'label'     => __( 'Background', 'elementive' ),
				'types'     => [ 'classic', 'gradient' ],
				'selector'  => '{{WRAPPER}} .uk-accordion-title',
				'separator' => 'before',
			]
		);
```

and get value 
```
print_r( $settings['accordion_title_background']);
```

bug get this error

```
Notice: Undefined index: accordion_title_background in ....
```

**Comment by bainternet** [comment]
@dimative 

A Group control is a group of controls, so you need to access the actual control and not the group itself and to do that you use your {group control name} + _ + the inner {control name}, so in your case for example if you want to access the background type ( named `background`) you need to access it like so:

```PHP
$group_name = 'accordion_title_background';
$inner_control = 'background';
print_r( $settings[ $group_name . '_' . $inner_control ] );
```

Same goes for any other group control and its inner controls.

**Comment by MehbubRashid** [comment]
Hi, @bainternet can you tell the same method for getting group control values in javascript?
