### ISSUE TITLE
Compatibility issue with custom post type

### ISSUE THREAD

**Issue by wpglossary** [elementor/elementor#8966]
Hi Team,

I am running a WordPress website which uses this plugin:
https://codecanyon.net/item/wp-glossary-encyclopedia-lexicon-knowledge-base-wiki-dictionary/16101768

This plugin comes with a cuistom post type 'glossary'. I reached out to the author of the fabulous WP Glossary plugin if he would be willing to make it compatible to Elementor.

He is quite willing to do so and tried to make his Plugin ACF compatible as you suggested. Now I can style single templates for it, but not archives. Especially categories are not available for rules and queries.

What could be the case to this and where should he look at?

Thanks!

**Comment by bainternet** [comment]
@wpglossary 

In order for the taxonomies to show up as conditions, they need to be registered as both `'public' = true` and `'show_in_nav_menus' => true`.

home this helps.

**Comment by wpglossary** [comment]
I have tried this already:
'public' = true 
'show_in_nav_menus' => true

but still doesn't work :(
