### ISSUE TITLE
Mobile PageSpeed is low

### ISSUE THREAD

**Issue by helvetica123** [elementor/elementor#8967]
Hi, my mobile page speed is low when desktop speed is 90+.Why and how can I solve it?
https://www.sac-ekimi.deniz-tasarim.site

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
