### ISSUE TITLE
Media Carrusel Dynamic

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#8970]
Hello,

Do I have an option for user Media carrusel with dynamic images? 

I have ACF with images and I need used them in a carrusel. Is possible user media carrusel with dynamic content. 

Do you know other plugin that it has this options?

Thank you

**Comment by shilo-ey** [comment]
I merged this issue with #5979, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
