### ISSUE TITLE
posts widget Query Include by format

### ISSUE THREAD

**Issue by hzv4424** [elementor/elementor#8972]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
as explaned here:
https://docs.elementor.com/article/101-posts
posts widget >> content >> Query >> Include By

We should be able to set Query Include to "format"
but Available Options are "term" & "author"
where is the "format" option?

<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/9jsl_query.png" border="0" alt="آپلود عکس" /></a>

Unlike "hello elementor theme" post format is activated in "astra theme"
nevertheless "format" Does not exist in query Include 

<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/tkqf_format.png" border="0" alt="آپلود عکس" /></a>

## Steps to reproduce
1-enable elementor pro
2-make a page
3-edit it with elementor
4-add posts widget to section
5-go to: content >> Query >> Include By

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win64) OpenSSL/1.1.1b PHP/7.2.16
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.2.16
	PHP Max Input Vars: 1000
	PHP Max Post Size: 120M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://vtest.com
	Home URL: http://vtest.com
	WP Multisite: No
	Max Upload Size: 110 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: fa-IR
	Timezone: Asia/Tehran
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.0.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.5
		Author: Elementor.com

== Log ==
	: 
JS: showing 1 of 1JS: 2019-09-01 10:05:26 [error X 2][http://vtest.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.8:2:41610] Cannot read property \'select2\' of undefined 

</details>

**Comment by shilo-ey** [comment]
Hi @hzv4424 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For the meantime, this can be done easily via [developers.elementor.com/custom-query-filter](developers.elementor.com/custom-query-filter)


Thanks for the feedback.
