### ISSUE TITLE
Events Calendar Equivalent for Elementor

### ISSUE THREAD

**Issue by get8bit** [elementor/elementor#8973]
Many people are looking for an Elementor widget event calendar with a thumbnail and list view like this: https://wpshindig.com/events/list/

I have heard of some having success by installing events calendar and adding custom code, and others having success with advanced custom fields and custom post types.

Nearly every non-profit, musician, teacher, school, entertainer, and community group requests an events calendar. Personally, I've had a nightmare in the past with this issue as elementor has failed me in this regard.

Don't you think it's time Elementor added a good calendar widget?

Here, are other third party options. Some are marketed directly to elementor users! I haven't tried them yet, but I will. But, let me ask. Why should an elementor pro user paying good money annually be forced to purchase this feature elsewhere?

https://webnus.net/modern-events-calendar
https://shop.namogo.com/elementor-extras/widgets/calendar/
https://demo.myeventon.com/

**Comment by shilo-ey** [comment]
Hi @get8bit 

Thanks for your feedback.

We are working hard on providing a better page builder and constantly improving our infrastructures.

Currently, this feature is out of our scope, and we see it as a complementary product.

There are many good 3rd party plugins which provide this ability and are extending Elementor pretty well (e.g https://wp-eventmanager.com/ )

Thanks again for your suggestion

ref: #7480

**Comment by gracedp** [comment]
I agree with get8bit - very much needed!!
