### ISSUE TITLE
RSS Error Input is not proper UTF-8

### ISSUE THREAD

**Issue by salahlababidi** [elementor/elementor#8978]
I've created a custom RSS feed and when I try to output the whole post I get an error: Input is not proper UTF-8, indicate encoding !

https://www.unitedmags.com/feed/unitedfeed2
the_content_feed

works fine when not outputting the whole post:
https://www.unitedmags.com/feed/unitedfeed
the_excerpt_rss

Appreciate any help, thx.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.27
	PHP Version: 7.0.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 96M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://www.unitedmags.com/new
	Home URL: https://www.unitedmags.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hemispheres
	Version: 0.1
	Author: Sal Lababidi
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.8.4
		Author: Elliot Condon

	AE ACF Accordion
		Version: 1.0
		Author: WebTechStreet

	AnyWhere Elementor Pro
		Version: 2.12.1
		Author: WebTechStreet

	Custom Post Type UI
		Version: 1.6.2
		Author: WebDevStudios

	Custom Simple Rss
		Version: 2.0.7
		Author: Danny(Danikoo) Haggag

	Duplicate Post
		Version: 3.2.3
		Author: Enrico Battocchi

	Elementor
		Version: 2.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.5
		Author: Elementor.com

	Fast Velocity Minify
		Version: 2.7.4
		Author: Raul Peixoto

	Jetpack by WordPress.com
		Version: 7.7
		Author: Automattic

	Minify HTML
		Version: 1.99
		Author: Tim Eckel

	ShortPixel Image Optimizer
		Version: 4.14.5
		Author: ShortPixel

	WP Super Cache
		Version: 1.7.0
		Author: Automattic

	Yoast SEO
		Version: 12.0
		Author: Team Yoast

== Log ==
	: 
PHP: showing 20 of 38PHP: 2019-08-27 01:26:09 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/modules/popup/document.php::313] Out of memory (allocated 60817408) (tried to allocate 49152 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-27 05:43:36 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/settings/settings.php::599] Out of memory (allocated 46923776) (tried to allocate 17920 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-27 22:17:56 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/core/editor/editor.php::13] Out of memory (allocated 37486592) (tried to allocate 576 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-28 14:24:26 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/schemes/color.php::215] Out of memory (allocated 45088768) (tried to allocate 12288 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-28 14:57:13 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/plugin.php::145] Out of memory (allocated 66846720) (tried to allocate 3072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-28 20:55:38 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/modules/theme-builder/documents/header.php::11] Out of memory (allocated 61079552) (tried to allocate 640 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-29 00:29:20 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/archive-title.php::48] Out of memory (allocated 87293952) (tried to allocate 248 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-29 00:29:20 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/base/controls-stack.php::611] Out of memory (allocated 87031808) (tried to allocate 72 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-29 06:00:14 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/core/settings/base/manager.php::354] Out of memory (allocated 44826624) (tried to allocate 3072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-29 06:00:25 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/base/controls-stack.php::611] Out of memory (allocated 87031808) (tried to allocate 32 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-29 10:28:35 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php::703] Out of memory (allocated 78643200) (tried to allocate 49152 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-29 21:38:23 [error X 2][/home/ua/public_html/new/wp-content/plugins/elementor/includes/controls/groups/background.php::264] Out of memory (allocated 63963136) (tried to allocate 14080 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-29 21:38:35 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/template-library/sources/local.php::1008] Out of memory (allocated 47710208) (tried to allocate 1280 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-30 08:42:51 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/modules/theme-builder/documents/archive.php::85] Out of memory (allocated 60555264) (tried to allocate 100 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-30 08:43:06 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/base/controls-stack.php::1938] Out of memory (allocated 67108864) (tried to allocate 4096 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-31 22:50:28 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/modules/popup/form-action.php::24] Out of memory (allocated 53477376) (tried to allocate 3072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-01 11:00:35 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/base/controls-stack.php::1148] Out of memory (allocated 87293952) (tried to allocate 96 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-01 13:28:25 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/modules/theme-builder/conditions/in-sub-term.php::39] Out of memory (allocated 58982400) (tried to allocate 248 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-02 14:09:11 [notice X 1][/home/ua/public_html/new/wp-content/plugins/elementor/includes/managers/image.php::80] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-03 17:34:41 [error X 1][/home/ua/public_html/new/wp-content/plugins/elementor-pro/base/module-base.php::27] Uncaught Error: Class 'ElementorPro\Modules\Blockquote\Widgets\Blockquote' not found in /home/ua/public_html/new/wp-content/plugins/elementor-pro/base/module-base.php:27
Stack trace:
#0 /home/ua/public_html/new/wp-includes/class-wp-hook.php(286): ElementorPro\Base\Module_Base->init_widgets(Object(Elementor\Widgets_Manager))
#1 /home/ua/public_html/new/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /home/ua/public_html/new/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/ua/public_html/new/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action('elementor/widge...', Object(Elementor\Widgets_Manager))
#4 /home/ua/public_html/new/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\Widgets_Manager->init_widgets()
#5 /home/ua/public_html/new/wp-content/plugins/elementor/includes/elements/column.php(1016): Elementor\Widgets_Manager->get_widget_types('image')
#6 /home/ua/public_html/new/wp-content/plugins/elementor/includes/base/elem [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2019-08-27 21:29:49 [error X 1][https://www.unitedmags.com/new/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13829\") has already been destroyed and cannot be used. 
JS: 2019-08-28 14:13:55 [error X 1][https://www.unitedmags.com/new/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3561\") has already been destroyed and cannot be used. 
JS: 2019-08-28 16:56:56 [error X 1][https://www.unitedmags.com/new/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3209\") has already been destroyed and cannot be used. 
JS: 2019-08-28 17:36:23 [error X 1][https://www.unitedmags.com/new/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1346\") has already been destroyed and cannot be used. 

Log: showing 1 of 12019-09-04 07:50:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.2',
  'to' => '2.6.5',
)]

				
</details>

**Comment by bainternet** [comment]
@salahlababidi 

Running that RSS URL in https://validator.w3.org/feed/ seems like there is an invalid Char around the text 
>The soup bowl–size chalices of salty, limey beer are garnished with ...

so check that content and see what it is.

Hope this helps.

**Comment by salahlababidi** [comment]
In fact I’ve checked this already and in the database there’s no such character for the post which makes me believe it is inserted by elementor as the page is built. Also, it seems that the illegal character is injected by the blockquote widget.
