### ISSUE TITLE
More or Less Colors in Color Picker

### ISSUE THREAD

**Issue by mskks64** [elementor/elementor#8982]
Pretty simple request. I think having more or less colors in the color picker would be ideal. Most of the time I don't have more than 6 colors including Black and White. I don't need the additional 2 slot. Site i'm working on now only needs 4 total. I think the number of colors could be set in Elementor Settings.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8

Feel free to update

Thanks!
