### ISSUE TITLE
Black screen in editor (possibly conflicting with Adsense)

### ISSUE THREAD

**Issue by xperter** [elementor/elementor#8984]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
There is a black screen appears in Elementor's editor page. The page content is visible partially at the top which is not editable as expected. See screenshot: https://prnt.sc/p21jlq

## What I've found so far
For some reason, the `iframe#elementor-preview-iframe` is getting an inline style `height:auto!important` by javascript, but it should be `100%`.
## Possible solution
Not found, but got a quick fix for this. 
1. Enqueue a js file to `elementor/editor/after_enqueue_styles` hook.
2. Put the following code there.

```
jQuery( document ).ready( function($){
    "use strict";
    // BEGINS quick fix for google ad conflicts in elementor's editor
     (function () {
        var x = 0;
        var intervalID = setInterval(function () {
            var editor = $( "#elementor-preview-iframe" );
                if(editor.length > 0){
                    editor.css({'min-height': '100%' });
                }
            if (++x === 5) {
                window.clearInterval(intervalID);
            }
        }, 3000);
    }());
    // ENDS
});
```

## Steps to reproduce
Add any Google Adsense ad into the site. 
Open that page to edit on Elementor.
You will see the issue there.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release rel14.7, Revision 23 v5.7.23-23
	PHP Version: 7.2.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://seethroughhearts.com
	Home URL: https://seethroughhearts.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Asia/Kolkata
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.0.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

== Active Plugins ==
	AccessPress Social Counter
		Version: 1.8.4
		Author: AccessPress Themes

	Contact Form 7
		Version: 5.1.4
		Author: Takayuki Miyoshi

	Controlled Admin Access
		Version: 1.3.6
		Author: WPRuby

	Elementor
		Version: 2.6.8
		Author: Elementor.com

	Mailchimp for WordPress
		Version: 4.5.3
		Author: ibericode

	Unyson
		Version: 2.7.22
		Author: ThemeFuse

	WP File Manager
		Version: 5.3
		Author: mndpsingh287

	Wp ultimate review
		Version: 1.0.0
		Author: XpeedStudio

== Must-Use Plugins ==
	ET Support Center :: Must-Use Plugins Autoloader
		Version: 
		Author: Elegant Themes

	System Plugin
		Version: 3.9.8
		Author: 

== Log ==
	: 
JS: showing 2 of 2JS: 2019-08-23 10:51:57 [error X 2][http://r42.e3d.myftpupload.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.8:32:116476] Cannot read property \'html\' of undefined 
JS: 2019-08-24 09:30:52 [error X 3][https://seethroughhearts.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.8:7:49874] Cannot set property \'controls\' of undefined

</details>

**Comment by shilo-ey** [comment]
This issue resolved by Google - not related to Elementor

Thanks for reporting!
