### ISSUE TITLE
Please update Google Fonts library to all the latest fonts available.

### ISSUE THREAD

**Issue by michelleist** [elementor/elementor#8996]
Hey Elementor, please update Google Fonts library as I miss this one here along with others: https://fonts.google.com/selection?query=manj&selection.family=Manjari:100,400,700
Thank you!!

**Comment by RafaelDeJongh** [comment]
Had the same problem today where I couldn't find two fonts (Red Hat Display and Lexend Deca) I posted this on Facebook: https://www.facebook.com/groups/Elementors/permalink/2207980375994403/ but was suggested to place it here, but as I've noticed someone already mentioned this in the past 12 hours I shouldn't be making the same thread, but that list really should be updated as it is almost a whole year old as the current list hasn't been updated since 23/10/2018!

**Comment by JohnPixle** [comment]
I totally agree. There are a number of awesome new google fonts available and it is such a shame that we are limited to using the same old fonts.

Honestly, we are talking awesome fonts with HUGE design potential. Please, guys.
https://fonts.google.com/?sort=date

**Comment by ROI-guy** [comment]
Please add the newest fonts. Thanks!

**Comment by mjros** [comment]
Please, add the latest and greatest typographic options.

**Comment by jasonb4u** [comment]
Yes about time..

**Comment by AlfaBlue** [comment]
Hi there Elementor devs.
I noticed several (new) Google fonts missing from the Elementor Google Fonts library.
As Elementor is all about designing beautiful and contemporary websites I find it kinda weird
something free like the Google Fonts library isn't update more often.

So, would you be so kind as to update to the latest Google Fonts library? It will make us all happy and inspired... Thanks in advance

**Comment by dotpdesign** [comment]
Need to update the Google Fonts library, please. And you need to come up with a schedule for regular Google Fonts library updates into Elementor so we don't have to keep creating requests to update the library in the future.

**Comment by OutgrowMarketing** [comment]
Would love to make use of the new google fonts. Can you please ad them to Elementor?

**Comment by jflagarde** [comment]
I don't understand why Elementor doesn't always keep Google Fonts updated when they release a new version. Definitively a +1 from me for this!

**Comment by efinit** [comment]
Would also like to request an update of the Google Fonts library to include Gelasio family. Thanks!

**Comment by g2creative** [comment]
+1 for this feature request

**Comment by mauryaratan** [comment]
Hey guys! Over at [Style Kits](https://wordpress.org/plugins/analogwp-templates/), we've added the missing fonts from Elementor. 

We created a workflow so it always generates a list of only missing fonts from the Elementors library. In total, currently, there seem to be around 80 fonts. We'll keep updating this list with each update as part of the release process.

cc @michelgotta @jflagarde

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.0

Google fonts has been updated.

Feel free to update

Thanks!
