### ISSUE TITLE
Samsung DeX !!!

### ISSUE THREAD

**Issue by 200206487** [elementor/elementor#8998]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I cannot travel the world and be mobile and productive with my current Samsung Dex setup. Basically, I can connect my phone or Tab S6 tablet into my monitors and run Desktop-like software but Elementor seems to recognize the mobile browsers as mobile only (despite the browsers being at full Desktop size and everything operating as a desktop)

**Describe the solution you'd like**

The solution is to hopefully allow for a certain screen size to be allowed to use the drag and drop Elementor builder and other features not possible with mobile software - I am editing on a 32 inch monitor on Samsung Internet and I cannot simply drag and drop elements when building a landing page.

**Describe alternatives you've considered**

Currently I am running a Linux container within my phone to run Chrome / Firefox however this can be a bit laggy and honestly not the idea solution at all. Please for the love of software can you allow for mobile productivity which reach a certain screen size at least!

**Additional context**

Samsung DeX is Samsung Desktop Experience software where your normal apps get converted into full desktop-like applications (such as Chrome which then can be ran very similarly to desktop chrome software)

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.

**Comment by neokking** [comment]
This should be fixed please, a lot of us have this issue but have not stumbled on this post yet. 

I have a galaxy tab 7+. I'm always on the road so dex is all I use but yet can't use elementor, can't update or make a simple change. Please again make the drag and drop accessible for mobile. This is a highly as I started looking for alternatives. Bakery

**Comment by rgon242** [comment]
This would be a great update.  I have started using dex for mobile editing and it is an issue that is tedious.  Please consider investing into a fix.

**Comment by tacur** [comment]
Like me, this would be a great update. I have started using dex for mobile editing too. I would appreciate if you  consider to investing into a fix.

**Comment by rgon242** [comment]
This would be a simple resize of the Elementor interface with a tablet, not sure how this can't be a quick focus
