### ISSUE TITLE
Condition for Widget Control Based on Parent Container

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#9003]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Condition for Widget control, based on parent container - is something like this possible?

For example:

In section:
```
$this->add_control(
	'advanced_section_settings',
	[
		'label' => __( 'Use Advanced Section Settings', 'elementor' ),
		'type' => \Elementor\Controls_Manager::SWITCHER,
		'label_on' => __( 'Yes', 'elementor' ),
		'label_off' => __( 'No', 'elementor' ),
		'return_value' => 'yes',
	]
);
```

In Column:
```
$this->add_control(
	'advanced_column_settings',
	[
		'label' => __( 'Use Advanced Column Settings', 'elementor' ),
		'type' => \Elementor\Controls_Manager::SWITCHER,
		'label_on' => __( 'Yes', 'elementor' ),
		'label_off' => __( 'No', 'elementor' ),
		'return_value' => 'yes',

		'condition' => [
			'parent-section->advanced_section_settings' => 'yes',
		],
	]
);
```

**Comment by rami-elementor** [comment]
Hi @black-eye 

Check the developers docs: https://developers.elementor.com/docs/controls/conditional-display/

The thing you describe is not possible. The conditional display based on controls not on container/section/column hierarchy.

May be you can check if both controls match a certain value:

```
'condition' => [
	'parent-section' => 'yes',
	'advanced_section_settings' => 'yes',
],
```
