### ISSUE TITLE
get_script_depends need to script load in both header and footer.

### ISSUE THREAD

**Issue by dimative** [elementor/elementor#9005]
Hello. 
Why ```get_script_depends``` function only load the script in the footer?
Will this function support load the script in the both header and footer? I am developing web elementer widget with [Typewriter.js](https://github.com/tameemsafi/typewriterjs) and i need to load script inside head tag. get_script_depends is nice feature, but only load in footer. Will your team add this feature?

Thanks.

**Comment by bainternet** [comment]
@dimative 	

An Elementor widget is built to load its own assets only when needed and there is no way to know in advance if the widget is used or not.
So, only after your widget has rendered (and in turn enqueued its scripts) which is probably after `wp_head()` which is where first native `wp_enqueue_scripts` has run already. 
All that Elementor can do is to enqueue your script using the next native `wp_enqueue_scripts` which gets called by `wp_footer()`.


So this is not really a feature to add.

Thanks.
