### ISSUE TITLE
Issue: Custom Emoji Control

### ISSUE THREAD

**Issue by mukeshpanchal27** [elementor/elementor#9006]
## Description

We have created the same control as given in example - https://developers.elementor.com/creating-a-new-control/

We had found the below issues when implemented demo code suggested in docs.

- We are not able to get emoji on the front with the click of the emoji icon. 
![01](https://user-images.githubusercontent.com/10103365/64422815-9a272400-d0c2-11e9-85b1-bfb3ca8a00c1.png)

- After filled up textarea with emoji then switch tab ( e.g "Style" tab to "Content" tab ) then it was generated an error in console. 
![02](https://user-images.githubusercontent.com/10103365/64422832-a1e6c880-d0c2-11e9-8d18-318b29db887b.png)

## System Info
https://pastebin.com/nY6UV1Cq

**Comment by shilo-ey** [comment]
Hi @mukeshpanchal27 

Please explain and provide code examples for how you added this field (`emojionearea`)

It seems that the script causes those issues.

Thanks

**Comment by mukeshpanchal27** [comment]
@shilo-ey Thanks for your fast response.

I have used below code please review it.

<pre>
class EmojiOneArea_Control extends \Elementor\Base_Data_Control {

	/**
	 * Get emoji one area control type.
	 *
	 * Retrieve the control type, in this case `emojionearea`.
	 *
	 * @since 1.0.0
	 * @access public
	 *
	 * @return string Control type.
	 */
	public function get_type() {
		return 'emojionearea';
	}

	/**
	 * Enqueue emoji one area control scripts and styles.
	 *
	 * Used to register and enqueue custom scripts and styles used by the emoji one
	 * area control.
	 *
	 * @since 1.0.0
	 * @access public
	 */
	public function enqueue() {
		// Styles
		wp_register_style( 'emojionearea', 'https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.1/emojionearea.css', [], '3.4.1' );
		wp_enqueue_style( 'emojionearea' );

		// Scripts
		wp_register_script( 'emojionearea', 'https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.1/emojionearea.js', [], '3.4.1' );
		wp_register_script( 'emojionearea-control', '/assets/js/emojionearea-control.js', [ 'emojionearea', 'jquery' ], '1.0.0' );
		wp_enqueue_script( 'emojionearea-control' );
	}

	/**
	 * Get emoji one area control default settings.
	 *
	 * Retrieve the default settings of the emoji one area control. Used to return
	 * the default settings while initializing the emoji one area control.
	 *
	 * @since 1.0.0
	 * @access protected
	 *
	 * @return array Control default settings.
	 */
	protected function get_default_settings() {
		return [
			'label_block' => true,
			'rows' => 3,
			'emojionearea_options' => [],
		];
	}

	/**
	 * Render emoji one area control output in the editor.
	 *
	 * Used to generate the control HTML in the editor using Underscore JS
	 * template. The variables for the class are available using `data` JS
	 * object.
	 *
	 * @since 1.0.0
	 * @access public
	 */
	public function content_template() {
		$control_uid = $this->get_control_uid();
		?>
		<div class="elementor-control-field">
			<label for="<?php echo esc_attr( $control_uid ); ?>" class="elementor-control-title">{{{ data.label }}}</label>
			<div class="elementor-control-input-wrapper">
				<textarea id="<?php echo esc_attr( $control_uid ); ?>" class="elementor-control-tag-area" rows="{{ data.rows }}" data-setting="{{ data.name }}" placeholder="{{ data.placeholder }}"></textarea>
			</div>
		</div>
		<# if ( data.description ) { #>
		<div class="elementor-control-field-description">{{{ data.description }}}</div>
		<# } #>
		<?php
	}

}
</pre>

</pre>

Insert below jQuery code in "emojionearea-control.js" and add js file in /assets/js/ folder

<pre>
jQuery( window ).on( 'elementor:init', function() {
	var ControlEmojiOneAreaItemView = elementor.modules.controls.BaseData.extend( {
		onReady: function() {
			var self = this,
				options = _.extend( {
					emojiPlaceholder: ':smile_cat:',
					pickerPosition: 'bottom',
					filtersPosition: 'top',
					searchPosition: 'bottom',
					saveEmojisAs: 'unicode',
					inline: false,
				}, this.model.get( 'emojionearea_options' ) );

			this.ui.textarea.emojioneArea( options );

		},

		saveValue: function() {
			this.setValue( this.ui.textarea.getText() );
		},

		onBeforeDestroy: function() {
			this.saveValue();
			this.ui.textarea.emojioneArea().destroy();
		}
	} );
	elementor.addControlView( 'emojionearea', ControlEmojiOneAreaItemView );
} );
</pre>

Insert below code in register_control function of custom widget

<pre>
$this->add_control(
	'emoji_control',
	[
		'label' => __( 'Content', 'elementor-hello-world' ),
		'type' => \Elementor_Addon_Test\Plugin::emojionearea,
		'default' => '',
	]
);
</pre>

To view emoji, we have added below code in our custom widget

```
protected function render() {
	$settings = $this->get_settings_for_display();
	?>
	<?php echo $settings['emoji_control']; ?>
	<?php
}

protected function _content_template() {
	?>
	{{{ settings.emoji_control }}}
	<?php
}
```

**Comment by mukeshpanchal27** [comment]
@shilo-ey any update on above?

**Comment by shilo-ey** [comment]
Hi @mukeshpanchal27 

Thanks for your feedback.

We have updated the above documentation and you are more than welcome to try it out.

Let us know if you still have issues.

Thanks

**Comment by mukeshpanchal27** [comment]
@shilo-ey Yup. updated changes fix the issue.

Thanks for fix it :smile:
