### ISSUE TITLE
Problem with excluded pages in multi language (WPML)

### ISSUE THREAD

**Issue by ProtocolNebula** [elementor/elementor#9008]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a dynamic footer in my site which show some listed pages using query *with exclude* (I can't use only include instead or filter by tag due pages functionallity), in the main language (spanish) works fine, but in translation show all pages (due has different IDs).

## Steps to reproduce

- Install WPML and configure in tow languages.
- Install elementor (pro optional).
- Create a template section or page.
- Add a dynamic block that show **pages** with some exclusions.
- Try to show in both languages.

**EXAMPLE:** https://ladygagamakeup.com/

In footer you will show **categories** section which in fact is a page list.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Possible improvement

Add inclusions instead only exclusions for page and show all (now are filtered by language) or use a filter by some special field.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
