### ISSUE TITLE
2.7.0b3 fatal error

### ISSUE THREAD

**Issue by kangarko** [elementor/elementor#9010]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description
![a](https://i.imgur.com/E6aKVUy.png)

## Steps to reproduce
Create a new page and hit Publish the first time. If I go back it does not happen again and the page appears to be published normally.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
![a](https://i.imgur.com/2zTRppV.png)

**Comment by shilo-ey** [comment]
Hi @kangarko 

Please update to the latest stable version of Elementor (v2.7) and see if the issue persists.

If it does, please contact our support in order to better debug this issue.

Thanks

**Comment by kangarko** [comment]
So I should downgrade instead, I don't see any 2.7 version I don't understand?
