### ISSUE TITLE
Form Widget (helpful text to add in tab)

### ISSUE THREAD

**Issue by cswebstuff** [elementor/elementor#9012]
Re: FORM WIDGET

This is a helpful "Text" addition for your user interface in the Form Widget.

1.)  When a user creates a new FORM.
2.)  In the "Content" area in Elementor, under the "Email" tab
3.) The "Subject" field should have added helpful text like this:
     Subject (adding a shortcode between "" displays the fields input - see field advanced tab)

Something like that.   Because I was trying for a while to figure out why adding in the ID for the field wasn't working, and it apparently needed a shortcode in there.    :-)

 That information is also not listed in your Elementor Docs for the Form Widget either. 

![Contact_Form_Widget_Suggestion_shortcode](https://user-images.githubusercontent.com/10590393/64444678-b4510a00-d0a2-11e9-8ae2-ea45add5e6e2.jpg)

**Comment by bainternet** [comment]
@cswebstuff 	

Thanks for the suggestion, 
we do have this in place:

> By default, all form fields are sent via [all-fields] shortcode. To customize sent fields, copy the shortcode that appears inside each field and paste it above.

right under the Message field, but I guess we can make it a bit more clear.

thanks again

**Comment by cswebstuff** [comment]
I think you may have misunderstood my posted suggestion…   

•	I was specifically talking about the "**Subject**" line text (not the main body picking up all the form message fields).  

•	If a developer wanted to dynamically display a users name in the email's "Subject" line, it's not really intuitive to know what to use because the default text in your field is this:

**New message from ""**   

- that to me suggested that I was supposed to use a field "ID" (which I tried but it didn't work).
 
So maybe just change your default text in that field to something like this:

**New message from "[name]"**    

- that would work right away when someone adds your basic Form widget, and at the same time let developers know to use shortcodes there.  :-)

**Comment by moonbeetle** [comment]
There is too much confusion.

Is it:
A. New message from "[name]"
B. New message from ["name"]
C. New message from [field id="name"]

PLEASE clarify this in your doc about using the form element. I see this so many times as a FAQ in the FB groups and I also always need to double check.
