### ISSUE TITLE
Custom Shape Doesn't Display in Editor

### ISSUE THREAD

**Issue by twmcmahan** [elementor/elementor#9013]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and  find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Adding Custom Shapes is resulting in shapes appearing on the front end but not in back end editor.

## Steps to reproduce
Code for Plugin:
```
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
$additional_shapes['acm-scurve'] = [
'title' => _x( 'S-Curve', 'Shapes', 'elementor' ),
'has_flip' => true,
'has_negative' => true,
'height_only' => false,
];

if(is_front_page()) {
     $additional_shapes['acm-scurve']['url'] = plugins_url('public/scurve.svg', __FILE__);
} else {
    $additional_shapes['acm-scurve']['path'] = plugin_dir_path(__FILE__) . 'public/scurve.svg';
}
return $additional_shapes;
});
```
I've tried passing just a 'path' attribute with both a path and uri.

SVG in Plugin Directory/public/scurve.svg:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">
	
<path class="elementor-shape-fill" d="M498-0c0,0,187.5,89.1,502,0"/>
</svg>`

## Environment

<details>
<summary>System Info</summary>
Latest elementor + elementor pro, running on multisite install.
```
</details>

**Comment by bainternet** [comment]
@twmcmahan 

You dont need to check if its the frontend or the editor, you need to add them both always, ex:
```php
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
	$additional_shapes['custom_shape_key'] = [
		'title' => 'My custom shape displayed name',
		'has_flip' => true,
		'height_only' => true,
		'path' => 'FULL/PATH/TO/SVG/FILE/SVG',
		'url' => 'https://FULL/TO/SVG/FILE.SVG',
	];

	return $additional_shapes;
});
```
so in your case it should be:

```php
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
    $additional_shapes['acm-scurve'] = [
        'title' => _x( 'S-Curve', 'Shapes', 'USE-A DIFFERENT-TEXT-DOMAIN' ),
        'has_flip' => true,
        'has_negative' => true,
        'height_only' => false,
        'url' => plugins_url ('public/scurve.svg', __FILE__),
        'path' => plugin_dir_path(__FILE__) . 'public/scurve.svg',
    ];
    return $additional_shapes;
} );
```
