### ISSUE TITLE
Can you create a "Restrict Access To Areas Of Your WordPress Website" widget?

### ISSUE THREAD

**Issue by eddatnite** [elementor/elementor#9015]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Q: In Elementor Pro: Can you create a "Restrict Access To Areas Of Your WordPress Website" widget?
I am attempting to add a login page for specific content pages. I want applicants to be able to access certain pages from a login screen in my WordPress site.

**Comment by bainternet** [comment]
@eddatnite 

Thanks for the suggestion, 
Currently, this feature is not supported, and we feel that this is more of a 3rd party plugin territory.

Thanks for the feedback.

**Comment by eddatnite** [comment]
Thanks guys...
