### ISSUE TITLE
Css id and Css classs in advenced tab dropped in template

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#9018]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I designed a section and in that section, I specified a css class in the advanced tab.

When I reuse that template on other pages, the template show up, but the css class is not there. I tried using the Id instead of the class, and the same problem happens.

## Steps to reproduce

1. Create a page and add a section with content.
2. In the advanced tab for the section, add a class in the Css class field.
3. Right click on the section handle and click Save as template.
4. Create a new page and add a widget template with the template just created.
5. Inspect the page and you won't find the css class that was in the original section.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
