### ISSUE TITLE
2.7.0b3 annoying custom CSS editing

### ISSUE THREAD

**Issue by kangarko** [elementor/elementor#9019]
I can't edit the custom CSS box properly. This annoying auto inserting of ; along with spaces acts like the Insert key but it renders it completely unusable and wastes time:

![fhSqOJ4dui](https://user-images.githubusercontent.com/1918426/64470973-bde27c80-d14b-11e9-8fc5-e43d603a6516.gif)

**Comment by shilo-ey** [comment]
Hi @kangarko 

Thanks for your feedback,

Unfortunately, we can't reproduce this issue.
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
