### ISSUE TITLE
Menu colouring

### ISSUE THREAD

**Issue by dartiss** [elementor/elementor#9021]
You’re using a coloured sub-menu option (“Go Pro”) – this can barely be read, depending on the Admin Colour Scheme that’s used, and is an accessibility issue.

The WordPress core default is to use non-coloured text which can be overridden by colour schemes – can you update the plugin to support this, please?

Here is an example of it using a specific colour scheme...

<img width="160" alt="Screenshot 2019-09-05 at 13 54 59" src="https://user-images.githubusercontent.com/14928971/64485744-24cf6680-d21c-11e9-89e6-8e438d7374f7.png">

**Comment by shilo-ey** [comment]
Hi @dartiss 

Thanks for your feedback.

In our latest versions, we altered the color of the Go Pro promotion to better comply with the accessibility rules.

In the next versions, we will address the color changes according to the color scheme selected.
