### ISSUE TITLE
How to Track "Button onClick" Event (for Facebook Pixel)

### ISSUE THREAD

**Issue by Mavenecom** [elementor/elementor#9028]
Hi
Your Support sends me to GitHub to get my issue solved. 

I got an issue with the script to Track an FB event on Button click. The Pixel is not firing when I use the script posted on https://docs.elementor.com/article/59-button
<script> 
document.addEventListener("DOMContentLoaded", function(event) { 
	jQuery('#My_Button a').click(function(){ 
	// tracking code here
	// for example Facebook Pixel: 
		fbq('track','AddToCart'); 
	}); 
	}); 
</script>

The script I'm using in the HTML field under the Button is:
<script> 
document.addEventListener("DOMContentLoaded", function(event) { 
	jQuery('order-now-1').click(function(){ 
 		fbq('track', 'AddToCart', {
    value: 12.95,
    currency: 'USD', 
	}); 
	}); 
</script>
The error I get on the FB Pixel Helper is:

Purchase

WARNINGS
We detected event code but the pixel has not activated for this event, so no information was sent to Facebook. This could be due to an error in the code, but could also occur if the pixel fires on a dynamic event such as a button click.Learn more
EVENT INFO
Pixel Code: Hide
fbq('track', 'Purchase', {
    value: 10.95,
    currency: 'USD 
	});
Pixel Location: Hide
https://mavenecom.com/cartflows_step/sealdome-upsell-stretchlid-set6-4-2/

Since I have no ideas about scripts somebody may just write an example script to show how it should be. 

Would be great is you guys could help me out with a solution

Thanks
Tilek

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
