### ISSUE TITLE
Facebook embed dynamic link

### ISSUE THREAD

**Issue by lucameglioli** [elementor/elementor#9030]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can't create a single post template with Facebook embed element inside it because that element doesn't support dynamic link.  

**Describe the solution you'd like**
I would like to have the possibility to use a dynamic link as I do in other elements like "SoundCloud" or "Video".

**Describe alternatives you've considered**
I need to duplicate all posts and change manually the Facebook links.

**Comment by shilo-ey** [comment]
So, what are you asking for?

Please be specific.

**Comment by lucameglioli** [comment]
What I'm asking for is that within the element "Facebook embed" in the field URL I can insert a dynamic url and not just a fixed one! 

I have attached two photos! The first one is what I can do with the element "SoundCloud" and the second one is what is missing with the element "Facebook embed".


![1](https://user-images.githubusercontent.com/48821528/64586290-2b84e780-d39c-11e9-918c-ad82cc17ac3b.JPG)
![2](https://user-images.githubusercontent.com/48821528/64586291-2b84e780-d39c-11e9-9059-be68f6afae26.JPG)

Thank you.
Luca

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!
