### ISSUE TITLE
Remove Action for edit_form_after_title

### ISSUE THREAD

**Issue by umnic** [elementor/elementor#9033]
I need to remove the elementor buttons from default post edit screen. What is the correct usage of the remove_action hook? In which action hook do I need to call it and with which classname?

I have this as a starting point but cant get it to work.

$classname= \Elementor\Plugin::instance();
remove_action("edit_form_after_title", array($classname,"print_swith_mode_button"));

Thanks!

**Comment by bainternet** [comment]
@umnic 	

There is no need to remove the action, you can simply go to Elementor >> Settings and uncheck "Posts" 
![image](https://user-images.githubusercontent.com/660572/64531578-896feb80-d318-11e9-8ad6-02624e3eb6a9.png)

**Comment by umnic** [comment]
Thanks @bainternet 
I should have been more precisely. I would like to remove only the buttons (as I have a different way of calling Elementor), but Elementor should work with these post types, I do not want to disable it for the posts
