### ISSUE TITLE
vertical align bug

### ISSUE THREAD

**Issue by Matanmu** [elementor/elementor#9034]
after update to 2.7.0 the vertical align is not working with safari both iphones and mac OS (it's align automatically to the top or not work at all, didn't have time to debug it, just make a rollback to v-2.6.8)
if you want i can make a duplicate website with the problem that you can debug it.

**Comment by shilo-ey** [comment]
Hi @Matanmu 

Thanks for your feedback,

We will take a look and address this issue soon.

thanks
