### ISSUE TITLE
Custom Widget: create file upon change/save/update

### ISSUE THREAD

**Issue by gpatelisld** [elementor/elementor#9036]
Hello!

I have created a custom widget which takes the settings (input fields) from the admin and creates a JS file with them. Right now this file is created on `render()` which obviously is a no-no. Are there any other ways to create/update this file in elementor editor environment, maybe upon save/update of the page?

**Comment by bainternet** [comment]
@gpatelisld 

try using wither 
https://github.com/elementor/elementor/blob/71943ef3357b84b460ff9799a9aee872c6b49ab5/core/base/document.php#L509-L519
or 
https://github.com/elementor/elementor/blob/71943ef3357b84b460ff9799a9aee872c6b49ab5/core/base/document.php#L552-L562
