### ISSUE TITLE
Toggle and Accordion title color cannot be changed

### ISSUE THREAD

**Issue by TheFirsh** [elementor/elementor#9038]
When using these blocks on v2.6.8 the title color control affects the icon and not the text. Seems like a copy-paste was left in from the icon color controls. Interestingly, the opacity affects both icon and text on these elements. Video: https://www.screencast.com/t/peLbfnooGuil

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.
We tried to reproduce your issue but without success.

Thanks.
