### ISSUE TITLE
Feature Request: Traditional Support Forum

### ISSUE THREAD

**Issue by jchornenky** [elementor/elementor#9039]
Maybe I'm just old, but git and facebook are both frustrating. Facebook moves too quickly and commonly addressed issues and solutions get lost. Git is not something I believe your "I'm just learning to use web stuff" finds accessible. It doesn't seem designed for tips and tricks, and learning to better user your tool.

Your software is often confusing, and video tutorials while helpful did not address many of the issues I am running into. A more traditional forum for discussion might allow your community some long term stability and make it easier for new users to adopt your software.

**Comment by bainternet** [comment]
@jchornenky 	

Thanks for the suggestion,
Github is not for "I'm just learning to use web stuff" it for bugs reports and feature requests and code replated help and discussions. 

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Other than that we are thinking about a more Traditional "Community Support Forum" but not sure **when** **if** and **how** it will work.

thanks for the suggestion.
