### ISSUE TITLE
Vertical Space Divider

### ISSUE THREAD

**Issue by finid** [elementor/elementor#9041]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'll like to have a vertical space divider between columns of a section, just as there already exist horizontal space divider between sections. 
**Describe the solution you'd like**
More visually appealing sections
**Describe alternatives you've considered**
None
**Additional context**

**Comment by bainternet** [comment]
@finid 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can use custom CSS to achieve that.

Thanks for the feedback.
