### ISSUE TITLE
Conditions class does not match its JS counterpart

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#9043]
JS Conditions function has contains 

https://github.com/elementor/elementor/blob/5d257d0455d17cd4dae7b1d0d21c73d11ecfafb2/assets/dev/js/editor/utils/conditions.js#L20-L23

which works right in the editor to check if the string is in the control that has array as value

```
				'conditions' => array(
					'terms' => array(
						array(
							'name' => 'meta_elements',
							'operator' => 'contains',
							'value' => 'author',
						),
					)
				)
```

this option does not exists in the php version of the Conditions class

https://github.com/elementor/elementor/blob/5d257d0455d17cd4dae7b1d0d21c73d11ecfafb2/includes/conditions.php#L33-L56

Although this works  in the editor to show/hide conditional controls,  the value is always null in the frontend because the missing cases.

A simple `in_array `would match both switches

```
			case 'contains':
				return false !== in_array($right_value,$left_value);
			case '!contains':
				return false === in_array( $right_value, $left_value );
```

**Comment by bainternet** [comment]
@danyj 

Thanks, 

Well be patched.
