### ISSUE TITLE
Background Slider - additional options

### ISSUE THREAD

**Issue by KONGSmash** [elementor/elementor#9044]
Would like the new background slider to include a continuous sliding option, so it would scroll sides way at a controlled pace without the speed up slow down between slides thing happening.

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Please be specific and provide examples

Thanks.
