### ISSUE TITLE
Please make "Remember Me" and "Lost your password?" translatable in login widget

### ISSUE THREAD

**Issue by Haraldjoh** [elementor/elementor#9046]
Thanks for a great service Elementor!

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using the login widget in Elementor Pro it is possible to translate some strings but not all. Namely: "Remember Me" and "Lost your password?"

Unfortunately, this makes our site look unprofessional.

**Describe the solution you'd like**
I would like to find a way to translate those strings. Either by added functionality in Elementor, or short term method such as PoEdit, LocoTranslate or similar. Just need these string translated.

**Describe alternatives you've considered**
First I posted the question in Elementor support and was then suggested to post the request here. I've looked into LocoTranslate and PoEdit for this issue, but I am afraid to break something since it does not find language files for Elementor Pro as for other plugins.

**Additional context**
![Skärmavbild 2019-09-10 kl  08 53 43](https://user-images.githubusercontent.com/55128569/64593361-41030d00-d3ae-11e9-8214-bf01bd146ff1.png)
_The lines are displayed on top and bottom of image. In middle a translated login button._

**Comment by Haraldjoh** [comment]
Also, when logged in strings are still in English: 
![Skärmavbild 2019-09-10 kl  10 20 17](https://user-images.githubusercontent.com/55128569/64596657-9cd09480-d3b4-11e9-89b1-ef8500cf5177.png)

**Comment by bainternet** [comment]
@Haraldjoh 	

All string mentioned here:
* Remember Me
* Lost your password?
* You are Logged in as X Logout

are all translatable strings already, simply make sure you have the translation files.

also see this:
https://docs.elementor.com/article/568-how-to-change-the-language-of-elementor-and-elementor-pro

**Comment by swisswebxperts** [comment]
@bainternet 

The problem is not that these strings are not translated. It's more some people would like to be able to change the already translated strings inside the widgets settings like it is available for the username and password labels:

![image](https://user-images.githubusercontent.com/796115/74753339-a79f2780-5278-11ea-8cfd-acf148844c96.png)

I suggest to reopen this issue and label it as feature request.

**Comment by eeprom-one** [comment]
Total needed, thanks +1

**Comment by Demiano** [comment]
Totally needed. I have tried to translate these strings with PoEdit, but it seems they are not accessible.

**Comment by dimoteca** [comment]
If only those quick wins were implemented in a few months instead of a few years... +1

**Comment by vogelmy** [comment]
+1 +1 +1

**Comment by mstroeve** [comment]
This is ridiculous why can't we change these labels

**Comment by Cheizr** [comment]
So where are we at? I can't use the loding widget because of the language....

**Comment by Cheizr** [comment]
Well i had to fix it using jquery... 

<script>
	jQuery(document).ready(function($){
  $('label').html(function (i, html) {
    return html.replace('Remember Me', 'Recordar sesión');
		});
	$('a.elementor-lost-password').html('Olvidé mi contraseña');
	});
</script>

Hope it helps...

**Comment by loiclecolier** [comment]
> 

Thank you ! I added the script thanks to the "HTML" element that I integrated at the end of my page.

**Comment by loiclecolier** [comment]
> Well i had to fix it using jquery... I'm using a condition to only apply to my account page
> 
> ```
> <script>
> 	jQuery(document).ready(function($){
>   $('label').html(function (i, html) {
>     return html.replace('Remember Me', 'Recordar sesión');
> 		});
> 	$('a.elementor-lost-password').html('Olvidé mi contraseña');
> 	});
> </script>
> ```
> 
> Hope it helps...

Thank you ! I added the script thanks to the "HTML" element that I integrated at the end of my page.

**Comment by leatonvof** [comment]
Just wanted to chime in for anyone struggling.. There is actually an option to change these within Elementor but it's hard to find: 
![image](https://github.com/elementor/elementor/assets/55189982/413de2b8-7362-4dc2-a4b2-596242e9dbe3)

**Comment by dannycarlsen** [comment]
> Just wanted to chime in for anyone struggling.. There is actually an option to change these within Elementor but it's hard to find: ![image](https://user-images.githubusercontent.com/55189982/277096118-413de2b8-7362-4dc2-a4b2-596242e9dbe3.png)

Where did you find this in the editor?

**Comment by LykPapa** [comment]
It is not a matter of translating. One may simply want to use different wording.

You are able to change the username/password labels/placeholders but nothing more.

Not sure why the issue is closed since nothing has changed.

**Comment by TjoheiPatrick** [comment]
Can someone please tell me where 

> > > Just wanted to chime in for anyone struggling.. There is actually an option to change these within Elementor but it's hard to find: ![image](https://user-images.githubusercontent.com/55189982/277096118-413de2b8-7362-4dc2-a4b2-596242e9dbe3.png)
> > 
> > 
> > Where did you find this in the editor?
> 
> So, anyone knows where to change the username/password labels/placeholders?

Where is this? Why is it not fixed yet??

**Comment by dudleydelgado** [comment]
Una opción simple es que con el plugin "[loco translate](https://es.wordpress.org/plugins/loco-translate/)" creés una plantilla para generar el archivo .PO en el plugin elementor pro, luego solo tenéis que buscar la cadena de texto "reset password" y modificarla por lo que queráis. No lleva más de 5 minutos realizarlo.
