### ISSUE TITLE
Form Widget - Email Dynamic Tags

### ISSUE THREAD

**Issue by RedGuardAgency** [elementor/elementor#9051]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As loyal Elementor users we are often find it frustrating not to be able to use a Dynamic Tag feature in some fields of Elementor Form Widget. Especially when it comes to E-mail. During developing process of several projects using many custom form fields with no possible application of templates or global widget features, we find it very ineffective and frustrating to be forced to fill same Emails again and again for every form widget we have placed. It's becoming too hard to keep track of them.

**Describe the solution you'd like**
This is a request to simply add a Dynamic Tag feature for every possible field of Email section of Form Elementor widget content tab, such as following: "Email to", "Email Subject", "From Email", "From Name", "Copy" , "Hidden copy" etc. We are aware that the task itself may not be as simple as we are putting it, though. 

**Describe alternatives you've considered**
We have tried using shortcodes in fields, but it does not work at the time. No other solutions were considered at the time, other than developing a custom code for this purpose only which is a too time consuming alternative for our deadline schedules.

**Additional context**
Your magnificent dev team have already added a Dynamic Tag to one of the Form Widget field  - "Redirect To", which is highly appreciated. We are eagerly awaiting of other extra Tags we are requesting in this ticket. 

As an example of why this request is being written, here's one. We are using Crocoblock JetEngine 'family' of plugins, which are awesome for Elementor users and have to be considerd for reviewing in your blog and YT channel. It allows to create and edit Custom Post Types and WordPress Options pages (in last update). We want to have an extra Options page filled with metafields that will be connected to form widgets and others, to be able to add new Emails and edit other strings we need to edit in a fast and efficient way. Our pipeline includes a custom theme and an out-of-the-box WordPress assembly with scrupulously pre-selected list of plugins, snippets and hooks, as we are huge fans of sorting and optimizing everything we can. Adding described Dynamic Tags would save a lot of time and would be much appreciated, as we appreciate every new update of our beloved Elementor. 

Thank you for your time and effort. 

Respectfully,
Red Guard.

**Comment by lucafagherazzi** [comment]
Will it be added in the next milestone? It would be appreciated! Thank you.

**Comment by onlykingjoe** [comment]
+1,000,000 I signed up to github to ask for exactly this! It's shocking this isn't implemented already. Every Elementor field should have dynamic options, but the email field to me seems crazy to be left out.

**Comment by kskonovalov** [comment]
+1 sometimes it's must have!

**Comment by Luxamman** [comment]
As a paying agency since years still waiting and being ignored...? This is of course a very important feature for a lot of use cases and no progress or answer for two years... Please at least tell us something like why this isn't happening or how we can workaround that. Thanks!

**Comment by bevanjkay** [comment]
+1 for this. Would love to be able to set global options for forms.

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
