### ISSUE TITLE
ACF dynamic field

### ISSUE THREAD

**Issue by lucafagherazzi** [elementor/elementor#9064]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When I create a button to call I have to enter 2 ACF fields, one with the mobile number and the other with the text "tel:" followed by the same mobile number; I wish I could only enter the mobile number once.

**Describe the solution you'd like**
I would like to know if in the button widget and in the icons list widget you can add the simple ACF dynamic field as in the video widget.

**Describe alternatives you've considered**
I use 2 ACF fields.

**Additional context**
Plugin used
Elementor - Elementor Pro - ACF

![01](https://user-images.githubusercontent.com/40598133/64766335-26639c00-d546-11e9-8602-56171e017d06.jpg)

![02](https://user-images.githubusercontent.com/40598133/64766360-2fed0400-d546-11e9-9a62-6bf92c1a8867.jpg)

**Comment by bainternet** [comment]
@lucafagherazzi 	

Currently, this is just our dynamic tags work, each field from ACF, Pods, toolset is mapped to the corresponding elementor control.

meaning that an `ACF LINK field` is connected to Elementors' `URL control` and an `ACF TEXT field` is connected to Elementors' `Text control`.

Thanks.
