### ISSUE TITLE
Cmd-E shortcut no longer works (Finder function)

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#9067]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In the latest version of Chrome for Mac, Command-E is assigned to a menu shortcut (Edit > Find > Use selection for Find) so Elementor Finder no longer opens. 

Perhaps Elementor could have a customise setting to change the shortcut to something else, or alternatively find an unused key combo?

## Steps to reproduce

1. Open Chrome 
2. Work in Elementor
3. Press Cmd-E (nothing happens)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

I am using Chrome Version 76.0.3809.132 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/1435638/64843084-462cba00-d643-11e9-9b2d-8416b69c30a3.png)

**Comment by DorShahar** [comment]
Hi
Sorry for the late response.
In case the issue persists with the latest version of Elementor, feel free to open a new task.
Currently, we couldn't find a problem with the Finder.

Thanks.

**Comment by drawcard** [comment]
Can confirm, fixed in Chrome v92

**Comment by Dyo131** [comment]
There is also an option on the WordPress userspannel to switch keyboard shortcuts on or off per user. This is standard set to off for lower tier users.
