### ISSUE TITLE
Icon-box Responsive Icon Alignment

### ISSUE THREAD

**Issue by wasduman** [elementor/elementor#9069]
Hi,

there is no icon alignment option for other devices. It works nicely on desktops but not on other devices.

Smartphone:
![Screenshot1](https://user-images.githubusercontent.com/54278187/64855762-e1f8fe80-d620-11e9-97de-0eb4b5dfda20.png)

Desktop:
![Screenshot2](https://user-images.githubusercontent.com/54278187/64855936-38fed380-d621-11e9-921e-dda62d4b1788.png)

I tried to display inline and float left but it was not like I wanted.
Are there any other solutions?

**Comment by arielk** [comment]
Duplicate of https://github.com/elementor/elementor/issues/3040
