### ISSUE TITLE
[Feature Request] - woocommerce: add "number of products to display" option for each breakpoint for the Product widget

### ISSUE THREAD

**Issue by mr-moto** [elementor/elementor#9076]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Currently the Product widget displays the original amount of items based on how many columns/rows ( 5 columns, 1 row will display 5 items, 6 columns 6 items etc ) at every breakpoint without a way to choose how many items to display.
if 6 items are shown in desktop, 6 items will show in tablet and mobile with no way to change how many items are shown at the other breakpoints.

**Describe the solution you'd like**

Provide a way to specify how many items to show at each breakpoint.

**Describe alternatives you've considered**

Hiding items via css ( not optimal )

**Additional context**

**Comment by bainternet** [comment]
@mr-moto 	

Elementor Pro products widget is based on the native WC products shortcode, so as long as WC products widget won't support items per breakpoint this can only be done via either custom coding or like you said with custom CSS.

Also just so you know that even if they did have support for something like that the items will still be hidden in the page via CSS.

Thanks for the suggestion.
