### ISSUE TITLE
Feature Request: rel nofollow and rel sponsored

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#9079]
**Google Webmaster Central Blog**: [Evolving “nofollow” – new ways to identify the nature of links](https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html)

Currently Elementor [URL Control ](https://github.com/elementor/elementor/blob/master/includes/controls/url.php) supports **rel="nofollow"**.

Now let's implement the new **rel="sponsored"** attribute.

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Support google's new rel attribute to mark links on that were created as part of advertisements or sponsorships. To increase SEO.

**Describe the solution you'd like**
Add new checkbox to URL control to add this rel attribute to a link.

https://github.com/elementor/elementor/blob/master/includes/controls/url.php

![links](https://user-images.githubusercontent.com/576623/64913275-b4f23c00-d745-11e9-9410-5c8cfd74b974.png)

**Additional context**
This can make Elementor a leader in SEO solution adoption with state of the are features and the latest web standards.

@arielk @joshmarom @kobizz @bainternet @KingYes @matipojo

**Comment by shimsa** [comment]
+1

**Comment by deckerweb** [comment]
Google also added the "ugc" attribute, which stands for "User Generated Content" -- so if Elementor team is on it already, then it should be an essential solution to cover all new Google attributes and make it extendable/filterable for developers as well. This would be a future proof solution then.

Thanks a lot in advance! :-)

**Comment by Jordidriesen** [comment]
Need this asap! Essential SEO features can't wait for multiple versions to be released.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!
