### ISSUE TITLE
allow html in animated headline text

### ISSUE THREAD

**Issue by knireis** [elementor/elementor#9082]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I need to break the text of the headline so it looks better on mobile. With the normal title element i can add a <br>, but in the animated headline the html is just printed as text.

I have not found a workaround or other solution.

**Comment by knireis** [comment]
funny, this editor does accepts html so the 'br' as i typed in the first post is not shown anymore as text

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
