### ISSUE TITLE
multiple post type related with the same taxonomie

### ISSUE THREAD

**Issue by mecalife** [elementor/elementor#9088]
Hello, 

I would like to be able to display items of different post type related to the taxonomy "city".
each type post has the taxonomy "city".

currently the configuration is as follows:

source : related
include by : term
term: city

unfortunately they only display items of the same post type and no additional post type display when everything is well configured

currently I am on version 2.6.7 and 2.6.5 pro

I didn't update to 2.7.1 because I have 500:s errors

thanks :-)

**Comment by bainternet** [comment]
@mecalife 	

this can be easily done via [`custom query filter`](https://developers.elementor.com/custom-query-filter)

see this https://developers.elementor.com/custom-query-filter/#Multiple_Post_Types_in_Posts_Widget

hope this helps.
