### ISSUE TITLE
Template - Categories - same name as Posts - Categories - reserved name

### ISSUE THREAD

**Issue by PeterInGitHub** [elementor/elementor#9094]
after a few years of using the word “category” in “posts”, then both become reserved words with special reserved meaning, in the same way as “posts” has a reserved meaning from “pages”.  However in Elementor you have used this reserved word “category” in two different places for two slightly different technical meanings.  We cannot select posts according to the “category” that is in the templates section and when switching to Elementor we expect to filter on “category” reserved for posts.  All I am suggesting is for you to use a different label for the word “category” that is used to differentiate between templates, eg “template category” or “groups”
Peter

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arielk** [comment]
I'm closing an issue due to inactivity.
Thanks!
