### ISSUE TITLE
Gallery to display image "filename" instead of "Caption"

### ISSUE THREAD

**Issue by PeterInGitHub** [elementor/elementor#9095]
The Elementor Basic Gallery allows an image grid with the option of Style - Caption.  In WPBakery I can have the filename shown instead of using the caption.  When I save images I give them a descriptive filename that is used in the PC File Explorer - and Wordpress copies the full filename into the Media Folder which your Elementor Basic Gallery then shows But you do not allow the filename to be shown  below the image in the Image Gallery.  Please either allow this to happen in future versions or tell me what widget may provide this function.  ps I have 1800 images so copying the filename to the caption is not an option!

However, there is a plugin that will copy the filename to the caption and alt, but this plugin should either be recommended by you on your "addons" page or integrated into future releases.
see "Automatically add Image attributes such as Image Title, Image Caption, Description And Alt Text from Image Filename. The plugin can update image attributes for both new images and existing images in the media library." at https://wordpress.org/plugins/auto-image-attributes-from-filename-with-bulk-updater/

**Comment by shilo-ey** [comment]
Hi @PeterInGitHub 
I merged this issue with  #4279, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

BTW, when selecting "Title" - the file name is the default value

Thanks for your feedback!
