### ISSUE TITLE
My Templates - Name - need to be able to edit the names of my templates

### ISSUE THREAD

**Issue by PeterInGitHub** [elementor/elementor#9096]
When I save my templates on different days, I name them slightly differently and so when I look for them in my templates list, they are not organised.  eg on one day I may name "Image grid small" and another day "Pics grid medium"
If you allow Templates - My Templates ... Edit name, then I can organise the template names better.
Also, when I want to save a template, then at the point I want to name it, it would be useful to see a grid of the names of the templates that I have already made so that I can be consistent in my naming.

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deckerweb** [comment]
You can always edit the Template names under "Saved Templates" (former "My Templates") like any other Post or Page or Post Type in WordPress:
your-wp-install/wp-admin/edit.php?post_type=elementor_library&tabs_group=library

Elementor also allows you to Categorize the Templates in this table - you assign a category like for posts. You can then also filter in this post type list table after these categories.

**Comment by bainternet** [comment]
@PeterInGitHub 

Thanks for the suggestion but as @deckerweb said its already possible: 

[**@deckerweb**](https://github.com/deckerweb) commented on [Sep 16, 2019, 11:37 AM GMT+3](https://github.com/elementor/elementor/issues/9096#issuecomment-531687631 "2019-09-16T08:37:11Z - Replied by Github Reply Comments"):
> You can always edit the Template names under "Saved Templates" (former "My Templates") like any other Post or Page or Post Type in WordPress:
> your-wp-install/wp-admin/edit.php?post_type=elementor_library&tabs_group=library
> 
> Elementor also allows you to Categorize the Templates in this table - you assign a category like for posts. You can then also filter in this post type list table after these categories.
