### ISSUE TITLE
License Key for Dev environment

### ISSUE THREAD

**Issue by GraphanixDziner** [elementor/elementor#9098]
Currently there is only 1 License Key. We need a License Key for a dev environment from the localhost or a staging server.

Currently I cannot use the License Key on both my localhost/staging environment and on my Live hosting server.

We need to have a Dev License Key and a Prod License Key.

**Comment by Aviad-Herman** [comment]
Hey,
I know this is an old issue.
Currently the only options we offer is to create the staging env. on a subdomain with a specific name:
https://elementor.com/help/do-i-need-a-license-for-my-subdomain/

or alternatively get a license that supports several sites.
