### ISSUE TITLE
Typekit fonts not applied when set as default

### ISSUE THREAD

**Issue by nicomollet** [elementor/elementor#9100]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Typekit fonts are not loaded in frontend when adding a typekit font as a "global" font.

## Steps to reproduce

1. Check "Disable default fonts" (the bug still happens when unchecked)
2. Add a Typekit project ID
3. Synchronize the font project
4. Edit an Elementor page
5. Go to "Defaut Fonts"
6. Add a Typekit font to the "main headings"
7. The font is correctly applied in the backend preview
8. The font is *not* applied  in the frontend page

Typekit CSS is not loaded in the HTML source so this is the source of the problem.
The function `print_font_link` requires a parameter but is called without param in an action.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian) mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_fcgid/2.3.9
	MySQL version: (Debian) v5.5.46
	PHP Version: 7.1.4-1+0~20170411221130.22+jessie~1.gbp4ea64a
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: http://wordpress.l
	Home URL: http://wordpress.l
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Active

== Theme ==
	Name: Thalasso 2018 OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.7.1
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.8.2
		Author: Elliot Condon

	Breadcrumb NavXT
		Version: 6.3.0
		Author: John Havlik

	Cookie Notice
		Version: 1.2.46
		Author: dFactory

	Disable Gutenberg
		Version: 1.9
		Author: Jeff Starr

	Easy Updates Manager
		Version: 8.0.5
		Author: Easy Updates Manager Team

	Ele Custom Skin
		Version: 1.2.5
		Author: Dudaster.com

	Elementor
		Version: 2.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.5
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.12
		Author: rocketgenius

	Mailjet for WordPress
		Version: 5.1.3
		Author: Mailjet SAS

	Ocean Extra
		Version: 1.5.16
		Author: OceanWP

	Ocean Modal Window
		Version: 1.0.14
		Author: OceanWP

	Polylang Pro
		Version: 2.3.4
		Author: Frédéric Demarle

	Product Open Pricing (Name Your Price) for WooCommerce
		Version: 1.4.0
		Author: WP Wham

	Rank Math SEO
		Version: 1.0.32.1
		Author: Rank Math

	TMSM Admin Cleanup
		Version: 1.1.3
		Author: Nicolas Mollet

	TMSM Customer Alliance
		Version: 1.0.11
		Author: Nicolas Mollet

	TMSM Frontend Optimizations
		Version: 1.1.5
		Author: Nicolas Mollet

	TMSM Gravity Forms DialogInsight Add-On
		Version: 1.0.3
		Author: Nicolas Mollet

	TMSM Gravity Forms Restaurant
		Version: 1.0.4
		Author: Nico Mollet

	TMSM Resaweb Integration
		Version: 1.0.7
		Author: Nicolas Mollet

	TMSM WooCommerce Billing Fields
		Version: 1.0.5
		Author: Nicolas Mollet

	TMSM WooCommerce Booking Thalasso
		Version: 1.1.17
		Author: Nicolas Mollet

	TMSM WooCommerce Payline by Monext Payment Gateway
		Version: 1.4.5
		Author: Nicolas Mollet

	TMSM WooCommerce Shipped Status
		Version: 1.0.1
		Author: Nicolas Mollet

	TMSM WooCommerce Vouchers
		Version: 1.1.9
		Author: Nicolas Mollet

	WooCommerce
		Version: 3.7.0
		Author: Automattic

	WooCommerce Beta Tester
		Version: 2.0.1
		Author: WooCommerce

	WooCommerce Email Validation
		Version: 2.1.1
		Author: Hugh Lashbrooke

	WP Crontrol
		Version: 1.7.1
		Author: John Blackbourn & crontributors

== Log ==
	
JS: showing 3 of 3JS: 2019-05-22 07:47:08 [error X 7][http://wordpress.l/wp-content/plugins/ocean-modal-window/assets/js/main.min.js?ver=1.0.13:59:3] oceanwpLocalize is not defined 
JS: 2019-06-17 09:46:48 [error X 1][http://wordpress.l/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.15:2:8507] Cannot read property \'select2\' of undefined 
JS: 2019-08-06 15:24:25 [error X 3][http://wordpress.l/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.7:7:49874] Cannot set property \'controls\' of undefined 

Log: showing 20 of 362019-08-06 17:17:30 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-08-06 17:17:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.7',
)]
2019-08-06 17:17:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.7',
)]
2019-09-02 15:21:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.2',
  'to' => '2.6.5',
)]
2019-09-02 15:21:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.7',
  'to' => '2.7.0-beta1',
)]
2019-09-02 15:21:20 [info] elementor::elementor_updater Started 
2019-09-02 15:21:20 [info] Elementor/Upgrades - _v_2_7_0_rename_document_types_to_wp Start  
2019-09-02 15:21:20 [info] Elementor/Upgrades - _v_2_7_0_rename_document_types_to_wp Finished 
2019-09-02 15:21:20 [info] Elementor/Upgrades - _v_2_7_0_remove_old_usage_data Start  
2019-09-02 15:21:20 [info] Elementor/Upgrades - _v_2_7_0_remove_old_usage_data Finished 
2019-09-02 15:21:20 [info] Elementor/Upgrades - _v_2_7_0_recalc_usage_data Start  
2019-09-02 15:21:21 [info] Elementor/Upgrades - _v_2_7_0_recalc_usage_data Finished 
2019-09-02 15:21:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.7',
  'to' => '2.7.0-beta1',
)]
2019-09-16 11:22:52 [info] elementor::elementor_updater Started 
2019-09-16 11:22:52 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-16 11:22:52 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-16 11:22:52 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-16 11:22:52 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-16 11:22:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.0-beta1',
  'to' => '2.7.2',
)]
2019-09-16 11:22:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.0-beta1',
  'to' => '2.7.2',
)]

PHP: showing 3 of 3PHP: 2019-06-17 14:35:34 [error X 9][/home/nico/Public/sites/wordpress/wp-content/plugins/elementor/core/dynamic-tags/manager.php::257] Uncaught Error: Class 'Elementor_Tag_DiscoveryPrice' not found in /home/nico/Public/sites/wordpress/wp-content/plugins/elementor/core/dynamic-tags/manager.php:257
Stack trace:
#0 /home/nico/Public/sites/wordpress/wp-content/plugins/tmsm-woocommerce-booking-thalasso/public/class-tmsm-woocommerce-booking-thalasso-public.php(453): Elementor\Core\DynamicTags\Manager->register_tag('Elementor_Tag_D...')
#1 /home/nico/Public/sites/wordpress/wp-includes/class-wp-hook.php(286): Tmsm_Woocommerce_Booking_Thalasso_Public->elementor_tags_register(Object(Elementor\Core\DynamicTags\Manager))
#2 /home/nico/Public/sites/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /home/nico/Public/sites/wordpress/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /home/nico/Public/sites/wordpress/wp-content/plugins/elementor/core/dynamic-tags/manager.php(243): do_action('elementor/dynam...', Object(Elementor\Core\DynamicTags\Manager))
#5 /home/nico/Public/sites/wordpress/wp-content/plugins/element [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-16 17:11:51 [error X 1][/home/nico/Public/sites/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php::218] Cannot redeclare ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Typekit_Fonts::print_font_link() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-16 17:17:38 [error X 5][/home/nico/Public/sites/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php::202] Uncaught ArgumentCountError: Too few arguments to function ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Typekit_Fonts::print_font_link(), 0 passed in /home/nico/Public/sites/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php on line 260 and exactly 1 expected in /home/nico/Public/sites/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php:202
Stack trace:
#0 /home/nico/Public/sites/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php(260): ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Typekit_Fonts->print_font_link()
#1 /home/nico/Public/sites/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/classes/assets-base.php(356): ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Typekit_Fonts->actions()
#2 /home/nico/Public/sites/wordpress/wp-content/plugins/elementor-pro/modules/assets-manager/classes/font-base.php(18): ElementorPro\Modules [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elements Usage ==
	
	archive
		archive-posts : 1
		portfolio : 1
		posts : 1
		theme-archive-title : 1
	footer
		button : 1
		text-editor : 1
	header
		nav-menu : 1
		theme-site-logo : 1
	loop
		button : 1
		heading : 2
		text-editor : 3
	page
		button : 3
		posts : 1
		text-editor : 1
	popup
		heading : 1
		image : 1
	single
		button : 3
		heading : 7
		image-carousel : 1
		posts : 1
		text-editor : 13
	wp-page
		button : 5
		form : 1
		heading : 1
		image-gallery : 1
		text-editor : 7
		wc-add-to-cart : 1
	product-archive
		theme-archive-title : 1
		woocommerce-archive-products : 1

				
</details>

**Comment by jak-kal** [comment]
Also experiencing the same issue on a fresh version of Wordpress, Elementor (+ Pro) and Typekit. Exactly the same issue.

Did you perhaps manage to find a resolution?

**Comment by jak-kal** [comment]
Apologies for the double post - but no longer experiencing this issue!

I managed to _fix_ it by regenerating the CSS in Elementor > Tools (see screenshot below!).

Not sure why this is necessary given that Typekit is generally included via a `<link/>` tag - not using a CSS import - but oh well!

![image](https://user-images.githubusercontent.com/34679006/78424442-6a92c700-7665-11ea-92a0-00682e674278.png)

**Comment by lioncatde** [comment]
Same issue here, regenerating CSS didn't help
