### ISSUE TITLE
Elementor should only load modules active on each page (when not in edit mode)

### ISSUE THREAD

**Issue by therealgilles** [elementor/elementor#9105]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor is loading modules which are not used on the current page (or any pages for that matter), slowing the page load time.

Here is a screenshot showing an xdebug profiling call tree extract:

<img width="842" alt="Screen Shot 2019-09-16 at 6 29 24 PM" src="https://user-images.githubusercontent.com/18076992/65004166-4da4cb00-d8b0-11e9-9b92-7319f98e01a4.png">

The widgets get_scheme_controls functions are being called even though I am not using any of them (and I am sure more widgets functions are called too).

## Steps to reproduce
Load any page, even one without any elements.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Any site using elementor will do.

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by black-eye** [comment]
+1

**Comment by goldenpony89** [comment]
+1

**Comment by Aviad-Herman** [comment]
Hi @therealgilles 
We are iteratively improving asset loading and including the changes in this Experiment (Elementor --> Settings --> Experiments)
![image](https://user-images.githubusercontent.com/73067562/121845661-727cdb00-ccee-11eb-9c0d-ade0180ec005.png)

Currently it's in Alpha but keep tuned :)

**Comment by therealgilles** [comment]
@Aviad-Herman: Thank you for the update. Would you know how this interacts with caching plugins?

**Comment by Aviad-Herman** [comment]
We do internal QA tests but if you find a bug with a specific plugin please share and we'll work to fix it.
