### ISSUE TITLE
Latest update to 2.7.1 or 2.7.2 hangs Elementor editing

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#9106]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
`					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.27
	PHP Version: 7.1.32
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: https://testhosting.co.uk/sherratt
	Home URL: http://testhosting.co.uk/sherratt
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: /%postname%
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Sherrat
	Version: 1.0
	Author: 
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.7.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.2
		Author: Elementor.com

== Log ==
	
Log: showing 20 of 212019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-08-08 09:06:20 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-08-08 09:06:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.6.2',
)]
2019-08-08 09:06:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.6.2',
)]
2019-08-19 14:15:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.2',
  'to' => '2.6.3',
)]
2019-09-05 11:32:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.3',
  'to' => '2.6.5',
)]
2019-09-17 07:32:10 [info] elementor::elementor_updater Started 
2019-09-17 07:32:10 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-17 07:32:10 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-17 07:32:10 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-17 07:32:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-09-17 07:32:10 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-17 07:32:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]

JS: showing 20 of 20JS: 2019-08-12 14:28:02 [error X 3][https://testhosting.co.uk/sherrat/wp-content/plugins/elementor/assets/js/editor-modules.min.js:2:37050] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `project_thumb_image` value. Expected array or object.',
)]
JS: 2019-08-12 14:28:56 [error X 2][https://testhosting.co.uk/sherrat/wp-content/plugins/elementor/assets/js/editor-modules.min.js:2:37050] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `tgx_slider_3_image` value. Expected array or object.',
)]
JS: 2019-08-12 14:28:56 [error X 2][https://testhosting.co.uk/sherrat/wp-content/plugins/elementor/assets/js/editor-modules.min.js:2:37050] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.themesgrove.com> as `tgx_slider_3_button_link` value. Expected array or object.',
)]
JS: 2019-08-12 14:29:11 [error X 4][https://testhosting.co.uk/sherrat/wp-content/plugins/elementor/assets/js/editor-modules.min.js:2:37050] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `slider_image` value. Expected array or object.',
)]
JS: 2019-08-12 14:29:20 [error X 2][https://testhosting.co.uk/sherrat/wp-content/plugins/elementor/assets/js/editor-modules.min.js:2:37050] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `slider_animation_image` value. Expected array or object.',
)]
JS: 2019-08-13 14:40:21 [error X 2][https://testhosting.co.uk/sherrat/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:22652] Cannot read property \'children\' of undefined 
JS: 2019-08-19 14:20:01 [error X 1][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view502\") has already been destroyed and cannot be used. 
JS: 2019-08-19 14:23:42 [error X 1][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view2737\") has already been destroyed and cannot be used. 
JS: 2019-08-19 18:12:57 [error X 1][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view505\") has already been destroyed and cannot be used. 
JS: 2019-08-20 08:14:36 [error X 2][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view513\") has already been destroyed and cannot be used. 
JS: 2019-08-20 13:38:26 [error X 3][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:46889] Cannot read property \'get\' of undefined 
JS: 2019-08-20 14:08:43 [error X 5][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/slick/slick.min.js:1:19335] Cannot read property \'add\' of null 
JS: 2019-08-20 14:49:39 [error X 1][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view1111\") has already been destroyed and cannot be used. 
JS: 2019-08-20 15:29:00 [error X 7][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view538\") has already been destroyed and cannot be used. 
JS: 2019-08-21 08:07:22 [error X 1][https://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view606\") has already been destroyed and cannot be used. 
JS: 2019-09-04 14:59:47 [error X 3][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view522\") has already been destroyed and cannot be used. 
JS: 2019-09-04 15:37:01 [error X 2][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view541\") has already been destroyed and cannot be used. 
JS: 2019-09-05 10:51:01 [error X 1][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view1673\") has already been destroyed and cannot be used. 
JS: 2019-09-05 11:52:37 [error X 1][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view536\") has already been destroyed and cannot be used. 
JS: 2019-09-17 07:52:27 [error X 2][http://testhosting.co.uk/sherratt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.2:7:49506] Cannot set property \'controls\' of undefined 

PHP: showing 1 of 1PHP: 2019-09-17 07:32:11 [warning X 1][/home/hakunamatata/public_html/sherratt/wp-content/plugins/elementor/modules/usage/module.php::481] Division by zero [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elements Usage ==
	
	Post
		Accordion : 7
		Button : 4
		Call to Action : 7
		Counter : 3
		Form : 2
		Global : 2
		Google Maps : 1
		Heading : 24
		Icon : 2
		Icon Box : 2
		Image : 6
		Image Box : 10
		Posts : 1
		Shortcode : 2
		Slides : 1
		Spacer : 6
		Text Editor : 10
	Theme - Single
		Featured Image : 1
		Global : 1
		Heading : 7
		Post Content : 3
		Post Excerpt : 1
		Post Info : 1
		Post Title : 1
		Shortcode : 1
	Theme - Header
		Heading : 1
		Icon : 1
		Image : 1
		Nav Menu : 3
		Search Form : 1
	Theme - Footer
		Heading : 7
		Icon : 1
		Icon List : 2
		Image : 2
		Nav Menu : 1
	Popup - Popup
		Button : 1
		Heading : 9
		Icon : 5
	Library - Section
		Button : 1
		Counter : 3
		Global : 1
		Heading : 3
		Spacer : 1

				`
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

Just updated to the latest Elementor version (2.7.1) this morning, now I can’t edit or create any pages in Elementor. Editor just hangs…

I did notice the following comment in the system info log section….

“…plugins/elementor/assets/js/editor.min.js?ver=2.7.1:7:49498] i is undefined ”

Also can't roll back to the previous version.

I see more people have this issue:
https://wordpress.org/support/topic/latest-update-to-2-7-1-hangs-elementor-editing/

```
Uncaught TypeError: Super expression must either be null or a function
    at _inherits (editor.min.js:2)
    at editor.min.js:7
    at Object.<anonymous> (editor.min.js:7)
    at __webpack_require__ (editor.min.js:2)
    at Object.<anonymous> (editor.min.js:7)
    at __webpack_require__ (editor.min.js:2)
    at Object.<anonymous> (editor.min.js:7)
    at __webpack_require__ (editor.min.js:2)
    at Object.<anonymous> (editor.min.js:7)
    at __webpack_require__ (editor.min.js:2)
```

**Comment by latheeshvmv** [comment]
+1 Having the same issue

**Comment by amindiary** [comment]
Our websites getting errors, no reply yet?

**Comment by shilo-ey** [comment]
Hi @amindiary 

Please update to the latest version of Elementor (v2.7.4) and see if the issue persists.

If not - please contact our support for better debugging.

Thanks!
