### ISSUE TITLE
The problem is when you insert a "Divider" without specifying a color

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#9112]
If you insert the widget "Divider" without specifying the color: https://www.screencast.com/t/6B2niFKv , we get this CSS markup: https://www.screencast.com/t/HqeX2ndL
This causes the line not to be displayed at all.
And inserting widgets in this way is convenient if the theme itself sets the default color for the dividers. So that if necessary, the user can change the color in one place, and not change it on all pages of the site.
Along the way, I want to make a General observation: in the last updates you changed the approach to specifying default widget styles and made it impossible to replace these styles to the theme styles! 
Consider the example of the widget "Divider": if before updates the default color was set for the selector".elementor-divider-separator", which allowed the theme to override it. And when the user choose a different color - increased the length of the selector and the new color had priority. Now when user change the color you change the css variable "--divider-border-color " inside the selector with the same length! It is very inconvenient for the theme authors!

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
