### ISSUE TITLE
Column spillover and stacking

### ISSUE THREAD

**Issue by BRValentine** [elementor/elementor#9120]
In Elementor build view, the layout is lovely and just as advertised from the Astra Sites/Elementor template I used:
![3](https://user-images.githubusercontent.com/29690117/65140173-d875ea80-d9c2-11e9-8243-ffe16b30843d.PNG)
Update and exit to site, and I'm looking at this:
![2and1](https://user-images.githubusercontent.com/29690117/65140192-e592d980-d9c2-11e9-8086-9077562f8e1a.PNG)
Seems a two column section presents the same issue. In Elementor:
![sbs](https://user-images.githubusercontent.com/29690117/65140262-03f8d500-d9c3-11e9-8c0c-2cacf7768395.PNG)
and after
![stacked](https://user-images.githubusercontent.com/29690117/65140280-09eeb600-d9c3-11e9-8f40-208b0795dfc9.PNG)
I've fiddled with every style and advanced section. Padding makes the issue worse. Boxed to Contained, width adjustments, etc et al...no effect.
I'd love for what Elementor shows me I've created to actually be the case.
Any and all feedback welcome, thank you.

**Comment by bainternet** [comment]
@BRValentine 

We can't replicate, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
