### ISSUE TITLE
Dark skin for Elementor

### ISSUE THREAD

**Issue by zimmiel** [elementor/elementor#9125]
FEATURE REQUESTS
Hello Elementors!
It would be nice add Dark skin for Elementor, like a WordPress or YouTube.
I don’t know what else to write, in Elementor settings make switch between Dark (night) and Light (already is)
I know that there are plugins, but better install less plugins.
Have a nice day! (or night)

**Comment by shilo-ey** [comment]
Hi @zimmiel 

We are playing around with the Idea of a darker theme/UI for Elementor but for now I would suggest you try a 3rd party plugin that does that already like this one: shofar-media.in.ua/elementor-dark-ui-theme

ref: #3435

**Comment by zimmiel** [comment]
Thank you
Good for the eyes. Need something modify, for example nav menu, and elements in the panel (img 1 2 3)
I hope this option appears in Elementor
Have a nice updates!
![1](https://user-images.githubusercontent.com/42843497/65224153-4c9bb580-dacb-11e9-9acc-3e123eb428f5.png)
![2](https://user-images.githubusercontent.com/42843497/65224202-6210df80-dacb-11e9-9f05-e62b10e5ba47.png)
![3](https://user-images.githubusercontent.com/42843497/65224209-663cfd00-dacb-11e9-9a65-bddd4a8b70d6.png)
