### ISSUE TITLE
Custom positionning for inner section

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#9126]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Often I have an inner section with different widgets in it, and I'd like to position that inner section in a specific way, the same way we can do it with other widgets.

**Describe the solution you'd like**

Custom position should be available for all widgets, including Inner section.

**Describe alternatives you've considered**

Presently, I need to change my design.

**Comment by Aviad-Herman** [comment]
Hey,
Some of the functionality is available in the "Layout" tab of the section / column.
Unfortunately we can't display all editing options because it will create bugs and bad UX for novice users.
Advanced users can always use custom CSS.

Thanks for raising this issue.
