### ISSUE TITLE
Collapse Navigationmenu Widget (Open just one item at a time)

### ISSUE THREAD

**Issue by timlama** [elementor/elementor#9132]
Hi there,

I am using the Navigation Menu Widget from Elementor with the Layout "Dropdown". No my problem: I would like only one single menu item can be opened on a click event.  At this time all menu items are openend on a click event. 
How is this possible?

Thank you very much for your answer.

Best,
Tim

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
