### ISSUE TITLE
How to Register a new Hotkey?

### ISSUE THREAD

**Issue by Paras16699** [elementor/elementor#9133]
Use Case: Registering a Hotkey to change the value of a switcher control.

**Comment by bainternet** [comment]
@Paras16699 	

hotKeys are more generic listeners and not bounded to controls, not sure you can do that without some major custom coding.

**Comment by Paras16699** [comment]
@bainternet  But the hotKey can execute callback, right? Just like how the `Ctrl+I` Navigator hotkey opens or closes the Navigator pane.

So, in a similar way, can't the callback be handled to change the control value?

**Comment by Paras16699** [comment]
Also, at least some hint / doc for registering a hotkey would help.
