### ISSUE TITLE
Elementor Pro v2.7 Beta Release

### ISSUE THREAD

**Issue by shilo-ey** [elementor/elementor#9137]
Elementor v2.7 Pro Beta is here and we would love to get feedback from you!
In Elementor v2.7 we introduced background slideshow. In this Pro version, we like to introduce to you it’s big brother: **The brand new Galleries widget!**

Before installing, please make sure you are using:

- Elementor Core v2.7.2
- Elementor Pro v2.7.0 beta1

## Meet The New Image Gallery Widget (#1898, #3103, #4279, #7631)

![gallery](https://user-images.githubusercontent.com/45009641/65258789-3104cf00-db0c-11e9-8e39-c20e64361390.gif)

There are thousands of gallery plugins in WordPress, and even Elementor has a basic gallery plugin.

Well, very basic, I must admit. Over the years, we’ve received many requests for a professional gallery solution, but this got postponed for various reasons, one of which is the fact that we weren’t completely satisfied with any of the galleries libraries out there.

Now, after many hours of dev work, we are finally releasing our ultimate image gallery library module.

### Introducing Elementor’s Image Gallery Widget.

Basically, go to your plugins list, click deactivate gallery… no, I’m kidding. But I bet this solution will serve many who needed to use external gallery plugins to get the required result.

- Various Layouts: Grid, justify and masonry
- Aspect ratio control
- Multiple galleries
- Filtered display
- CSS filters
- Animations
- Full overlay design control

I can go on… but I want you to play around with the handles and get the same satisfaction from tinkering and unboxing it yourself.
 
**Test flows:**

**A:**
- Create a new page and insert “Gallery” widget to it
- Select Single gallery type, and select your images using the Gallery control
- Select the Layout of your choice and select which elements to show on the overlay
- Go to Style tab and style your gallery 
- Make sure everything works as expected in both the Editor and on Frontend.

**B:**
- Drag another Galleries widget
- Select Multiple gallery type, click “Add New” and select your images using the Gallery control
- Under Gallery Title field fill in your gallery sorting label
- Add another set of galleries and repeat the previous steps
- Go to Style tab and style your gallery 
- Make sure everything works as expected in both the Editor and on Frontend.

## Full Content Posts Skin (#4617)

![full post](https://user-images.githubusercontent.com/45009641/65258778-2ba78480-db0c-11e9-9587-c91979c07775.gif)

In this version we added a new skin to our Posts widget, allowing you to display the entire post content in each of the posts lists. 

Many blogs show the entire content of the post in the homepage or main blog page. This is a request we often received, so if you are one of the users who asked for it - scratch it off your wish list.

**Test flow:**
- Add Posts widget to your page
- Under Layout > Skin choose ‘Full Content’
- Make sure everything works as expected in both the Editor and on Frontend.

### 1.  Tags support to forms MailChimp action (#5418)
The new tag support we’ve added gives marketers an important tool to pass visitor information while submitting contact forms and registering users to MailChimp.
Imagine you have 3 copies of identical landing pages, one for each platform: Google Adwords, Facebook Ads, and Twitter Ads.
Each landing page has a corresponding form, registering all visitors to your MailChimp list of subscribers. Now, you can include the relevant tag: Google, Facebook, and Twitter to the subscriber. This can be very useful for managing your email marketing efforts in the future.
This is just one example, but the ability to integrate to MailChimp tags can be useful in many situations. 

**Test flow:**
- Drag a Form widget to your page
- Under Actions After Submit section add “MailChimp” option
- Go to MailChimp section and set your API key if you haven’t done that already
- Select your Audience, and in the new Tags field you can insert the tags you wish to pass over to MailChimp
- Go to frontend, fill in your form and make sure the record is sent to MailChimp correctly

### 2. MailerLite resubscribe action support (#8799)
If you have newsletter unsubscribers that decide to get your updates again, it is easily done. We have now added support to MailerLite’s resubscribe feature, so any member who has previously unsubscribed can be reassigned as active with a simple form submission. 

**Test flow:**
- Drag a Form widget to your page
- Under Actions After Submit section add “MailerLite” option
- Go to MailerLite section and set your API key if you haven’t done that already
- Select your List and after your fields mapping switch “Allow Resubscribe” toggle on
- Go to frontend, fill in your previously unsubscribed details in the form and make sure the record is sent to MailerLite correctly and resubscribes the user

### 1. Dynamic Number (#5952)
Until now, dynamic content was restricted to textual input. With the new ‘Dynamic Number’ feature, you can embed dynamic numbers in any widget that has a number field: counters, price tables, star rating and more.

Dreamt of creating an IMDB type of website? A progress bar that changes according to the page being viewed? Get creative and start using dynamic numbers to create even more advanced websites using Pods & ACF custom fields.
 
**Test flow:**
- Drag a Counter widget to your page
- Above each Number field there is a Dynamic Tag control, click on it and select your preferred source of dynamic number
- Make sure everything works as expected on Frontend.
- Do the same flow to Price List, Price Table, Slider, Star Rating & Progress Bar widgets

 
### 2. Custom Field Key (#7789)
Not all custom fields appear in the WordPress ‘Edit Post’ area. 
This is why we added the ability to incorporate custom fields in dynamic Elementor pages by using their custom field key.

**Test flow:**
- Insert Text Editor widget to your Post which has a custom field populated
- Click on the Dynamic Tag control and select Post Custom Field
- In the popover settings window you can see the “Custom Key” field. Fill in your custom field key
- Make sure everything works as expected on Frontend.

 
### 3. User Profile Picture dynamic (#7947, #8740)

What do author pages, listing sites and multi-author websites have in common?
That’s right, they all include the profile picture of the user.
Well, now you can create advanced websites that include dynamic profile pages, with the image dynamically changing according to the user logged in to the website.
Now, you are one step closer to creating advanced personalized type websites. 

Excuse me while I go build the next Facebook using Elementor…
 
**Test flow:**
- Create a new Post
- Drag in image widget
- Click on the Dynamic Tag control and select User Profile Picture
- Make sure everything works as expected on Frontend.
- Switch to a different user with a different photo and check if the photo is the correct one.

## New Approach to WooCommerce mini-cart
Starting Pro v2.7, Elementor adds its own mini-cart template. Instead of having the Menu Cart widget print the mini-cart markup, we are introducing a new mini-cart template which will be used by the Elementor Menu Cart widget.

This change doesn’t affect the majority of our users.
Want to revert to your theme's mini-cart template instead of Elementor's? disable the Elementor mini-cart markup and keep using the custom mini-cart template.

In order to disable Elementor mini-cart template simply go to your Dashboard > Elementor > Settings > Integrations tab > WooCommerce section and choose “`Disable`”.

**Test flow:**
- Install & Activate a theme that has it’s own mini-cart template 
- Make sure WooCommerce is installed, activated, and your shop is set up with products
- Create a new header and drag in a Menu Cart widget and design it
- Set your header to Entire Site condition
- Go to frontend, navigate to your Shop page and add a product to cart
- Click on the Menu Cart button and see your mini-cart drawer design
- Go to your Dashboard > Elementor > Settings > Integrations tab > WooCommerce section and choose “Disable”
- Go to frontend, click on the Menu Cart button and see the theme’s mini-cart drawer design
- Make sure everything works as expected on Frontend

-------
## More Improvements

- New: Enhanced Galleries widget (#1898, #3103, #4279, #7631)
- New: Dynamic Number (#5952)
- New: Full content skin for Posts and Archive-posts widgets (#4617)
- Tweak: Added dynamic number capability to Price List, Price Table, Slider, Counter, Star Rating, Progress Bar widgets
- Tweak: Added tags support to forms Mailchimp action (#5418)
- Tweak: User Profile Picture Dynamic Tag (#7947, #8740)
- Tweak: Added `font-display` support to custom fonts (#5993, [Developers Blog Post](https://developers.elementor.com/elementor-pro-2-7-custom-fonts-font-display-support/))
- Tweak: Added Text Shadow control to Slides widget (#8800)
- Tweak: Added Re-subscribe support to MailerLite (#8799)
- Tweak: Added Dynamic capabilities to Facebook Embed widget (#9030)
- Tweak: Use `swiper.js` instead of `slick.js` in Slides widget ([Developers Blog Post](https://developers.elementor.com/elementor-2-7-moving-sliders-from-slick-to-swiper/))
- Tweak: Added `elementor_pro/search_form/before_input` action hook to Search Form widget (#5598)
- Tweak: Added `elementor_pro/search_form/after_input` action hook to Search Form widget (#5598)
- Tweak: Added dynamic support for Custom field key (#7789)
- Tweak: Increased expired license notice bar frequency
- Tweak: Changed the icon name of Slides widget 
- Tweak: Added designated Finder's Icons for Custom icons & Custom fonts
- Tweak: Use Ken Burns Effect as an external module
- Tweak: Remove Fontello conflicting CSS on import to Custom Icons sets
- Tweak: Editor Panel UI tweaks
- Tweak: Added DOM events on Popup show/hide ([Developers Blog Post](https://developers.elementor.com/elementor-pro-2-7-popup-events/))
- Tweak: Added option to change the variations field width in Add to Cart widget
- Tweak: Use select control instead of select2 in Menu Cart widget
- Tweak: Added conditions to the tabs instead of to each control in Share Buttons widget
- Tweak: Added Typography controls to HTML field in Forms widget
- Tweak: Allow edit selected Font file in Custom Font
- Tweak: Changed reCAPTCHA v3 error message
- Tweak: Remove the "Save as Global" option on Global widget context menu
- Fix: Corrected selector for `removeControlSpinner()` (#8790)
- Fix: Slides widget navigation icons misplacement (#8533)
- Fix: Horizontal Scrollbar when Slider widget is set to Full Width (#8527)
- Fix: Inconsistent behavior when "Infinite Loop" enabled with "Autoplay" in Slides widget (#6726)
- Fix: Ken Burns effect on Chrome transition glitches (#1671)
- Fix: Nothing found message shows up inside the columns set in Posts Archive widget (#7347)
- Fix: Responsive UI glitch in Popup Conditions modal tabs
- Fix: Custom Add To Cart - button style (size, position and background color) when `quantity` is enabled.
- Fix: Add support for Document/PageBase in Theme Builder. (Core >=2.7.0)
- Fix: Ampersand character breaks email link in Share Buttons widget
- Fix: Correct custom font attachment `mime-type` to show uploaded Custom Fonts
- Fix: Mini-Cart not refreshing in Menu Cart widget
- Fix: Cart drawer not working when WC Subscriptions plugin is activated
- Fix:  Querying CPT with custom taxonomies does not show the taxonomies before saving
- Fix: Double rendering on change caused console error in Theme Builder's conditions screen
- Fix: Translations and Strings in Share Buttons widget
- Fix: Avoid using offset if the source is Manual selection in Query Control
- Fix: Form being submitted although reCAPTCHA v3 validation failed in Forms widget

See the entire planned deprecations for v2.7 in our Developers Blog: https://developers.elementor.com/v2-7-0-planned-deprecations/

-------
## How to Install the Beta Version
If you still haven't enabled beta testing in Elementor, please follow these steps:

- Go to Elementor > Tools > Versions
- Enable the beta tester feature
- Go to Dashboard > Updates and update to the latest beta version.

This will get you set up to test the new Elementor Pro v2.7.0 Beta.
 
### Notes
For bugs and remarks, please reply with a comment on the specific issue here on GitHub.

**Please keep this related to the Current beta Only! Any other issue or feature request, feel free to open a new issue.**

Designated time for release: `September 24, 2019 (Estimated)`
Many thanks for your support and help!

Cheers,
_The Elementor Team_

**Comment by crsmoore** [comment]
I tested the **MailerLite resubscribe action support** ([#8799](https://github.com/elementor/elementor/issues/8799)) and it worked! :) 

Thanks so much for enabling support for this! 👍

**Comment by amos-arviv** [comment]
Super cool! Congratulations! 
When we will get a dynamic color capabilities? :) Can't wait!!

**Comment by srcek** [comment]
Will there be an option to dynamically add images to Gallery using ACF Pro? Basic Gallery already has that capability.

**Comment by Kishorchandth** [comment]
I still can't see **font-display:swap** on custom fonts.  If i am wrong please correct me 

Here the reference i am assuming : wp-content/uploads/elementor/css/global.css, wp-content/uploads/elementor/css/post-7.css

**Comment by tamelander** [comment]
Very nice Galley Widget! Haven't found a bug yet. Looks great!

It would be very nice to have an extra import function for the new gallery widget where you can add a comma separated string of image ids (copying them from regular WP gallery shortcode [gallery ids="1,2,3,4,5,..."].

**Comment by sermalefico** [comment]
No dynamic options for Image Gallery Widget ¿?¿

**Comment by HQRaja** [comment]
A major feature I see missing from the Gallery widget is dynamic content. It'll be great to use ACF Gallery fields with it for the content. With that, we could simply add one or more ACF gallery fields to our post or CPT so that authors or editors can upload photos to the gallery while editing the post, and then our Elementor template can take care of displaying them in the right spot using the Gallery widget. It'll open up a lot of great layout options for posts and CPTs that involve lots of images. I really hope you guys add support for this soon.

**Comment by avermat** [comment]
I'm unable to find the "border radius" option for the images in the Gallery widget. Am I missing this somewhere?

**Comment by Josimarcsilva** [comment]
Hi

The world today is driven by videos.
The biggest blog and news sites use videos.
Post Files Page needs to be compatible with videos.
I requested this feature from github, but didn't get a satisfactory answer:
https://github.com/elementor/elementor/issues/7021

See an example of videos on the Post Archive Page:
https://www.elegantthemes.com/preview/Divi/blog-masonry/

![Video](https://user-images.githubusercontent.com/4340052/65377380-7f87aa00-dc81-11e9-86f1-3b6a38ea7c57.jpg)

**Comment by avermat** [comment]
MailChimp tags worked great on my end. Thanks for adding this!! I was expecting to be able to choose the tags from a drop-down list though like you do for groups. It's going to be hard not to screw up typing in exact matches for longer more detailed tags. And now I have to log into MailChimp in order to create my opt-ins to make sure I'm using the right tags.

**Comment by shilo-ey** [comment]
Hi all!

We just released a new beta version, please update your version to v2.7.0 Pro Beta2.

This beta release includes:

- Tweak: Added Dynamic capabilities to Gallery
- Tweak: Changed the description of the WC Mini-Cart integration option
- Tweak: Added Filter Bar alignment option in Gallery widget
- Tweak: Minor UI changes in Gallery widget
- Fix: Removed unnecessary divider in Call to Action widget
- Fix: Border Radius does not apply to the entire box in Full Content Posts skin
- Fix: Layout issues caused by adding Cart Menu widget
- Fix: Transparent background images overlapping when the transition is set to `fade` in Slides widget (#9153)


**Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.**

Thanks again to everyone.

**Comment by sermalefico** [comment]
For asking for one more thing ... With the new gallery widget add to grid, justify, masonry a SLIDE layout? : D It would be like a sunami

**Comment by pingram3541** [comment]
@Kishorchandth @bainternet just put up a dev blog post showing how to hook font-display on custom fonts - https://developers.elementor.com/elementor-pro-2-7-popup-events/

**Comment by Kishorchandth** [comment]
> @Kishorchandth @bainternet just put up a dev blog post showing how to hook font-display on custom fonts - ~https://developers.elementor.com/elementor-pro-2-7-popup-events/~ oops - https://developers.elementor.com/elementor-pro-2-7-custom-fonts-font-display-support/

Got it @pingram3541 . I was using .ttf file that why it always displaying  Display:block , when i switch to woff and woof2 it return to swap

Thanks

**Comment by srcek** [comment]
@shilo-ey Thanks for adding the Dynamic capabilities to Gallery widget.

Now there are two separate Gallery widgets with one clearly being the upgraded, more capable version of the other. What's the point of keeping the Basic Gallery?

**Comment by deckerweb** [comment]
@srcek I guess they keep the original now "basic" widget for backward compat reasons so that absolutely no sites will break. In my opinion this is very important as no one wants to have a broken gallery on a site and maybe discover the brokeness a lot later even...

Since it's the Elementor widgets are all class based and auto loading it will not harm performance or anything, I guess even in the Builder. So even if they may deprecate it in the future that approach gives everyone enough time to test & try things out and maybe migrate old galleries over.

**Comment by black-eye** [comment]
@deckerweb, @srcek I guess the the other reason for keeping the basic gallery widget (besides the backward compatibility) is that the "basic" is in plain Elementor and "advanced" is in EPro.

I think this is completely reasonable and undesrstandable. On the other hand, this situation raises the need for some kind of Widget Manager more than ever before - even Elementor itself is starting to double it's own widgets, not to mention other addons.

**Comment by shilo-ey** [comment]
Elementor Pro v2.7 is available, Feel free to update.

Thank you all for your feedback!

**Comment by parfilov** [comment]
Image caption can be shown only on hover but not constantly as in review video.

**Comment by sermalefico** [comment]
The Justified Layout in gallery Widget dont Justify fine last Row.  The last image is always larger (overflows the layer) or is smaller (does not acquire the same height as the other rows).

You should have an option to justify left, right, center, and hide the last row.

**Comment by parfilov** [comment]
Switching between filter elements looks like a “nervous tick”. No smoothness and everything twitches. See video https://youtu.be/9y5PA0GGjRg

All plugins off. Theme Twenty Nineteen.

**Comment by parfilov** [comment]
And i didn't get email about beta Pro 2.7 ((

**Comment by parfilov** [comment]
Tweak: Added dynamic number capability to ... Slider ... 
Where?!

**Comment by justdudeone** [comment]
I don't understand - at that ticket: https://github.com/elementor/elementor/issues/9150 RazOhad tells that Elementor at Pro 2.7 will get possibility to enter and get any meta (database -> postmeta table -> metakey -> data). But I don't see this function at changelog and announce. Can you confirm it? How it will work? From meta-data-widget or from dynamical tags? Clarify, please!

**Comment by justdudeone** [comment]
Finally I found how to open this dialogue: Custom -> Individual -> Dynamical -> Custom meta -> Custom key... OMG!!! 
Without FAQ-articles with screenshots found this place are really impossible!
Highly recommend to move this possibility to enter any metakey to a first upper step - just "Custom key..." - that all!
