### ISSUE TITLE
Elementor Backslash Characters in Database

### ISSUE THREAD

**Issue by Jimboshoe** [elementor/elementor#9140]
I'm posting this here because Cesar at Elementor advised me to.

I'm using Elementor Pro to migrate my guitar lesson site to Wordpress. I'm more of a guitar player than a techie.... I have latest version E.Pro, WP; Hello v.1.2. I've tried turning off all non-essential plugins. I searched this repository, but found no similar issue. I've asked on the Facebook group, etc.

I use the Better Search Replace (BSR), plugin to change some URLs, etc., which works quite well and is highly rated. However, I tried using it to fix the path to an image which appears on many pages, it didn't work. 

I searched for this:

"../../_images/buttons/btn_donateCC_LG.gif"

to be replaced by this:

"https://sept-4-2019.local/dgpdev/wp-content/uploads/-images/btn_donateCC_LG.gif"

BSR said it made over 400 changes, but nothing changed on the actual pages.

I sent a copy of my Wordpress database to BSR support and a guy there wrote back,

"...there appears to be a lot of references to "btn_donateCC_LG.gif" in the "wp_postmeta" tables, but the data is stored differently, for example:

"..\/..\/_images\/buttons\/btn_donateCC_LG.gif"

I would check in with the developers of the Elementor plugin to see how they recommend updating the data. Short of that, you could try searching for the string as it appears in the database, with the backslashes preceding any forward slashes in your search string."

Well, I took his advice and tried another search/replace using the path he suggested (with the backslashes), and it worked.

However...

- why does Elementor add the backslashes in the database? (I guess this is what's called an 'escape character'? If so, why is it needed?)
- is this normal?
- is the only way to fix it as Matt suggested (search for string with backslashes)?
- in what cases does Elementor add backslashes?

That is, why does this happen, how can I know when it happens, is there anything I can do to prevent it from happening (etc.)?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
