### ISSUE TITLE
Theme Builder compatibility with WooCommerce Memberships restrictions

### ISSUE THREAD

**Issue by tamarazuk** [elementor/elementor#9141]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm reaching out about a compatibility issue between the Theme Builder templates in Elementor Pro and [WooCommerce Memberships](https://woocommerce.com/products/woocommerce-memberships/) content restrictions. WooCommerce Memberships is a very popular extension adding a memberships system to mane WooCommerce stores. 

Currently, any content using a Theme Builder template isn't restricted by the Memberships extension. I suspect this is due to the Theme Builder displaying content outside of the regular WordPress loop while this isn't compatible with how Memberships restricts content currently. 

**Describe the solution you'd like**

I'd love to work together to put together an integration, but have a few questions first to get a better idea of what solution would be ideal. 

Does Elementor Pro provide any filters surrounding the post content when it outputs a template? 

Does the Theme Builder offer any conditional logic features currently to allow site owners to show/hide specific blocks based on certain conditions? 

**Describe alternatives you've considered**

As an alternative to direct integration in either plugin, I'd love to put together a code snippet mutual customers can use. This can serve as _the_ solution or as a temporary workaround until either or both of the plugins is updated to include full compatibility. 

**Additional context**

Please get in touch with us [here](https://www.skyverge.com/contact/?form_type=general) if you have specific questions or would like a copy of our plugin for your own testing.

**Comment by pingram3541** [comment]
I think this is of similar interest.  https://github.com/elementor/elementor/issues/9493

**Comment by bainternet** [comment]
@tamarazuk 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by DoronYosha** [comment]
any solution for that??
