### ISSUE TITLE
Get label of selected option separately

### ISSUE THREAD

**Issue by iffifan** [elementor/elementor#9142]
Let me break some rules here. I am sorry for that but I wanted to keep it concise and direct;

I already opened a ticket for this but it was closed without getting good attention.

https://github.com/elementor/elementor/issues/9127

I am asking for some feature as we have in Contact Form 7 where we can get the value before "|". I mean only the label of selected option as mentioned here:

https://contactform7.com/selectable-recipient-with-pipes/

> To get the value after pipe character, put the usual mail tag corresponding to the form tag ([your-recipient] in the case of the above example) in the Mail templates. To get value before pipe, you can use [_raw_{field name}] ([_raw_your-recipient] in the case of the above example).

I hope you get my point now?

**Comment by iffifan** [comment]
I have done a workaround.

I did create a hidden field with id `department raw` and added this code 

```
add_action( 'elementor_pro/forms/process/hidden', function ($field, $record, $ajax_handler ) {
        // Get Form Fields Settings and find current field
        if (strpos($field['id'], '_raw') !== false) {
            $fields = $record->get( 'fields' );
            $settings = $record->get( 'form_settings' );
            $fieldId = str_replace('_raw', '', $field['id']);
            $valueField = $fields[$fieldId];
            foreach ( $settings['form_fields'] as $form_field ) {
                if ($form_field['_id'] == $fieldId && $valueField) {
                    $options = preg_split( "/\\r\\n|\\r|\\n/", $form_field['field_options'] );
                    if ( ! $options ) {
                        return '';
                    }
                    // loop over the options and find the selected one
                    foreach ( $options as $option ) {
                        if ( false === strpos( $option, '|' ) ) {
                            continue;
                        }
                        list( $label, $value ) = explode( '|', $option );
                        if ( $value === $valueField['raw_value'] ) {
                            // This is a match so we set the value to contain the label as well
                            $record->update_field( $field['id'], 'value', $form_field['field_label'] );
                        }
                    }
                }
            }
        }
    }, 10, 3 );```

**Comment by bainternet** [comment]
Glad you figured it out.

**Comment by claralinda** [comment]
@iffifan where did you write the code you provided? 
Did you use [field id="department raw"] to have the label in the body of the email? Thanks
