### ISSUE TITLE
ELEMENTOR_PARTNER_ID removed?

### ISSUE THREAD

**Issue by markfail** [elementor/elementor#9143]
Hi Guys

Can you explain why ELEMENTOR_PARTNER_ID was removed?

Seems a lot of affiliates are unaware of this and therefore losing out on comission.

Can you explain how affiliates should be adding their partners ID into their themes/plugins the correct way.

Thank you.

Mark

**Comment by markfail** [comment]
Still nothing guys? Can you please address this as it's important.

**Comment by arielk** [comment]
I'm closing an issue because it's a affiliates issue. Feel free to contact our support through your account.
