### ISSUE TITLE
Merging default widgets' categories under one or two categories

### ISSUE THREAD

**Issue by goldenpony89** [elementor/elementor#9145]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

To clean my UI, I blacklisted lots of Elementor widgets redundant with other advanced plugins' widgets, ending up with only a few widgets per category.

With the flexible elementor panel plugin this means each categories occupies about a line and a half of widgets, which is a very inefficient use of UI space (see the sample image).
![WhatsApp Image 2019-09-20 at 9 16 23 AM](https://user-images.githubusercontent.com/44218789/65326781-a0b89f80-db88-11e9-82c4-f179a410e3a9.jpeg)

I would like to stack these categories under the general or basic category so that Elementor widgets take a third less space than now, also saving empty space between categories. I've got started with something like this but not really sure it would help me gain access to private properties and just in general how to progress

```PHP
add_action( 'elementor/elements/categories_registered',  function(\Elementor\Elements_Manager $elements_manager ) {
	$set_categories = function( $categories ){
    	$???->categories = $categories;
	};
    $set_categories->call($elements_manager, $???);
} );
```

Alternatively, I am trying to find where each widget category is defined to reassign it -as that would be a great UI customization option to speed up workflow - but that seems more complicated.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@goldenpony89 

Each widget holds its own category so changing to change the widget category you'd have to loop over all widgets and set the category per widget.

To do that you can use the provided `elementor/editor/localize_settings` filter hook to alter the widgets config array.

hope this helps.
