### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Keep original file upload name (Merged with #4868)

### ISSUE THREAD

**Issue by 863chick** [elementor/elementor#9147]
I need the original user submitted file upload name sent to me not a unique ID.

How do I remove this filter and solve this issue?
I understand the risk but it's important for my goal.

```php
/**
 * @param string        $filename                 Unique file name.
 * @param string        $ext                      File extension, eg. ".png".
 * @param string        $dir                      Directory path.
 * @param callable|null $unique_filename_callback Callback function that generates the unique file name.
 */
add_filter( 'wp_unique_filename', function( $filename, $ext, $dir, $unique_filename_callback ) {
	static $file_count = 0; //used to get the current file when multiple uploads in a form
	// first make sure its an upload via elementor forms
	if ( false === strpos( $dir, '/elementor/forms' ) ) {
		return $filename;
	}

	// get the original file name
	$path_parts = pathinfo( $_FILES['SET_FORM_FIELD_ID_HERE'][ $filename ] );
	// Bump counter for next file
	$file_count++;
	// Return your desired file name (original-unique_suffix.extension)
	return $path_parts['filename'] . '-' . $filename;

}, 10, 4 );
```

**Comment by bainternet** [comment]
@863chick 

There is nothing to remove, this doesn't exist in Elementor or Elementor Pro, It was given as an example to how you could use the WordPress native `wp_unique_filename` to restore the original file name.

> In a custom plugin or your themes functions.php would be just fine.

Just make sure to replace `SET_FORM_FIELD_ID_HERE` to the actual upload form field id.

**Comment by TedChenNZ** [comment]
The function posted above didn't work for me, but after some tinkering I got this to work

```
/**
	* @param string        $filename                 Unique file name.
	* @param string        $ext                      File extension, eg. ".png".
	* @param string        $dir                      Directory path.
	* @param callable|null $unique_filename_callback Callback function that generates the unique file name.
	*/
	add_filter( 'wp_unique_filename', function( $filename, $ext, $dir, $unique_filename_callback ) {
		$FORM_FIELD_FILE_ID = 'file';

		static $file_count = 0; //used to get the current file when multiple uploads in a form

		// first make sure its an upload via elementor forms
		// or you can once again only add this filter hook if you know that this is
		// a desired form as in the above example
		if ( false === strpos( $dir, '/elementor/forms' ) ) {
			return $filename;
		}

		// get the original file name
		$original_filename = $_FILES['form_fields'][$FORM_FIELD_FILE_ID][$file_count]['name'];
		
		// Bump counter for next file
		$file_count++;
		// Return your desired file name (original-unique_suffix.extension)
		return $original_filename;
	}, 10, 4);
```

You will need to update `$FORM_FIELD_FILE_ID`.

I'm not sure what happens if there's a naming conflict, since I actually modified the above code and added a guid in front of the $original_filename to prevent any conflicts.

**Comment by sss9212** [comment]
@TedChenNZ This works for a single form with a single upload field. However, any idea how to get this to work on a 1) form with more than one upload fields, and 2) if there are multiple forms on the website? I tried using your code for each form by replacing with the respective upload field id of that form but it didn't work. Any help would be appreciated. Thanks!

**Comment by TedChenNZ** [comment]
@sss9212 I believe you would just need to keep getting the filename by changing a combination of
$FORM_FIELD_FILE_ID
and also potentially loop over or increment the $file_count variable so that it grabs other files in the `$_FILES['form_fields'][$FORM_FIELD_FILE_ID]` array? 

I'm not super sure sorry, I'm not super proficient in WordPress or php.

**Comment by dexit** [comment]
> wp_unique_filename

The below code has been set to work, on Multi-Upload Form field with set Max File Count = 1 (in elementor).
And in my case we have 5 file uploads on 1 form,  each have a ID of "upload_1", "upload_2" etc... so below we iterate as @TedChenNZ has initially written but just use the field id and leave file count to static.

```

/** add form attachments to email and delete from server /
/
* @param string $filename Unique file name.
* @param string $ext File extension, eg. ".png".
* @param string $dir Directory path.
* @param callable|null $unique_filename_callback Callback function that generates the unique file name.
*/

add_filter( 'wp_unique_filename', function( $filename, $ext, $dir, $unique_filename_callback ) {
    //$mehed = var_dump($_FILES['form_fields']);
    // echo "<script>console.log($mehed);</script>"; 
    static $ident = 1;
	$FORM_FIELD_FILE_ID = 'upload_'. $ident;	// enter YOUR field ID			

	static $file_count = 0; //used to get the current file when multiple uploads in a form

	// first make sure its an upload via elementor forms
	// or you can once again only add this filter hook if you know that this is
	// a desired form as in the above example
	if ( false === strpos( $dir, '/elementor/forms' ) ) {
		return $filename;
	}

	// get the original file name
	$original_filename = $_FILES['form_fields'][$FORM_FIELD_FILE_ID][$file_count]['name'];	
	  
	// Bump counter for next file
	// $file_count++;
	$ident++;
	// Return your desired file name (original_filename)		
	return $original_filename;
	
}, 10, 4);


```

**Comment by cloudhigh** [comment]
> @TedChenNZ This works for a single form with a single upload field. However, any idea how to get this to work on a 1) form with more than one upload fields, and 2) if there are multiple forms on the website? I tried using your code for each form by replacing with the respective upload field id of that form but it didn't work. Any help would be appreciated. Thanks!

@sss9212 Did you find a solution for this?

A website has multiple forms. Some forms either have one upload or multi uploads.

@dexit Your above code works for one form with multiple uploads but doesn't work for another form with one upload,

Regardless of the form, I naming the ID upload_1, upload_2 etc. 

Thanks.
