### ISSUE TITLE
Usage of FontAwesome 5 icons in menu items

### ISSUE THREAD

**Issue by therealgilles** [elementor/elementor#9149]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's great that Elementor tracks the icons used on a page to reduce the number of icon libraries being loaded. But if one wants to use an icon in a menu, Elementor does not see it and therefore does not load the corresponding library.

**Describe the solution you'd like**
Either provide a way to force particular libraries to be loaded on a page (or all pages). Or make give a way to add icons to other places so that Elementor can see their usage (maybe through a shortcode). Or some other alternative.

**Describe alternatives you've considered**
I am considering adding an invisible icon to the footer to make sure the icon library I need gets loaded. Kind of a dirty solution.

In my case, I want to use the facebook brand icon but the menu is the only place I am using any brand icons.

**Comment by bainternet** [comment]
@therealgilles 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, if it's only a single icon or two, I would suggest that you use SVG instead of loading a full Icon set CSS and Font files.


Thanks for the feedback.
