### ISSUE TITLE
How to add a new Meta to Elementor widgets for using meta at many places?

### ISSUE THREAD

**Issue by justdudeone** [elementor/elementor#9150]
Hello!

Sorry, but github-support still seems the optimal place for my question, because:
- With this question your support team send me to github here for create a feature request.
- For me it still seems that supporter does not understand question and it can be resolved without new function.

Here is my question:
How to add a new Meta to Elementor widgets for using them at many places? How add my "metakey's" from "postmeta" database table to a (same at attached screenshot):
1) "Posts widget - Meta - Author, Date, Time, Comments..."
2) "Dynamical data" dropdown list with many meta from Posts, Categories, Author, etc.
I want to add there a new meta from different plugins. How is it possible to make?

It seems near to https://developers.elementor.com/dynamic-tags/ but I'am not a web-developer, so it's a too complicated for me, so I bough ElementorPro to not use code, but only an easy visual editing.

I have a Pro licensed version, so please answer detailed and with sample for example for ULike plugin (metakey from postmeta table at database = "_liked") that can be found at main WP plugins repository.

![Eelementor_how_add_new_meta](https://user-images.githubusercontent.com/43311177/65369991-d929ad80-dc5c-11e9-8ca6-17f21365d757.png)

**Comment by bainternet** [comment]
@justdudeone 

Your question is not clear, the first posts widget meta section is completely different than our dynamic tags.

as for using post meta that starts with underscore `_` in elementor pro v2.7 which is currently in [Beta](#9137) we've added support for manually setting the meta key.

thanks.

**Comment by justdudeone** [comment]
Please, clarify - where and how exactly I can add any metakey? I try some variants, but it does not work.

**Comment by justdudeone** [comment]
Finally I found how to open this dialogue: Custom -> Individual -> Dynamical -> Custom meta -> Custom key... OMG!!! 
Without FAQ-articles with screenshots found this place are really impossible!
Highly recommend to move this possibility to enter any metakey to a first upper step - just "Custom key..." - that all!

**Comment by olvikmor** [comment]
> Finally I found how to open this dialogue: Custom -> Individual -> Dynamical -> Custom meta -> Custom key... OMG!!! Without FAQ-articles with screenshots found this place are really impossible! Highly recommend to move this possibility to enter any metakey to a first upper step - just "Custom key..." - that all!

Hello, i try to find this dialogue in Elementor: Custom -> Individual -> Dynamical -> Custom meta -> Custom key
But i can't find it.
Can you please make screenshot or maybe some video to show where i can find it?

**Comment by olvikmor** [comment]
> Hello!
> 
> Sorry, but github-support still seems the optimal place for my question, because:
> 
> * With this question your support team send me to github here for create a feature request.
> * For me it still seems that supporter does not understand question and it can be resolved without new function.
> 
> Here is my question: How to add a new Meta to Elementor widgets for using them at many places? How add my "metakey's" from "postmeta" database table to a (same at attached screenshot):
> 
> 1. "Posts widget - Meta - Author, Date, Time, Comments..."
> 2. "Dynamical data" dropdown list with many meta from Posts, Categories, Author, etc.
>    I want to add there a new meta from different plugins. How is it possible to make?
> 
> It seems near to https://developers.elementor.com/dynamic-tags/ but I'am not a web-developer, so it's a too complicated for me, so I bough ElementorPro to not use code, but only an easy visual editing.
> 
> I have a Pro licensed version, so please answer detailed and with sample for example for ULike plugin (metakey from postmeta table at database = "_liked") that can be found at main WP plugins repository.
> 
> ![Eelementor_how_add_new_meta](https://user-images.githubusercontent.com/43311177/65369991-d929ad80-dc5c-11e9-8ca6-17f21365d757.png)

Hello, i try to find this dialogue in Elementor: Custom -> Individual -> Dynamical -> Custom meta -> Custom key
But i can't find it.
Can you please make screenshot or maybe some video to show where i can find it.

**Comment by olvikmor** [comment]
Hello, @justdudeone, i try to find this dialogue in Elementor: Custom -> Individual -> Dynamical -> Custom meta -> Custom key
But i can't find it.
Can you please make screenshot or maybe some video to show where i can find it.
