### ISSUE TITLE
Hook/option to disable Elementor on specific posts/pages

### ISSUE THREAD

**Issue by ligne13** [elementor/elementor#9151]
It would be great to be able to disable Elementor on some specific posts/pages IDs.
As this is an advanced feature, it could be set up with action hooks. IMO, no need for a UI.

What do you think ?

**Comment by bainternet** [comment]
@ligne13 

You can already use the native hooks API to do that, ex:

```PHP
// remove from classic editor
add_action( 'edit_form_after_title', function( $post ) {
	$admin = \Elementor\Plugin::instance()->admin;
	remove_action( 'edit_form_after_title', [ $admin, 'print_switch_mode_button' ] );
}, 9 );

// remove from gutenberg
add_action( 'enqueue_block_editor_assets', function() {
	wp_scripts()->dequeue( 'elementor-gutenberg' );
}, 11 );
```
run you checks either inside the hooks above or even before to avoid adding these hooks if not needed.

**Comment by ChiKaLiO** [comment]
> @ligne13
> 
> You can already use the native hooks API to do that, ex:
> 
> ```
> // remove from classic editor
> add_action( 'edit_form_after_title', function( $post ) {
> 	$admin = \Elementor\Plugin::instance()->admin;
> 	remove_action( 'edit_form_after_title', [ $admin, 'print_switch_mode_button' ] );
> }, 9 );
> 
> // remove from gutenberg
> add_action( 'enqueue_block_editor_assets', function() {
> 	wp_scripts()->dequeue( 'elementor-gutenberg' );
> }, 11 );
> ```
> 
> run you checks either inside the hooks above or even before to avoid adding these hooks if not needed.

this is nice but it's not disabling it from the whole page, in my case emlementor causing bugs on add product page woocommerce anyway to dsable the whole imports etc in that page ?
