### ISSUE TITLE
PNG Slides shows all slides stacked

### ISSUE THREAD

**Issue by gravnetic** [elementor/elementor#9153]
If you use the slider module and only have transparent background slide content, the slides are stacked showing the other slides.  This only occurs when the fade transition is selected.

**Comment by shilo-ey** [comment]
Thanks for reporting, 

We will check this issue and address it in the upcoming versions.

Next time please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**

Thanks.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!
