### ISSUE TITLE
Change Control Value from `_content_template()` of a Widget

### ISSUE THREAD

**Issue by Paras16699** [elementor/elementor#9154]
I've created a widget where I'm using a JS library to generate dynamic content based on settings.

I only want this content generation process to happen in the editor area and not load the library on the frontend.

So, the solution I thought of was to create a Hidden control field and save the content there.

But, in the `_content_template()` function, when I try to do - `settings.hiddenField = generatedContent`, the value is updated in the editor but doesn't reflect in the WordPress preview or frontend which means that the control's value hasn't actually changed. It shows empty value on the frontend.

**So, how do I update the control's value from the `_content_template()` function?**

**Or, is there any way to use the output of the `_content_template()` function in the frontend render as well?** Because currently, when I don't write the `render()` function, nothing appears on the frontend.

**Comment by Paras16699** [comment]
Currently, I've implemented a workaround by directly modifying the hidden input value from `_content_template()` using jQuery and trigger the change:

`jQuery('#elementor-panel .elementor-control-my_control input').val( newValue ).trigger( 'input' );`

@bainternet, is this approach correct? Any other native Elementor way of implementing it?

**Comment by Paras16699** [comment]
`view` is available in `_content_template()`, so `view.model.setSetting( 'my_control', value );` works.

Got the hint from #4941.

That solves the problem without having to apply any JQuery hack and forcefully trigger input change.

**Comment by bainternet** [comment]
@Paras16699  

You got the right idea, `view` is available for you in the `_content_template()` and you can update the model from there but it's not advised to do so and `_content_template()` should be used for render only.

The reason it runs twice is that every time the model is changed `_content_template()` gets triggered.

thanks
