### ISSUE TITLE
✈️ 🔃 Thumbnails navigation for Image Gallery, or dynamic images for Media Carousel (Merged with #25442)

### ISSUE THREAD

**Issue by girl-mood** [elementor/elementor#9155]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I cannot use my template with ACF without dynamic images in Media Carousel or without thumbnails navigation in widget of Image Gallery

**Describe the solution you'd like**
Or add thumbnails navigation to widget of Image Gallery, or add option for dynamic images to Media Carousel. 

**Additional context**
Is there any way I can use template and add only images for Media Carousel widget manually?

**Comment by nicholaszein** [comment]
Hi there @girl-mood!

Thank you for submitting your request, and apologies for the delay in answering you! 🙏 

As we work to organize our GitHub repository, and group all of the Feature Requests in our new Discussions section, we would like to let you know we are merging your request with the one that is already submitted there.

### 🔃 This Feature Request is being merged with #25442 which is on the same subject. 

if you still think this request should be considered for our roadmap, please cast your **⬆️ Upvote** on the first comment.

Don't worry, your comments, reactions, and participation in this issue will be accounted for when considering this Feature Request for our Roadmap.

Happy voting! 🙂
