### ISSUE TITLE
Elementor Repeater , Font Family control not working in live edit mode.

### ISSUE THREAD

**Issue by latheeshvm** [elementor/elementor#9156]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have added a font family control in a repeater. Though it works in frontend it does not work in live edit mode. 
 
## Steps to reproduce

This asper documentation does not work in live edit mode
```
$repeater->add_control(
			'font_family',
			[
				'label' => __( 'Font Family', 'plugin-domain' ),
				'type' => \Elementor\Controls_Manager::FONT,
				'default' => "'Open Sans', sans-serif",
				'selectors' => [
					'{{WRAPPER}} {{CURRENT_ITEM}} .title' => 'font-family: {{VALUE}}',
				],
			]
		);
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by latheeshvmv** [comment]
?? Nothing. Seems Elementor Team pretty dead these days

**Comment by ashikurrahmanbd** [comment]
Same Issue facing for the last 3 days. And not getting any solution. Did you solve this? if so how you did do this?

**Comment by latheeshvm** [comment]
> Same Issue facing for the last 3 days. And not getting any solution. Did you solve this? if so how you did do this?

it should be `add_group_control` 

see here : https://developers.elementor.com/docs/control-classes/group-control-typography/
