### ISSUE TITLE
Popup - Dynamic URL

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#9159]
Hello. After speaking with the theme developer first and then Elementor support, I was advised (see bottom of this ticket) by Elementor support to create a ticket here.

Please see this [short video of the issue](https://www.loom.com/share/23bbff43665643bb8ba67c142faaa9fb). 

I have a Popup that works on every page, except one, which is shown at the :21 mark in the video.

I've included the credentials for the user so that this issue can be replicated on your end.

1. Log in as user
2. Go to Menu > Dashboard > My Listings (or [just click this link](https://app-5d757ad3f911c90950a5529e.closte.com/my-account/my-listings/))
3. Edit one of the listings
4. Click on Menu again and this is where you'll see the issue

[Admin URL
](https://app-5d757ad3f911c90950a5529e.closte.com/wp-admin/)
/* removed */
_> Hi Ryan,
> I really apologize for the long delay with the answer. 
> 
> However, I have checked the code and I see that the action parameter can't be used as it is already used in Elementor, so when you set up a dynamic function to open or close a popup, an action parameter with the value "close" or "open" is used for this. And if you add your custom Action parameter to the page URL it will break the dynamic popup function in Elementor.
> 
> I'm afraid this can't be changed in any other way in the short perspective. But if you believe there is a simple solution for this or you have any other suggestions, you can feel free to contact our developers on our GitHub account.
> Simply open a new issue and describe the problem, you can also mention the information you have received in this email so they can be in a better position to assist you with this._

Thank you,
Ryan

**Comment by bainternet** [comment]
@wpturnedup 

We can't replicate the issue on our end,
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
