### ISSUE TITLE
[feature request] ability to style (!) category archive pages for woo and others

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#9164]
having the ability to set up custom archives for woocommerce is - great.

BUT: as it seems they are extremely limited in terms of styling, which is unusual for elementor... unless i am missing something crucial.
so why not having custom styling in an extended manner and let us use skins??
as far as i can see now theres practically no option to _really_ style the woo category archives - category grid and products.

os did i miss something to get over the standard styling??? i cant even set the headline besides the image easily and give each entry some frames ... not to mention dynamic content as acf fields -  really disappointing :(

and while making this possible - maybe make it possible too for all other categories?
would be a real bummer.

-

Ahhh (EDIT):
and what if we even could assign different category archive templates to different category LEVELS(!) ??? 
so -> parent / first child / second child / ... each could have its own styling regardless of parent level. not sorted by 'child of' etc. - simply according to level of category/subcategory. clear enough?

**Comment by shilo-ey** [comment]
I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
