### ISSUE TITLE
Backend Language

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#9170]
I thought, I've reported this already a while ago, but couldn't find it here.

When I change the language of my user account in a WordPress instance, all plugins change the displayed language to that language, at least the good plugins. In the Elementor editor the language remains with the language of the  WordPress instance.

This is a bug or a misconception. You need to change that! Imagine, if you're working on a live site (so you can't change the language of the website) and you don't speek the language of that website. You can't work on the site, or it's a hassle.

**Comment by klainser** [comment]
Both Elementor and Elementor Pro use the [language set in the WordPress admin](https://docs.elementor.com/article/568-how-to-change-the-language-of-elementor-and-elementor-pro).

What version are you using of Elementor ?

**Comment by HelmutGoebel** [comment]
The most recent one. But this problem has ever been there.

**Comment by klainser** [comment]
You should revise your website install. Please check this on a fresh blank install using only the latest Wordpress and Elementor as on a fresh install.

I've set, from my end, a fresh sandbox using WP 5.2.3 & Elementor 2.7.3 & Elementor Pro 2.7.0 and set German as my language from my profile and[ I can see the Elementor Editor in German](https://i.imgur.com/mMywzzD.png) as the rest of the Wordpress admin.

What module are you using for translation ?

**Comment by dasigna** [comment]
@HelmutGoebel seems to be right ...

tested this second while hunting errors and wanted elementor to show the original language:changing user language leaves the language set for site in elementor.
only changing the sites language changes the language in elementor as well.

everything updated to the latest versions.

**Comment by HelmutGoebel** [comment]
So, hopefully you'll change that ASAP

**Comment by HelmutGoebel** [comment]
@klainser  You probably changed the language of the WordPress instance itself to German as well. But the point is, the language of the backend including the Elementor editor should be the language of the user currently logged in.

Modules for translation? What are you talking about?

**Comment by dasigna** [comment]
... i knew i had this recently :)

-> #5148

**Comment by shilo-ey** [comment]
Hi @HelmutGoebel 

Thank you for your feedback, but this issue, as you know has already been reported.


This issue is something we will refer in the after resolving all the possible conflicts (and there are several ones).

I merged this issue with  #5148, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by HelmutGoebel** [comment]
But honestly, an obvious bug like this just to administrate and not to have solved after more than a year is not appropiate to the claim, to be the best WordPress pagebuilder out there.

**Comment by Ooops-404** [comment]
2022, and its still an issue.
