### ISSUE TITLE
Templates For A Stock Trading Subscription Service

### ISSUE THREAD

**Issue by joshcorti11** [elementor/elementor#9172]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Dear Ben Pines,

Releasing a set of website templates for a stock trading subscription service would be epic and help you win over more subscribers. 

The ratio of crappy websites to good stock traders who need a beautiful site to promote their strategy/product is enormous. 

Elementor could find an entire new market segment amongst the day trading community with well-designed templates. 

If the day traders see Elementor is paying attention to their weaknesses, which is the website, they will warm up to the idea of using Elementor to improve their product. 

I appreciate everything your team does for this community. 

Joshua Cortigiano.

**Comment by bainternet** [comment]
@joshcorti11 

Thanks for the kind words, but this is not the place.

thanks again.
