### ISSUE TITLE
Add dynamic capabilities to 2.7 background slideshow feature

### ISSUE THREAD

**Issue by formulaclick** [elementor/elementor#9174]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can't use Elementor's new background slideshow feature in 2.7 dynamically. In my case I have a CPT with ACF's gallery field and I'd like to be able to show this images as background slideshow in single template.

**Describe the solution you'd like**
There should be dynamic options in background slideshow feature, just as happens with gallery widget, and then select a ACF gallery field.

**Comment by formgarten** [comment]
+1  Absolutely necessary !!!

**Comment by shilo-ey** [comment]
I merged this issue with #6683, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by formgarten** [comment]
Thank you. Didn’t find it before.

Cheers Thorsten


=================================================================

formgarten | informations.architektur
Thorsten Röver AGD

Waldhofer Str. 52
69123 Heidelberg
T  0049 (0)6221 - 585999
F  0049 (0)6221 - 585997
E  tr@formgarten.com
O  www.formgarten.com
     www.dribbble.com/formgarten
     www.behance.net/formgarten
     www.facebook.com/der.formgarten

Geschäftsführer: Thorsten Röver
USt-IdNr: DE211500929
Steuer-Nr.: 32357/42021


Diese E-Mail kann vertrauliche und/ oder rechtlich geschützte Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail (inklusive aller Kopien und Anhänge). Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/ or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail (including any attachments). Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Cet e-mail peut contenir des informations confidentielles et / ou exclusives. Si vous n'êtes pas le bon destinataire ou si vous avez reçu cet e-mail par erreur, veuillez en informer immédiatement l'expéditeur et détruire cet e-mail (y compris toutes les copies et pièces jointes). La copie non autorisée ainsi que la transmission non autorisée de ce courrier ne sont pas autorisées.

Questa e-mail può contenere informazioni riservate e / o proprietarie. Se non si è il destinatario corretto o si è ricevuta questa e-mail per errore, si prega di informare immediatamente il mittente e distruggere questa e-mail (incluse tutte le copie e gli allegati). La copia non autorizzata e la trasmissione non autorizzata di questa posta non sono consentite.

**Comment by formulaclick** [comment]
> I merged this issue with #6683, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> 
> Thanks for your feedback!

That issue you mention is related to Slider Widget. This issue is related to new background slideshow feature introduced in 2.7. Similar but not the same...

![image](https://user-images.githubusercontent.com/2376672/65593442-c5e64d00-df90-11e9-8daf-795b8bfbea4c.png)

**Comment by formgarten** [comment]
No, it's not the same subject. You're wrong. This request is about a new Elementor feature published a few weeks ago! What you now merged doesn't belong to this new feature.

@formulaclick : Thank you!!

**Comment by formulaclick** [comment]
@shilo-ey Why is this closed? As I described, this issue is not the same issue as you mentioned.

**Comment by ratsoid** [comment]
This should not be closed!

**Comment by aquaminh** [comment]
@shilo-ey Please open this feature request again. It's not the same as the issue you referred to. Thank you.

**Comment by idocme** [comment]
@shilo-ey this is not the same issue as you merged..
this talks about the slideshow of a background images...
