### ISSUE TITLE
Add the ability to specify a custom aspect ratio for the new Gallery widget

### ISSUE THREAD

**Issue by HQRaja** [elementor/elementor#9176]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Problem:

Allow us to have our images appear in their own aspect ratio rather than being limited to the options provided in the selection drop-down in the widget.

## Solution desired:

A 'Custom' option in the dropdown, which lets us specify an aspect ratio of our choice in width:height format. (It could use two separate fields for width and height parts of the ratio, or just instruct us to specify it in width:height format using a label.)

**Comment by black-eye** [comment]
+1

**Comment by DorShahar** [comment]
Hi @HQRaja 
I appreciate your suggestion. However, this request is out of our scope due to other priorities. 
You can use [CSS](https://css-tricks.com/aspect-ratio-boxes/) to accomplish your request.  

Don't hesitate to suggest more ideas! 
Thanks
