### ISSUE TITLE
Allow Custom Icon for Popup Close Button

### ISSUE THREAD

**Issue by jotcreative** [elementor/elementor#9177]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate. (https://github.com/elementor/elementor/issues/8728)
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
My designer thinks that the "X" on the popup and the arrows on post navigation are too thick, and wants me to use a thinner version (I have FontAwesome pro). Unfortunately, I can't seem to make the change.

**Describe the solution you'd like**
The close button and navigation arrows could/should be treated the same as every other icon type in Elementor.

**Describe alternatives you've considered**
Inserting a manual close button as an icon, but I'm not sure I can make the link close the popup.

**Comment by philmatt** [comment]
+1

I am trying to deactivate eIcons from my frontend, but this Popup Close icon is holding me back

**Comment by Waleedviews** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue #11361 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by t0ben** [comment]
The close Button from the Popup is still not changeable.

**Comment by SomeGuyNamedAlex** [comment]
This was closed due to issue #11361, which talked about the same thing, but for the nav bar. Nav bar was changed, and 3 years later, no implementation was made for the popup...

Can we get this feature ? @arielk
