### ISSUE TITLE
Popup dont save

### ISSUE THREAD

**Issue by zezao123** [elementor/elementor#9178]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Popup dont save. When i click on save a popup appear with this error

![2](https://user-images.githubusercontent.com/37622166/65534900-b4406f00-ded6-11e9-8f26-8580bf62d7b1.png)

## Steps to reproduce

Make a popup
Try to save

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.


It seems like you have some server configuration issues.

Please contact our support for better troubleshooting your problem.

Thanks.
