### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Elementor Form File Upload Offload to Cloud Storage (Google Drive, DropBox, S3, etc) (Merged with #4868)

### ISSUE THREAD

**Issue by fireleap** [elementor/elementor#9181]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, Elementor Form File Upload stores all uploaded files on the server under uploads/elementor/forms/file-name.extension

**Describe the solution you'd like**
Ideally, I would like to offload storage of uploaded files to a cloud storage provider like Google Drive, Dropbox, S3, etc to hold the files.

I capture form inputs to google sheets using the Zapier web hook integration, so preferable Google Drive for simplicity of workflow.

**Describe alternatives you've considered**
I'm not aware of any alternatives, though I've trawled through multiple search engines looking.

I might be able to do something with the email hack presented here, however it is definitely a hack, not a solution.
https://github.com/elementor/elementor/issues/4868

**Additional context**
N/a

**Comment by zachkinsey** [comment]
This would be great.

**Comment by afektomer** [comment]
YESSS

**Comment by sunawang** [comment]
it's also great if we could connect our forms to a form backend service

**Comment by stefanhz** [comment]
+1

**Comment by Flegme** [comment]
Oh this would be soooo great !

**Comment by d0ky** [comment]
+1

**Comment by Azertooth** [comment]
this would be awesome!

**Comment by wes1337** [comment]
Why is this still not a feature??

**Comment by lucasgf007** [comment]
Has anyone found any solution?

**Comment by nicholaszein** [comment]
Hello everybody!

Thank you for your submission! 🙏 

### 🔃  We are **Merging** this issue with #4868.

Which is on the same subject, so we can have all the discussions in one location, and deal with them more efficiently.

Feel free to continue the conversation there. 😉

Best regards,

Nick
