### ISSUE TITLE
ACF Repeater Field integration for multiple item widgets

### ISSUE THREAD

**Issue by formgarten** [elementor/elementor#9183]
I think it is urgent that all widgets with multiple items can be fully dynamically linked to ACF. Especially important is the use of the repeater fields of the Advanced Custom Fields (ACF) to dynamically create the number of contained items. These functions would be important to: slider, pricelist, media carousel, testimonial carousel, reviews.

Check out the ACF Repeater Fields: https://www.advancedcustomfields.com/resources/repeater/

**Comment by shilo-ey** [comment]
I merged this issue with #5979, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
