### ISSUE TITLE
[Elementor pro - Login Widget] Features missing in French language

### ISSUE THREAD

**Issue by lmoncany** [elementor/elementor#9192]
I noticed that when Wordpress & Elementor are in French language there is some missing features.

For exemple, for the login widget, The label option is missing in French : 

![71767354_388765738483621_7344103105010597888_n](https://user-images.githubusercontent.com/2823538/65617189-a107cf00-dfbc-11e9-8833-99c495f4fd1d.jpg)
![Capture](https://user-images.githubusercontent.com/2823538/65617190-a107cf00-dfbc-11e9-87c9-377a791d538e.JPG)

Version used : 
Elementor v2.7.3
Elementor Pro v2.7.0

**Comment by lmoncany** [comment]
Update : I changed the translation but i still don't have this Custom label checkbox showing even in en_gb

Any ideas ?

**Comment by bainternet** [comment]
@lmoncany 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for you issue, make sure that labels are set to `show` in the form fields section:

![Gwvaptn](https://user-images.githubusercontent.com/660572/65673405-6d2bb880-e053-11e9-9cd0-703760eb68cb.png)
