### ISSUE TITLE
Customize Hover Effects Overlay

### ISSUE THREAD

**Issue by summernola** [elementor/elementor#9193]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I reached out to support because I just thought the ability to customize the overlay for the hover effect was standard. But I learned it is not. The only customization that is allowed is a color option that can have the transparency adjusted. Thats it. :(
**Describe the solution you'd like**
I would like the option to be able to add a photo and/or text option to the hover effects overlay. specifically for me I wanted the hover overlay to be a photo that once you hover it reveals another photo.
**Describe alternatives you've considered**
I have not found any other solutions other than coming here to request that it is added to features 
**Additional context**
The box to the left is shown with the color option hover over lay that I edited
The box to the right is the template untouched
<img width="675" alt="Screen Shot 2019-09-25 at 10 27 39 AM" src="https://user-images.githubusercontent.com/55802333/65617092-ca573980-df81-11e9-9eac-ec6cb3f3709e.png">

**Comment by bainternet** [comment]
@summernola 

Take a look at https://elementor.com/widgets/flip-box/

thanks.
