### ISSUE TITLE
Slider - overlay and copy not going full width

### ISSUE THREAD

**Issue by agcreateit** [elementor/elementor#9196]
Just to note that in the Slides when using the overlay option on images it only boxes the overlay at around 800 pixels or thereabouts. Looks like the content box too does not go to full width either so if you have justified left or right it only goes to 800px in that direction not all the way to the full width. 

This happens only on latest release of Elementor and Pro. 

Commented a few times on Elementor Community group but no official notice of a fix as yet.

**Comment by shilo-ey** [comment]
I merged this issue with #9180, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
