### ISSUE TITLE
Different names of the Page Settings panel when creating and editing pages

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#9197]
When creating / editing pages, I need to add my (additional) page settings to the Page Settings panel. So I wrote a handler action 'elementor/element/after_section_end', which adds a new tab 'Layout' to the panel 'Page Settings' for element 'page-settings'. However, you often change the name of the element that creates this panel. First it was 'page-settings', then' post', now 'wp-post'. And for all types of posts using the name 'wp-post' (including when editing pages), but when creating a new page, the name 'wp-page' is used !

To illustrate, I retain the name of the element to the file in the handler action 'elementor/element/after_section_end': https://www.screencast.com/t/DoTbnQrh

Now open an existing page for editing: https://www.screencast.com/t/TtBDAU4Zf
And get panel name "Post Settings": https://www.screencast.com/t/yp1imUMbrnn and element name 'wp-post' https://www.screencast.com/t/IR69jzKt9

And now create a new page: https://www.screencast.com/t/IhQxwLztu678 
and press button "Edit with Elementor": https://www.screencast.com/t/I6MRg6uRI
And get panel name "Page Settings": https://www.screencast.com/t/lr6wxyD31t7 and element name 'wp-page' https://www.screencast.com/t/UUhDzJEL

Why do you change the names of previously created elements from previous versions of the plugin? I wish the developers of "Elementor" took into account that they do not write a usual plugin. They write a Page Builder, for which other developers will write addons. And with each such change of names that are used in actions and filters or names and class structures, they doom many other developers to problems with clients who suddenly have something stopped working and urgent release of updates to their themes and plugins due to lost compatibility!

I have been developing themes for WordPress for many years and worked with different Page Builders (such as Visual Composer, Site Origin Panels, King Composer) and none of them allowed themselves to change the rules of the game so often!  Over several years of use WPBakery PageBuilder (aka Visual Composer) we haven't been as many forced updates, how much we had to do over the past year, the use of Elementor!
We do not in any way regret the transition - Elementor is really the best PageBuilder that is on the market today, but we would like its developers to pay more attention to backward compatibility when releasing new updates.

I apologize for my English, but I hope I will understand and hear the developers of "Elementor".

**Comment by udidol** [comment]
Hi @VadymPogorelov,
To be sure I understand, you want to add a controls section to Elementor's Page Settings, only when editing Pages (but not posts, CPTs, etc.)?

You can do this with the action `'elementor/documents/register_controls'`.

```
add_action( 'elementor/documents/register_controls', function( $document ) {
	$document->start_controls_section(
		'your_settings_section_id',
		[
			'label' => __( 'Vadym's Settings', 'elementor' ),
			'tab' => Controls_Manager::TAB_SETTINGS,
		]
	);

	// Add your controls here

	$document->end_controls_section();
} );
```
