### ISSUE TITLE
Nav Menu Widget: Toggle Button Text

### ISSUE THREAD

**Issue by wpacademy** [elementor/elementor#9205]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will add enhancements to the toggle button.

**Describe the solution you'd like**
Toggle button should have a field to add text to the button, instead of just an icon it should be able to display text as-well. Like we want to use the toggle button in an eCommerce header and we want CATEGORIES or similar text along with toggle button to display drop-down of categories.

**Describe alternatives you've considered**
I have used custom CSS to produce a similar result, but that's a painful job. A working example with custom CSS is below
![Untitled Project](https://user-images.githubusercontent.com/38207694/65765869-cf171b80-e142-11e9-964f-0f4740708d1c.gif)

**Comment by besweeet** [comment]
@wpacademy - Care to share your CSS trick?

**Comment by wpacademy** [comment]
@besweeet well it's pretty simple. 
The menu widget and a heading widget aligned side by side (you can do that by changing widget width to inline from advanced tab > positioning) 
Then you can make the menu button 
```
.elementor-menu-toggle {
        width: 100%;
        text-align: left;
        display: block;
        position: absolute;
        top: 0;
        padding: 0;
        line-height: 1.4;
        padding-left: 5px;
}

```

**Comment by besweeet** [comment]
@wpacademy I dropped in a heading widget and set both widgets' positioning to inline. The next mystery is getting the heading widget to trigger the dropdown :/.
