### ISSUE TITLE
In EA Post Grid, load more button is not working

### ISSUE THREAD

**Issue by smlavoie** [elementor/elementor#9207]
In a page, with EA post grid model in place, since wordpress update to 5.2.3, even with the latest elementor extension (2.7.3), button "load more" is not working.

We're using a customized theme, but with twenty sixteen, problem is still there.

<summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.18 (Ubuntu)
	MySQL version: (Ubuntu) v5.7.27
	PHP Version: 7.0.33-0ubuntu0.16.04.5
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: https://aprescours.ticfga.ca
	Home URL: http://aprescours.ticfga.ca
	WP Multisite: Yes
	Max Upload Size: 98 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: FGA - Book Rev Lite
	Version: 1.0.0
	Author: Sylmedia - Sylvain Vachon
	Child Theme: Yes
	Parent Theme Name: Book Rev Lite
	Parent Theme Version: 1.7.10
	Parent Theme Author: Themeisle

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

== Active Plugins ==
	Add From Server
		Version: 3.3.3
		Author: Dion Hulse

	Akismet Anti-Spam
		Version: 4.1.2
		Author: Automattic

	Anywhere Elementor
		Version: 1.1
		Author: WebTechStreet

	Contact Form by BestWebSoft
		Version: 4.1.6
		Author: BestWebSoft

	Elementor
		Version: 2.7.3
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.6
		Author: WP Vibes

	Essential Addons for Elementor
		Version: 3.3.2
		Author: WPDeveloper

	FD Footnotes
		Version: 1.36
		Author: John Watson

	Front Page Category
		Version: 3.3
		Author: Ben Gillbanks

	Google Analytics for WordPress by MonsterInsights
		Version: 7.8.2
		Author: MonsterInsights

	Google Calendar Widget
		Version: 1.4.6
		Author: Kaz Okuda

	HT Mega - Absolute Addons for Elementor Page Builder
		Version: 1.2.3
		Author: HasThemes

	Kimili Flash Embed
		Version: 2.5.3
		Author: Michael Bester

	Skip to Timestamp
		Version: 1.4.4
		Author: Mark Deutsch

	Sticky Menu (or Anything!) on Scroll
		Version: 2.1.1
		Author: Mark Senff

	Unfiltered MU
		Version: 1.3.1
		Author: Automattic

	WP Category Tag Cloud
		Version: 1.7.1
		Author: Henri Benoit

	WP to Twitter
		Version: 3.4.1
		Author: Joseph C Dolson

	WPtouch Mobile Plugin
		Version: 4.3.37
		Author: WPtouch

== Network Plugins ==
	All In One SEO Pack
		Version: 3.2.9
		Author: Michael Torbert

	Captcha
		Version: 4.4.5
		Author: simplywordpress

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Clear Cache For Me
		Version: 1.0
		Author: Webhead LLC

	CodeStyling Localization
		Version: 1.99.30
		Author: Heiko Rabe

	Custom CSS and Javascript
		Version: 2.0.9
		Author: Potent Plugins

	Custom Sidebars
		Version: 3.2.3
		Author: WPMU DEV

	Font Awesome
		Version: 4.0.0-rc13
		Author: Font Awesome

	Pixabay Images
		Version: 3.4
		Author: Simon Steinberger

	Simple Calendar
		Version: 3.1.22
		Author: Simple Calendar

	Slimstat Analytics
		Version: 4.8.7.3
		Author: Jason Crouse

	WPtouch Mobile Plugin
		Version: 4.3.37
		Author: WPtouch

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Log<a href="/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=2fcc2a1925#elementor-clear-log" class="box-title-tool">Effacer le journal</a><span id="elementor-clear-log"></span> ==
	
JS: showing 7 of 7JS: 2019-08-12 18:52:17 [error X 1][https://aprescours.ticfga.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.8:7:49874] Cannot set property \'controls\' of undefined 
JS: 2019-08-13 13:55:49 [error X 1][https://aprescours.ticfga.ca/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:60824] Cannot read property \'query\' of null 
JS: 2019-08-13 15:37:23 [error X 3][https://aprescours.ticfga.ca/wp-admin/post.php?post=6037&action=elementor:3:40] Invalid or unexpected token 
JS: 2019-08-28 18:55:49 [error X 5][https://aprescours.ticfga.ca/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.6.8:2:38135] n.attributes[e.name].each is not a function 
JS: 2019-09-24 14:16:17 [error X 82][https://aprescours.ticfga.ca/wp-content/uploads/essential-addons-elementor/eael.min.js?ver=3.3.1:1:42452] Cannot read property \'totalPosts\' of undefined 
JS: 2019-09-25 13:19:20 [error X 4][https://aprescours.ticfga.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.2:32:63917] this.ui.apply.add is not a function 
JS: 2019-09-25 18:57:32 [error X 2][https://aprescours.ticfga.ca/wp-content/uploads/essential-addons-elementor/eael.min.js?ver=3.3.1:1:42430] r is undefined 

Log: showing 8 of 82019-09-21 08:59:37 [info] elementor::elementor_updater Started 
2019-09-21 08:59:37 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-21 08:59:38 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-21 08:59:38 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-21 08:59:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-09-21 08:59:38 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-21 08:59:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-09-25 14:56:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]

== Elements Usage ==
	
	page
		eael-post-grid : 1
	wp-post
		divider : 1
		eael-post-grid : 13
		heading : 5
		html : 1
		image : 13
		spacer : 1
		text-editor : 1
		wts-modal-popup : 1

				
</summary>

**Comment by shilo-ey** [comment]
Hi @smlavoie 

EA Post grid is a 3rd party widget.

You should consider contacting EA developers for help fixing your issue.

Thanks.
