### ISSUE TITLE
Ken Burns Effect removes background overlay colour on slides element

### ISSUE THREAD

**Issue by martinsmall25** [elementor/elementor#9209]
Ken Burns Effect removes background overlay colour on slides element even after the latest update 2.71. When I turn off Ken Burns effect the background colour comes back. Please fix.

**Comment by salsa-system** [comment]
I've got the same issue

**Comment by SparksSEO** [comment]
To confirm, same here.

**Comment by perks98** [comment]
#9180 They're aware of the issue but has of yet to be fixed. Likely they are fixing other issues to bundle with the next update. ~maybe

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7.2

Feel free to update

Thanks!
