### ISSUE TITLE
How do I transfer a setting from the Elementor Customizer to a JS file?

### ISSUE THREAD

**Issue by UrchenkoV** [elementor/elementor#9210]
Hello.

I'm making a widget carousel using Swiper.js how to pass the selection settings by the user in the JS file where the prescribed settings Swiper.js?

I didn't find the answer to this question in your documentation.

**Comment by udidol** [comment]
Hi @UrchenkoV,

See our doc about adding JS to Elementor widgets:
https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/
