### ISSUE TITLE
Enable right click (Duplicate and delete) for roles marked as "edit content only"

### ISSUE THREAD

**Issue by formulaclick** [elementor/elementor#9212]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When user is marked as "Access to edit content only" this user can't duplicate either delete sections/widgets. In some situations, it would be useful to make this possible without giving full edition options, that can be too complicated for some users.

**Describe the solution you'd like**
Enable an aditional access level including this options or create a php filter to customize this.

**Comment by formulaclick** [comment]
No comments for this? Any thoughts?

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
