### ISSUE TITLE
Create Pagination Widget for Elementor Pages

### ISSUE THREAD

**Issue by Steve0814** [elementor/elementor#9214]
Hi,

Recently I found that it is not possible to create pagination in Elementor pages, so hopefully Elementor can consider to design a pagination specifically for pages.

My page currently have 12 flip box, but I want to make it into only 9 flip box and another 3 flip box will be in another page.

Here is the example: http://stevesuccessnorms.com/free-downloadable-resources/
![basic-pagination](https://user-images.githubusercontent.com/55923176/65819257-ed693e00-e24c-11e9-9abf-8370ae927a4a.jpg)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1284, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
