### ISSUE TITLE
Form widget: Please add more Date field format options

### ISSUE THREAD

**Issue by govusfi** [elementor/elementor#9221]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Date field is in English and I have looked for code to change the format from mm/dd/yyy to d.m.y and also translate the calendar, which I found and it worked. However, on desktop the calendar weeks still start from Sunday and end in Saturday, which is an American format I think? The rest of the world's calendar weeks go from Monday to Sunday.

**Describe the solution you'd like**
Have the option to set the date format as you please, and what kind of calendar you want to use. In Finland our calendar's weeks go from Monday to Sunday for example. Also the option to translate the months and days would be awesome.

**Describe alternatives you've considered**
Find a function that changes the calendar weeks to go from Monday to Sunday.

**Additional context**

**Comment by bainternet** [comment]
@govusfi 

As you know Elementor Forms uses Flatpickr library for date\time fields on desktop and native on mobile devices. So you can use the Flatpickr API to modify the "First day of the week", ex:

```JS
flatpickr.l10ns.default.firstDayOfWeek = 1; // Monday
```

see more here: https://flatpickr.js.org/localization/
