### ISSUE TITLE
Navigation Menu/Header Theme Builder - Pop-up or Reveal Template on HOVER

### ISSUE THREAD

**Issue by createdbyred** [elementor/elementor#9224]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

This feature would put Elementor Theme Builder Header and Nav menus at the same high quality level as custom websites and websites built on other themes which use MEGA MENU layouts. Where for each main tab of a navigation menu, a large drop down is revealed which can contain many elements and not just text links. ie: icons to make menu more visual and approachable, buttons, images, search boxes and more!

**Describe the solution you'd like**
Right now, a pop-up can be used in a versatile way to create a sort of "mega menu" which appears on "click" of an item/tab in a built navigation menu in header, or by just creating a "hamburger" icon menu button in top right/left corner of header that triggers a header (this approach is great for mobile menus).

HOWEVER, it would be amazing to have instead a modification to the navigation menu or an option so that a pop-up could trigger on HOVER. Or so that specifically with a new "mega menu" widget, that for each tab of the menu, when you hover over it, it reveals a drop down of an Elementor built template that is for each section of the navigation menus.

PLEASE VIEW DEMO: https://www.loom.com/share/725a4c86a0174ae7ac0dba29a1032dc0

**Describe alternatives you've considered**
Just triggering pop-ups on "click" and building separate pop-ups, however, getting the spacing done really well can be a challenge to have it all look cohesive. It's also not as ideal to use since Mega Menus for a website is a very particular use-case and also a widely used design/functionality practice for websites which have lots of content/areas for users to navigate through.

A mega menu which can use drop down large tabs/sections to put in icons/pictures and other media makes the navigating for user more engaging and easy.

**Additional context**
Check out the desktop menu navigation for https://usps.com

Also can see my short video:
https://www.loom.com/share/725a4c86a0174ae7ac0dba29a1032dc0

Thanks so much!!! Shalom from San Francisco. :)

**Comment by srpotman72** [comment]
This would be great to have, thanks Jared for writing this down!

**Comment by anastk** [comment]
Yes totally agree with your approach to solve the mega menu issue, we already have the popups ready we can use them on hover as sub menus, I will tag your request with the other thread for menu enhancements if you don’t mind... #3275 

Thanks again.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
