### ISSUE TITLE
🔗 🚀 Feature Request: Edit text on mobile devices (Duplicate of #482)

### ISSUE THREAD

**Issue by jvkrimpen** [elementor/elementor#9230]
I really miss the possibility to **edit text** on mobile devices. I understand that Elementor Pro is a (great) page/theme builder, but everybody is used to working on mobile devices. It's hard to explain to clients that they can not do a quick text adjustment on their phone while they are on the way.

So I'm not looking for a way to use the page/theme builder options of Elementor on a mobile device, but merely text. And maybe in the future the possibility to change images or other small things.

I looked at the option to create something myself, but due to the way the pages are stored in the database this looks to complex for me.

[At the moment not even editing on iPad is possible, which is an extra shame](https://github.com/elementor/elementor/issues/3365). By the way, this request is different from previously mentioned thread.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #482, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
