### ISSUE TITLE
FULL Responsive Editing

### ISSUE THREAD

**Issue by jotcreative** [elementor/elementor#9233]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
What can be changed between desktop/tablet/mobile is currently a crapshoot. For example, my designer wants a background overlay gradient different on tablet and mobile, but background overlay isn't a responsive feature, apparently. Many feature requests here on Github are for various things to be editable for tablet and mobile ([example](https://github.com/elementor/elementor/issues/8265): a background photo be able to be REMOVED from tablet or mobile, instead of just replaced).

Bottom line: Those little desktop/tablet/mobile icons are beside many—but unfortunately not all—of the settings.

**Describe the solution you'd like**
In *my* perfect world, those little desktop/tablet/mobile icons would go away. Instead, we'd simply use the "view" icon in the bottom tray to swap between the sizes, and it would be understood that EVERYTHING in the settings tray would be editing one specific size.

Similarly, the actual preview would reflect what was and wasn't hidden on any given size ([Issue 8020](https://github.com/elementor/elementor/issues/8020)), and on/off toggles on the navigator (similar to Photoshop layers) would allow us to manipulate which elements are visible or hidden on the current view. (This would also reduce the confusion of people wondering where a hidden element went.)

**Describe alternatives you've considered**
For certain things, like background overlay, I guess I could try to manually code it in CSS.

**Additional context**
I can't believe I'm requesting this - Elementor has made designing far, far easier than ever before. After using it for months now, however, a few shortcomings are becoming apparent.

**Comment by ThomasS4b** [comment]
Is this what you want? Background/photo depending on device:
https://pafe.piotnet.com/docs/responsive-background-color/
https://pafe.piotnet.com/docs/custom-media-query-breakpoints%E2%80%8B/

**Comment by arielk** [comment]
Thanks for your feedback, I merged this issue with another issue https://github.com/elementor/elementor/issues/2043 in the similar subject so we could deal with it more efficiently. So please let's continue the conversation there.
