### ISSUE TITLE
Wp CLI – cannot activate elementor pro license

### ISSUE THREAD

**Issue by Micu22** [elementor/elementor#9235]
I am trying to activate elementor pro license using WP CLI, 
it returnes a message saying it has been activated successfully , but when I go to the page It isin't really activated

There was already someone asking a similar question, but there are some substantial differencies, so I have created a new one. Here is the old one: 
https://github.com/elementor/elementor/issues/4149#issuecomment-534963369

**Comment by macktic** [comment]
Same here, it says activated but I can't update the plugin, so not really activated

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
