### ISSUE TITLE
FAQ block element

### ISSUE THREAD

**Issue by smcrmo** [elementor/elementor#9237]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

A way to insert a FAQ block into a page or post from within the Elementor editor

**Describe the solution you'd like**

I'd like to see the addition of an element in the Elementor editor that would add a FAQ block to the page or post I'm editing. It would have a question field that appears in bold on the front end, and an answer field that appears in normal text. The ability to add a FAQ block to a post or page would be an SEO feature.

Thanks!

**Comment by shilo-ey** [comment]
Hi @smcrmo 

This feature has been added to Accordion and Toggle widgets

Feel free to update to the latest Elementor versions
