### ISSUE TITLE
Input mask for a field phone

### ISSUE THREAD

**Issue by anton-vv** [elementor/elementor#9238]
Good day! Really need a input mask for a field phone.
Tell me, please, do you plan to make this feature? 
Without this feature, the site looks frivolous. Thanks in advance!

**Comment by shilo-ey** [comment]
I merged this issue with #3236, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by anton-vv** [comment]
> I merged this issue with #3236, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> 
> Thanks for your feedback!
But #3236 was closed a year and a half ago. Please answer this question.

**Comment by anton-vv** [comment]
But #3236 was closed a year and a half ago. Please answer this question.

**Comment by anton-vv** [comment]
> I merged this issue with #3236, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> 
> Thanks for your feedback!

But #3236 was closed a year and a half ago. Please answer this question.

**Comment by eduardovillao** [comment]
Use this plugin: https://wordpress.org/plugins/form-masks-for-elementor/

Form Masks for Elementor
