### ISSUE TITLE
Enqueues unnecessary JS/CSS files on the backend

### ISSUE THREAD

**Issue by bompus** [elementor/elementor#9240]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Possibly related to #8572 , but this is regarding the backend. On my WP dashboard index.php, I'm seeing a total of 12 Elementor CSS/JS files being loaded. I've removed the Elementor Overview widget (which there really should be an option to disable completely). Below is the list of files being enqueued, when **ideally**, they should only be enqueued on the pages that need these files.

elementor-icons.min.css?ver=5.4.0 (free)
common.min.css?ver=2.7.3 (free)
admin.min.css?ver=2.7.3 (free)
backbone.marionette.min.js?ver=2.4.5 (free)
backbone.radio.min.js?ver=1.0.4 (free)
common-modules.min.js?ver=2.7.3 (free)
dialog.min.js?ver=4.7.3 (free)
common.min.js?ver=2.7.3 (free)
admin.min.js?ver=2.7.3 (free)
eicons.woff2? (free)
admin.min.css?ver=2.7.1 (pro version)
admin.min.js?ver=2.7.1 (pro version)

The files above alone (brotli/gzip transferred) take up 142KB / 844 KB of the assets loaded on the page, thats about 17% that could be cut out from loading on most pages in admin.

## Steps to reproduce

- Load the WP admin area dashboard, /wp-admin/index.php
- View Network panel in browser developer tools.
- Refresh page to see requests, filter for elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by drawcard** [comment]
This is just an uneducated guess but I wonder if these scripts need to be enqueued because of the Elementor Finder function:

https://elementor.com/blog/introducing-finder/

**Comment by bainternet** [comment]
@bompus 
These asset files are enqueued for a reason, not really sure how you got these numbers(844KB) and with simple browser cache these are only transferred once to the browser and for the rest of the page loads they are loaded from the cache anot not requested from the server:

![image](https://user-images.githubusercontent.com/660572/66126029-1b55d600-e5f1-11e9-9812-f2bf1ed74737.png)

And you can always wp_dequeue_style(), wp_deregister_style(), wp_deregister_script(), wp_dequeue_script() any asset Elementor adds that you don't want.

@drawcard 
correct, among other features.
