### ISSUE TITLE
Cannot see items from custom query

### ISSUE THREAD

**Issue by roiko** [elementor/elementor#9244]
Hello,
I'm working on a website where I should use custom query for showing custom posts in a "Edit Posts" widget.
Actually, I need to filter these custom posts based on some parameters in query string, so I decided to use the custom query feature.
As first step, I just wanted to use a fixed query (without query string parameters) just to see if this method is ok, but I already faced some problems. 
I'm using:
- Elementor 2.7.3
- Elementor PRO 2.6.5.

I followed this guide: [https://developers.elementor.com/custom-query-filter/](https://developers.elementor.com/custom-query-filter/)

In particular, I set the following properties in "Edit Posts" widget:
- Query: Current query
- Query ID: my_custom_filters
![edit_posts](https://user-images.githubusercontent.com/7915641/66125647-d7aa9e80-e5e7-11e9-9122-58a2f676362a.png)

Then I updated the functions.php file of my child theme (OceanWP) and you can find it here:
[functions.php.txt](https://github.com/elementor/elementor/files/3685942/functions.php.txt)

The code I wrote is:

```
add_action( 'elementor/query/my_custom_filter', 'showMyResults');

function showMyResults( $query) {
    $query->set( 'post_status', ['publish'] );
	$query->set('post_type',['automobili']);
	$meta_query = $query->get( 'meta_query' );
	$meta_query = [
	    ['key' => 'marca',
	    'value' => 'Renault',
	    'compare' => '=']
	    ] ;
	$query->set( 'meta_query', $meta_query );    
	
	$javascript_ouput = "<script>console.log('Debug Info: DUDU');</script>";
echo $javascript_ouput;
}
```

The action correctly fires (because I can read "Debug Info: DUDU" in the browser console), but data is not displayed.
I also tried to leave the post_status filter part only, like this:

```
function showMyResults( $query) {
    $query->set( 'post_status', ['publish'] );
}
```

But nothing changes. 
The page where the issue is present is: [https://stage.ioroiko.com/custom-query/](https://stage.ioroiko.com/custom-query/)

Am I missing something? I cannot understand how to use this feature...

Thank you in advance!

**Comment by bainternet** [comment]
@roiko 

Don't use a custom query filter on "Current Query" source. for that use the native WP `pre_get_posts` filter.

thanks.

**Comment by roiko** [comment]
Thanks @bainternet. Then what do I have to set as Source in order to use the custom query?
