### ISSUE TITLE
Conflict with NinjaForms

### ISSUE THREAD

**Issue by happy-harry** [elementor/elementor#9249]
Please provide a fix regarding this issue : [#7476](https://github.com/elementor/elementor/issues/7476) The issue is discussed further here: #8267  

You can get more details here as well: https://wordpress.org/support/topic/bug-in-compatibility-php-conflicting-with-ninja-forms-and-causing-loss-of-data/

The issue has been closed while it's still occurring.

On August 22, @shilo-ey had said the issue would be resolved in the next build [in this comment](https://github.com/elementor/elementor/issues/8267#issuecomment-523754618). However, several versions have been released, and the faulty code is still included.

**Comment by shilo-ey** [comment]
This function will be deleted in v2.8, 

We notified the plugin author to create an Elementor widget that handles their forms in a better way that the WP one.

Thanks

**Comment by markd91** [comment]
Bump, still having this issue

**Comment by aroemen** [comment]
@shilo-ey can you elaborate on what the better way the widget should handle Ninja Forms?
