### ISSUE TITLE
Responsive options in Post widget

### ISSUE THREAD

**Issue by anjot** [elementor/elementor#9252]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will help us create a responsive posts.

**Describe the solution you'd like**
I think it would be better that elementor will put responsive options for the image positions in the post widget. 

**Describe alternatives you've considered**
Also, I noticed that there are no responsive options for the style> Box and Layout options. I dont know whether to report it as a bug or feature request.

**Additional context**
For example in this post, it would be better if we can change the image position to top while in mobile view:
![image](https://user-images.githubusercontent.com/36961825/66187837-42c3a600-e6b8-11e9-93d7-0ad5df29f2b4.png)

something like this (i used a different plugin for this widget):
![image](https://user-images.githubusercontent.com/36961825/66187783-2293e700-e6b8-11e9-8a40-7e097bebba86.png)

(no responsive option:)
![image](https://user-images.githubusercontent.com/36961825/66187699-eb253a80-e6b7-11e9-9868-5125e5e42f4c.png)

**Comment by shilo-ey** [comment]
Hi @anjot 

I merged this issue with #1851, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
