### ISSUE TITLE
Product comparator does not show on Product Archives templates created with Elementor Theme Builder 

### ISSUE THREAD

**Issue by tropicaldev** [elementor/elementor#9256]
Product comparator does not show on Product Archives templates created with Elementor Theme Builder 

Hello, 

I'm using the plugin 
WooCommerce Product Comparison (By Bolder Elements)
https://bolderelements.net/plugins/compare-products-woocommerce/

The plugin comparator works just fine when using woocomerce default templates.
When creating Product archives templates with Theme Builder it does not work.

The developer of the plugin says its essential that the template has 
get_footer( 'shop' ) in order the comparator to work ( to show as a floating box at the bottom near the footer)

Developer feedback (of plugin Comparator) :

"for this plugin the important missing piece is the correct argument in the wp_footer function"

"I do not personally understand why a page builder would modify this portion of the template. I have been using WPBakery Page Builder for years and dabbled with a couple others and have never seen a complete template override like this. So I can't explain to you why this happens and there's really nothing I can do from my own plugin since it's purpose is to modify WooCommerce, not the Elementor plugin."

"I'm sure they will be able to help you determine why the wp_footer function changes when you create a page template through them and hopefully how to fix it."

So,
Is the argument on footer being changed by page builder?
How am i able to customize a Product Archive Template but keep the argument on the footer function?

wordpress 5.2.3
woocommerce 3.7.0

**Comment by bainternet** [comment]
@tropicaldev 

Please feel free to direct the plugin developer to our support, will try to help him.

thanks.
