### ISSUE TITLE
✔️ 🚀 Feature Request: Option to allow aligning button (and other widgets) to the bottom of a column

### ISSUE THREAD

**Issue by joelnewcomer** [elementor/elementor#9258]
A common need we have is to align a button to the bottom of a column. I am always having to add CSS for that. It would would also be great to have that option for a WooCommerce product loop as well—to make the "Add to Cart" button align to the bottom of the block. Thanks!

Joel

**Comment by nicholaszein** [comment]
Hello there @lior-sh!

We have great news! 🙌 

### 📢 We're happy to announce that you can now halve full control over the position of the items inside a container with the <ins>stable</ins> version of the Flexbox Container experiment introduced in Elementor **v3.8**! 🥳 

You are invited to update Elementor to the latest version, activate the Flexbox Container experiment, and enjoy the full power of CSS Flexbox! 💪 

Cheers 🥂
