### ISSUE TITLE
Cannot center align images with Gutenberg while Elementor is active

### ISSUE THREAD

**Issue by michaelswengel** [elementor/elementor#9259]
Team,

I cannot center align images while Elementor/Elementor Pro are active on my sites. This occurs on multiple self-hosted installations running Elementor and the Sydney theme (though it happens with other themes as well.)

When I add an image in the Gutenberg editor, I can click the center align option. However, it does not center when previewing or when publishing.

If I select the align right button, the image correctly aligns to the right. Aligning center does not work.

Disabling Elementor resolves the issue, and image alignment works as it should.

This is the code of one such image that will not align correctly.
`<div class="wp-block-image"><figure class="aligncenter"><img src="https://listbootcamp.com/wp-content/uploads/2019/10/email-click-through-rate.png" alt="Example email CTR in GetResponse" class="wp-image-707"/><figcaption>Example email CTR in GetResponse</figcaption></figure></div>`

I do not have any custom CSS set for my theme.

**Comment by michaelswengel** [comment]
Update: Adding this custom CSS fixes the issue, but I should not have to add this custom CSS.
Elementor breaks Gutenberg's ability to center align images without this code.

.elementor .elementor-widget .wp-block-image .aligncenter {
    margin-left: auto;
    margin-right: auto;
}

**Comment by shilo-ey** [comment]
Thanks, we will review your PR and consider adding it as a fix for this issue.

ref: #7331

**Comment by shilo-ey** [comment]
Hi @michaelswengel 

Thanks for your PR,
Unfortunately, after examining your PR and after we ran some visual compare tests, we found that this fix is incomplete and may cause backwards compatibility issues.

We appreciate the time and effort you spent on fixing this issue, but we need to think about less "strict" rule for this issue.

Currently I'm closing this issue.

If you have another idea please share it with us in #7331 !

Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!
