### ISSUE TITLE
Button custom CSS won't work

### ISSUE THREAD

**Issue by GenetixEMR** [elementor/elementor#9262]
I am trying to create a gradient button with a animated hover effect. For the example of effect go to:

https://gradientbuttons.colorion.co/

I use the following code in my button custom CSS:

selector .elementor-button {background-image: linear-gradient(to right, #314755 0%, #26a0da 51%, #314755 200%)}

selector .elementor-button:hover { background-position: right center; 
} 

The hover effect won't work. Also the gradient (normal) is not what it looks like as seen on https://gradientbuttons.colorion.co/  -  If I look at the CSS code for the linear - gradient I notice why, but if I look at other websites with the same effect, they all explain and show the same code. 

Why isn't this CSS code working in elementor ?

**Comment by shilo-ey** [comment]
This issue is not related to Elementor.

This is a CSS question.
Try adding background-size to your button:

```CSS
    background-image: linear-gradient(to right, #e52d27 0%, #b31217 51%, #e52d27 100%);
    background-size: 200% auto;
```
