### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Starkemis** [elementor/elementor#9263]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Dark mode for Elementor editor. My eyes hurt from looking at it all day. I have dark mode toggle on my browser but turn it off for Wordpress because it changes the color of the website being designed slightly.

**Describe the solution you'd like**
Dark mode for everything Elementor. Hopefully Wordpress will implement their own dark mode soon.

**Additional context**
Here's how it looks.
![pjmqZdg](https://user-images.githubusercontent.com/6629056/66261593-16687080-e803-11e9-92a4-26375ec6468f.png)

**Comment by drawcard** [comment]
And as a 🍒on the 🎂make it detect the user's browser / OS preferences:

https://web.dev/prefers-color-scheme

**Comment by jazir5** [comment]
This is a necessity. This isn't just a UX issue, this is actually a health issue. 

http://www.bluelightexposed.com/

https://www.sciencedirect.com/science/article/pii/S2351978915004606

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6288536/

https://www.tandfonline.com/doi/full/10.1080/07420528.2018.1527773

https://www.cnn.com/2019/05/16/health/blue-light-led-health-effects-bn-trnd/index.html

https://www.webmd.com/sleep-disorders/news/20170619/is-blue-light-bad-for-your-health

https://www.ocushield.com/what-are-the-effects-of-blue-light-on-ocular-health-and-circadian-rhythms/

The sheer volume of literature supporting the harmful effects of blue light are staggering. This is a small fraction of the body of research supporting the fact that blue light is detrimental to your health. This should be an important issue to every single web developer who reads this topic, Dark Mode is simply a necessity for those who work with computer screens daily.

Working in web design already requires you to be sitting and immobile, which i think we can all agree is taxing on our health. We should at least have the option to reduce blue light exposure as much as possible.

Please Elementor team, make this a focus for the next release.

**Comment by jazir5** [comment]
@arielk, @bainternet

Unsure if you are pinged if the @ reference is edited into a submitted comment.

**Comment by KingYes** [comment]
Final work there: https://github.com/elementor/elementor/pull/9580

**Comment by numanzahid** [comment]
Dark mode is added to the elementor UI in beta. this looks great.

we need support for dark mode in page design too so that we can design for light mode and dark mode on the bases of user preferences. 

this request was closed and merged with this thread. https://github.com/elementor/elementor/issues/9772

please reconsider. as it is completely new function that will need your work.

do let me know if I need to recreate request with more details and design examples.

thanks.

**Comment by drawcard** [comment]
I would love to see this feature in Elementor as well. Maybe to make it less complicated, it could be a global style setting for Sections, where you can currently set link / heading text colours etc.

But for now you can use the prefers-dark-mode media query in your CSS stylesheet:

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

The other benefits (aside from health) are that dark mode can save battery usage on OLED screens (as a black pixel on an OLED turns off the backlight for it). So there are a few positive selling points to having it as a feature.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8

Feel free to update

Thanks!

**Comment by bestelife** [comment]
[bestelife](https://www.bestelife.com)

**Comment by mantracareorg** [comment]
very informative.
Also view - https://mantracare.org/
https://mantracare.org/diabetes-treatment/

**Comment by eyemantrain** [comment]
Very Helpful content .
Also have a look on - https://eyemantra.in/cataract-surgery/
https://eyemantra.in/delhi/cataract-surgery-delhi/
https://eyemantra.in/specs-removal/
https://eyemantra.in/lasik/
https://eyemantra.in/squint/
https://eyemantra.in/glaucoma-surgery/
https://eyemantra.in/cornea-surgery/
https://eyemantra.in/retina-surgery/
https://eyemantra.in/eye-hospital-paschim-vihar/
https://eyemantra.in/eye-hospital-rohini/

**Comment by eyemantraorg** [comment]
Liked the content. Informative
kindly view also - https://eyemantra.org/cataract-surgery/
https://eyemantra.org/lasik/
https://eyemantra.org/squint/
https://eyemantra.org/glaucoma-surgery/
https://eyemantra.org/retina-surgery/

**Comment by diabetesmantraa** [comment]
precise and informative post.
Also view - https://diabetesmantra.com/diabetes-treatment/
https://diabetesmantra.com/diabetes-clinic/
https://diabetesmantra.com/diabetologist/
https://diabetesmantra.com/franchise/

**Comment by mantracareinn** [comment]
Gave a reading and found it very informative.
Also view - https://mantracare.in/piles/
https://mantracare.in/fistula/
https://mantracare.in/fissure/
https://mantracare.in/franchise/
https://mantracare.in/consultant/hospital-registration-empanelment/
https://mantracare.in/consultant/nabh-accreditation/
