### ISSUE TITLE
elementor_pro/forms/new_record: Too few arguments to function

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#9264]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and DID find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

This issue is identical to #5941 - closed by author w/o explanation...
and possibly related to #4162

I guess its a setup issue.
Clearly, A paragraph explaining $ajax_handler in documentation is missing!

## BUG/PROBLEM Description

I am trying to set a WC products filter based on the following code from documentation.
Note: I tried $handler as in documentation and also $ajax_handler as a guess.
Both produce the same result.
```
add_action( 'elementor_pro/forms/new_record', function( $record, $ajax_handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'pkg-filter' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'http://kal.site2goal.net/xyz', [
		'body' => $fields,
	]);
});
```

## Steps to reproduce

1. Use either 2017 or Hello child theme
2. Wordpress latest 5.2.3
3. Elementor 2.7.3
4. Elementor pro 2.7.1
5. Generate a page with form widget (name 'pkg-filter', in my example)
6. Set webhook URL to '/xyz'

Result is:
Error (i.e. "message not sent")
and in debug.log:
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function {closure}(), 1 passed in <home>/public_html/wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in <home>/public_html/wp-content/themes/twentyseventeen/functions.php:666
Stack trace:
#0 <home>/public_html/wp-includes/class-wp-hook.php(288): {closure}(Object(ElementorPro\Modules\Forms\Classes\Form_Record))
#1 <home>/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 <home>/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 <home>/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php(145): do_action('elementor_pro/f...', Object(ElementorPro\Modules\Forms\Classes\Form_Record), Object(ElementorPro\Modules\Forms\Classes\Ajax_Handler))
#4 <home>/public_html/wp-includes/class-wp-hook.php(286): ElementorPro\Modules\Forms\Classes\Ajax_Handler->ajax_send_form('')
#5 <home> in <home>/public_html/wp-content/themes/twentyseventeen/functions.php on line 666
[system-info-kal.site2goal.net-06-10-2019.txt](https://github.com/elementor/elementor/files/3693932/system-info-kal.site2goal.net-06-10-2019.txt)

## Isolating the problem
- [ yes] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ yes] This bug happens with a default WordPress theme active.
- [ yes] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
see attached
</details>

**Comment by Mulli** [comment]
Fix...
add_action was missing parameters...
add_action( 'elementor_pro/forms/new_record', function( $record, $ajax_handler ) { ...} , 10, 2 );

I just post it here for others that may missed it as I did...

**Comment by shilo-ey** [comment]
Hi @Mulli 
 
Glad you figured it out. as you can see it also exists in [our documentation](https://developers.elementor.com/forms-api/).

Thanks!

**Comment by Mulli** [comment]
BUT, there is a problem:
wp_remote_post( 'http://kal.site2goal.net/xyz', [
		'body' => $fields,
	]);

does not show any output & no error - Just message sent successfuly
Is there a better example of the above - or directions how to reply
with list of posts (archive like) to display on same page?

**Comment by sharif21307** [comment]
hi 

I have the same problem, i ma using elemntor for the reason it needs not coding, and I found myself learning to code to solve very simple function like sending email via popup 
I am really feel overwhelmed for the reason all my energy going to solve such basic functions while i suppose to focus on my main business.
elemntor should notice that
