### ISSUE TITLE
Swiper version update to 5.*.*

### ISSUE THREAD

**Issue by wayheming** [elementor/elementor#9275]
Hello team Elementor,
Now Elementor uses version Swiper 4.4.6 and version 5.0.4 is already available. Please tell me when you plan to upgrade to version 5. Since they updated the documentation for version 5 and development for 4 causes problems. Thanks in advance.

**Comment by shilo-ey** [comment]
Hi @wayheming 

Thanks for your feedback.

Upgrading Swiper version is on our roadmap. we will do it after we make sure nothing breaks and then we will release it.

Follow this issue for more updates.

Thanks

**Comment by wayheming** [comment]
@shilo-ey thank you

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.0

Feel free to update

Thanks!

**Comment by wayheming** [comment]
@shilo-ey hello! thank you
