### ISSUE TITLE
wp_remote_post in elementor_pro/forms/new_record return 404 page not found

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#9278]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The problem - wp_remote_post() fail - on exact same code as in documentation

I am using $response = wp_remote_post() ; Just to see that "page not found"
**Here is part of the log:**
```
remote success response = Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [date] => Mon, 07 Oct 2019 09:31:06 GMT
                    [server] => Apache
                    [x-powered-by] => PHP/7.3.9
                    [expires] => Wed, 11 Jan 1984 05:00:00 GMT
                    [cache-control] => no-transform, no-cache, must-revalidate, max-age=0
                    [link] => <https://kal.site2goal.net/wp-json/>; rel="https://api.w.org/"
                    [upgrade] => h2,h2c
                    [content-type] => text/html; charset=UTF-8
                )

        )
// whole page html & more ... truncated for clarity
[status_code] => 404
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    **[url] => https://kal.site2goal.net/xyz**
```
[ur] exists! see [https://kal.site2goal.net/xyz](https://kal.site2goal.net/xyz)

**Here is the code as in example**
```
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
//make sure its our form
$form_name = $record->get_form_settings( 'form_name' );
if ( 'pkg-filter' !== $form_name ) {
return;
}

$raw_fields = $record->get( 'fields' );
$fields = [];
foreach ( $raw_fields as $id => $field ) {
    $fields[ $id ] = $field['value'];
}

$response = wp_remote_post( '<full-path-my-domain>/xyz', [
    'body' => $fields,
]);
// for part of error_log of $response - see below
error_log('Response ='. print_r($response, true));
}, 10, 2 );
```
## Steps to reproduce

Use either 2017 or Hello child theme
Wordpress latest 5.2.3
Elementor 2.7.3
Elementor pro 2.7.1
Generate a page with form widget (name 'pkg-filter', in my example)
Set webhook URL to '<full-path-my-domain>/xyz'

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Same as in #9264

**Comment by shilo-ey** [comment]
Hi @Mulli 

Try to check your function with https://requestbin.com and see if your request is being processed there. (works perfectly with the example [provided here](https://developers.elementor.com/forms-api/#Form_New_Record_Action))

If so, you need to check your endpoint and see why it returns 404 status.

Thanks!
