### ISSUE TITLE
[issue] slider errors since 2.7 - broken and not working anymore

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#9280]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

since latest updates slider element does not work as before.
- change animation doesnt work at all
- content animation not working anymore and does not start on second slide -> empty content
- arrows and dots are warped, arrows without function

worked perfectly until 2.71/2.65pro - afterwards stopped working and caused errors.
not solved with the latest updates!!

screenshot before:
![slider-normal-2019](https://user-images.githubusercontent.com/22448174/66311193-333d9a80-e90e-11e9-81e5-9a7dbdc6b0cb.PNG)

screenshot after:
![slider-error-2019](https://user-images.githubusercontent.com/22448174/66311205-3cc70280-e90e-11e9-87b3-bb856351b8f4.PNG)

CANT UPDATE TO USE LATEST FUNCTIONS BECAUSE OF THAT!
theres no way to get it repaired via backend as even some of the controls e.g. for dots dont do anything ...!

even no animations on backend for preview.

total mess ...

## Steps to reproduce

take an previously created slider and have a look after update ...

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
... staging available for research ...
```
</details>

**Comment by shilo-ey** [comment]
Hi @dasigna 

We can't replicate your issue.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
