### ISSUE TITLE
SendinBlue

### ISSUE THREAD

**Issue by danna556** [elementor/elementor#9281]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by danna556** [comment]
Hello, can u integrate elementor with [send in blue](www.sendinblue.com)

**Comment by bainternet** [comment]
Duplicate of #6527 and https://github.com/elementor/elementor/issues/3315#issuecomment-361078878
