### ISSUE TITLE
Elementor Certifications

### ISSUE THREAD

**Issue by diegoestrada510** [elementor/elementor#9282]
Hi! Im an Marketing profesor on a university of México.

I love to use Elementor, I'm a great fan of the plugin.

Is there a way to be certified as Elementor Teacher? 

It would be a great form to promote your plugin within my students, I'll be pleased if there is a way to make it official. 

Also I have a consulting agency and it would be awesome also to promote it with my clients!

**Comment by bainternet** [comment]
@diegoestrada510 

Please contact our support at support @elementor.com and mention that you were directed by me and reference this issue.

thanks.
