### ISSUE TITLE
widgets custom query for posts/ products visited

### ISSUE THREAD

**Issue by vallered** [elementor/elementor#9286]
It would be great, to have a php code snippet to address the custom query filter of e.g. elementor post widgets to display only the posts the user visited.
So far I only managed to find a code snippet to deliver a respective shortode (working, but that is not a good solution, as it bypasses Elementors design included in its widgets), it is as follows:

```PHP
add_shortcode( 'recently_viewed_products', 'bbloomer_recently_viewed_shortcode' );
 
function bbloomer_recently_viewed_shortcode() {
 
   $viewed_products = ! empty( $_COOKIE['woocommerce_recently_viewed'] ) ? (array) explode( '|', wp_unslash( $_COOKIE['woocommerce_recently_viewed'] ) ) : array();
   $viewed_products = array_reverse( array_filter( array_map( 'absint', $viewed_products ) ) );
 
   if ( empty( $viewed_products ) ) return;
    
   $title = '<h3>Recently Viewed Products</h3>';
   $product_ids = implode( ",", $viewed_products );
 
   return $title . do_shortcode("[products ids='$product_ids']");
   
}
```
A quick soltion would be if you can provide us with a respective code snippet to hook into your custom query filter. I think this is of great interest for many Elementor users.

Regards
Herbert

**Comment by bainternet** [comment]
@vallered 

WordPress doesn't save a cookie (or any other session storage) of recently viewed/visited posts out of the box. But if your question is how to work with `woocommerce_recently_viewed` cookie and our posts widget custom query its actually very simple:

```PHP
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	$viewed_products = ! empty( $_COOKIE['woocommerce_recently_viewed'] ) ? (array) explode( '|', wp_unslash( $_COOKIE['woocommerce_recently_viewed'] ) ) : array();
	$viewed_products = array_reverse( array_filter( array_map( 'absint', $viewed_products ) ) );
 
	$query->set( 'posts_in', $viewed_products );
} );
```

Which is the same way you would modify any WP_Query in WordPress.

thanks

**Comment by vallered** [comment]
many thanks, I did the settings as you recommended, even keeping "my_custom_filter" as ID. Put that into Elementors post widget. As query ID, as source I set "products".

Apart from that I managed to get the necessary woocommerce cookie up and running (but that is not the issue).

As a result, the query ID does not have any effect on the results from the widget. Regardless what I am putting into the widget as ID (my_custom_filter, XYZ, anything else...), it does not narrow down the results. What I am missing?

**Comment by amjulash** [comment]
Hi, on my website recently viewed products of woocommerce don’t work when elementor enabled on the website.

When I disable elementor, then I can see cookies get updated with new product id of recently viewed products, but when enabled cookies don’t update with product ID and keep showing old product of when elementor was disabled.

I use this below to set custom query to show recently viewed products with posts widget:

```
add_action( 'elementor/query/customquery', function( $query ) {
	
	// Get WooCommerce Global
	global $woocommerce;

	// Get recently viewed product cookies data
	$viewed_products = ! empty( $_COOKIE['woocommerce_recently_viewed'] ) ? (array) explode( '|', $_COOKIE['woocommerce_recently_viewed'] ) : array();
	$viewed_products = array_filter( array_map( 'absint', $viewed_products ) );

	// If no data, quit
	if ( empty( $viewed_products ) )
		return;

	$query->set( 'post__in', $viewed_products );

});
```

But with elementor enabled cookies don't get updated with new product ID of recently viewed products, same issue for woocommerce recently viewed widget.

I am using latest elementor pro version. Is this maybe a bug?

**Comment by rad0301** [comment]
This still doesn't seem to work. Can someone help
