### ISSUE TITLE
New form feature

### ISSUE THREAD

**Issue by mikeecho2** [elementor/elementor#9287]
Add a tick to each field on the elementor form widget, that I can tick so that any URL"S entered into that field by a visitor, will block the form from being sent, and show an error informing the user that URL's are not allowed in that field.
In addition, it would be fantastic, if there is a place where I can type in the "allowed" characters for each field (default all) eg Only allow "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,"
Maybe have a tick box for A-Z, a-z, 0-9, standard special characters such as ",m*&^%$#@()", and then a option to enter your own Custom allowed characters.

I have done this on custom non-wordpress website's, and it had a massive effect on reducing the spam the client received via the website forms.

It is very easy to do, and it would be an AWESOME feature if Elementor builds it into their form widget

**Comment by bainternet** [comment]
@mikeecho2 

thanks for the suggestion, Currently, our forms support (mostly) native HTML5 validation for required, email, phone pattern ...
Anything other than that could be validated via our [Forms API](https://developers.elementor.com/forms-api/) on the server-side, ex:

```php
// Validate the Tel field is in XXX-XXX-XXXX format.
add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {

    // Match this format XXX-XXX-XXXX, 123-456-7890

    if ( preg_match( '/[0-9]{3}-[0-9]{3}-[0-9]{4}/', $field['value'] ) !== 1 ) {
        $ajax_handler->add_error( $field['id'], 'Please make sure the phone number is in XXX-XXX-XXXX format, eg: 123-456-7890' );
    }
}, 10, 3 );
```

thanks.
