### ISSUE TITLE
Lazy Load for swiper slides

### ISSUE THREAD

**Issue by astbarc** [elementor/elementor#9288]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I would like to have the option of lazy load for the slides module.

In the previous version of Elementor pro that uses the slick slider, I was able to implemented it  using the beforeChange event and loading the images dynamically:
`jQuery('.elementor-widget-slides').on('beforeChange', function(event, slick, currentSlide, nextSlide){`

Now, the swiper slider doesn't have this feature and it's necessary to have access to the swiper object if you want to implement a 'on slide change' event.

**Comment by astbarc** [comment]
I've finally been able to do it using this function:

`document.querySelector('.elementor-main-swiper').swiper.on( 'slideChange', function() {`

**Comment by dxdigg** [comment]
thank you, but how to use it?

**Comment by dxdigg** [comment]
> I've finally been able to do it using this function:
> 
> `document.querySelector('.elementor-main-swiper').swiper.on( 'slideChange', function() {`

where should i put this code?
