### ISSUE TITLE
How can I get repeater item index ?

### ISSUE THREAD

**Issue by AbanobAkram** [elementor/elementor#9289]
Hello guys,

I'm working on a widget with a repeater control option. I'm using one of the controls (color control) inside the repeater. The color option inside each repeater item is applied to a different element. For example, If I have three layers in my HTML code, then what I need to have is something like below
```
'selectors' => [
   '{{WRAPPER}} #layer-{{INDEX}}' => 'background-color: {{VALUE}}'
]
```

Any help would be greatly appreciated.

Thanks,
Abanob

**Comment by bainternet** [comment]
@AbanobAkram 

You can use this syntax:

```
'selectors' => [
	'{{WRAPPER}} {{CURRENT_ITEM}}' => 'background-color: {{VALUE}};',
],
```

thanks.

**Comment by riadcitaku** [comment]
@bainternet {{CURRENT_ITEM}} currently is not working, I am trying to use it inside a repeater but no luck so far. Can you please confirm.

```
'selectors' => [
    '{{WRAPPER}} {{CURRENT_ITEM}} .custom-selector' => 'background-color: {{VALUE}};',
]
```

If current_item is removed the option works alright.

**Comment by babakfp** [comment]
> Edit: I've found it by digging into the social icons element, by adding the class elementor-repeater-item-' . $item['_id'] on the slide item makes it work.
Thank you @riadcitaku
