### ISSUE TITLE
Accessibility: <main> element

### ISSUE THREAD

**Issue by swinggraphics** [elementor/elementor#9293]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Elementor needs a way to choose the wrapper for whole templates, especially the ability to create a `<main>` element between headers and footers. "main" is selectable as a section type, but that is inappropriate in most cases. Instead, the entire contents of the template needs to be wrapped.

This extends to headers and footers, too, where presumably an entire header and footer template might be wrapped in a single `<header>` or `<footer>` with potentially multiple sections or divs inside.

The wrappers also need id, class, and custom attributes, like any Elementor section.

**Comment by ramiy** [comment]
Elementor already has this feature.

When editing a **Section** or a **Column** you have the option to set **HTML Tag**, set it to **main** and Elementor will replace the container HTML tag from `<div>` to `<main>`.

**Comment by swinggraphics** [comment]
@ramiy When an entity that you edit using "Edit with Elementor" is output to the page, it is wrapped in a couple divs. It would be most appropriate to be able to set the tag of one of these wrappers. Adding extraneous nested sections is far from ideal, and creating multiple `<main>, <header>, and <footer>` elements is obviously inappropriate.

**Comment by cirkut** [comment]
I think this is out of the scope of Elementor. If you need to have a specific output tag wrapped around all Elementor content on a page, you should use a theme that outputs that tag, or use a different page template that uses that tag. Other than that, editing the **HTML Tag** changes the tag for the section or column wrapper, so unless we're missing something else, you should probide more detail on what specific parts should be selectable (with code examples from Elementor's output)

**Comment by swinggraphics** [comment]
I use Hello when building a site with Elementor. The output generated by Elementor is not out of the scope of Elementor. 

Instead of `<div data-elementor-type="header"` this should be be `<header data-elementor-type="header"`. 

Instead of `<div data-elementor-type="wp-post"` this should be `<main data-elementor-type="wp-post"`

Instead of `<div data-elementor-type="footer"` this should be `<footer data-elementor-type="footer"`

**Comment by black-eye** [comment]
+1

**Comment by tiskraba** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.9.1

Feel free to update

Thanks!

**Comment by lae-qguiraudie** [comment]
@shilo-ey this issue is back again
No main tag in elementor pages...

**Comment by SeamonsterDeneb** [comment]
I agree with @lae-qguiraudie: Unless I'm just doing something wrong, I don't see that any pages I've made with Elementor Pro (version 3.19.2) have a <main> element.

I've built this site on a child theme of Hello Elementor 3.0.1. Is there a step I need to take to get the <main> in there?

**Comment by adrianw** [comment]
Not sure why this issue has been closed as others have mentioned this is still an on going issue with Hello 3.1.1 and is creating code that fails on many accessibility checks, "no landmarks generated"
