### ISSUE TITLE
Caching tool 

### ISSUE THREAD

**Issue by idaho26** [elementor/elementor#9295]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
I've use 2 cache plugins. Both plugin were no compatible to Elementor. They crashed my Accordion Widget. Is there some way you could develop a caching tool? I think that would be a selling point. I would upgrade if it was.

**Additional context**

**Comment by bainternet** [comment]
@idaho26 

Thanks for the suggestion, but we feel that this is a 3rd party plugin territory, and there are a few plugins out there that work really well with Elementor.

See this for more info: https://elementor.com/blog/5-best-wordpress-caching-plugins-2019/
