### ISSUE TITLE
Linking Evergreen Countdown Timer On Multiple Pages

### ISSUE THREAD

**Issue by zachkinsey** [elementor/elementor#9297]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will allow people to know how much time they have left when they hit the checkout page from the sales page. So, when I'm following up and sending them directly to the checkout page they'll still have the current time before the promotion is over.

**Describe the solution you'd like**
Able to link countdown timers and put them on various pages. I'm imagining a shortcode solution.

**Comment by bainternet** [comment]
@zachkinsey 

You can already do that with [Template Widget](https://docs.elementor.com/article/425-template-widget) and Elementor template shortcode aka `[elementor-template id="template_id"]`.

Thanks.

**Comment by DLivshin** [comment]
This does not work???
It just sets 2 different timers, with different times set...
