### ISSUE TITLE
Add rounded border setting to Image Box widget

### ISSUE THREAD

**Issue by kaelhoel** [elementor/elementor#9301]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Please add a setting for rounded border for images in the Image Box Widget. 

**Describe the solution you'd like**
Please add a setting for rounded border for images in the Image Box Widget, without having to use CSS.

**Describe alternatives you've considered**
Adding the styling with CSS.

**Additional context**

**Comment by bainternet** [comment]
@kaelhoel 

Just to be clear you are talking about the images inside an Image Box widget and not the whole widget??

**Comment by kaelhoel** [comment]
Yes, to have rounded team staff member photos, for example.

lør. 12. okt. 2019, 21:55 skrev Raz Ohad <notifications@github.com>:

**Comment by patbell101** [comment]
Something like this worked for me. 
.img-radius #CSSID {
  border-radius: 50%;
}

**Comment by rodolphebertozzo** [comment]
+1, @matipojo, @kobizz, @udidol, can this still be done for version 3.0?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!
