### ISSUE TITLE
Instagram in social share widget

### ISSUE THREAD

**Issue by lilianjansbeken** [elementor/elementor#9302]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I want to add Instagram to social share widget]

**Describe the solution you'd like**
Make it possible to choose Instagram in social share widget
**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Do you know a way for sharing to Instagram?

As far as we know, there is no way to share to Instagram, and this is the reason we are not adding it.
