### ISSUE TITLE
Woocommerce Menu Cart not working on latest updates (had to rollback to previous versions)

### ISSUE THREAD

**Issue by mylimoproject** [elementor/elementor#9304]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
After last updates of Elementor, Woocommerce menu cart stopped working. The only way for getting it back to work is to roll back Elementor (see attached working version image. Anything above those version causes menu cart to crash).

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active + Hello Theme.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
[system-info-igadgedx.com-10-10-2019.txt](https://github.com/elementor/elementor/files/3710485/system-info-igadgedx.com-10-10-2019.txt)
![elementor-rollback](https://user-images.githubusercontent.com/29313121/66538932-60e43880-eaf4-11e9-8a00-decba1b2fcbf.JPG)

</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @mylimoproject 

As mentioned in our Pro v2.7 beta release specs, we implemented a New Approach to WooCommerce mini-cart.

Starting Pro v2.7, Elementor adds its own mini-cart template. Instead of having the Menu Cart widget print the mini-cart markup, we are introducing a new mini-cart template which will be used by the Elementor Menu Cart widget.

This change doesn’t affect the majority of our users.
Want to revert to your theme's mini-cart template instead of Elementor's? disable the Elementor mini-cart markup and keep using the custom mini-cart template.

In order to disable Elementor mini-cart template simply go to your Dashboard > Elementor > Settings > Integrations tab > WooCommerce section and choose “Disable”.

Let me know if your issue persists.

**Comment by JonSullivanDev** [comment]
Hi @shilo-ey 

I've just updated one of my sites to Elementor 2.7.4 and Elementor Pro to 2.7.2 and believe I am being impacted by the changes made to the mini-cart. For starters, you mentioned that 2.7 changes the render pipeline of the Menu Cart to now render a new Elementor mini-cart template rather than the default mini-cart for the site. By 'template' I was assuming that this would be a user-created and/or user-modifiable Elementor Pro template (from the template library) but I don't see a new template type for mini-cart nor do I see a template selector in the Menu Cart widget to assign to the fly-out overlay. Presuming that this 'template' is just something Elementor is doing under the hood, my larger concern is that the Integrations menu feature to disable the Elementor Mini-Cart markup and use the default may not be working?

Long story short, my site's pre-2.7 menu fly-out looks like: 

<img width="442" alt="image" src="https://user-images.githubusercontent.com/8585984/66941350-b51b7b00-f014-11e9-87b0-aa0d746670d9.png">


And post-2.7 menu now renders blank even though there are multiple items in the cart:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/8585984/66941493-fa3fad00-f014-11e9-8748-16092eeafdbd.png">


I've changed my Integrations menu option for "Mini Cart Template" to 'Disable' then cleared my full cache stack / rebooted my web servers entirely in case that was an issue but to no avail. Frankly I'm not sure if this is something in the Elementor rendering stack or possibly a mis-match with WooCommerce hooks (Currently on 3.7.1) but would like to get some movement somewhere. Happy to provide any further info I can if it's helpful in debugging the situation

**Comment by shilo-ey** [comment]
Hi @mylimoproject 

Please contact our support at support @elementor.com for guidance in resolving this issue and **mention that you were directed by me (shilo-ey) and reference this issue.**

thanks.

**Comment by berkmh** [comment]
@shilo-ey @JonSullivanDev @mylimoproject  was a fix found for this? Im having same issue, I contacted support and they cant figure it out. I have disabled the cart option in settings, reset cache, tried everything. Only thing that works is downgrading to 2.6.5 please advise.

**Comment by JonSullivanDev** [comment]
@berkmh I wasn’t ever able to get it working and didn’t want to go through the pain of monkey-patching Elementor so ended up just swapping my menu cart with an icon that statically links to my /cart/ page 😕 not great but it is functional.

**Comment by mylimoproject** [comment]
@berkmh nah... I've gone through every plugin/switch themes and see if there is a conflict, but as you pointed-out yourself... version 2.6.5 is the latest version you can downgrade to if you want the cart to work.

![elementor-rollback](https://user-images.githubusercontent.com/29313121/67708972-80ec7680-f993-11e9-95a9-add19b1ca706.JPG)

**Comment by shilo-ey** [comment]
Hi @mylimoproject 

If you're having issues with the mini-cart, 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by shilo-ey** [comment]
@berkmh Please proceed your conversation with our support team for troubleshooting this problem.

@mylimoproject Have you tried contacting our support?

Thanks

**Comment by oooh-boi** [comment]
The most frequent answer here when things REALLY DON'T WORK is:
"Please proceed your conversation with our support team for troubleshooting this problem."

Why do these issues require _private messaging_ to resolve, we all here are interested to figure out what's wrong and you - as a tech staff member(s) - shouldn't just CLOSE IT as being resolved while it's not.
Are you trying to keep the issues number relating to Elementor under 10000?

mr. shilo-ey wrote:

> In order to disable Elementor mini-cart template simply go to your Dashboard > Elementor > Settings > Integrations tab > WooCommerce section and choose “Disable”.

Did you actually try to do that? You can not DISABLE that stupid mini-cart, it keeps showing up regardless of being Disabled. 

Stop closing issues that persist, that's not the way to keep your customers!

**Comment by mylimoproject** [comment]
Have really no idea why a global problem needs to be sorted-out privately.
Elementor should really start delaying deployment of new features and start addressing long standing issues affecting every user (i.e. the "post excerpt length" issue that has been reported again and again and still not resolved).

**Comment by JoshBreda** [comment]
Any solutions yet? Im reading this 7 months later and I am having the exact same problem..

**Comment by oooh-boi** [comment]
@JoshBreda welcome to the club.

**Comment by sebito32** [comment]
@JoshBreda same fuc**** problem here...I'm in conversations with Elementor suppor, we'll see how it goes...

**Comment by JoshBreda** [comment]
@sebito
This is ridiculous. So we've spent money and time on a non viable product here? I thought this was a professional business. There goes all my hours of work. Incredible..

Could you keep us updated? And I sure do hope you get a solution within this year.

**Comment by sebito32** [comment]
@JoshBreda no worries mate, as soon as they provide me a solution I'll get in touch with you guys!

**Comment by JoshBreda** [comment]
Would be great thanks.

To let you know, I asked a guy on fiverr to fix the problem. He said it would not be a problem. I just can not wait months for a solution. Will send the bill to Elementor.

**Comment by sebito32** [comment]
@JoshBreda THIS IS THE SOLUTION eELEMENTOR SUPPORT PROVIDED ME...of course any of the steps fix the issue...

If you haven't already done so, could you kindly try the steps below and see if the issue remains?

1. Try to deactivate all your plugins (besides Elementor) and see if it helps. If it solves the issue reactivate them one by one to find the culprit.
2. If it didn't help, try to switch your theme (temporarily) to a default WP theme such as Twenty Sixteen.

Along with that, could you try toggling the menu cart between Elementor and WooCommerce's version and see if the issue remains? To do that, just go to Dashboard > Elementor > Settings > Integrations tab > WooCommerce section and choose “Disable”

Please let me know how that turns out.

Best Regards,

**Comment by JoshBreda** [comment]
@sebito32 Step 1 did the trick for me! Thank you very much. The strange thing about it is that I tried it before without positive results. But now all of a sudden it did. Thank you once again.

Did it worked out for you as well?

Kind regards

**Comment by sebito32** [comment]
@JoshBreda No way mate...there is any incompatibility between woocommerce plugins and Elementor....

**Comment by JoshBreda** [comment]
@sebito32 sorry to hear man. Hope it can be resolved asap. Wish you the best.

Kind regards

**Comment by eltoine** [comment]
Hi. I bought elementor pro and when I activate it, then the mini cart icon at the top right side shows not correct. in the backend there is a settings / Integration there is a point: Mini Cart Template, where you can switch do “disable” to show the themes mini cart icon but it does not work. it always shows the cart wrong and when I switch to disable, the shop gets a 500 error!

here you find some screenshots: first 3 pictures shows correct mini cart and last 2 shows the bug version with elementor pro:

https://ibb.co/ZVfp7Kz
https://ibb.co/K5M0DHM
https://ibb.co/g3L5Ft4
https://ibb.co/mbWB5v9
https://ibb.co/pXdqq4c

you can compare to original site: linsenklick.ch where just elementor free version is actually activated.

at staging4.linsenklick.ch is elementor pro activated and here you see the mini cart bug.

I already made ticket to elementor company but I have the feeling they DONT WANT to help.

they mention always 3rd part plugin conflict or theme conflict. But if it would be like that, the WHOLE shop would break and not just the mini cart.

I found different similar topics about mini cart problem so it must be a problem by the elementor pro plugin.

Who can help?
![without elementor pro product in cart](https://user-images.githubusercontent.com/72234684/94874089-5a5f7700-0451-11eb-852f-692561b6f53b.png)
![without elementor pro  product in cart mouse hover](https://user-images.githubusercontent.com/72234684/94874093-5c293a80-0451-11eb-991c-3074be5b831b.png)
![without elementor pro](https://user-images.githubusercontent.com/72234684/94874095-5cc1d100-0451-11eb-82c6-cce2800fdbb5.png)
![with elementor pro](https://user-images.githubusercontent.com/72234684/94874097-5d5a6780-0451-11eb-8978-5094bb468ed5.png)
![with elementor pro product in cart](https://user-images.githubusercontent.com/72234684/94874098-5df2fe00-0451-11eb-9974-fde2c005aec8.png)

**Comment by legenddaniel** [comment]
Jan 2021 with Elementor Pro 3.0.9. Disabling still not working and I can't find rollback option.

**Comment by dimitrios1988** [comment]
Any news about the issue? Elementor's cart widget is not compatible with Google Tag Manager and remove from cart events are not fired unless I switch to woocommerce's cart which doesnt work

**Comment by wu-data** [comment]
I'm experiencing this same issue. But only on my homepage. I have a different header menu on homepage from the rest of the site. The menu cart on homepage loads blank. Can't figure out why. 
If i disable and enable will I lose my custom styling set currently in my elementor header templates?

**Comment by JamboMedia** [comment]
Yes, we have the same issue. Only on the homepage the menu cart loads blank. On all the other pages the menu cart is showing the cart items.

**Comment by szolcek** [comment]
Same issue 21st april 2021 - elementor breaks the cart so that it simply doesn't appear anymore and fixes above eg Disable option do nothing.

**Comment by IlPizza79** [comment]
Same issue here :-(
Why is this issue closed?

**Comment by oooh-boi** [comment]
> Same issue here :-(
> Why is this issue closed?

It looks like this is how issues of that kind usually get resolved. I don't understand how come is possible that for over 2 years nobody in charge doesn't care.

**Comment by ATaylor66** [comment]
Does anyone else have this issue with the menu cart? It all seems to be working for me but then clicking on it stops working?
Elementor Pro and Hello theme, asking on here as support is so slow.

**Comment by niraj-mistry** [comment]
I am having the same issue, but I figured out that speed optimization/cache plugin is causing this, plugin is minifying js files and its stopping cart items to display on the flyout cart. Try to deactivate your cache/speed optimization plugin and see if this issue is fixed.

**Comment by scrobbleme** [comment]
Same here.... anoying.

**Comment by sebito32** [comment]
> I am having the same issue, but I figured out that speed optimization/cache plugin is causing this, plugin is minifying js files and its stopping cart items to display on the flyout cart. Try to deactivate your cache/speed optimization plugin and see if this issue is fixed.

@niraj-mistry  could you please tell me the name of the cart javascript file in order to avoid wp-rocket minify it?

Can't find it...:S Many thanks in advanced!

**Comment by niraj-mistry** [comment]
First of all try to deactivate the Optimization plugin and see if that
works?
I use a different optimization plugin, not sure if WP Rocket has this
setting - try to find if there are any settings in Asset Optimization for
'Cart Fragmentation' or anything related to cart like that and disable it.

**Comment by UnrealPixel** [comment]
> I am having the same issue, but I figured out that speed optimization/cache plugin is causing this, plugin is minifying js files and its stopping cart items to display on the flyout cart. Try to deactivate your cache/speed optimization plugin and see if this issue is fixed.

This is not related to that in my case. I disabled WP Rocket but this fixed nothing. Even checking for the minifying js files option I found out that it was disabled in the first place...

**Comment by farman333** [comment]
I have no speed optimization plugins on my WordPress website but still facing the same issue.

**Comment by isvaljek** [comment]
Also no caching/optimizations and icon first renders then disappears.
First it is sent from server like this `<i class="eicon-basket-medium"></i>` as seen in source html code, then JS/something changes it to `<i class="eicon" aria-hidden="true"></i>`.

**Comment by oooh-boi** [comment]
I've noticed that Elementor devs updated the icon class names of the Lightbox from "e-eicon-SOMETHING" to "eicon-SOMETHING" which is extremely bad practice and caused a lot of trouble on some of my client websites. If that's the case with the basket as well, it's gonna be really fun.

**Comment by cfloinc** [comment]
> Also no caching/optimizations and icon first renders then disappears. First it is sent from server like this `<i class="eicon-basket-medium"></i>` as can be seen in the page's rendered HTML source, then JS/something changes it to `<i class="eicon" aria-hidden="true"></i>`. I can confirm this at least on Hello and Storefront themes. I'm using header builder, and might have done some imports/exports of the header template, but I believe this was happening prior to that.

I too am experiencing this exact same issue. Any help would be appreciated

**Comment by Nieder-hu** [comment]
> > Also no caching/optimizations and icon first renders then disappears. First it is sent from server like this `<i class="eicon-basket-medium"></i>` as can be seen in the page's rendered HTML source, then JS/something changes it to `<i class="eicon" aria-hidden="true"></i>`. I can confirm this at least on Hello and Storefront themes. I'm using header builder, and might have done some imports/exports of the header template, but I believe this was happening prior to that.
> 
> I too am experiencing this exact same issue. Any help would be appreciated

Yes, it's the same for me.

**Comment by AndreasX12** [comment]
> > > Also no caching/optimizations and icon first renders then disappears. First it is sent from server like this `<i class="eicon-basket-medium"></i>` as can be seen in the page's rendered HTML source, then JS/something changes it to `<i class="eicon" aria-hidden="true"></i>`. I can confirm this at least on Hello and Storefront themes. I'm using header builder, and might have done some imports/exports of the header template, but I believe this was happening prior to that.
> > 
> > 
> > I too am experiencing this exact same issue. Any help would be appreciated
> 
> Yes, it's the same for me.

I've got the exact same issue with the newest versions of Elementor + Elementor Pro.

**Comment by rangel21** [comment]
Hi there, i am using the astra theme with elementor pro and having the same issues.
I also found the  <i class="eicon" aria-hidden="true"></i> inside the html coding.
For what i can see is that the icon is closing right after is being loaded.....

Did anyone already found a solution???

**Comment by cloudpageoficial** [comment]
Hello guys.
I'm from Brazil, so I'm translating this comment.

I managed to get it working by following the following steps.

I activated Elementor and Elementor Pro + Woocommerce, then I disabled the cart in: Elementor > Configuration > Integration > Mini Cart Template > Disable then I activated the Astra Theme and then I activated the Astra Pro Plugin.

Once done in that order it worked.

I hope I have contributed to the community.

Big hug!

Brazilian greetings.

cloudpage.com.br

**Comment by matintzh** [comment]
hi guys , I had this issue this morning and after a lot of changing , I figuered out thats because of the plugin "perfmatters" , it disables some of the woocommerce scripts to increase website performance and will cause this issue

**Comment by kskonovalov** [comment]
There's some issue between Woocommerce JS which should populate the menu cart, somehow it's not working.
As a temporary hotfix, this file could be changed:
\wp-content/plugins/elementor-pro/modules/woocommerce/module.php
`
public static function render_menu_cart( $settings ) {
...
<?php if ( true || $is_edit_mode ) {
	woocommerce_mini_cart();
} ?>
`

so add  **true ||** before **$is_edit_mode** check, or completely remove that check

**Comment by ChristianoToledo** [comment]
> There's some issue between Woocommerce JS which should populate the menu cart, somehow it's not working.
> 
> In my case the issue was because the cart-fragments js file wasn't loading (/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js) So I just made it always included (just added code to my theme functions.php):
> 
> ```
> function custom_js_css()
> {
> 	wp_enqueue_script( 'wc-cart-fragments' );
> }
> add_action('wp_enqueue_scripts', 'custom_js_css', 999);
> ```

Great guy! I put the code there in functions.php and now it's working perfectly.
Thank you very much!

**Comment by jretamal** [comment]
> There's some issue between Woocommerce JS which should populate the menu cart, somehow it's not working.
> 
> In my case the issue was because the cart-fragments js file wasn't loading (/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js) So I just made it always included (just added code to my theme functions.php):
> 
> ```
> function custom_js_css()
> {
> 	wp_enqueue_script( 'wc-cart-fragments' );
> }
> add_action('wp_enqueue_scripts', 'custom_js_css', 999);
> ```

What a stupid solution! I love you! unbelievable that a company can't fix this for years and a developer somewhere in the world does it.

We Love you! <3

**Comment by pmsteil** [comment]
elementor pro v3.72 - still has the same problem... 

The above fixes worked for me... 

Elementor - why hasn't this been rolled into the product?
