### ISSUE TITLE
New icons control backward Compatibility issue

### ISSUE THREAD

**Issue by easin-xs** [elementor/elementor#9305]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
After converting the old icon control to new icons control,  new icons is not rendering if I do not save again the content. If I save the content after conversion its working fine.

## Steps to reproduce
Convert any old icon control to new icons control
See the preview in the frontend
Try to update the icons
You will see the issues that new updated icons is not displaying

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @easin-xs 

We cannot reproduce your issue with the instructions provided.

Try to read more about this topic [in this doc](https://docs.elementor.com/article/584-migration-to-font-awesome-5), and if your issue still persists please try to contact our support

Thanks.
