### ISSUE TITLE
How to run elementor scripts after initial page loading?

### ISSUE THREAD

**Issue by tijosfx** [elementor/elementor#9309]
Elementor page builder script not loading with swup.js (it's ajax page loading system), 

The issue is:
When I am going to the home page to another page(any page), there is no page loading( demo url: [https://swup.github.io/swupjs-gia-demo/index.html](https://swup.github.io/swupjs-gia-demo/index.html)), only some page transition effects with the help of swup.js. But, the elementor scripts run only with the page reloading.

swup.js already provides reloading-javascript, but need to put the elementor secript inside that. so what script I need to place inside the below code, to load elementor scripts.

document.addEventListener(“DOMContentLoaded”, () => {

// I want to load elementor builder script here!!

});

Reference url
https://swup.js.org/getting-started/reloading-javascript

Thanks

**Comment by bainternet** [comment]
@tijosfx 

Currently, there is no way in elementor to re-init frontend scripts after they get called, so it up to you to re-init every specific element that gets loaded via your AJAX mechanism.

thanks
