### ISSUE TITLE
Hide the wordpress standard edit menu for elementor pages and posts

### ISSUE THREAD

**Issue by h-morales** [elementor/elementor#9311]
![image](https://user-images.githubusercontent.com/153176/66581695-255c7380-ebb3-11e9-9792-8f604c3e8754.png)

For non-Administrator roles, most likely, they will choose the "edit" menu rather than "edit with elementor" menu, or maybe remove the "edit with elementor" menu and when the user click the edit and the page is created from elementor, it will automatically show the Elementor Editor.

**Comment by cirkut** [comment]
That's not true. There are scenarios where you will need to edit the metadata in a page, especially if you use an SEO plugin. Additionally, if there's any custom field plugin (ACF, Pods, JetEngine, etc.), you'll only be able to edit those on the WordPress backend.

That being said, I don't think it's a terrible idea to include that as an option/hook that can be used by developers, but I don't think this functionality should be included by default at all.

**Comment by h-morales** [comment]
What Im saying is for the non-admin users like the business owners. What they only want to do is to update the content. And if there's an edit (standard edit) link there, they would probably choose that over "edit with elementor", and that would break the page.

**Comment by bainternet** [comment]
@h-morales 

I don't see us implementing this anytime soon, but this can be done via native WordPress filter hooks more specificly `post_row_actions`.

Hope this helps.
