### ISSUE TITLE
"Uncaught TypeError: n.attributes[e.name].each is not a function" when changing history actions for a repeater control

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#9313]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**Note:** The issue is related to editor JS (i.e. only happens during JS render)

The problem occurs when one of the repeater controls is changed/added/removed and then a user goes to History and clicks on a previous action (i.e. undo / Ctrl+Z, but manually).

When this is done, Elementor re-processes the CSS style for that element (because of element `onRender` -> `renderUI` -> `renderStyles` -> `getStyleControls`).

In the [getStyleControls](https://github.com/elementor/elementor/blob/385f50c840065e3c689bd62f08403ad3af5de41c/assets/dev/js/editor/elements/models/base-settings.js#L112) function, it is assumed that the control is a normal control and there's no check if it's a repeater.

So, when it comes to [Line 128](https://github.com/elementor/elementor/blob/385f50c840065e3c689bd62f08403ad3af5de41c/assets/dev/js/editor/elements/models/base-settings.js#L128) (in that function) to process that control's CSS, it throws an error because it gets a repeater object instead of the expected Backbone Collection.

For normal repeater widgets with no CSS selector child controls, this is fine, but for the repeaters which have controls with CSS Selectors, it does not revert back to the previous state CSS (because of this error) and it messes up the Element's CSS output in Editor.

## Steps to reproduce

(Keep the Browser Console open)

1. Add any repeater Widget (for eg: Icon List).
2. Change any repeater control setting / add / delete a repeater item.
3. Go to History (from bottom navigation bar, option besides responsive mode icon), and go 1 action back (so that the action is the previous state of the repeater).
4. The error `Uncaught TypeError: n.attributes[e.name].each is not a function` will appear in console.

![Elementor Repeater History Actions Error](https://user-images.githubusercontent.com/18551588/66586652-9f3a3000-eba6-11e9-8141-9286eee3e730.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.0

Feel free to update

Thanks!
