### ISSUE TITLE
 An SVG image does not appear in Firefox if a link is pinned to it.

### ISSUE THREAD

**Issue by anton-vv** [elementor/elementor#9314]
There is a problem with svg image display. An SVG image does not appear in Firefox if a link is pinned to it. If you remove the link, it is displayed. Other browsers do not have this problem. Can you solve this problem?

**Comment by cirkut** [comment]
Make sure to put an explicit width on the SVG image, otherwise there won't be any inherent height/width to the image.

**Comment by anton-vv** [comment]
Thank you! It helped.
