### ISSUE TITLE
Customizable slider / carousel

### ISSUE THREAD

**Issue by Cecile-Lebleu** [elementor/elementor#9315]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The existing carousels and sliders only allow for images, videos, and specific layouts of title/button arrangements.

**Describe the solution you'd like**
This carousel should have each "slide" be like a column; where any other elements can be placed. There is a selection of 1 to 6 slides visible at a time, similar to columns, but with more columns hidden on either side. The navigation works as usual with carousels, using arrows and/or buttons and/or timed sliding.

**Describe alternatives you've considered**
Well, nothing actually because it doesn't exist and I don't want to fiddle with external plugins

**Comment by bainternet** [comment]
@Cecile-Lebleu 

Currently, this is not possible, but it will be with #2587.

so I'll merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Cecile-Lebleu** [comment]
Thanks! I wasn't searching with the same terms so I couldn't find it.

**Comment by srack835** [comment]
+1 for customizable carousels/sliders. I would LOVE to be able to style each "slide" using Elementor tools. This would be especially great if you could use the standard range of widgets inside a column, so you can pull dynamic content through (if you use ACF/Pods/Toolset). Currently I use Slider Revolution or a mess of Elementor templates, shortcodes, and third party plugins, but I find the Elementor interface far more intuitive and consistent with my workflow.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Carousel introduced in Elementor Pro v3.14.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
