### ISSUE TITLE
Elementor Posts Pro widget badges

### ISSUE THREAD

**Issue by ti0** [elementor/elementor#9318]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I already emailed your support and was told to open a feature request here.

**What problem is your feature request going to solve? Please describe.**
I would like to be able to show badges in the Posts widget without the need to enable images. There are several posts and custom post types on my blog that do not have images but in the listing I would still like to show badges. Currently I am doing this by putting a default image on each post, and then in the Posts widget I make the image size 0, this way the image is hidden and the badges still show. I would like to be able to do this without having to have a default image or without even to have to select the image option on the posts widget as this causes images to load increasing page load time.

**Describe the solution you'd like**
Included above.

**Describe alternatives you've considered**
Included above.

**Additional context**
None

**Comment by bainternet** [comment]
@ti0 

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
