### ISSUE TITLE
Add article date in html sitemap 

### ISSUE THREAD

**Issue by efintina** [elementor/elementor#9319]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need to have article published date into html sitemap

**Describe the solution you'd like**
In html sitemap add published date after article title 

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
@efintina 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
