### ISSUE TITLE
I need to include elementor css and scripts to be loaded on a non elementor page

### ISSUE THREAD

**Issue by greggh** [elementor/elementor#9320]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!
^ I was told to come ask this question here by the support team, I am a pro customer and they said I might get a good answer here.

I am creating custom post types on my site with the Pods framework. I am also using Elementor Pro on the rest of the site. I am creating some saved templates in Elementor and I want to actually display them on my Pods custom post types.

To do this I am using a block of code in functions.php to add code after the_content, by calling do_shortcode() with the shortcode for the Elementor saved template.

This works, the saved template gets drawn. It just isn't drawn very pretty. The custom post type is not loading the scripts or styles for Elementor.

Is there a way in functions.php for me to tell Elementor to load up all of it's scripts and styles on my custom post type? Something like an object I an grab and call elementor_enqueue_files on?

Some of my code, this is just in a function that fires on the_content. I am echoing out 4 saved templates:

```php
// Do something to enque Elementor css and js here.
echo do_shortcode('[elementor-template id="61590"]');
if ( is_user_logged_in() ) {
	echo do_shortcode('[elementor-template id="61620"]');
} else {
	echo do_shortcode('[elementor-template id="61605"]');
}
echo do_shortcode('[elementor-template id="61640"]');
echo do_shortcode('[elementor-template id="61655"]');
```

**Comment by bainternet** [comment]
@greggh 

Why not use the theme builder for your custom post type???

anyway, you can look at how we enqueue the assets for the frontend and get an idea how you can do the same:
https://github.com/elementor/elementor/blob/42cdb73444cf207064d6386c41b2ab42bf46bc85/includes/frontend.php#L296-L418

hope this helps.

**Comment by greggh** [comment]
The custom post types are created by Pods, and drawn by a Pods Template. I have no idea how I could use the theme builder there. Pods Templates are just you putting html/css/js into a text box in the backend of Pods.

With that code, it looks like I can just call these functions because the scripts and styles are already registered:

```php
wp_enqueue_script( 'elementor-frontend' );
wp_enqueue_style( 'elementor-icons' );
wp_enqueue_style( 'elementor-animations' );
wp_enqueue_style( 'elementor-frontend' );
```

**Comment by commercial-hippie** [comment]
I also ran into this issue and could only get it to work using this:
```
\add_action('wp_footer', function () {
	if (\is_singular('my-custom-post-type')) {
		\Elementor\Plugin::$instance->frontend->enqueue_styles();
		\Elementor\Plugin::$instance->frontend->enqueue_scripts();
	}	
}, 0);
```
