### ISSUE TITLE
Animation Delay is not removed when Entrance Animation is set to 'none' on mobile

### ISSUE THREAD

**Issue by dollhauss** [elementor/elementor#9321]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

When you have an 'Entrance Animation' selected with an 'Animation Delay', 
and you set the animations to 'none' on mobile.
The Animation no longer appears but the Animation Delay still stays.

The Animation Delay is not removed when the Animation is removed.
Thus - if you are trying to turn off animations on mobile - it doesn't work correctly as all the animation delays remain.

## Steps to reproduce

1) Select an 'Entrance Animation' - such as Fade In
2) Add an 'Animation Delay' - such as 1000 ms
3) Set the 'Entrance Animation' to 'none' on mobile only.
4) Test on mobile
5) The 'Entrance Animation' no longer works (as expected) but the 'Animation Delay' remains.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: mariadb.org binary distribution v10.3.18
	PHP Version: 7.3.6-1+0~20190531112546.39+jessie~1.gbp6131b7
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 128M
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 2.1.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```
</details>

**Comment by irjaelisa** [comment]
I'm having this same issue. Exactly as described.

**Comment by dannibee** [comment]
Hi @irjaelisa - just happened upon this post and saw your comment. I realise the post is old, but saw your comment is much more recent so thought I'd see if my answer helps!

When you remove the entrance animation, you actually have to click the little x to close the word "none", which converts it to "default". I believe this removes all animation and time delays, and I don't think it's a bug, I think it's so that you can still set an animation time (which would double as an "entrance time") with 'none' chosen as the actual animation. I hope this helps, but knowing me I've probably just misunderstood the question. 

Good luck!

**Comment by irjaelisa** [comment]
@dannibee -- thanks so much! I really appreciate you taking the time to respond.

**Comment by ofmarconi** [comment]
@irjaelisa sure that doing this your element no longer animates on mobile? for me when it is Default it inherits the animation from the tablet.

Wouldn't there be a way to eliminate cell phone delays?

**Comment by ofmarconi** [comment]
For me the problem still persists, even with the suggested solution.
