### ISSUE TITLE
Remove comma between tags

### ISSUE THREAD

**Issue by wattan1** [elementor/elementor#9322]
I was send here by support. 

I would like to be able to remove the comma's between the tags in a single post. 

This is a feature request, but if anyone could point me in the right direction how to temporarily solve this with some custom code that would be very nice!

**Comment by bainternet** [comment]
@wattan1 

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hi @wattan1,

your request was related to **Post Terms** in single templates, is that correct? This feature was already available when you came here. You just needed to use a widget like the **Heading widget** with [Dynamic Tags](https://elementor.com/help/dynamic-tags-pro/). Then choose the **`Post Terms`** option, and in the Dynamic Tag settings change the separator.

Here is an article that explains the Dynamic Tags available: https://elementor.com/help/dynamic-tags-pro/

![image](https://github.com/elementor/elementor/assets/113993460/82dd0851-816b-40fd-aadc-32db0ecc0662)
![image](https://github.com/elementor/elementor/assets/113993460/b8ca2607-efc7-4aea-8428-97f617dc03eb)


----

However, if you wish to edit your Loop Item templates, then the solution is the [Loop Builder](https://elementor.com/help/loop-grid/) and use the same method as above. 😉 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

I know it's a bit late, but I hope this helps. 🙂 

Kind regards
