### ISSUE TITLE
Add preSelected Option for the form select option

### ISSUE THREAD

**Issue by jparker0714** [elementor/elementor#9324]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

> This will allow a developer to pre-select an option with form select.

**Describe the solution you'd like**

> You currently are using the pipeline option to separate between Label and Value. I suggest if you add another pipeline with the word "selected" after it this would pre-select that option. Using your example it would look like this:  First Name|f_name|selected

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Hi @jparker0714 

Thanks for your feedback

This feature is currently available for single select values, go to the fields' "Advanced" tab and specify your Default Value.
![image](https://user-images.githubusercontent.com/45009641/66811245-6a790080-ef39-11e9-907b-e679e6ef0230.png)

We will add the option to preselect multiple values.

Thanks.

**Comment by jparker0714** [comment]
Wow, I’m an idiot! Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.1

Feel free to update

Thanks!

**Comment by nohl** [comment]
Documentation for this feature would be a great addition to this support page: https://elementor.com/help/form-fields/
