### ISSUE TITLE
Developer docs - How to build your own Integration

### ISSUE THREAD

**Issue by waqas996** [elementor/elementor#9329]
Hi,

I can see the powerful feature provided by Elementor of integrations with different marketing and CRM tools. I want to build my own Integration like ActiveCampaign, Drip. As a developer, I am not sure how to do this. Any help towards guidelines, tutorials, documentation would be appreciated.

**Comment by bainternet** [comment]
@waqas996 

We have a developers API doc just for that: [Custom Form Action](https://developers.elementor.com/forms-api/custom-form-action/)

hope it helps.
