### ISSUE TITLE
url with params cause issue with form and popups

### ISSUE THREAD

**Issue by aksirob** [elementor/elementor#9330]
I have an elementor page containing a form with submit button and redirect after submitting. I have an issue with page url with params that I get from mail responder service. For example I get a link  https://www.mysite#?ref123&name=abc. The issue that form submit and redirect does not work on a page with such url. Popus also not working with such urls. I assume that the problem is with a fragment identifier. Is it possible that it interferes with Ajax methods and what solution for this?

**Comment by bainternet** [comment]
thanks for reporting, fixed in Elementor Pro 2.7.3
