### ISSUE TITLE
Theme Builder Templates

### ISSUE THREAD

**Issue by nathanjdarby** [elementor/elementor#9331]
Hi, 

I am an elemntor pro user and I am currently working on a project with it and Advanced Custom Fields. My question is hopefully a simple one. 

**When you create a theme template against a certain post type (normal/custom post type) where is the template saved in terms of the WordPress directory and is it accessible so we can make minor tweaks to it on the backend through code?** 

The reason I ask is that I want to add in a function on a certain page through ACF which your plugin doesn't yet support (flexible content/relationship fields). 

Any help you could give me or point me in the right direction would be grateful. I am learning to hard cord themes from scratch but love your plugin so much I hope I could get around this problem.

**Comment by shilo-ey** [comment]
Hi @nathanjdarby 

The entire Elementor page settings and Theme templates are being saved to the Database as posts and not to the file system.

If you have a more specific question feel free to ask

thanks.

**Comment by pingram3541** [comment]
One way to get around the fact that these are not php files saved to the file system but stored as serialized meta within the database instead is to create a custom widget or shortcode that performs the function you need and drop that inside your theme builder template.

I had to do this recently w/ the maps widget, where I would drop in a custom widget where the map element would normally exist for my "post type" template created in the Theme Builder and have it check some logic first to determine what to render.

My client desired to be able to use a custom map embed code but only on certain pages of said post-type. (i.e. City pages)

I had already used the Google Map element in my template to dynamically generate the map based using dynamic ACF fields contained in these "City" posts (city name, zip etc.).

I saved this as a global element, captured the shortcode it generated (saving it for later use) and removed it from my template.

I then created a new ACF field for my post types called Map Embed and created my custom widget to essentially be an if/else switch, checking first to see if the Map Embed ACF field has any value and if so to render that in my template (where I placed my custom widget in my template) or if the Map Embed ACF field is empty it would then perform a `do_shortcode('[elementor-shortcode-here]')` rendering the global element I saved earlier which is the Elementor Map widget which also renders the address based on other ACF fields.

Shorter explanation: The result is all City pages have ACF fields for City, Zip and Map Embed.  If Map Embed has any html, it renders that, if not, it renders the Elementor Google Map widget using the other ACF fields instead.
