### ISSUE TITLE
Template for custom post type "event_listing" not showing

### ISSUE THREAD

**Issue by hiteshmakvana** [elementor/elementor#9332]
Hi

I am the author of the WP Event Manager. We have integrated elementor in our plugin with some default wp event manager widgets. I am having an issue with custom templates while creating with event listing post type. 

As per my troubleshoot it looks like Elementor don't provide a template with `has_archive`  

We need rewrite rules and has_archive in our plugin while registering post type event_listing.

Thank you

**Comment by shilo-ey** [comment]
Hi @hiteshmakvana 

Please explain your issue better.

Thanks

**Comment by Webtica** [comment]
Hi! I am using your plugin. If you change show_in_nav in the cpt file to true it will work :-)

**Comment by hiteshmakvana** [comment]
Hi @shilo-ey  

I have tested some code with Elementor for registering post types. There is some restriction on the Elementor custom post type template. It won't show registered post type until we change the code in register post type function. Same as @Webtica example I have also done that it works if we do that. Can you please provide why it is restricted on the Elementor custom template. We want to create a custom single post type template for our plugin using Elementor.

Thank you

**Comment by shilo-ey** [comment]
Hi @hiteshmakvana 

Since Pro v2.3, we added `elementor_pro/utils/get_public_post_types` filter hook to allow non-supported post-types to be added to Elementor, Usage example:
```
/**
 * Add non-supported post type support
 */
add_filter( 'elementor_pro/utils/get_public_post_types', function() {
	$post_types['YOUR_CPT_KEY'] = 'YOUR_CPT_LABEL';
	return $post_types;
} );
```

Try using this hook to achieve your goal.

**Comment by brianyerkes** [comment]
> Hi @hiteshmakvana
> 
> Since Pro v2.3, we added `elementor_pro/utils/get_public_post_types` filter hook to allow non-supported post-types to be added to Elementor, Usage example:
> 
> ```
> /**
>  * Add non-supported post type support
>  */
> add_filter( 'elementor_pro/utils/get_public_post_types', function() {
> 	$post_types['YOUR_CPT_KEY'] = 'YOUR_CPT_LABEL';
> 	return $post_types;
> } );
> ```
> 
> Try using this hook to achieve your goal.

That filter causes all other post types, aside from the one you're trying to add support for, to be removed from the list when creating a single post template in Elementor.

**Comment by juanglzm** [comment]
> > Hi @hiteshmakvana
> > Since Pro v2.3, we added `elementor_pro/utils/get_public_post_types` filter hook to allow non-supported post-types to be added to Elementor, Usage example:
> > ```
> > /**
> >  * Add non-supported post type support
> >  */
> > add_filter( 'elementor_pro/utils/get_public_post_types', function() {
> > 	$post_types['YOUR_CPT_KEY'] = 'YOUR_CPT_LABEL';
> > 	return $post_types;
> > } );
> > ```
> > 
> > 
> > Try using this hook to achieve your goal.
> 
> That filter causes all other post types, aside from the one you're trying to add support for, to be removed from the list when creating a single post template in Elementor.
> 
> To keep others supported, you have to add them to the filter:
> Example:
> $post_types['post'] = 'Posts';
> $post_types['page'] = 'Pages';
> $post_types['event'] = 'Event';
> return $post_types;

Hi all, this can be solved passing the argument $post_types to the function inside the filter, so you will just add your custom post type to the array of default cpts and you won't need to re-declarate them

add_filter( 'elementor_pro/utils/get_public_post_types', function( $post_types ) {
	$post_types['YOUR_CPT_KEY'] = 'YOUR_CPT_LABEL';
	return $post_types;
} );

**Comment by wpem-kishan** [comment]
Hello

add_filter( 'elementor_pro/utils/get_public_post_types', function( $post_types ) {
	$post_types['YOUR_CPT_KEY'] = 'YOUR_CPT_LABEL';
	return $post_types;
} );

I have apply above filter but still not getting list in dropdown.

![screenshot](https://user-images.githubusercontent.com/61741365/75777781-9546e280-5d7c-11ea-9c99-c1800b7a1946.png)


Also I checked elementor code I think below code issue

![Screenshot_1](https://user-images.githubusercontent.com/61741365/75778044-1900cf00-5d7d-11ea-9984-6aa4ac3b7d53.png)

**Comment by hiteshmakvana** [comment]
@shilo-ey 

Your following code still doesn't work for any post type.
```
/**
 * Add non-supported post type support
 */
add_filter( 'elementor_pro/utils/get_public_post_types', function() {
	$post_types['YOUR_CPT_KEY'] = 'YOUR_CPT_LABEL';
	return $post_types;
} );
```

Can you please provide more explainatoin?

**Comment by andersonnarciso** [comment]
Work for me, thanks!

```
/**
 * Add non-supported post type support
 */
add_filter( 'elementor_pro/utils/get_public_post_types', function() {
	$post_types['post-type-slug-1'] = 'Post Type Name 1';
        $post_types['post-type-slug-2'] = 'Post Type Name 2';
        $post_types['post-type-slug-3'] = 'Post Type Name 3';
        $post_types['post-type-slug-4'] = 'Post Type Name 4';
        $post_types['post-type-slug-5'] = 'Post Type Name 5';
	return $post_types;
} );
```
