### ISSUE TITLE
elementor.templates JS throwing an error

### ISSUE THREAD

**Issue by seanbarton** [elementor/elementor#9334]
Hi there. I've written a plugin which uses the following calls:

elementor.templates.closeModal();
elementor.templates.getLayout().showLoadingView();
elementor.templates.getLayout().hideLoadingView();

These were working fine until recently but now they throw a JS error. I guess access to elementor.templates is no longer accessible in this way? Can you please let me know what the situation is and, if possible, provide replacement lines that will work in the current version of Elementor.

thanks
Sean

**Comment by VerdiH** [comment]
@bainternet Is this something you could help Sean with? Personally I can't wait to see his next Elementor Plugin.

**Comment by shilo-ey** [comment]
Hi @seanbarton 

Try using:
```
elementor.templates.getLayout() > elementor.templates.layout
elementor.templates.closeModal() > elementor.templates.layout.hideModal();
```

Let me know if you have any other questions.

Thanks

**Comment by seanbarton** [comment]
Thanks. The replacements for elementor.templates.getLayout() for elementor.templates.layout worked ok although the elementor.templates.layout.closeModal(); threw a JS error. I can get around it using conventional jQuery but any ideas about doing it using the Elementor method?

Thanks
S

**Comment by shilo-ey** [comment]
Hi @seanbarton 

It will be better if you will use this to open the template library to the default route:

`$e.run( 'library/open' );`

And to close the library via command:

`$e.run( 'library/close' );`

We will soon publish documentation for the new JS API.

Thanks
