### ISSUE TITLE
Section etc naming

### ISSUE THREAD

**Issue by patbell101** [elementor/elementor#9335]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am using navigator with several hidden sections and not being able to easily see which one I wan.

**Describe the solution you'd like**
I would like to be able to customise a name for navigator elements. Perhaps if they have been given a class ID, show this after the type of element e.g. Section Windowsdropdown

**Describe alternatives you've considered**
Just click on each one go to advanced and look

**Additional context**

**Comment by shilo-ey** [comment]
Hi @patbell101 

This option is available, try to double click on the elements' name.

read more here: https://elementor.com/blog/introducing-navigator/

Thanks
