### ISSUE TITLE
Default values of control "DIMENSIONS" are not applied before I touched the control

### ISSUE THREAD

**Issue by jscontrust** [elementor/elementor#9345]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

I set default values for a responsive DIMENSION control. When I add the related widget, the css defined in 'selectors' is not applied. I have to touch the control (change a value) to have it applied. After the control was touched once, everything works fine

## Steps to reproduce

Add this code to your theme or plugin.

    add_action( 'elementor/element/section/section_layout/after_section_start', function( $element, $section_id, $args ) {

        $element->add_responsive_control(
            'my_custom_margin',
            [
                'label' => __( 'Margin (Custom)', 'elementor' ),
                'descriptions' => __( 'u', 'elementor' ),
                'type' => \Elementor\Controls_Manager::DIMENSIONS,
                'size_units' => [ 'rem', 'px', '%' ],            
                'placeholder' => [
                    'top' => '15',
                    'right' => '5',
                    'bottom' => '15',
                    'left' => '5',
                ],
                'selectors' => [
                    '{{WRAPPER}}' => 'margin-top: {{TOP}}{{UNIT}}; margin-left: {{LEFT}}{{UNIT}}; margin-right: {{RIGHT}}{{UNIT}};',
                ],                
                'default' => [
                    'unit' => 'rem',
                ],
                'tablet_default' => [
                    'unit' => 'rem',
                ],
                'mobile_default' => [
                    'unit' => 'rem',
                ], 
            ]
        );

    }

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@jscontrust 

This is the desired behavior, Elementor doesn't save default values for performance and optimization reasons.

You should set your default values for design controls (ex: dimensions, bacground, color ...) in your CSS. This is what we do.

thanks.
