### ISSUE TITLE
CSS generated from control with "selectors" is only applied after save, when it is shown on "condition"

### ISSUE THREAD

**Issue by jscontrust** [elementor/elementor#9346]
I have two controls:
1) A SWITCH (on/off). Default is off
2) A SLIDER control with defined "condition" and defined "selectors" and a "default" value. Condition says, that the control is visible, when the switch is set to "on"

When I now activate the switch, the CSS from the SLIDER control is not applied. I have to change value of the slider or save the post to have it applied.

**Comment by bainternet** [comment]
@jscontrust 

Same as with https://github.com/elementor/elementor/issues/9345#issuecomment-542571369

Default design values should come from CSS and not controls.
