### ISSUE TITLE
Elementor Widgets in Classic Editor / Shortcode Creation

### ISSUE THREAD

**Issue by molemanproductions** [elementor/elementor#9348]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Use Elementor widgets in Woo Commerce Single Products

**Describe the solution you'd like**
Use Shortcode Toggle Toolbar that allows the creation of Accordions, Tabs and other Elementor widgets. almost like a wizard of sorts. This would make elementor widgets integrate in a pure text system while being able to update themes/styles later.

**Describe alternatives you've considered**
Originally I use to do this in WP Bakery, creating this in the frontend, and then converting to classic rich text in the backend to copy into WooCommerce.

**Comment by shilo-ey** [comment]
Hi @molemanproductions 

You can customize your WooCommerce product pages using our WooCoomerce Builder integrated into Elementor Pro.

If you wish to use shortcodes, you can create templates and grab the generated shortcode.

Thanks
