### ISSUE TITLE
Flodesk integration

### ISSUE THREAD

**Issue by LuisBelcher** [elementor/elementor#9349]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Many of my clients are getting clever and wokring hard on their email marketing.  Most use Mailchimp, but Flodesk is growing in popularity.  I just know that most of my clients are going to start needing integration with Flodesk instead of Mailchimp.

**Describe the solution you'd like**
It would be great to be able to easily integrate Elementor Pro with Flodesk - just like how it currently is for Mailchimp, ConvertKit, etc.  That way I can build lovely forms using the forms widget and then select Flodesk as an action on submit.

**Describe alternatives you've considered**
I've considered just embedding a Flodesk form into the client sites, but that doesn't look as good as the Elementor Pro forms widget does.

**Comment by bainternet** [comment]
@LuisBelcher 

As far as I know, Flodesk is still in private beta and without publicly available API. We will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by ashleyhughesdesign** [comment]
@LuisBelcher, I have about 7 clients lined up who will all be using Flodesk.   Any update on if Elementor will be adding that to the mix?

**Comment by vgstef** [comment]
I now have client using Flodesk. Can you reopen this issue?

**Comment by kitsunecreativeco** [comment]
Another +1 for this...any update here?

**Comment by vgstef** [comment]
Hi! Flowdesk isn't in beta version anymore. Can you reopen this issue?
