### ISSUE TITLE
Font Awesome - swap - google page speed insights

### ISSUE THREAD

**Issue by david-strejc** [elementor/elementor#9351]
I got latest Elementor and Elementor Pro with following: 

![font-awesome](https://user-images.githubusercontent.com/6084451/66918494-c3bb5f80-f01f-11e9-934b-c5cb16481202.png)

What is wrong?

**Comment by bainternet** [comment]
@david-strejc 

Basically, nothing is wrong, only the fact that Google sees all fonts and can't differentiate between textual fonts to icon fonts which should **not** be set to `font-display: swap;`

you can actually see that the section is called: "Ensure **text** remains visible during webfont load" and the fonts listed are FontAwesome fonts.

thanks.
