### ISSUE TITLE
Problem with Elementor / Unlimited Elements

### ISSUE THREAD

**Issue by spiritbeatz** [elementor/elementor#9352]
Hello! I ran into a problem after purchasing unlimited elements.  I did everything as shown to me in the video tutorial https://unlimited-elements.com/2019/06/27/interactive-image-map-for-elementor/, but after all I tried to click on the link and it does not work.   I tried to paste the code manually using elementor but the link also does not work.   You can see 2 examples on this page. http://elementor.echotag.net/test-image-map/ Upper example using the unlimited elements plugin, lower code inserted manually. Both examples do not work. Is there a problem with the plugin elementor? I contacted the support of the elementor and I was sent to this site.

**Comment by spiritbeatz** [comment]
http://test2.stroybulvar.com/test-composer/ I tried using visual composer, I inserted the code manually and it works, I also tried using addon creator, both examples work, if you click on the icon you will go to google.com, why does this method not work with elementor? I paid money and was hoping to get a working plugin ...

**Comment by spiritbeatz** [comment]
I was also informed that the problem could be with the unlimited elements plugin, but if the problem were only with this plugin the manual method with raw html would work, but it does not work.

**Comment by bainternet** [comment]
@spiritbeatz 

Sorry for the confusion but we have nothing to do with "unlimited elements".

try contacting their support.
