### ISSUE TITLE
Extend Elementor Widgets

### ISSUE THREAD

**Issue by Praesidiarius** [elementor/elementor#9363]
Hi

i've already developed a couple of elementor plugins, super easy to extend elementor
with own widgets - great work, you have an awesome API!

Now i want to extend the original "Elementor Toggle Widget" with some extra options like
choose items to be opened at start, close all open items when opening another one (i saw its a feature that is requested here already a lot of times). Was looking for other tickets, but the only thing i found is about the Forms API which is not what i need. I also had a look at
https://code.elementor.com/methods/elementor-controls_stack-update_control/
but theres the same problem - i can only update my widgets controls - i don't see any hint how to access and update / extend controls for an other, existing widget.

can you give me any hint - i guess there is no real documentation but maybe some code examples or references how to extend an existing elementor plugin? According to what i see in docs so far, i would need to copy the whole elementor toggle widget and make a new one - but i would really like to just add options on top of the original widget which is much more conventient. Also, as i know how to extend elementor widgets, i would extend some others too.

Any help would be greatly appreciated.

**Comment by bainternet** [comment]
There are many examples here how to update controls of our native widgets ex:

https://github.com/elementor/elementor/issues/6171#issuecomment-439184421

also in our hooks ref docs: [elementor/element/{$section_name}/{$section_id}/before_section_start](https://code.elementor.com/php-hooks/#elementorelementsection_namesection_idbefore_section_end)

Basically, if you want to add controls of existing widget use the provided hooks:

```PHP
add_action( 'elementor/element/heading/section_title/before_section_end', function( $element, $args ) {
	// add a control
	$element->add_control( 'title_color',
		[
			'label' => 'Color' ,
			'type' => Controls_Manager::SELECT,
			'default' => 'red',
			'options' => [
				'red' => 'Red',
				'blue' => 'Blue',
			],
			'section' => 'section_title',
			'tab' => 'content',
		]
	);
}, 10, 2);
```

The same Hook applies for updating existing controls:

```PHP
add_action( 'elementor/element/heading/section_title/before_section_end', function( $element, $args ) {
	$elementor = \Elementor\Plugin::instance();
	// Get the control you want to update
	$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'title_color' );

	if ( is_wp_error( $control_data ) ) {
		return;
	}
        // Alter the control
	$control_data['default'] = 'blue';
        // Update the control
	$element->update_control( 'title_color', $control_data );
}, 10, 2);
```

other examples: 
https://github.com/elementor/elementor/issues/3569#issuecomment-368307198
https://github.com/elementor/elementor/issues/8862#issuecomment-523064717
https://github.com/elementor/elementor/issues/8832#issuecomment-521189093
https://github.com/elementor/elementor/issues/3497#issuecomment-370736478
https://github.com/elementor/elementor/issues/8347#issuecomment-502972967

Feel free to open a new issue if you have a specific question.

**Comment by kbradleyg** [comment]
@bainternet 
I've been trying to adapt the upper code to the description field of the call-to-action-widget by looking at the widget's structure etc. within elementor pro directory. I want to turn the regular description field into a WYSIWYG also. But somehow nothing happens. If I change it in the plugins source file it works, but sure I want to override it through my functions.php. What am I missing here?

```
/*
 * Set Elementor > CTA widget description as wysiwyg Text Editor
 */
add_action( 'elementor/element/call-to-action/section_content/before_section_end', function( $widget, $args ) {
	$cta_control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $widget->get_unique_name(), 'call-to-action' );

	if ( is_wp_error( $cta_control ) ) {
		return;
	}

	$cta_control['fields']['description']['type'] = \Elementor\Controls_Manager::WYSIWYG;

	$widget->update_control( 'call-to-action', $cta_control );
},10 ,2 );
```

Any help appreciated. Thank you.
