### ISSUE TITLE
Global font size setting please

### ISSUE THREAD

**Issue by blitz999** [elementor/elementor#9364]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by blitz999** [comment]
Hi, your feedback system is less than user friendly. I don't understand if this submitted correctly or not.
Just requesting global font size settings - to go with the already included font style and weight choices.

The previous ticket was closed without answer.

This GitHub form as a means of interaction with your customers is painful and dysfunctional as can be seen from teh above submission. Would you like me to create you a beautiful form in Elementor for feedback? Happy to.

**Comment by shilo-ey** [comment]
I merged this issue with  #5252, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
