### ISSUE TITLE
Problem with new pro gallery feature.

### ISSUE THREAD

**Issue by matur1022** [elementor/elementor#9366]
When having multiple galleries one one page, it glitches and show like half images or just one picture of the whole gallery until you click all or one of the sub-galleries.
 Heres an example on my site: http://goldframez.com/wedding-event/
 
I am worried potential clients are thinking the photos don't exist.

**Comment by srcek** [comment]
I have the same problem.

**Comment by hbryanjones** [comment]
Yes. I'm having the same issue. I've had a lot of back and forth with Elementor support. They've been responsive, but so far no luck with everything they've suggested (updating WordPress, Elementor, Elementor Pro), recreating the page from scratch, starting over with new galleries. 

I seem to have more issues when logged into Incognito in Chrome, but also do get the issue in regular Chrome. I'm really hoping we get this resolved soon. I'll let you know if I make any progress.

**Comment by hbryanjones** [comment]
Hi guys. Quick update from Elementor support. After some back and forth troubleshooting, here's the answer:

> "After looking into this further, It seems like it's due to some glitch in the masonry mode in the gallery. I have reported the issue to our dev team and hopefully, they will resolve this soon.
> 
> We are truly sorry for the inconvenience caused by this issue, but our devs will resolve this as soon as possible and roll it out in a future update."
 
matur1022 - I looked at your gallery and it is also "masonry," as was mine. I've switched it to "justified" for the time being, and the issue went away. Once they roll out the fix, I plan to switch back to "masonry." 

Hope that helps! 
Bryan
