### ISSUE TITLE
Connect posts to ANY widget with title/content.

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#9368]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

More flexibility when it comes to where the content in post types are stored in front-end.

**Describe the solution you'd like**

When posting something in a post type in the back-end, we insert title, main content, custom fields etc. We can add this to a template and show it on the front-end.

But, what if this could be connected to every widget that contained a title and a description.

Let's take the TABS-element as an example. This contains the TITLE and it contains a WYSIWYG editor with THE CONTENT. What if you could automatically create a new tab each time you created a new post. 

See here for a video example: http://bit.ly/2pBDrbi
This is created in AVADA.

**Describe alternatives you've considered**
None.

**Additional context**
See here for a video example: http://bit.ly/2pBDrbi

**Comment by shilo-ey** [comment]
I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
