### ISSUE TITLE
 Pro Gallery Navigation

### ISSUE THREAD

**Issue by Hoffl-GitHub** [elementor/elementor#9369]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

There is not the possibility to define the whole sequence of the multiple gallery navigation including the "All".
For the multiple gallery I can activate the "All" filter. But then the "All" is always the first point in the navigation and default. But I think  it makes more sense to start with the "filtered" galleries. First start with the shortlist, the best images, if I get the client there than may be he wants to see more or even all...

Put the "All" filter in the row with the other galleries, so I can define by drag and drop the sequence of the gallery navigation including the "All".

**Comment by lior-sh** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
