### ISSUE TITLE
Lightbox Navigation too small

### ISSUE THREAD

**Issue by Hoffl-GitHub** [elementor/elementor#9370]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

For the navigation in the lightbox the user has to click exactly on the little tiny arrow buttons on left and right side. 

For a better usability a bigger area to click would be better, like left and right half of the image.

For the moment I helped my self with something like that in the css:

.elementor-lightbox .elementor-swiper-button-next {
    padding: 25vh 0 25vh 40%;
}

.elementor-lightbox .elementor-swiper-button-prev {
	padding: 25vh 40% 25vh 0;
}

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!
