### ISSUE TITLE
Formular Message

### ISSUE THREAD

**Issue by koppandiatt** [elementor/elementor#9371]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am building a multilingual website using Elementor and I have created few Formular using Elementor Formular widget, and the problem is with messages after sending the formular, my main language is German and I would like to write custom messages for the formular.

**Describe the solution you'd like**
I would like to have an option to rewrite messages of Formular, message like Successfully sent or Errors, and so on.

**Comment by bainternet** [comment]
@koppandiatt 


If you are talking about the form messages then you can already set your own:

![Fj299vB](https://user-images.githubusercontent.com/660572/67403499-b02d6d00-f5ba-11e9-95e1-d7972c3f5ef6.png)


Hope this helps.
