### ISSUE TITLE
Add CSS Loading... Screen to the New Pro Gallery

### ISSUE THREAD

**Issue by jparker0714** [elementor/elementor#9373]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

> Photos take too long to load if there are a lot and you have a slow connection.

**Describe the solution you'd like**

> So I noticed someone else has already request to have a load more option. But I have also noticed that all photos load at once. So I think your code is set to load the photos in the background, then shows when loaded. Which is okay, but if you have a lot of photos like 50 or more and a slow internet connection then those photos can take time to load so it just shows a blank page until those load. So I suggest have a CSS Loading Circle that can be edited with your own style. Or if you change the coding up to load individual files one at a time, then you can use what the other person suggested or have a Lazy Loading Option. This way its lets the user know that images are there and it will either load more or have the loading screen for them to see.  

**Describe alternatives you've considered**

**Additional context**

**Comment by lior-sh** [comment]
invalid Feature request
----
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Description and examples.
* One request per thread
Thanks.
