### ISSUE TITLE
Embedded video iFrame does not have title attribute.

### ISSUE THREAD

**Issue by shipley-dcc** [elementor/elementor#9374]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

As a user relying on web accessibility technology to access the internet I would like to know more information about an iframe when it is included in a web page so that I can better understand its purpose and content.

According to W3C Web Content Accessibility Guidelines 2.0 - 4.1.2 Name, Role, Value - For all user interface components the name and role can be programmatically determined.
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#ensure-compat-rsv

To aid in satisfying this requirement the W3C recommends Technique H64: Using the title attribute of the frame and iframe elements.
https://www.w3.org/TR/WCAG20-TECHS/H64

## Steps to reproduce

Add a Video widget to a website using Elementor.  Inspect the embedded iFrame.  The title attribute is not included.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.41 (Unix) OpenSSL/1.1.1d PHP/7.3.10
	MySQL version: Homebrew v10.4.6
	PHP Version: 7.3.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.6.8
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.2
		Author: ServMask

	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Duplicate Page
		Version: 3.8
		Author: mndpsingh287

	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.11
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.11.4
		Author: rocketgenius

	GravityWP - CSS Selector
		Version: 1.0.1
		Author: GravityWP

	JetElements For Elementor
		Version: 1.15.16
		Author: Zemez

	Ocean Extra
		Version: 1.5.10
		Author: OceanWP

	Styles & Layouts Gravity Forms
		Version: 4.2.1
		Author: Sushil Kumar

	UpdraftPlus - Backup/Restore
		Version: 1.16.16
		Author: UpdraftPlus.Com, DavidAnderson

	WP Fastest Cache
		Version: 0.8.9.6
		Author: Emre Vona

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8

Feel free to update

Thanks!
