### ISSUE TITLE
Control condition is not working with new icons control

### ISSUE THREAD

**Issue by easin-xs** [elementor/elementor#9376]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Controls condition is not working with the new icons. I have tried several ways to make the condition work.

My Need:  If new icon is empty then a control won't show. otherwise it will show.

Below I have share my code with my possible try.
* First try:
1. This is my icon controls:

<pre>
$this->add_control(
	'ekit_btn_icons',
	[
		'label' =>esc_html__( 'Icon', 'elementskit' ),
		'type' => Controls_Manager::ICONS,
		'fa4compatibility' => 'ekit_btn_icon',
		'label_block' => true,
		'default' => [
                     'value' => '',
                ],
        ]
);		
</pre>

2. This is the possible try I have done so far to show the control based on condition. If my above icons is not empty then the below control will be displayed otherwise hidden.
<pre>
$this->add_control(
            'ekit_btn_icon_align',
            [
                'label' =>esc_html__( 'Icon Position', 'elementskit' ),
                'type' => Controls_Manager::SELECT,
                'default' => 'left',
                'options' => [
                    'left' =>esc_html__( 'Before', 'elementskit' ),
                    'right' =>esc_html__( 'After', 'elementskit' ),
                ],
                'condition' => [
                    'ekit_btn_icons!' => '',
                ],
            ]
 );		
</pre>

* Second try: 

1. This is my icon controls:

<pre>
$this->add_control(
	'ekit_btn_icons',
	[
		'label' =>esc_html__( 'Icon', 'elementskit' ),
		'type' => Controls_Manager::ICONS,
		'fa4compatibility' => 'ekit_btn_icon',
		'label_block' => true,
		'default' => [
                     'value' => '',
                ],
        ]
);		
</pre>
2. This is the possible try I have done so far to show the control based on condition. If my above icons is not empty then the below control will be displayed otherwise hidden.
<pre>
$this->add_control(
            'ekit_btn_icon_align',
            [
                'label' =>esc_html__( 'Icon Position', 'elementskit' ),
                'type' => Controls_Manager::SELECT,
                'default' => 'left',
                'options' => [
                    'left' =>esc_html__( 'Before', 'elementskit' ),
                    'right' =>esc_html__( 'After', 'elementskit' ),
                ],
                'conditions' => [
			'terms' => [
					[
						'name' => 'ekit_btn_icons',
						'operator' => '!=',
						'value' => [
							'value' => ''
						],
					],
				],
			],
            ]
        );
</pre>

## Steps to reproduce
Above I have shown the issues code. I hope that will clear to you.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@easin-xs 

The new Icons control stores the value as an array so in your condition you need to check the value element of the control ex:

```PHP
'condition' => [
	'icon_control_id[value]!' => '',
],
```

and you can actually see how we use it in our native widgets:
https://github.com/elementor/elementor/blob/42cdb73444cf207064d6386c41b2ab42bf46bc85/includes/widgets/button.php#L197-L222

thanks.

**Comment by easin-xs** [comment]
@bainternet thank you so much. It's working great.
