### ISSUE TITLE
Nav-Menu expands and contracts on page load

### ISSUE THREAD

**Issue by critterles** [elementor/elementor#9379]
I have the latest version of WP and Elementor and Pro and I use Nav-Menu over the Theme menus because of the huge flexibility. The Issue is after creating a nav-menu and adding it in a section on the page, when the page is loaded, the menu expands and then contracts. It seems to load the current styled menu correctly and then falls back to a default style and then reloads the correct format. I've tried this in Hello, OceanWP and Astra themes and they all react the same. I found one post that talked about some code that was in the footer that should be in the top of the code but it was not very clear on how to do this. Has anyone found a solution to this?

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
