### ISSUE TITLE
Feature Request: Comprehensive Action Hooks throughout Elementer and Hello

### ISSUE THREAD

**Issue by tictok** [elementor/elementor#9392]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor Pro is great for quick and visual building of pages and themes. However often, as a theme builder or theme developer for a client extra functionality needs to be added within the page structure that is out of the scope of Elementor but could easily be added via functions.php in a child theme, if there were well thought-out action hooks through the pages and content Elementor creates and also within Hello theme. Particularly when using the Theme Builder and it's template parts. 

**Describe the solution you'd like**
Ideally, well thought-out action hooks placed throughout the template parts and content that Elementor creates and also throughout Hello theme. Particularly when using the Theme Builder and it's template parts. A good example for action hook could 'before_theme_builder_header',  
'after_theme_builder_header', 'before_theme_builder_footer' etc.  

**Describe alternatives you've considered**
I managed occasionally to get around this by registering new Elementor locations or by adding my own hooks within theme files, but it'd be great if Elementor cam with a comprehensive set of action hooks included. 

Thanks

**Comment by bainternet** [comment]
@tictok 

There are already hooks all over Elementor and Elementor pro, just by looking at your example: 

> A good example for action hook could `before_theme_builder_header`,
`after_theme_builder_header`, `before_theme_builder_footer` etc.

We have these hooks in place already:

```PHP
/**
 * Before location content printed.
 *
 * Fires before Elementor location was printed.
 *
 * The dynamic portion of the hook name, `$location`, refers to the location name.
 *
 * @since 2.0.0
 *
 * @param Locations_Manager $this An instance of locations manager.
 */
do_action( "elementor/theme/before_do_{$location}", $this );
```

and 

```php
/**
 * After location content printed.
 *
 * Fires after Elementor location was printed.
 *
 * The dynamic portion of the hook name, `$location`, refers to the location name.
 *
 * @since 2.0.0
 *
 * @param Locations_Manager $this An instance of locations manager.
 */
do_action( "elementor/theme/after_do_{$location}", $this );
```

which means the action hooks are triggered before and after each location, ex:
```PHP
add_action( 'elementor/theme/after_do_header',function() {
	echo ;<div>I come before header location</div>';
} );

add_action( 'elementor/theme/before_do_footer',function() {
	echo ;<div>I come after footer location</div>';
} );
```

Now if you feel there is a specific hook missing, please let us know and will consider adding it.


Thanks.

**Comment by tictok** [comment]
Amazing - thank you. 
I searched the API docs but must have missed the info. Thanks again.

**Comment by Jeremynicholas** [comment]
Hi @bainternet, how can elementor templates be hooked into parts of the page if using the Hello theme? Similar to how other themes do it like generate press.
