### ISSUE TITLE
Icon Library not Loading

### ISSUE THREAD

**Issue by Paras16699** [elementor/elementor#9396]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

As stated in this ticket #9239, I am also unable to add an icon to the Icon List widget since the Icon library is rendering empty and I'm getting the same message in the console as the OP posted.

I opened this as a separate issue because the previous one was closed by the bot due to improper report format.

![image](https://user-images.githubusercontent.com/18551588/67461016-000f4100-f65a-11e9-9529-2ff7162d6c36.png)

![image](https://user-images.githubusercontent.com/18551588/67461049-12897a80-f65a-11e9-8bd5-7ecf8fa22a68.png)

## Steps to reproduce

1. Install the latest versions of Elementor and EPro - v2.7.4 and v2.7.2 respectively.
2. Edit a page in Elementor.
3. Add any icon widget (eg: Icon List) and add an icon to it.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Paras16699 
Please contact our support at support @elementor.com for guidance in resolving this issue **and mention that you were directed by me and reference this issue**.

Please address them with login credentials to this affected site.

thanks.

**Comment by parasshah195** [comment]
Solved following these steps - https://docs.elementor.com/article/610-icon-library-is-empty
