### ISSUE TITLE
Change lightbox image size

### ISSUE THREAD

**Issue by kikopobla** [elementor/elementor#9399]

**Comment by kikopobla** [comment]
HI,
I would like to change the lightbox image size.

(with a plugin or changing CSS or other doesnt matter)
It's very little
Can you help me?

Thanksss
![lightbox size](https://user-images.githubusercontent.com/56972162/67503358-c9e8b600-f687-11e9-911e-d209ad20b582.jpg)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!

**Comment by PauKokura** [comment]
Updated to Pro 2.9.9 (not beta!) and lightroom is not working properly. It appears uncentered, on the right/bottom of the browser, showing just half of its size.
The strange thing is that when I manually move the browser window (like to check responsiveness), it fixes to the center!

![Captura de pantalla 2020-06-05 a les 9 22 44](https://user-images.githubusercontent.com/3900806/83849160-4871ff80-a70f-11ea-9b80-18fe60edced2.png)
![Captura de pantalla 2020-06-05 a les 9 23 00](https://user-images.githubusercontent.com/3900806/83849162-490a9600-a70f-11ea-8196-6853640422b6.png)
