### ISSUE TITLE
Have the option to remove delay on drop-down menu

### ISSUE THREAD

**Issue by sunnyt7** [elementor/elementor#9400]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Any time you hover over a menu item, the drop-down menu takes a second to show up (this can be seen on https://elementor.com/)

It's fine when there's just one drop-down, but the user experience starts to feel a little laggy when you have multiple drop-down nav items side by side.

I feel like it should be possible to change or remove the half-second delay for drop-down menus.

I'd be open to just apply a script to change this, but Elementor support essentially told me "What you are trying to achieve is not possible due to the JS libraries we are using for nav menu widget in Elementor. Interfering in that code would affect many areas of Elementor."

**Comment by sunnyt7** [comment]
Actually, found a solution in https://github.com/elementor/elementor/issues/4989. Just needed to add "showTimeout: 0".

Added this inside the Code Snippets plugin:

`add_action( 'wp_footer', function () { ?>
	<script>

		jQuery(document).ready(function($) {

   // Get the menu instance
   // Ultimately smartmenus is expecting a <ul> input, so you need to target the <ul> of the drop-down you're trying to affect.
  var $menu = $('.elementor-nav-menu:first');

  // Get rid of the existing menu
  $menu.smartmenus('destroy');

  // Re-instantiate the new menu, with no delay settings
  $menu.smartmenus( {
      subIndicatorsText: '',
      subIndicatorsPos: 'append',
      subMenusMaxWidth: '1000px',
      hideDuration: 200,
      hideTimeout: 150,
      showTimeout: 0,	// timeout before showing the sub menus
  });

});

	</script>
<?php } );
`

**Comment by bainternet** [comment]
@sunnyt7 

Glad you figured it out.

**Comment by scottybo** [comment]
Can this be re-opened @bainternet - this should really be a feature within the GUI rather than having to do a hacky override.

**Comment by dawgor** [comment]
Instead of destroying and re-instantiating an existing menu you could directly edit the HTML source before the menu init this way:

`$('.elementor-nav-menu--main > ul').attr('data-sm-options', '{ showTimeout: 0 }');`

More options to play around with on their site: https://www.smartmenus.org/docs/

**Comment by felixpt** [comment]
@dawgor what wp file do you need to edit for this?

**Comment by dawgor** [comment]
```
add_action( 'wp_footer', function () { ?>
	<script>
	jQuery(document).ready(function($) {
            $('.elementor-nav-menu--main > ul').attr('data-sm-options', '{ showTimeout: 0 }');
        });
	</script>
<?php } );
```

Try adding the above code to your functions.php, should work. But I think the best way of implementing this would be manully adding a custom javascript file to your theme using wp_enqueue_script function: 
https://developer.wordpress.org/themes/basics/including-css-javascript/. 

You could use a plugin to add a custom js code as well: https://wordpress.org/plugins/custom-script-for-customizer/

**Comment by deepak-ghimire** [comment]
We have been using a simple CSS override on hover, to set the display block early on.
```
.elementor-nav-menu--main .menu-item:hover .elementor-nav-menu--dropdown{
    display: block !important;
}
```
So far it looks fine.

**Comment by user34209348** [comment]
> 
> 
> ```php
> add_action( 'wp_footer', function () { ?>
> 	<script>
> 	jQuery(document).ready(function($) {
>             $('.elementor-nav-menu--main > ul').attr('data-sm-options', '{ showTimeout: 0 }');
>         });
> 	</script>
> <?php } );
> ```


Does this also work for the hamburger menu and the submenu (.sub-menu.elementor-nav-menu--dropdown)? It did not work with this.
```php
add_action( 'wp_footer', function () { ?>
	<script>
	jQuery(document).ready(function($) {
            $('.elementor-nav-menu--main > ul, .elementor-nav-menu--dropdown > ul').attr('data-sm-options', '{ showTimeout: 0 }');
        });
	</script>
<?php } );
```

**Comment by jordan-webdev** [comment]
Regarding the solution posted above:
`$('.elementor-nav-menu--main > ul').attr('data-sm-options', '{ showTimeout: 0 }');`

Note that as of current writing, this gives an alert on the site with an error that it is invalid syntax. Add quotes to showTimeout to fix, like this:
`$('.elementor-nav-menu--main > ul').attr('data-sm-options', '{ "showTimeout": 0 }');`
