### ISSUE TITLE
A Filter to show or not show a popup.

### ISSUE THREAD

**Issue by greggh** [elementor/elementor#9401]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I love Elementor's popup system, but I need a way to block a popup from displaying, or the inverse, a way to force one to display. I have a membership site, and I want to show popups to specific membership levels, so I can show upgrade prompts and upsells. So I need to be able to show an upgrade from level 1 to level 2, only to level 1 members.

**Describe the solution you'd like**
I want a filter that I can use in functions.php that gives me a popup id and I return true or false to allow or disallow it showing up on this page load.

Very rudimentary example idea:

```php
add_filter( ‘elementor_allow_pop_up', ‘allow_pop_up’ );

function allow_pop_up( $popup_id) {
 if ($user_is_this_level && $popup_id = 10) {
  return true;
 } else {
  return false;
 }
}
```

**Describe alternatives you've considered**
I reached out to support and after talking to them they told me to come post this here.

**Additional context**

**Comment by bainternet** [comment]
@greggh 

You can add the popup to the a page based on your condition using the provided API, ex:

```PHP
add_action( 'wp_footer', function() {
	if ( ! $CONDITION ) {
		// exit and dont even print the popup
		return;
	}
	//add the popup to the page
	ElementorPro\Modules\Popup\Module::add_popup_to_location( '234' ); // 234 is the popup id
} );
