### ISSUE TITLE
Validate credit card numbers entered into Form?

### ISSUE THREAD

**Issue by jackslayer1234** [elementor/elementor#9403]
I currently use Forms to capture the credit card information of my customers. Is there a way to validate the details entered prior to allowing users to submit their inputs? I am getting alot of errors in submission eg. wrong credit card number, wrong CVV code etc.

Thank you.

**Comment by bainternet** [comment]
@jackslayer1234 

You can run any kind of validation you want against the form fields using the API and provided hooks: https://developers.elementor.com/forms-api/

ex:

```PHP
// Validate the Tel field is in XXX-XXX-XXXX format.
add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {

    // Match this format XXX-XXX-XXXX, 123-456-7890

    if ( preg_match( '/[0-9]{3}-[0-9]{3}-[0-9]{4}/', $field['value'] ) !== 1 ) {
        $ajax_handler->add_error( $field['id'], 'Please make sure the phone number is in XXX-XXX-XXXX format, eg: 123-456-7890' );
    }
}, 10, 3 );
```
