### ISSUE TITLE
Global Elementor style settings.

### ISSUE THREAD

**Issue by savakms** [elementor/elementor#9404]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Why Elementor does not allow to change global styles?
For example padding and margin of columns in the whole project.

**Describe the solution you'd like**

It would be cool to add such an option like changing the padding widgets in the settings.

**Describe alternatives you've considered**

Something like [this](https://wordpress.org/plugins/analogwp-templates/).

**Additional context**

At the moment I am working with a project that uses a modular grid of 8 pixels in size, so the default settings are not suitable for me and I would not want to change everything manually.

**Comment by shilo-ey** [comment]
I merged this issue with  #1553, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
