### ISSUE TITLE
Post content does not create an elementor text editor (With restriced user roles)

### ISSUE THREAD

**Issue by jszineap** [elementor/elementor#9414]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**Quick summary:** Users with limited access to Elementor ("Access to edit content only") cannot edit a post if they don't write content in Gutenberg or the classic editor _before_ clicking on "Edit in Elementor".

## Steps to reproduce

**Mandatory first step:** Create a template in the theme builder. Add a "Post Content" element, and use that template for all posts.

**Issue:** Log in on WordPress as a User with "Access to edit content only", create a new post, add a title, **don't add content**, publish, edit as elementor.  => No way to edit anything.

**Way around it:** Log in on WordPress as a User with "Access to edit content only", create a new post, add a title, **add content**, publish, edit as elementor.  => Now there's a "Text editor" element that the user can edit for this post. 

[Images describing the problem](https://imgur.com/a/K52BkEP)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.10
	MySQL version: mariadb.org binary distribution v10.4.8
	PHP Version: 7.3.10
	PHP Max Input Vars: 4000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.4
	Site URL: http://localhost
	Home URL: http://localhost
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: WQSB Schools
	Version: 1.0.0
	Author: Aponia
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.8.6
		Author: Elliot Condon

	Advanced Database Cleaner
		Version: 2.0.0
		Author: Younes JFR.

	Aponia - WQSB schools theme options
		Version: 0.1.0
		Author: Aponia

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.6.2
		Author: WebDevStudios

	Elementor
		Version: 2.7.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.5
		Author: Elementor.com

	Premium Addons for Elementor
		Version: 3.8.0
		Author: Leap13

	Premium Addons PRO
		Version: 1.7.5
		Author: Leap13

	Yoast SEO
		Version: 12.3
		Author: Team Yoast


== Log<span id="elementor-clear-log"></span> ==
	


== Elements Usage ==
	
	footer
		heading : 1
		icon : 1
	header
		heading : 1
		image : 1
		nav-menu : 2
		theme-page-title : 1
	section
		breadcrumbs : 1
	single
		post-navigation : 1
		theme-post-content : 2
	wp-post
		text-editor : 1
	wp-page
		heading : 1
		icon-box : 6
		image : 1
		text-editor : 1
		theme-post-featured-image : 1

				

</details>

**Comment by jszineap** [comment]
I forgot to add that the issue occurs whether it's the classic editor that is enabled or Gutenberg.

**Comment by bainternet** [comment]
@jszineap 

This is ok and the desired behavior. The Post content Widget is not editable regardless of what type of access you have. its a placeholder for the post content either via "classic editor", "Gutenberg" or Even Elementor when the user can add elements.

thanks.
