### ISSUE TITLE
JSON error in some Themes (also Default Theme) in Prestashop Environment

### ISSUE THREAD

**Issue by surebro00** [elementor/elementor#9419]
Hi, 

I would like to report an error about Elementor Module I have bought on Prestashop Addon Store.
I have tried to use it on the Default theme of Prestashop but noting changed.
This is the error I get on the page:
![image](https://user-images.githubusercontent.com/36013049/67692478-7be1f400-f9a0-11e9-9b88-00a41f5698cc.png)
The JSON format of the layout is printed directly inside the page...

You can view it here real time: http://dev.taggaci.shop/content/6-dev-test

Why this happen?

Thanks.

**Comment by shilo-ey** [comment]
Hi @surebro00 

Thanks for your feedback, unfortunately, this addon is not developed by Elementor (this is a 3rd party addon).

Please contact the plugin author to fix this issue.

Thanks
