### ISSUE TITLE
TikTok Icon

### ISSUE THREAD

**Issue by ex-avenger** [elementor/elementor#9423]
Hi there, first of all thank you very much for the great plugin!

I was just thinking if it was possible to add TikTok to the icons available in Elementor. It is one of the fastest growing global social media network, & it is missing. It would maybe be of great use for many users.

Thanks in advance for consideration and all the best.

**Comment by shilo-ey** [comment]
Hi @ex-avenger 

Thanks for your feedback, 

Elementor uses FontAwesome & FontAwesome Pro as native icons source.

Currently FontAwesome doesn't have an icon for this social network. As soon as it will release we will consider updating the FA library.

For now, you can use SVG icon to suit your needs. 
If you are using Elementor Pro, you can import this icon using the Custom Icon sets feature.

Thanks

**Comment by neophytewriter** [comment]
Yes, I second this! Need the Tik Tok icon! I'll send Google a message today. and also Thank you for the great plug-in!

**Comment by ex-avenger** [comment]
Font Awesome now has TikTok icon in their library.. Can you please consider updating it?

TIA

**Comment by zaehlpixel** [comment]
Excuse me, it's 2022! Still no tiktok icon!?

**Comment by zaehlpixel** [comment]
If you don't see the tiktok icon in Elementor, switch to "All icons" ;-)
