### ISSUE TITLE
Form Widget | Add "left blank" note to empty submitted form fields

### ISSUE THREAD

**Issue by likeasimon** [elementor/elementor#9430]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We want to submit the form data via email. If the user leaves non-required fields blank or untouched the corresponding shortcode from the email template will also be left blank. This could lead to confusing and also "not that beautiful" contact form emails. :)

**Describe the solution you'd like**
How about a new per-field text-setting to be shown for the shortcode if that field is left blank. Maybe defaulted to "`-`" or "`< left blank >`". I could set this value to e.g. "`<i>left blank"</i>`" for HTML typed emails to prevent confusion if the user indeed put "left blank" into the form ;)

**Describe alternatives you've considered**
None beside marking fields as "required" or using another method for contact forms.

**Additional context**
_Intentionally left empty._

**Comment by bainternet** [comment]
@likeasimon 

This can be done easly via the provided API and hooks, ex:

```PHP
// this hook is triggered after validation passe
add_action( 'elementor_pro/forms/process', function( $form_record, $ajax_handler ) {
	// get fields
	$raw_fields = $form_record->get( 'fields' );

	// loop over the fields
	foreach ( $raw_fields as $id => $field ) {
		if ( empty( $field['value'] ) ) {
			// if the field is empty set its value to "left blank"
			$form_record->update_field( $id, 'value', 'left blank' );
		}
	}
}, 100, 2 );
```
