### ISSUE TITLE
Custom Class For Inputs on Widget Form

### ISSUE THREAD

**Issue by saulobraine** [elementor/elementor#9438]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'd like to add custom classes on each include input on form.
This way is easy for better customization and make more interation for the users.
Like, if I use a mask (phone, money) on input and have some forms on the same page, today I'm use the ID and create for each input, with class on input is just add a class for work more easely.

**Describe the solution you'd like**
I'm think just including a new Custom Class option, on advanced tab in each input, where have ID and default value. 

**Describe alternatives you've considered**
In moment really dont know more alternatives. For me is a the solution above is the only way.

**Comment by bainternet** [comment]
@saulobraine 

Our forms API and Hooks already allow you do to something like that, ex:

```PHP
class Elementor_Forms_Input_Classes {

	public $allowed_fields = [
		'text',
		'email',
		'url',
		'password',
	];

	public function __construct() {
		// Add class attribute to form field render
		add_filter( 'elementor_pro/forms/render/item', [ $this, 'maybe_add_css_class' ], 10, 3 );

		add_action( 'elementor/element/form/section_form_fields/before_section_end', [ $this, 'add_css_class_field_control' ], 100, 2 );
	}

	/**
	 * add_css_class_field_control
	 * @param $element
	 * @param $args
	 */
	public function add_css_class_field_control( $element, $args ) {
		$elementor = \Elementor\Plugin::instance();
		$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'form_fields' );

		if ( is_wp_error( $control_data ) ) {
			return;
		}
		// create a new css class control as a repeater field
		$tmp = new Elementor\Repeater();
		$tmp->add_control(
			'field_css_class',
			[
				'label' => 'CSS class',
				'inner_tab' => 'form_fields_advanced_tab',
				'tab' => 'content',
				'tabs_wrapper' => 'form_fields_tabs',
				'type' => 'text',
				'conditions' => [
					'terms' => [
						[
							'name' => 'field_type',
							'operator' => 'in',
							'value' => $this->allowed_fields,
						],
					],
				],
			]
		);

		$pattern_field = $tmp->get_controls();
		$pattern_field = $pattern_field['field_css_class'];

		// insert new class field in advanced tab before field ID control
		$new_order = [];
		foreach ( $control_data['fields'] as $field_key => $field ) {
			if ( 'custom_id' === $field['name'] ) {
				$new_order['field_css_class'] = $pattern_field;
			}
			$new_order[ $field_key ] = $field;
		}
		$control_data['fields'] = $new_order;

		$element->update_control( 'form_fields', $control_data );
	}

	public function maybe_add_css_class( $field, $field_index, $form_widget ) {
		if ( ! empty( $field['field_css_class'] ) && in_array( $field['field_type'], $this->allowed_fields ) ) {

			$form_widget->add_render_attribute( 'input' . $field_index, 'class', $field['field_css_class'] );
		}
		return $field;
	}
}
new Elementor_Forms_Input_Classes();
```

this will add the control in the panel:
![n3qY5E2](https://user-images.githubusercontent.com/660572/68006759-5136ba80-fc82-11e9-8bef-479cbd967fa6.png)

and the CSS class to the actual input.

thanks for the feedback.

**Comment by saulobraine** [comment]
Thanks for answere!

For note (to anothers users), if needed to use on select, or others type of inputs.
On: `$allowed_fields` just add the type, like 'select';

And in the output too:

`$form_widget->add_render_attribute( 'INPUT_YOU_NEED' . $field_index, 'class', $field['field_css_class'] );`

**Comment by eduardovillao** [comment]
> @saulobraine
> 
> Our forms API and Hooks already allow you do to something like that, ex:
> 
> ```
> class Elementor_Forms_Input_Classes {
> 
> 	public $allowed_fields = [
> 		'text',
> 		'email',
> 		'url',
> 		'password',
> 	];
> 
> 	public function __construct() {
> 		// Add class attribute to form field render
> 		add_filter( 'elementor_pro/forms/render/item', [ $this, 'maybe_add_css_class' ], 10, 3 );
> 
> 		add_action( 'elementor/element/form/section_form_fields/before_section_end', [ $this, 'add_css_class_field_control' ], 100, 2 );
> 	}
> 
> 	/**
> 	 * add_css_class_field_control
> 	 * @param $element
> 	 * @param $args
> 	 */
> 	public function add_css_class_field_control( $element, $args ) {
> 		$elementor = \Elementor\Plugin::instance();
> 		$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'form_fields' );
> 
> 		if ( is_wp_error( $control_data ) ) {
> 			return;
> 		}
> 		// create a new css class control as a repeater field
> 		$tmp = new Elementor\Repeater();
> 		$tmp->add_control(
> 			'field_css_class',
> 			[
> 				'label' => 'CSS class',
> 				'inner_tab' => 'form_fields_advanced_tab',
> 				'tab' => 'content',
> 				'tabs_wrapper' => 'form_fields_tabs',
> 				'type' => 'text',
> 				'conditions' => [
> 					'terms' => [
> 						[
> 							'name' => 'field_type',
> 							'operator' => 'in',
> 							'value' => $this->allowed_fields,
> 						],
> 					],
> 				],
> 			]
> 		);
> 
> 		$pattern_field = $tmp->get_controls();
> 		$pattern_field = $pattern_field['field_css_class'];
> 
> 		// insert new class field in advanced tab before field ID control
> 		$new_order = [];
> 		foreach ( $control_data['fields'] as $field_key => $field ) {
> 			if ( 'custom_id' === $field['name'] ) {
> 				$new_order['field_css_class'] = $pattern_field;
> 			}
> 			$new_order[ $field_key ] = $field;
> 		}
> 		$control_data['fields'] = $new_order;
> 
> 		$element->update_control( 'form_fields', $control_data );
> 	}
> 
> 	public function maybe_add_css_class( $field, $field_index, $form_widget ) {
> 		if ( ! empty( $field['field_css_class'] ) && in_array( $field['field_type'], $this->allowed_fields ) ) {
> 
> 			$form_widget->add_render_attribute( 'input' . $field_index, 'class', $field['field_css_class'] );
> 		}
> 		return $field;
> 	}
> }
> new Elementor_Forms_Input_Classes();
> ```
> 
> this will add the control in the panel:
> ![n3qY5E2](https://user-images.githubusercontent.com/660572/68006759-5136ba80-fc82-11e9-8bef-479cbd967fa6.png)
> 
> and the CSS class to the actual input.
> 
> thanks for the feedback.

I copied this, but dont work form me.

**Comment by marcel-za** [comment]
@bainternet https://github.com/elementor/elementor/issues/9438#issuecomment-548683065

Do you place this code in the theme functions.php, or somewhere else?

**Comment by PhilipRochester** [comment]
> @bainternet [#9438 (comment)](https://github.com/elementor/elementor/issues/9438#issuecomment-548683065)
> 
> Where should I insert the code to be able to add a css class to my form inputs?

**Comment by nguyenhoang92** [comment]
@bainternet I can not input source code where and name php file. You can tutorial me.

**Comment by Ragapriyaait** [comment]
Hi Team,

On the advanced tab. I need to update the ID & Shortcode based on the custom dropdown selection on Genoo/WPMktgEngine Field dynamically & update it on the database. Can you please suggest?

![image](https://user-images.githubusercontent.com/75374788/114261676-86a81180-99f9-11eb-8c4a-fbc20279a091.png)
![image](https://user-images.githubusercontent.com/75374788/114261702-a50e0d00-99f9-11eb-8151-6e6a260e17dd.png)

**Comment by DonKolia** [comment]
Paste the code in functions.php of yout wordpress theme

**Comment by maximilien-leleu** [comment]
Hi everyone, hi @bainternet 
I need to do something like this but to add attributes instead of classes
Based on the same pattern, would it be possible to add a custom attribute field (key|value) to elementor form fields through the functions.php file ? 
Could you give some tips on how to do so ?
Thanks for hepling 🙏
