### ISSUE TITLE
Allow vertical resize of textareas

### ISSUE THREAD

**Issue by pingram3541** [elementor/elementor#9439]
For whatever reason it was chosen to not allow the vertical resizing of textareas.  This is extremely inconvenient, especially when using Pro's custom css ACE editor.  Having only a few lines visible is torture, please consider changing this.  Thank you.

**Comment by bainternet** [comment]
@pingram3541 

As far as I know, Textareas in the panel do allow resize: 
![Xj4irZf](https://user-images.githubusercontent.com/660572/67990303-29256800-fc3e-11e9-82f5-f6d8efd3bb10.png)


As for the ACE editor, it has an option `maxLines` which we set to `Infinity` by default and its height is derived from the content height so you can actually resize it as much as you need:

![iBtK3Cu](https://user-images.githubusercontent.com/660572/67990724-6dfdce80-fc3f-11e9-8d4a-a66b66c6cdc2.png)

not sure if it's the best approach but it is possible already. side note: we are thinking about replacing it with Codemirror which is now native to WP.

thanks.

**Comment by pingram3541** [comment]
@bainternet Ah ok, fair enough, it grows as you use it.  I had tried a few different sites at random and tried dragging (before adding content) the bottom right handle to drag and all had the same result, no resize.

+1 for codemirror, I am very familiar with that library as I've built it into many projects, I especially like it's modularity and fun stuff you can do with emmet.io
