### ISSUE TITLE
Add dynamic data for text color and background color options in Heading and post grid widgets

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [elementor/elementor#9440]
See the screenshot here: [(https://imgur.com/a/OJWG0K3)]

This will greatly expand the ability to style block lists and improve usability.
For example: this feature allow to display colored labels for post grid. Colored categories and tags etc.

**Comment by bainternet** [comment]
I merged this issue with  #6485, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
