### ISSUE TITLE
roles of users.

### ISSUE THREAD

**Issue by ber41** [elementor/elementor#9441]
Hi,

I think that for people like me and working better with my clients a new important feature should be to limit the role of users.
I know there is already a function to prohibit or allow access to Elementor's tools. But there should be something else, an intermediary.

1- It would be necessary to be able to authorize the users to modify the pages with the tools only used in the page but to hide the others.
But by allowing the right click to duplicate the sections to complete the pages.

2- Or only the Elementor utils used in the creation of the site, but hide the others. But by allowing the right click to duplicate the sections to complete the pages.

3- What would be wonderful is to be able to select the tools to display or not for customers.

With these 3 cases plus what is already possible, it gives a better possibility to manage the work and the users according to their competences.

With all this the webmasters keep the control of the site, give more or less functions to the customers users. That way they do not destroy everything and they fotn call the webmaster for if they want additional functions.

I do not know if it's very clear but I think it's useful.

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.18.0, and improved with Elementor Pro 3.19.0! 🥳 

You can now use the Element Manager to decide what widgets should appear in the Editor and your website, and with Elementor Pro you can decide who can use those widgets. To learn more check the [documentation in the Help Center](https://elementor.com/help/element-manager/).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
