### ISSUE TITLE
Add close option for CTA

### ISSUE THREAD

**Issue by Ohaithere55** [elementor/elementor#9442]
I would like to add a close option to my call-to-action window. 
By any chance, does anybody know how I can enable this or use some additional code in order to do so?

The other option would be to create a popup and make the rest of the page available while the popup is out there.

Kind regards,
Thomas

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
