### ISSUE TITLE
Allow Custom Icons & Fonts to be used on non-elementor pages

### ISSUE THREAD

**Issue by bitojoe** [elementor/elementor#9446]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There are times when I'd like to use a custom icon or font on a non-elementor page, such as woocommerce pages. The problem is that the styles / scripts only load on the conditional that an elementor icon widget is in use on the current page. I believe this is to increase performance but it would nice for there to be an override feature.

**Describe the solution you'd like**
I believe it would be ideal for there to be an override switch within the custom icon/font detail page where one can set the icon / font to be loaded on all pages rather than just elementor pages.

**Describe alternatives you've considered**
Re-enqueueing the icon pack (fontello) / font via functions.php and custom styles... but if they are already loaded elsewhere on the site, then why not make use of that.

**Additional context**
I keep mentioning fonts within this message but have actually only experienced it with icons as I load all my custom fonts (local, google fonts, typekit) through functions.php - However, I'd be less likely to do this if I knew the fonts / styles would load on all posts/pages regardless if elementor is in use or not.

**Comment by bainternet** [comment]
@bitojoe 

You are correct, Elementor only enqueues the fonts (both textual and icon fonts) when they are actually used via Elementor on that page for performance.

the alternative is to manually enqueue the icon fonts (e.g via functions.php) but if you do that using the exact same handle that elementor uses, then it will only be enqueued once per page regardless if it's used via elementor or not.

You the handle elementor uses for your custom icon font is usually `elementor-icons-{ICON_SET_NAME}` but to be sure I suggest that you create a new page and add an icon from that set to that page via Elementor's Icon widget, then view that page and look at its source and look for `elementor-icons-` to get the exact handle.

Now once you know that handle you can easily enqueue it via your functions.php with something like this.
```PHP
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_script( 'elementor-icons-{ICON_SET_NAME}' );
}, 100 );
```

Hope this helps.
