### ISSUE TITLE
Media Carousel widget not working properly on iPad

### ISSUE THREAD

**Issue by jackslayer1234** [elementor/elementor#9452]
Hi there, I face an issue with the Media Carousel widget. This is what I see: https://i.imgur.com/HeMHrF8.gif. I used Google Chrome's responsive viewer and viewed it as an iPad. The same issue occurs when I use Firefox's responsive viewer and view it as an iPad. Thank you.

**Comment by lior-sh** [comment]
Hi @jackslayer1234,

Thanks for reporting, we couldn't reproduce the issue we need more info.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
