### ISSUE TITLE
License renawal FLOOD

### ISSUE THREAD

**Issue by shirokoweb** [elementor/elementor#9458]
Why do you flood installations with renewal notices ?????

Admin area, builder area... only missing is to email our final customers to tell them their developer has 30 left to renew license.

This FREAKS our customers out for nothing! Already got dozen emails from clients asking me if their site will continue to work !!!

This is insane and is unacceptable. We run a company with VAT, and if we don't renew 30 in advance, is because we have legit reasons not to.

When you purchase a PRO license and got dozen installations, it means you build websites for FINAL customers. Why would you include em in a License matter they are not concerned by ???

**Comment by black-eye** [comment]
Agreed, the notices are way too intrusive and, moreover, without an option to close!  I’ve send several mails to your support concerning this matter and the answer was, it’s for my good, so I won’t forget! Please! Let me manage my memory and payment schedule by myself and try to be less obvious with your “give us your money already” intention. ;-)

**Comment by shirokoweb** [comment]
> Agreed, the notices are way too intrusive and, moreover, without an option to close! I’ve send several mails to your support concerning this matter and the answer was, it’s for my good, so I won’t forget! Please! Let me manage my memory and payment schedule by myself and try to be less obvious with your “give us your money already” intention. ;-)

Precisely, I don't care about morrons and idiots, I don't have to suffer their lack of seriousness, dedication or whatsoever. Got same answer from support:

> Thank you for contacting us.
> 
> It's an automatic message that goes away within 24-48 hours after your Elementor license is renewed. Unfortunately, it's not possible to remove the renewal notification as according to our records some customers indeed forgetting to renew the license.
> 
> I appreciate your understanding.

As a workaroud, I simply added display none to following css:

#elementor-notice-bar, .notice.elementor-message {
    display: none;
}

But I can't do it for every website...

Another option would be to use a script:

var element = document.getElementById("elementor-notice-bar");
element.parentNode.removeChild(element);

**Comment by shilo-ey** [comment]
Hi @shirokoweb 

Based on this community request we decided since v2.6 to hide all admin notices to roles besides Administrator role.

We try to enforce misusing of Elementor Pro, and improve the way our users interact with their account on Elementor website.

Only Administrator are seeing those messages until the account is connected/renewed. 

Simply keep your instances connected and valid and no other "hack" is needed.

Thanks

**Comment by bouveng** [comment]
It should not be shown on accounts that has auto renewal active.
