### ISSUE TITLE
DialogsManager events/hooks

### ISSUE THREAD

**Issue by macgyvercy** [elementor/elementor#9459]
It's a question about developer API. 

I am trying to run a function after this dialog (https://screenshot.net/dkgvyby) is shown. I read some codes but still can't figure out a solution.

I also tried to run my function after commands, routes (like `$e.route('library/save-template')`), ... but it seems I can't hook into them.

Any help is appreciated.

**Comment by macgyvercy** [comment]
@kobizz It seems it's built by you, any help is appreciated.

**Comment by iNewLegend** [comment]
Currently, hooks on routes are not available using `$e.hooks`, but you can hook it manually using
```
$e.routes.on( 'run:after', ( component, route ) => {
} );
```
