### ISSUE TITLE
Add Fade Effect to Section Background Video Loop Cycles 

### ISSUE THREAD

**Issue by kcwebguy** [elementor/elementor#9461]
I would like to suggest that a new feature be added to the section background video widget. 

I frequently run shorter videos as backgrounds... when the video loops and starts over it is a hard restart. 

This request is that there be added the ability to loop with a fade in effect where the end of the current loop cycle fades out as the start of the next loop cycle fades in. 

I would like to be able to set the timing of the fade in seconds from 0 to X seconds.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
