### ISSUE TITLE
Open Accordion by clicking on a link in Elementor

### ISSUE THREAD

**Issue by spiritbeatz** [elementor/elementor#9462]
Maybe I chose the wrong section - sorry. I have question.
How to make an accordion open by clicking on a link in a map? I studied the code, found the id element of the block and content tab. When I click on any icon on my map, I move to the necessary accordion (by the way, not quite to the necessary), but I move, but the accordion does not open, how can I open it?

http://elementor.echotag.net/products/ 

you can try clicking on the yellow EchoAdBroadcast icon on the left and I would like the accordion on the right to open

**Comment by bainternet** [comment]
@spiritbeatz 

You can catch the click event of your svg links and trigger a click on the accordion title since they have the same anchor as the selector, ex:

```js
jQuery( 'YOUR_SVG_SELECTOR' ).find( 'a' ).on( 'click', function() {
	const selector = jQuery(this).attr( 'xlink:href' );
	jQuery( selector ).click();
});
```
in you case:
```js
jQuery( '#_x23_Layer_1' ).find( 'a' ).on( 'click', function() {
	const selector = jQuery(this).attr( 'xlink:href' );
	jQuery( selector ).click();
});
```

hope this helps.

**Comment by spiritbeatz** [comment]
> @spiritbeatz
> 
> You can catch the click event of your svg links and trigger a click on the accordion title since they have the same anchor as the selector, ex:
> 
> ```js
> jQuery( 'YOUR_SVG_SELECTOR' ).find( 'a' ).on( 'click', function() {
> 	const selector = jQuery(this).attr( 'xlink:href' );
> 	jQuery( selector ).click();
> });
> ```
> 
> in you case:
> 
> ```js
> jQuery( '#_x23_Layer_1' ).find( 'a' ).on( 'click', function() {
> 	const selector = jQuery(this).attr( 'xlink:href' );
> 	jQuery( selector ).click();
> });
> ```
> 
> hope this helps.

Thank you bainterne ,  
I am trying to use this script but it does not work, should I change something in the code? 
To activate the script, I added this code to functions file , function load_js_assets() {
    if( is_page( 1450 ) ) {
        wp_enqueue_script('myscript', 'http://elementor.echotag.net/myscript.js', array('jquery'), '', false);
    } 
}

add_action('wp_enqueue_scripts', 'load_js_assets');

**Comment by spiritbeatz** [comment]
> @spiritbeatz
> 
> You can catch the click event of your svg links and trigger a click on the accordion title since they have the same anchor as the selector, ex:
> 
> ```js
> jQuery( 'YOUR_SVG_SELECTOR' ).find( 'a' ).on( 'click', function() {
> 	const selector = jQuery(this).attr( 'xlink:href' );
> 	jQuery( selector ).click();
> });
> ```
> 
> in you case:
> 
> ```js
> jQuery( '#_x23_Layer_1' ).find( 'a' ).on( 'click', function() {
> 	const selector = jQuery(this).attr( 'xlink:href' );
> 	jQuery( selector ).click();
> });
> ```
> 
> hope this helps.


Accordions do not open.
