### ISSUE TITLE
GDPR compliant cookie banner

### ISSUE THREAD

**Issue by Bartechnika** [elementor/elementor#9465]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor websites are not currently 100% GDPR compliant. This is because GDPR requires that users give their consent to cookies before they are loaded on a site. It is currently not possible to do this with elementor.

**Describe the solution you'd like**
I would like a feature added that gives an option to disable cookies when the website is loaded and then enable them again with a button press or other action. This could be in a specific widget dedicated to cookie banner popups or just another button press action.

**Describe alternatives you've considered**
The only other solutions I have found are third party WordPress plugins.

**Additional context**

**Comment by AertHulsebos** [comment]
This is the way to go to provide a general solution, and consent layer. Applicable to different regions and privacy laws; https://github.com/elementor/elementor/pull/12567

**Comment by Bartechnika** [comment]
> This is the way to go to provide a general solution, and consent layer. Applicable to different regions and privacy laws; #12567

Hello. Thankyou so much for your reply, I will take a look!
