### ISSUE TITLE
ResearchGate icon is rendered wrong in Reviews Widget

### ISSUE THREAD

**Issue by marceloaof** [elementor/elementor#9467]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In Reviews Widget of Elementor Pro, the "ResearchGate" icon is rendered as a gray block of square in default size. Expanding the icon makes no better result.
Expected behavior: a [readable and green official icon](https://camo.githubusercontent.com/20302dbecb13e03c63ecae7d07c694696c66da19/68747470733a2f2f6c68342e676f6f676c6575736572636f6e74656e742e636f6d2f2d32387046764c35337576552f41414141414141414141492f41414141414141414163452f65446a3275473750574b732f73302d632d6b2d6e6f2d6e732f70686f746f2e6a7067).

## Steps to reproduce
Create a Reviews widget. In Slide 1, select Icon "ResearchGate". There you have it, a gray squared icon.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@marceloaof 

ResearchGate is not included in the "Recommended" Icons for this widget, hence it has no support for its official colors, we do however allow adding any Icon you want but you will have to take care of its styling, which in this case using custom CSS is simple and short:

```CSS
selector .fa-researchgate {
	color: #0cb;
}

hope this helps.

**Comment by marceloaof** [comment]
@bainternet 
Thank you, but the color was just a suggestion...
The real issue here is the icon provided by Elementor not being rendered in a proper way. **Right not we have a block of square** icon, instead of anything similar to ResearchGate.

Real example:
![researchgateworng](https://user-images.githubusercontent.com/55504889/68535310-1fc38c00-031f-11ea-9fd2-6de635272eb7.png)

**Comment by marceloaof** [comment]
@bainternet Please, look into this, sir.
