### ISSUE TITLE
Product Search Widget

### ISSUE THREAD

**Issue by CohenAvraham** [elementor/elementor#9468]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I convert all my websites from their current themes & plugins and would like to use Elementor. Some of these websites have WooCommerce, and as such I will need to have the product search box. 
So, I would like to have a Product Search Widget that I will be able to design manually (colors, styles and etc;...)- this will be like the Search Form Widget you did. 

**Describe the solution you'd like**
Currently, I will use the Search Form widget, or the Product Search Widget (by WP) but none of the options brings me the outcome I want. 

**Describe alternatives you've considered**
As said, I will try to use the Search Form widget, or the Product Search Widget (by WP) 

**Additional context**
I want to convert all my websites to Elementor, however, since the Product Search box in the current templates the website have, prevent it from looking the way its needed.

**Comment by bainternet** [comment]
@CohenAvraham 

We have added action hooks (`elementor_pro/search_form/before_input`, `elementor_pro/search_form/after_input`) in the search widget so you can utilize them to set the post type to `product` so the search result will consist of products only, ex:

```PHP
add_action( 'elementor_pro/search_form/before_input', function() {
	?><input type="hidden" name="post_type" value="product"><?php
} );
```

hope this helps.
