### ISSUE TITLE
Nav Menu "Hamburger" Icon is Wrong.

### ISSUE THREAD

**Issue by amrilling** [elementor/elementor#9469]
Hello, 

I've noticed that the Hamburger Menu icon on the nav menu for mobile is actually the "numbered list" icon (fas fa-list-ol). I don't see a setting to switch it to a normal "hamburger menu" icon, and I have clients getting upset that their menu icon is actually a numbered list. 

Please look into this, I'm sure it's a simple fix!

<img width="445" alt="Screen Shot 2019-11-02 at 6 51 11 PM" src="https://user-images.githubusercontent.com/57303751/68077930-0fe9fc00-fda3-11e9-9b2c-d15954fe97d4.png">

**Comment by shilo-ey** [comment]
Hi @amrilling 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

From past issues submitted here, it is usually a cache problem. 

Thanks.
