### ISSUE TITLE
MEC

### ISSUE THREAD

**Issue by JessicaParler** [elementor/elementor#9474]
Hello guys, 
I was reading the issues and they were very much like the one I had. The best solution I could find was the modern events calendar and I highly recommend it to ya all.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
