### ISSUE TITLE
how to use event for elementor button?

### ISSUE THREAD

**Issue by bilalbutt** [elementor/elementor#9478]
I'm building a custom Elementor Widget for one of my client I have used button, when clicked upon should change values in the fields below it. See https://i.imgur.com/HAuM3uZ.jpg for details.

**Comment by oddlots** [comment]
I am also trying to sort this out. As of right now the breadcrumbs are leading me to [needing to use javascript to listen for the event](https://github.com/elementor/elementor/issues/5153#issuecomment-407053063) and then it's likely you'll have to do some jQuery to insert your desired values.

**Comment by bainternet** [comment]
@bilalbutt 

When you add a button control you can set an event name to be triggered and then add a listener on that event to do whatever you need, ex:

```PHP
$this->add_control(
	'my_button',
	[
		'type' => \Elementor\Controls_Manager::BUTTON,
		'label' => '',
		'text' => 'Click Me',
		'event' => 'MyClickEvent',
	]
);
```

```JS
elementor.channels.editor.on( 'MyClickEvent',() => alert( 'This is where you do your stuff') );
```

Hope this helps.

**Comment by nimaaminz** [comment]
> @bilalbutt
> 
> When you add a button control you can set an event name to be triggered and then add a listener on that event to do whatever you need, ex:
> 
> ```
> $this->add_control(
> 	'my_button',
> 	[
> 		'type' => \Elementor\Controls_Manager::BUTTON,
> 		'label' => '',
> 		'text' => 'Click Me',
> 		'event' => 'MyClickEvent',
> 	]
> );
> ```
> 
> ```js
> elementor.channels.editor.on( 'MyClickEvent',() => alert( 'This is where you do your stuff') );
> ```
> 
> Hope this helps.

Not working for please explain more or tell another solution !
