### ISSUE TITLE
Custom query in Elementor Archive Post template

### ISSUE THREAD

**Issue by Akaaal** [elementor/elementor#9484]
Hi,

I'm posting my request here, as Elementor Support advised me to do.
I'm working on the blog of [my website](https://staging.stage-kungfu-chine.fr/actualites/). In the native behavior of WP, posts from child category will also be displayed under the parent category. With little piece of code,

```
<?php 
  if ( is_category() & !is_category(23)  ) {
  $cat = get_query_var('cat');
  query_posts(array('category__in' => array($cat)));
  }
?>
```
I've found an easy way to excluded the posts that are not directly related to their parent category. I'm using hello elementor theme and put this code in archive.php

```
/**
 * The template for displaying archive pages.
 *
 * @package HelloElementor
 */

[...]
<div class="page-content">      
<!--custom code-->
    <?php 
      if ( is_category() & !is_category(23)  ) {
      $cat = get_query_var('cat');
      query_posts(array('category__in' => array($cat)));
      }
    ?>
<!-- end custom code-->
        <?php
        while ( have_posts() ) {
            the_post();
            $post_link = get_permalink();
            ?>
            <article class="post">
                <?php
                printf( '<h2 class="%s"><a href="%s">%s</a></h2>', 'entry-title', esc_url( $post_link ), esc_html( get_the_title() ) );
                printf( '<a href="%s">%s</a>', esc_url( $post_link ), get_the_post_thumbnail( $post, 'large' ) );
                the_excerpt();
                ?>
            </article>
        <?php } ?>
    </div>
[...]
```
Now I want to design all the categories pages using elementor archive template. Of course I know that elementor will stop using the archive.php, so what can I do with that code in order to get it works with elementor archive template ?

Thx for reading
Bye. 
Akal

**Comment by bainternet** [comment]
@Akaaal 

This really has nothing to do with elementor and a lot to do with the way you modify the Query of the category.

instead of modifying the query directly in your archive.php file you should use the `pre_get_posts` hook in your functions.php file to do that, ex;

```PHP
add_action( 'pre_get_posts', function( $wp_query ){
	if ( $wp_query->is_main_query() &&  $wp_query->is_category() & ! $wp_query->is_category(23)  ) {
      $cat = get_query_var('cat');
      $wp_query->set( 'category__in', [ $cat ] );
    }
});
```

thanks

**Comment by Akaaal** [comment]
Hi, thx for your reply, the code you provide doesnt work but I understood this is not the right place to discuss about it. So thanx for the approach, I'll discuss about how to make your code works for me in another place. Best regards. Akal
