### ISSUE TITLE
Change image on hover

### ISSUE THREAD

**Issue by sonnesworld** [elementor/elementor#9485]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

It would be great if there's a function like "change product image for product lists on hover". Like this plugin which doesn't work with elementor: https://de.wordpress.org/plugins/woocommerce-image-hover/

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by yossicahen** [comment]
+1

**Comment by boghy933** [comment]
Hello, i would like this feature to.
Thanks 🍻

**Comment by BoBella** [comment]
Yes, please

**Comment by mdfoo8** [comment]
Yes please

**Comment by flashforge-wiesbaden** [comment]
14 months after sonnesworld's request, I am wondering if this feature will come in the near future?

**Comment by flashforge-wiesbaden** [comment]
14 months after sonnesworld's request, I am wondering if this feature will come in the near future?

**Comment by Alisa-khodadadi** [comment]
can you please add this feature  , it would be so useful

**Comment by ccmbrother** [comment]
+1

**Comment by LykPapa** [comment]
That would be a very nice feature indeed. :)
