### ISSUE TITLE
Feature request: Add section to multiple pages/posts at once globally

### ISSUE THREAD

**Issue by Bobolinos** [elementor/elementor#9492]
I would really like a feature where you can create a section and add it to multiple pages and/or posts at once at a certain part of that page (theme hook).

Beaver Themer has this option too and you can see it in the video below after 1 minute.
https://www.youtube.com/watch?v=1SOfekPyH7s

I also noticed that Hello Elementor theme does not a (a lot) of theme hooks for this to work (I think), for example: after_the_footer, before_the_header, after_the_body, before_the_comments

Beaver Theme [has those hooks](https://probeaver.com/beaver-theme-hooks/) where you can add your section to globally.

**Comment by bainternet** [comment]
@Bobolinos 

We have our own [Theme Locations API](https://developers.elementor.com/theme-locations-api/) which you can use the create unlimited  "Hooks" so you can place sections globally,

ex:

```PHP
add_action( 'elementor/theme/register_locations', function ( $elementor_theme_manager ) {

	$elementor_theme_manager->register_location(
		'above-header',
		[
			'label' => __( 'Above Header', 'theme-name' ),
			'multiple' => true,
			'edit_in_content' => true,
		]
	);
	$elementor_theme_manager->register_location(
		'bellow-header',
		[
			'label' => __( 'Bellow Header', 'theme-name' ),
			'multiple' => true,
			'edit_in_content' => true,
		]
	);
});
```

and to display it you can just call it in your theme files, located anywhere you need, ex:

```PHP
<?php
if ( function_exists( 'elementor_theme_do_location' ) ) {
	elementor_theme_do_location( 'above_header' ); 
}

// theme native
get_header();

if ( function_exists( 'elementor_theme_do_location' ) ) {
	elementor_theme_do_location( 'bellow_header' ); 
}
```

create a section and set its location to one of the locations you added.

Hope this helps.

**Comment by Bobolinos** [comment]
Hi, thanks, tested this but does not work. Added the codes to function.php and single.php and set the template of different pages to default, went to Theme Builder, added a new section to "Above the header" sitewide, but nothing shows up. Can you confirm this?

**Comment by Bobolinos** [comment]
Works now, sorry
