### ISSUE TITLE
Theme Builder Conditions Allow Filter of $post_types

### ISSUE THREAD

**Issue by pingram3541** [elementor/elementor#9493]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

There actually are many similar requests here but not worded in a developer centric way.  This also seems like a fairly low level code inclusion to simply add a filter.

Looking through the code it does not appear there is any way to inject our own "non-public" post types to the Theme Builder which prevents or makes difficult the assigning of Elementor templates to said post types.

This will be a huge game changer for LMS and private membership post types and archive pages.  Currently this is a painful process because one has to use traditional php templates which muddies up the development tasks where some of the theme is provided by Elementor and other parts exist as raw code.

Thanks for giving this any consideration!

**Comment by bainternet** [comment]
@pingram3541 

We actually have a filter for that in place: `elementor_pro/utils/get_public_post_types` ex:

```PHP
/**
 * Add Learndash lesson post type support
 */
add_filter( 'elementor_pro/utils/get_public_post_types', function() {
	$post_types['sfwd-courses'] = 'Courses';
	$post_types['sfwd-lessons'] = 'Lessons';
	$post_types['sfwd-quiz'] = 'Quizzes';
	$post_types['sfwd-topic'] = 'Topics';
	return $post_types;
} );
```

thanks.

**Comment by pingram3541** [comment]
FYI @bainternet this works great but without passing the original $post_types object, instead of adding new post types to the existing object, it replaces it with a new object with only the post types you pass to this filter.

```
/**
 * Add Learndash lesson post type support
 */
add_filter( 'elementor_pro/utils/get_public_post_types', function( $post_types ) {
	$post_types['sfwd-courses'] = 'Courses';
	$post_types['sfwd-lessons'] = 'Lessons';
	$post_types['sfwd-quiz'] = 'Quizzes';
	$post_types['sfwd-topic'] = 'Topics';
	return $post_types;
} );

```

**Comment by pingram3541** [comment]
Update, passing the $post_types object inside the function params and returning it is required for this to work.
