### ISSUE TITLE
How to design product quantity field in woocommerce in elementor

### ISSUE THREAD

**Issue by Haeshkumar** [elementor/elementor#9497]
Hi, I need your help , I create 1 group project and also create 4 simple project and these 4 simple products I added to group products. and when I click to group product it will show me those 4 simple products. Great Now I want to design product quantity field. Please help me how can I design

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
