### ISSUE TITLE
✅ 🚀 Feature Request: Support 3rd party and WordPress native meta fields in Elementor's Star Rating Widget

### ISSUE THREAD

**Issue by smileBeda** [elementor/elementor#9499]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor offers a star rating Widget which can be populated with Dynamic data coming from (amongst others) Custom Fields. However only ACF fields seem supported.

**Describe the solution you'd like**
Several users seem to want to use Toolset Custom Fields or other fields (for example WordPress Core meta fields)

**Describe alternatives you've considered**
There is no alternative. The Widget requires proprietary integration for each software registering Fields.

You can make a very simple test:
Register a Custom Field with any other tool (WordPress core features, custom code, or a plugin) and check if the Star Rating Widget of Elementor does show the fields.
If it does it's because Elementor added specific support for that field (or tool you use) for that particular widget.

I've taken the time and made those tests and created several fields with different tools.
- ACF Field, which I then was able to see in the Elementor Star Rating widget, which means support for ACF in that Widget was added.
- Simple Custom Field with core WordPress features, which does not appear in the Widget.
- Simple Custom Post Type Custom Field Plugin (https://de.wordpress.org/plugins/simple-content-construction-kit/), which does not appear in the Widget.

It should hence be safe to say, that for those Custom Fields to appear in the Star Rating Widget, a specific support for it needs to be added in Elementor's Code base, as the test above shows.

You can do that test on your sites as well by activating Custom Fields in the single post you edit (in WordPress that's done with the "Screen Options" if you use classic editor or the cog/wheel and then > options > custom fields if you use Gutenberg) or using the plugins I suggested, they are free.

**Comment by kaan81** [comment]
I'm an Elementor Pro user and I would like to use Elementor Widget while getting the data from Dynamic sources. Currently Toolset fields are NOT listed as an option under the dynamic field.

Fixing this problem will be highly appreciated.

**Comment by lswee** [comment]
Could I please check on the progress of this?

If I manually enter the number '4.25' into the Star Widget, it displays this correctly, however when it receives the same thing from JetEngine, it displays a full 5-stars.

When I hover over the 5-stars, the text pop-up displays '4.25/5', so the right data _is_ coming in from JetEngine, it's just not being displayed or interpreted correctly by the Star Widget.

I've tested it and can confirm that (for JetEngine) it curretnly only works with inegers and .5s

**Comment by nicholaszein** [comment]
Hello guys!

Thank you so much for your patience! 🙏 

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved with the release of the new Rating widget in Elementor v3.17! 🥳 

With this new widget, you have more options to choose the number of rating points, custom icons, and styling options, and it is fully compatible with Google Rich snippets (updated) and fully accessible. The rating field also accepts some Dynamic Tags if you're using Elementor Pro.

Your current Start Rating widgets will remain as they were before this update. But moving forward, only the new Rating widget will be available to add to your layouts.

If you are using the old Star Rating widget, we would recommend that you replace it with the new Rating widget.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
