### ISSUE TITLE
Use select option text instead of value in repeater title_field

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#9501]
Hello,

I have a repeater field with a select inside. I want to use the selected option text as the repeater group title (not the option value).

As of today, it seems to be impossible.

By checking some of your widgets, I see that you can use Mustach code in the title_field value like:

`'title_field' => '<i class="{{ elementorPro.modules.shareButtons.getNetworkClass( button ) }}" aria-hidden="true"></i> {{{ elementorPro.modules.shareButtons.getNetworkTitle( obj ) }}}',`

Because Elementor is React based, this code is probably executed in a context (the for loop of repeater items).

So, would it be possible for you to add us an helper like `elementorPro.helpers.getRepeaterSelectFieldText(repeater_item, 'control_key')`?

**Comment by bainternet** [comment]
@tristanleboss 

Few Corrections:

* Elementor is not React based. (not yet anyway :) )
* You can use https://underscorejs.org/#template with curly braces as an interpolate.

Basically you can create your own helper functions to render/ get whatever you want, and the simplest way would be to hold the options in that helper ex:

```js
function myHelper( value ) {
	const labelValues = {
		value1: Label1,
		value2: Label2,
	};
	return labelValues[value] ? labelValues[value] : 'default';
}```
```

and you could use it: 
```PHP
'title_field' => '{{{ myHelper( control_key ) }}}',
```

Hope this helps.
