### ISSUE TITLE
AMP with Elementor PRO Plugin

### ISSUE THREAD

**Issue by pedromvf** [elementor/elementor#9503]
Hello! 

I am a PRO Member and i need know when the Support TEAM will luch a Google AMP Solution?

How can i fit my site in AMP format? I really love Elementor and i wan't leave or change to WpBakery (wich has AMP compatible plugins).

Thanks for all!
Pedro Henrique

**Comment by ingoratsdorf** [comment]
Not sure what you are after. All works and verifies in google search console under AMP, at least mine does. What is NOT working? Or what feature are you missing?
Guess it would depend on your AMP plugin.

**Comment by pedromvf** [comment]
Hi! I'm sorry, I haven't expressed myself very clearly. 
I am looking for a solution "Click and Go", because I'm new to programming. What plugin do you use?

Thanks very much for your attention.
Pedro.

**Comment by ingoratsdorf** [comment]
I use AMP for WP. Works better for me than the official Wordpress AMP plugin. If you go pro, there's also a plugin for Elementor support (https://ampforwp.com/amp-pagebuilder-compatibility/). Together with "Schema & Structured Data for WP" you get a pretty good coverage.

**Comment by abbeygrimes** [comment]
Anyone know of any free AMP plugins that are compatible with Elementor? Trying to use weeblr AMP and running into issues on our [custom sock website](https://custom.sockclub.com/).

**Comment by alexplayer** [comment]
@abbeygrimes What issues do you have? 
I'm running AMP with Elementor PRO, and it works very very well. I tried that Amp for WP prior to using the free Wordpress AMP plugin, but I don't see why it costs $140 a year, when the free plugin works fine, if not better. Currently running is on my website - http://eggheaddesigns.co.uk/ .. I have a couple of none amp pages (ie the contact page, and a page where I have a chat bot - as I need the JS to run there, aside from that, works well.

**Comment by mredodos** [comment]
pls optimize or integrate elementor with amp official plugin!

**Comment by mredodos** [comment]
> Anyone know of any free AMP plugins that are compatible with Elementor? Trying to use weeblr AMP and running into issues on our [custom sock website](https://custom.sockclub.com/).

you can use the official and run reader mode for use 2 different theme and different page. or you trty with use astra template and elementor. amp for wp is the only have a full compatibility with elementor and amp tech but is not free
