### ISSUE TITLE
Header Template removes Footer

### ISSUE THREAD

**Issue by wpsoul** [elementor/elementor#9507]
Latest version which I use has critical bug for me.

When I create Header layout and set it on entire site, it also removes Footer (everything from get_footer()), so, I must create Footer template also. But I want to use default footer from theme, which is not possible now.

And opposite, if I create Footer Template, it also removes Header of theme

I tried several themes, including default Twenty theme - the same issue. 

I deactivated all plugins, except Woocommerce. So, it's not plugin's incompatibility

I checked on few sites and on local server - the same issue.

**Comment by shilo-ey** [comment]
Hi @wpsoul 

Thanks for your feedback.

Unfortunately, we can't reproduce your issue.

If the issue persists, please contact our support for further assistance.

Thanks
