### ISSUE TITLE
Insert custom meta in archive template

### ISSUE THREAD

**Issue by barrycrous** [elementor/elementor#9508]
Hi guys,

We've set up a custom post type that has a text-based "Location" custom field:

![image](https://user-images.githubusercontent.com/1662545/68367611-bedd5d80-013e-11ea-9673-cfaaf434fd42.png)

Ideally we'd like to dynamically include this custom field in an archive template using the Archive Posts or Posts element:

![image](https://user-images.githubusercontent.com/1662545/68367964-96a22e80-013f-11ea-9755-14cc863bdae5.png)

This feature should greatly improve the customization options for archives.

Cheers

**Comment by shilo-ey** [comment]
I merged this issue with  #4440 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
