### ISSUE TITLE
Elementor Loading Font even when typography setting is not loaded

### ISSUE THREAD

**Issue by nirbhay18** [elementor/elementor#9520]
![image (6)](https://user-images.githubusercontent.com/2735045/68383362-86a84000-017b-11ea-868a-d367201ae291.png)
![image (5)](https://user-images.githubusercontent.com/2735045/68382972-c28ed580-017a-11ea-9b71-243bdcf61978.png)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am Nirbhay and I work as a Customer Happiness Engineer for PowerPack for Elementor at IdeaBox Creations.

Recently while handling a client issue for our Off-Canvas Content Widget I came across an issue. In our Off-Canvas Content Widget, we used to provide typography options for anchor tags in the case of custom and sidebar Content-Type. When the user selects Saved Section then these options are not available anymore. The issue that is happening is that the anchor tag font is still loading on the published page while it should not.

## Steps to reproduce

Please check the attached screenshot for the code I am referring too.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@nirbhay18 

We can't replicate without seeing the full code are more details,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
