### ISSUE TITLE
Elementor Page Template and Code Disappearing 

### ISSUE THREAD

**Issue by Jenn0014** [elementor/elementor#9521]
Hi All, 

Since the latest Wordpress update, I am having consistent problems with my ELemento page templates. 

Most of my pages Elementor layout have disappeared and left only text. I have got some of the pages back by going back to previous revisions, however after saving they look fine then a short time later again the layout disappears and only text shows.

I ave tried Regenerate CSS on Elementor and clearing cache on my server but this seems to make no difference. Can anyone help?

An example of one page effected is https://stepscotland.co.uk/funding-support/innovation-vouchers/. 

Thanks in advance, 
Jenn

**Comment by rahul404error** [comment]
I am also facing the same issue. All the Elementor Blocks have turned into one text editor.

 It would be great if anyone has a solution!

**Comment by Jenn0014** [comment]
I managed to resolve this. It seems that there was a conflict error with my lets encrypt. My hosting provider had to turn it off. I then had to revise all effected pages back to a revision and save.

**Comment by shilo-ey** [comment]
@Jenn0014 
Thanks for sharing your inputs.

@rahul404error Hope that solves this for you as well

Thanks
