### ISSUE TITLE
Search bar for accordion content

### ISSUE THREAD

**Issue by jackslayer1234** [elementor/elementor#9524]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have multiple accordion sections on my FAQ page. Is it possible to have a search bar that can search the content of the accordions only?

Elementor has a search bar element but it will search the entire website.

**Describe the solution you'd like**
I will like a search bar that can search for contents of accordions only. That way users can search through the FAQs based on keywords.

**Describe alternatives you've considered**
I do not have an alternative to propose. Currently, I leave my site as it is.

**Additional context**
Thank you Elementor team. Love your plugin!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by HQRaja** [comment]
Would love to get this feature where a search box can be used to filter accordion content and show only the matching items.

**Comment by alex-rybachenk0** [comment]
Are there solutions? I need a search like this.

**Comment by agungsp2000** [comment]
its been 2 years, please implement this feature 🙏

**Comment by elfilalime** [comment]
its been 3 years, please implement this feature

**Comment by tapasfun** [comment]
I also looking for this feature. Should be an option to choose AJAX search and In page content search only. Like Accordings, section, posts etc.

**Comment by MathiasKirkegaard92** [comment]
Please implement this! Would be very helpful

**Comment by itsadityasharma** [comment]
Finally Found [this solution ](https://theplusaddons.com/docs/elementor-accordion-search/)for Elementor Accordion Search.

**Comment by unitedonline** [comment]
It has been 4 years.
IMHO This is an important feature.
Would you please be kind enough to implement this feature on your next update?

**Comment by Lindorndiaye** [comment]
@unitedonline @HQRaja @bainternet @agungsp2000 @tapasfun I was looking for this feature and came across this discussion. I propose a version in html css ajax and js which perfectly meets what we are looking for only you have to have some knowledge of coding find this project in my profile and give me feedback. we can improve it together.
Link : https://github.com/Lindorndiaye/accordeon-with-ajax-search-elementor/tree/main/FAQ%20github
