### ISSUE TITLE
How do I get the values of the custom widget Elementor and pass them to a JS file?

### ISSUE THREAD

**Issue by UrchenkoV** [elementor/elementor#9526]
Hello.
How to create your widget for Elementor and pass settings to JS file to manage Swiper Slider plugin.
They have what the its method, but in documentation normal instructions there is no.
Here is, that found on topic, but there, too, there is no answer on this question:

https://github.com/elementor/elementor/issues/4968
https://github.com/elementor/elementor-hello-world/blob/master/assets/js/hello-world.js
https://github.com/elementor/elementor/issues/5476
https://code.elementor.com/js-hooks/

Thanks.

**Comment by shilo-ey** [comment]
We created documentation regarding creating new widgets
https://developers.elementor.com/building-a-simple-custom-widget-with-javascript/
and adding JS in your custom widgets. https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/
I hope that figures the issue for you.

thanks

**Comment by UrchenkoV** [comment]
@shilo-ey The examples you gave don't fit, they just pass a selector. 
I am interested in how to transfer settings for a custom widget Swiper. That is, the playback speed, pause on hover and so on. 

How to do this?
