### ISSUE TITLE
Dynamic Content is Not Working with the Reviews Widget by Elementor

### ISSUE THREAD

**Issue by nirbhay18** [elementor/elementor#9527]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The Dynamic Content feature is not working with link settings in the Reviews Widget.
![screenshot-ibxtest kinsta cloud-2019 11 08-16_10_54](https://user-images.githubusercontent.com/2735045/68470817-d56cdd00-0242-11ea-8672-4487928fde76.png)

## Steps to reproduce

1. Add Reviews Widget
2. Use dynamic content to set the link
3. Publish and Click the Reviews to check the issue

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.2

Feel free to update

Thanks!
