### ISSUE TITLE
Add 3rd-party widget's company name in its footer

### ISSUE THREAD

**Issue by joecodino** [elementor/elementor#9528]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If you use some 3rd-party widgets, often is not so easy to understand which widget really is on the page. Try to use a 3rd-party Video Player, a widget always present in any 3rd-party Elementor plugin, and you probably cannot understand which video widget you dropped on the page... Is it from Elementor Anywhere? Is it from Elementor Extra? Is it the standard Elementor video player?

**Describe the solution you'd like**
Place the 3rd-Party name on the bottom of the widget property window, e.g., where usually you place the "Need Help?" link.

**Describe alternatives you've considered**
Every place is good, if described somewhere in the Elementor Help

**Additional context**
![example](https://user-images.githubusercontent.com/16733755/68472799-9da16d80-0221-11ea-980f-7aa3c7aeb72e.png)

**Comment by shilo-ey** [comment]
Hi @joecodino 

Thanks for your feedback.

We do not control how 3rd party plugins extend Elementor.

If they would like to do so, this option is possible for them.

Thanks.
