### ISSUE TITLE
style_transfer control

### ISSUE THREAD

**Issue by vlthemes** [elementor/elementor#9532]
Hello team!

Let me know how to use style_transfer => true?

What is it for?

**Comment by bainternet** [comment]
@vlthemes 

The `style_transfer` parameter of a control is used to set its Copy & Paste behavior.

Each control that has a `selector/selectors` parameter is copied and pasted by default unless you set `style_transfer` to `false`.

Or if you want to define a control without a `selector/selectors` parameter to be copied and pasted then you need to set `style_transfer` to `true`.


Hope this helps.
