### ISSUE TITLE
Show a Specific "Hidden Block" After the Click

### ISSUE THREAD

**Issue by pedromvf** [elementor/elementor#9536]
Hello! I have a question and i would like your help, please! =D

I am a beginner in Web Design area, but i really happy because I found myself professionally. I am so grateful to have your support, thanks!

Lets go to te question:
This is my landing page: https://plantaocontabil.com.br/abrir-mei-landing-page

Close of the footer there is a Price Table and a button "Abrir MEI".

My idea: The leads see it and think "Yeah, i want it". 
So, they click on "Abrir MEI". 

*How can i show the FORM in this page (without redirect)?* I mean, how show a "block" after a click in "Abrir MEI" with  eForm (Form Subscription + Payment)?

How can i add it? Is there a resource in Elementor to do that? 

I need a block with a Form Subscription hidden until the click in "Abrir MEI". So, after a click the lead would see the subscription form on the same page, without redirect to another page to do that.

Again, thanks! :D
Pedro

**Comment by cuelholima** [comment]
What you've got isn't an issue but a need for support.
You must write a message in the following link and delete this one: https://elementorforum.com/chat/elementor-help-and-support.12/

**Comment by pedromvf** [comment]
Matheus H. Faria, where can I find the official support for that question?

Thanks.

**Comment by lior-sh** [comment]
Thanks,
Please create GitHub issues only for bugs reports and feature requests.
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Thanks!
