### ISSUE TITLE
Metadata Search

### ISSUE THREAD

**Issue by itookyourusername** [elementor/elementor#9538]
[x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )
What problem is your feature request going to solve? Please describe.

The search widget has 4 options for metadata to display in the results: Author-date-time-comments.

Describe the solution you'd like
I would like to see post_type as option/page_type as an option

Describe alternatives you've considered
Programming

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/6226 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
