### ISSUE TITLE
Reconfigurable Global Widgets that will NOT Affect Content of Other Instances

### ISSUE THREAD

**Issue by pauljoel** [elementor/elementor#9539]
A plugin or method to deploy multiple instances of a widget over an entire site that would be reconfigurable after deployment without affecting unique content such as text, links, media, etc. This is analogous to the HTML/CSS class selector.

As a start, basic widgets (unique content for each instance) for pages such as buttons (text, link), headings (text), text editor (text, media link), and images.(image, caption, link).

Elementor Pro has the Global widget but requires both content and beautification/configuration be the same for each instance. Yes, you can unlink it but then the beautification/configuration will not change when the Global widget is modified.

**Comment by arielk** [comment]
Please check this out: https://elementor.com/blog/introducing-theme-style/

Thanks for your feedback!
