### ISSUE TITLE
Popups must work in browsers that don't support flexbox

### ISSUE THREAD

**Issue by maitNoserYoung** [elementor/elementor#9540]
- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate. (There are bug reports, but this is a missing feature not a bug)
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Elementor Popup uses Flexbox to align the popup as stated by @shilo-ey in the following [post ](https://github.com/elementor/elementor/issues/7303). How ever older browser versions don't necesserily support Flexbox

So I see two possible ways to fix this. First option would be to include a Flexbox Polyfill in the Framework, how ever this might bloat the website a bit. The better solution in my opinion would be to add additional CSS, which uses the [@supports](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) key word to apply the flexbox layout only if flexbox is available. Else you could simply place the popup using absolute positioning relative to the body tag.

Of course one could simply load a polyfill by themself, how ever that would not solve the problem for other users. That for I think this is a badly needed feature.

**Comment by black-eye** [comment]
+1
Moreover, the problem is not limited to non-flexbox browsers. See: #8277 or https://wordpress.org/support/topic/popups-not-centering-on-mobile/

**Comment by Netzlichter** [comment]
Is there a solution for opening popups via IE11? There is nothing happening if I click on a button which points to a Elemenotr PopUp...

**Comment by kingfisher64** [comment]
Any news on this elementor guys? We need a fix. Not really an option to leave it :)

**Comment by maitNoserYoung** [comment]
I am honestly kind of let down by elementor. One would think, that the premium users of such a widely used pagebuilder would get some more attention by the devs...

**Comment by maitNoserYoung** [comment]
Here an idea to elementor devs: Define a default positioning by absolute values, that should be fairly easy to implement. Then if the browser supports CSS3 @support syntax (https://caniuse.com/#search=%40support) use the flexbox positioning, that is the default atm.

**Comment by Aviad-Herman** [comment]
Hi everyone.
Closing this old issue as Elementor stopped supporting IE.
Don't worry, other bugs mentioned here are still open.
