### ISSUE TITLE
Header Box Shadow Appear on Scroll

### ISSUE THREAD

**Issue by Tahor** [elementor/elementor#9555]
Hi everyone. 

I'm looking for CSS to insert into my header where when at the top of the page, the header is seamless with no box shadow. When you scroll down, a box shadow will appear below the header. An example of this can be found on tagmediaspace.com where you can see the box shadow appear on the bottom when you scroll. I've already gotten the transparent background to work based off a video created by Elementor found on YouTube, that's no issue. Website I'm working on is calicoastcbdstore.com

**Comment by lior-sh** [comment]
invalid issue report
----
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
