### ISSUE TITLE
IE browser problems with responsive images

### ISSUE THREAD

**Issue by cuelholima** [elementor/elementor#9559]
## Issue on IE - Previews
Preview on Opera (100% ok)

![image](https://user-images.githubusercontent.com/37085699/68764543-ac10d000-05f9-11ea-9b9e-1b134c8703fa.png)

Preview on IE

![image](https://user-images.githubusercontent.com/37085699/68764441-7c61c800-05f9-11ea-9de4-d77aa706c125.png)

## Description
Just when I insert a link on the image, they lose their responsive on IE. The tree images above are linked and the rest not.

- [ ] No responsive on IE with a linked image.

**Comment by lior-sh** [comment]
invalid issue report
----
Thanks for reporting,
It working fine for us.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help. 
Thanks.
