### ISSUE TITLE
[IE BROWSER ERROR] [FORM FIELD: ACCEPTANCE] One word by line

### ISSUE THREAD

**Issue by VIUNDESIGN** [elementor/elementor#9560]
## Prerequisites
- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description
![ie-explorer](https://user-images.githubusercontent.com/52358877/68767012-4421b000-0620-11ea-9d94-be39b84c39f2.PNG)
![elementor-acceptance](https://user-images.githubusercontent.com/52358877/68767013-4421b000-0620-11ea-9491-97c01873ca02.PNG)

Error de visualización en formulario en INTERNET EXPLORER.
Type: Acceptance.
-Check the images-

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Aviad-Herman** [comment]
Hi,
We have stopped supporting internet explorer.
Thanks for the feedback.
