### ISSUE TITLE
Elementor Carousel Custom Image Height not working

### ISSUE THREAD

**Issue by uliwest** [elementor/elementor#9561]
Hi,
I'm using an Elementor Carousel on this site:
https://essbarer-naturpark.de/carouseltest/
In Edit with Elementor view I can set a custom image height of for example 222px (that's what its set to currently) and it shows fine in edit view.
However after publishing the images are displayed in full height (650px)
When setting the image size to "Thumbnail - 150 x 150" it works fine also after publishing. Just not when I try to set a custom image height.
I spend hours trying to figure out what goes wrong.
Can anyone take a look at it?
Thank you!

**Comment by uliwest** [comment]
I figured it out it was a settings problem, unrelated to Elementor Carousel. The Site and Home URL was different (http and https).

**Comment by Tafmakura** [comment]
Worked for me as well
