### ISSUE TITLE
render_content filter on section element

### ISSUE THREAD

**Issue by KimchaC** [elementor/elementor#9564]
## Prerequisites
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have created a plugin that wraps a button and image to open a Thrive Leads 2-step lead gen popup.

Now I am trying to extend this to the section / inner section element so that a click on it opens the popup.

Unfortunately it seems like the filter `elementor/widget/render_content` is only applied to widgets and not to the section or even the column elements.

**Describe the solution you'd like**
The ability to apply filters to render_content of sections.

**Describe alternatives you've considered**
I considered using `elementor/frontend/the_content`, but have performance concerns about it.

**Comment by bainternet** [comment]
@KimchaC 

`elementor/widget/render_content` is a widget specific hook and is not triggered for columns or sections.

However, you can use one of the many action and filter hooks that are called for all elements including widgets columns and sections in the `print_element` method:

https://github.com/elementor/elementor/blob/385f50c840065e3c689bd62f08403ad3af5de41c/includes/base/element-base.php#L564-L642

thanks.
