### ISSUE TITLE
Protecting page content with builder_content_data and the posts template

### ISSUE THREAD

**Issue by jcbpl** [elementor/elementor#9566]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This is a [follow-up question](https://github.com/elementor/elementor/issues/8930#issuecomment-548841692) to advice from #8930, about using the `elementor/frontend/builder_content_data` instead of `elementor/frontend/the_content` to protect only the "main" part of the page.

The recommendation on that thread, to remove the hook after it runs, causes none of the templates on a page to be protected when the page contains the Elementor Pro posts template.

I suspect this has to do with how the posts template interacts with `WP_Query` and `get_queried_object_id`. I'm seeking guidance on behalf of a mutual customer, on how to protect pages that include the posts template.

I posted the comment below to the original issue but haven't received a response; the Elementor support team said to open a new issue:

> We updated our plugin back in September to use `builder_content_data` as recommended above, and we also added `remove_filter` to `memberful_wp_protect_content` per that advice: https://github.com/memberful/memberful-wp/blob/29b49e558cefb5462d48b3fc91241e2604a33cfb/wordpress/wp-content/plugins/memberful-wp/src/content_filter.php#L17
>
> We recently discovered that the latter change is causing problems for a mutual customer who's using Elementor Pro's posts template; adding the posts template to a page protected by Memberful causes all of the Elementor templates to be displayed unprotected.
>
> Removing `remove_filter` causes it to work again, but I'm not sure I understand the implications. Could you elaborate on the possible "infinite loop or re-runs on other elementor template parts down that page" that we need to avoid?

**Comment by bainternet** [comment]
@jcbpl 

As I said in the first issue,

> And make sure that you remove that action hook from your memberful_wp_protect_content once to avoid infinite loop or re-runs on other elementor template parts down that page.

If you don't want to protect only the main content and every single template part then simply hook your function and don't remove it.

thanks
