### ISSUE TITLE
Problem with pdf download function

### ISSUE THREAD

**Issue by IngriddeB** [elementor/elementor#9572]
With Elementor WordPress I'm trying to make a pdf download but it doesn't work.
First I uploaded in the media folder the pdf's but I couldn't see it when choosing 'an image'. 
Then in the htcaccess I put extra code: 

ExpiresByType image/pdf "access plus 1 year"

So now I'm able to see the pdf's which I uploaded :)
But when I go the the text editor and choose a pdf file and try to save it, I get a 403 forbidden error... What can I do to make the download of a pdf possible?

**Comment by bainternet** [comment]
@IngriddeB 

This seems like some kind of security issue triggered by your hosting.
Please check with them.

thanks.
