### ISSUE TITLE
Include FontAwesome Pro Doutone icons

### ISSUE THREAD

**Issue by PiotrKrzyzek** [elementor/elementor#9578]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor Pro with FontAwesome kits is missing Doutone icons

**Describe the solution you'd like**
At a minimum, the ability to select Doutone icons when using icons. 

I was able to get this working manually by editing Elementor Pro's core code (yes I know, bad idea) with the following:

File: .../elementor-pro/modules/assets-manager/asset-types/icons/font-awesome-pro.php

after line: 85

`$icons['fa-duotone'] = [
			'name' => 'fa-duotone',
			'label' => __('Font Awesome - Duotone Pro', 'elementor-pro'),
			'url' => false,
			'enqueue' => false,
			'prefix' => 'fa-',
			'displayPrefix' => 'fad',
			'labelIcon' => 'fad fad-flag',
			'ver' => '5.9.0-pro',
			'fetchJson' => sprintf($json_url, 'duotone'),
			'native' => true,
		];`

And then copying over light.js into a doutone.js file in the assets/lib/font-awesome-pro/ folder.

This gave me a working doutone list:

<img width="1222" alt="Screen Shot 2019-11-14 at 9 36 48 PM" src="https://user-images.githubusercontent.com/602636/68915284-e7f58380-0726-11ea-91fa-a93e0117230d.png">

And it worked wonderfully.

Not required, but it would also be great to them have an option to control the duotone colors without using css directly.

**Comment by artifex-media** [comment]
+1

**Comment by tristanleboss** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.1

Feel free to update

Thanks!
