### ISSUE TITLE
Elementor image carousel doesn't work on Safari

### ISSUE THREAD

**Issue by cycyr11** [elementor/elementor#9586]
Hi everyone,

I am facing a little issue with my elementor image carousel. I have 5 photos on my carrousel but on Safari, I just get the first image and it stays blocked on it: it doesn't slide automatically to next photos and it doesn't even show the other photos if I click on the arrow.

Does anyone know why and how to fix the issue?

Thanks a lot!

Cyrielle

**Comment by lior-sh** [comment]
Hi @cycyr11,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
