### ISSUE TITLE
addEventListener to a control element?

### ISSUE THREAD

**Issue by dbjpanda** [elementor/elementor#9587]
I am trying to attach a listener to a control ( say a button or select control ) in my custom form widget action. But it doesn't work as expected. 

Please show us an example of how can we attach a listener to control. Though It can be achieved by using `event` property in button control. But in general, how can I attach an event to any element in Elementor way?

```js
(function( $ ) {
    $(document).ready( function() {
        
        elementor.hooks.addAction( 'panel/open_editor/widget/form', function( panel, model, view ) {

            let $element = view.$el.find( '#ap_google_sheet_credentials_validate_button' );
            
            $element.addEventListener("click", function(){
                alert ('clicked');
            });

        } );

    });
})(jQuery);
```

Currently, I am doing something like below and it works but, is this the right way?

```js
self.test = function( panel, model, view ) {
            
        const $this = $( panel.$el );

        $this.on('click','#ap_google_sheet_credentials_validate_button',function () {
                console.log('clicked');
        });

        $this.on('change','#elementor-control-default-c562',function () {
            console.log('changed');
        });
 };
elementor.hooks.addAction( 'panel/open_editor/widget/form', self.test );
```
Also is there any other way to act on those events already defined in Elementor core e.g `onElementChange`  etc

**Comment by bainternet** [comment]
@dbjpanda 

These kinds of listeners are not recommended. Elementor already has events systems built-in you can and should take advantage of its native events.

First for button control, when you add a button control you can set an event name to be triggered and then add a listener on that event to do whatever you need, ex:

```PHP
$this->add_control(
	'my_button',
	[
		'type' => \Elementor\Controls_Manager::BUTTON,
		'label' => '',
		'text' => 'Click Me',
		'event' => 'MyClickEvent',
	]
);
```
and you attach a listner like this:
```JS
elementor.channels.editor.on( 'MyClickEvent',() => alert( 'This is where you do your stuff') );
```

Now For Change event, you are correct in using that hook, just not in the way you add the listener, ex:

```JS
elementor.hooks.addAction( 'panel/open_editor/widget/form', ( panel, model ) => {
	const settingsModel = editedModel.get( 'settings' );
	settingsModel.on( 'change', ( changedModel ) => {
		console.log( changedModel );	
	} );
} );
```

Hope this Helps.

**Comment by dbjpanda** [comment]
@bainternet Thanks. Is there any event system available in Elementor admin settings page? Or we should need to write it on our own? 
Say, i want to validate custom action's api keys that is rendered on integration page.

**Comment by lukesnider** [comment]
> @dbjpanda
> 
> These kinds of listeners are not recommended. Elementor already has events systems built-in you can and should take advantage of its native events.
> 
> First for button control, when you add a button control you can set an event name to be triggered and then add a listener on that event to do whatever you need, ex:
> 
> ```
> $this->add_control(
> 	'my_button',
> 	[
> 		'type' => \Elementor\Controls_Manager::BUTTON,
> 		'label' => '',
> 		'text' => 'Click Me',
> 		'event' => 'MyClickEvent',
> 	]
> );
> ```
> 
> and you attach a listner like this:
> 
> ```js
> elementor.channels.editor.on( 'MyClickEvent',() => alert( 'This is where you do your stuff') );
> ```
> 
> Now For Change event, you are correct in using that hook, just not in the way you add the listener, ex:
> 
> ```js
> elementor.hooks.addAction( 'panel/open_editor/widget/form', ( panel, model ) => {
> 	const settingsModel = editedModel.get( 'settings' );
> 	settingsModel.on( 'change', ( changedModel ) => {
> 		console.log( changedModel );	
> 	} );
> } );
> ```
> 
> Hope this Helps.

The settingsModel on change listener is working for me. However it's only listening to changes for top level settings. For instance I am attempting to edit my repeater fields on duplication. What would be the most efficient way to achieve this?
Currently I am trying to register an on click event to all ".elementor-control-fields .elementor-repeater-row-tool.elementor-repeater-tool-duplicate" elements within the panel within the "panel/open_editor/widget/{my-widget}" action but I'm having trouble getting this to work.

**Comment by RH-Xihad** [comment]
Hello @lukesnider instead of button I want to use event in dropdown. What is the method for that??

**Comment by manchumahara** [comment]
@lukesnider  from line of code

`const settingsModel = editedModel.get( 'settings' );`

how did you get the variable editedModel ?

**Comment by jasvir-strategiclight** [comment]
I want to use event in dropdown . how can i do that.

**Comment by nimaaminz** [comment]
hello 
you can use this code if you want to have an event on any control value change : 
```
  elementor.channels.editor.on('change' , (e) => {
     // your code . . . . 
    // e parameter contain a lot valuable information and function . . .  
    // debug code to watch all properties and methods inside e 
  });
```  
**BUT** i have a problem and i dont know that this is bug or not , 
the repeater controls wont call this events on control changing and i really need this know 
i want to have events like top code in repeater also but its seems there is a bug here 
can anyone help ? 

@bainternet

**Comment by ajayshrivas** [comment]
Hello all ,
I have solved this issue 
// ele-widgets.js this my js file
jQuery(document).ready(function($) {
        elementor.hooks.addAction('panel/open_editor/widget/fb_newsletter', function (panel, model, view) {
			console.log('working');
			const $this = $( panel.$el );
			$this.on('change', 'select[data-setting="newsl_autoresponder"]', function (event) {
				alert('this is testing!');
				var selectedValue = event.currentTarget.value;
				console.log('Selected Value: ' + selectedValue);
				// You can perform any actions or call functions here based on the selected value
			});
		});	
}); 
// fb_newsletter is my widget name  
this is php code 
public function __construct($data = [], $args = null) {
		  parent::__construct($data, $args);
		   wp_register_script( 'ele-widgets', plugin_dir_url( __FILE__ ).'assets/ele-widgets.js', [ 'jquery'], '1.0.0', true );

	   } 
  
	   public function get_script_depends(): array {
		   return [ 'ele-widgets' ];
	   }
	   
	   // Filed name 
	   $this->add_control(
			'newsl_autoresponder',
			[
				'label' => esc_html__( "Select Autoresponder", 'videospire' ),
                'type' => \Elementor\Controls_Manager::SELECT,
				'default' =>'list1s',
				'classes' => 'fb-autoresponder-list',
				'options' => [
					'list1s' => esc_html__( 'Lists 1', 'funnel-builder' ),
					'list2s' => esc_html__( 'Lists 2', 'funnel-builder' ),
					'list3s' => esc_html__( 'Lists 3', 'funnel-builder' ),
					'list4s' => esc_html__( 'Lists 4', 'funnel-builder' ),
				],
				
			]
		);

**Comment by dbjpanda** [comment]
@bainternet Let's say I have few sections in the widget. And except from the first one, all sections are normally collapsed. So I want to run an event when a section is opened or active. `settingsModel.on( 'change',` does not work for it. So how can I attach the event to a control of type section. 

```php
       // New Control section
        $this->start_controls_section(
            'content_section_api',
            [
                'label' => esc_html__( 'API Settings', 'elementor-pro' ),
            ]
        );
```

**Comment by dbjpanda** [comment]
Okay, It seems for section control, it is already dispatching an event `'section:activated'`

```js
elementor.channels.editor.on('section:activated', (sectionName, panelView)=>{
          
});
```
