### ISSUE TITLE
Labels for Sections – for a better overview

### ISSUE THREAD

**Issue by xkol1** [elementor/elementor#9597]
Dear Elementor Team

I've been working on more complex design projects lately. Especially with responsive webdesign many sections are created very fast. It would really help a lot if there was a way to label or name the sections so that you can keep them sorted in the navigator.  X

![Bildschirmfoto 2019-11-17 um 17 26 04](https://user-images.githubusercontent.com/57792938/69010490-a6501d00-0960-11ea-8582-1c8022a6b0d3.png)

Thank you for your answer and kind regards.

**Comment by bainternet** [comment]
@xkol1 

Simply double click on the section in the navigator and rename it to whatever you want.

![file-iVIOXVjAAc](https://user-images.githubusercontent.com/660572/69043686-2d060800-09fc-11ea-89b0-c8ac44bb14b4.gif)
