### ISSUE TITLE
The clear button of the Search Form widget needs styling options

### ISSUE THREAD

**Issue by MatthewWillHammer** [elementor/elementor#9620]
I've been building with Elementor for a while now and noticed that there's nothing I can do to style the blue X that appears when entering a search term in a Search Form widget.

Example:
![image](https://user-images.githubusercontent.com/49630489/69160129-05c04100-0ab7-11ea-8df0-bfdb8c11d8b7.png)

I've tried inspecting it to see if I could get its class name to style it with CSS but I couldn't even find that. I think adding styling options for this feature would enhance the widget greatly. At the very least, one should be able to edit its color. Thanks!

**Comment by arielk** [comment]
Long time, but this button comes from the browser, unfortunately we can not add the option to design it.

Thank you for your feedback!
