### ISSUE TITLE
Color Field height is breaking with Theme Twenty Twenty

### ISSUE THREAD

**Issue by monika-12** [elementor/elementor#9625]
## Steps to reproduce
1. Activate WP default theme Twenty Twenty
2. Open any color picker in elementor
3. Color field height is breaking.

##Screenshots:
https://share.getcloudapp.com/X6u2Pdo6

##Environment
Mac 
Chrome Browser
Elementor Plugin - Version 2.7.5 
WP Version - 5.3

**Comment by shilo-ey** [comment]
This is due to WP 5.3 modifications.

We will release compatibility for various issues soon.

Thanks
