### ISSUE TITLE
Popup container should use `<dialog>` tag, not `<div>`

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#9643]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Elementor should produce semantic code. We can set the HTML tag for sections and columns but the Popup container tag is hard-coded.

**Describe the solution you'd like**

You should update **Elementor Pro** to set the popup container tag to `<dialog>` instead of `<div>`.

**Additional context**

This simple change will potentially increase SEO visibility as search engines will not consider the popup content part of the main content.

**Comment by ramiy** [comment]
@matipojo

**Comment by matipojo** [comment]
It's currently [not supported](https://caniuse.com/#feat=dialog) by all browsers

**Comment by ramiy** [comment]
Correct me if I'm wrong but...

Browser support required only if want to use the dialog features like open/close the popup, interactions with other elements like forms and input fields and using pseudo elements. Elementor uses it's own JS for that, we don't need to use browser features.

We will be using this tag for SEO reasons only, this way search engines separate the popup content from the main content. Semantically marking the popup. The same way we mark headers, footers, asides, nav menus and other page parts.

**Comment by udidol** [comment]
Elementor's popup functionality could clash with browsers' native `<dialog>` behavior.

**Comment by rodolphebertozzo** [comment]
Hello,
So this function is still on the table for the Pro version?
