### ISSUE TITLE
Responsive video embed in text editor

### ISSUE THREAD

**Issue by wabo2190** [elementor/elementor#9644]
As a blogger, it would be great to be able to embed YouTube videos in a text editor box and keep them responsive. It works in WordPress's default text editor, but not Elementor's. I know I can do this with a video widget, but I don't want to have to use that many elements/divs in my blog posts and it would also be much faster to just paste the URL. Right now, when I just copy and paste a URL into a text editor it works, but it does not resize properly on mobile so I have to use the shortcodes ultimate plugin and paste the shortcode into the Elementor text editor block to achieve the desired results.

Thanks for your time.

**Comment by shilo-ey** [comment]
Hi @wabo2190 

Thanks for your feedback.

Embedding YouTube/other video players are set using iFrame with specific properties.

If you don't want to use the dedicated video widget, you can use responsive dimension units to the iframe embedded (%)

Thanks

**Comment by wabo2190** [comment]
Hi,

Thanks for getting back to me. Can you give me the example code showing how
to do that?

Thanks,

Kevin

**Comment by wabo2190** [comment]
Any chance you have example code to embed the videos responsively with iframes? I can't seem to get it.
