### ISSUE TITLE
✅ 🚀 Feature Request: Option to disable/anable any Elementor widget - [ED-12546]

### ISSUE THREAD

**Issue by webstarspro** [elementor/elementor#9647]
Nobody use all Elementor widgets for 1 websiste.
We usually use only a few from all widgets.
But all of their code is read by web browser and if you debug a website you see that 95% of css/js code is useless.
It leads to slow down every website.

We need these options to disable/enable any widget we want.
![image](https://user-images.githubusercontent.com/57489251/69387274-9ff5d400-0cc5-11ea-8b72-715f4cc45b19.png)

Disabling a particular widget should also disable their CSS and JS code in order not to downloaded by customer webbrowser.
Even debugging Elementor.com websiste you can see this, that more or less 90% of code is useless:
![image](https://user-images.githubusercontent.com/57489251/69387519-535ec880-0cc6-11ea-8e70-d1d533f2daaf.png)
What a shame.

This is it.
![image](https://user-images.githubusercontent.com/57489251/69387732-0cbd9e00-0cc7-11ea-98eb-d878aaa237fe.png)

**Comment by drawcard** [comment]
My understanding is that most of the JS / CSS is already disabled on the fly. For instance the SwiperJS library isn't loaded, if you don't use any galleries on your page. I may be wrong but that's been my observation over the years.

I guess the stuff that does get loaded is essential to running Elementor either in the frontend or the backend.

**Comment by webstarspro** [comment]
> My understanding is that most of the JS / CSS is already disabled on the fly. For instance the SwiperJS library isn't loaded, if you don't use any galleries on your page. I may be wrong but that's been my observation over the years.
> 
> I guess the stuff that does get loaded is essential to running Elementor either in the frontend or the backend.

Absolutely, any code is not disabled on the fly.
Have you seen all the proofs above? I showed example on elementor.com webiste. This is the proof that Elementor is completely not optimized in terms of disabling unused code.
95% of Elementor code is useless and downloaded by our browsers.
Look at this:
![image](https://user-images.githubusercontent.com/57489251/69953340-52653c80-14f9-11ea-93bc-00a1476997cf.png)

**Comment by C-Nog** [comment]
+1 vote

**Comment by KarzanTT** [comment]
+1

**Comment by MacSimLtd** [comment]
+1

**Comment by zkang93** [comment]
Up vote + 1

**Comment by taropaa** [comment]
+1

**Comment by MacSimLtd** [comment]
+1

**Comment by andcha** [comment]
**Come on Elementor Devs**, do something about this.

**### Help us debloat elementor to our liking.**

Page speed should be on top of your priority list, whereas the present scenario is absolutely opposite.

 There are lot of open & closed issues regarding this problem but none with proper working solution.

**Comment by Trilochan20** [comment]
+1

**Comment by jdub850000** [comment]
+1

**Comment by nishimwealain** [comment]
+1

**Comment by Noeil182** [comment]
Has anybody found a fix to at least clean up the frontend.min.css?
So much unused css is called...

**Comment by davidamarek** [comment]
+1

**Comment by adempius** [comment]
Yes very very very important

**Comment by fatmatts** [comment]
+1

**Comment by mentorele** [comment]
+1

**Comment by y0rg0s** [comment]
+1

**Comment by andytwl** [comment]
+1 - this is extremely important now. Please don't go down the path the bloated old "premium" themes did. Thanks

**Comment by YourFavedave** [comment]
Plus 1

**Comment by jdub850000** [comment]
Deffo +1

**Comment by MichaelDarko** [comment]
This should be a next step when it comes to performance. Google Page speed is showing a lot of unused JS and CSS.

**Comment by btward79** [comment]
+1 Cannot agree more.

The gentlemen did a good job of documenting what I was about to report. Unused CSS is loaded everywhere. I see woocomerce, share icons, price list, cart, testimonials, and so on. We use none of that and there is a lot more.

CSS should only be loaded if the widget is used on the page. Elementor folks need to help us out with this. It's one of the biggest contributors to page load for our site now. We are working hard to make it faster, but we are hitting a wall here. 90-95% of the CSS Elementor generates is not used on our site. We do support the plugin via the Pro version as well.

Thank you for listening.

**Comment by SuperstrongBE** [comment]
This is insane! Performance should be in center of the debate now elementor is mature enought !

**Comment by MichaelDarko** [comment]
It might be useful to visualize how badly designed Elementor is when it comes to performance.

### Elementor

This is a list of JS and CSS files that Elementor is loading on the frontend and the red color indicates what portion is not used.

(And that's on top of all the other WordPress and plugin assets!)

![Elementor](https://user-images.githubusercontent.com/36289156/111038270-5edc8280-8428-11eb-9d61-c01c14af3c90.png)

### Webflow

And here is the same thing from website built on Webflow. 

(And Webflow is 10x more powerful page builder in terms of features!)

![Webflow](https://user-images.githubusercontent.com/36289156/111038272-5f751900-8428-11eb-805a-17de232ff854.png)


Performance demands from my clients are basically forcing me to switch to Gutenberg (simple websites) and Webflow (more complex websites). Elementor is no longer at the cutting-edge when it comes to features and the performance is not acceptable for a professional tool.

**Comment by Noeil182** [comment]
Totally agree, which is why i moved all my sites to Gutenberg. I was tired
of trying to optimize Elementor and not getting any support from Elementor.

**Comment by black-eye** [comment]
+1

**Comment by DavidGMiles** [comment]
+1 this should be the highest priority

**Comment by 79ho3ein** [comment]
+1 This feature is extremely required. Especially as elementor widgets are increasing day by day.
I hope this feature will be added to elementor soon.

**Comment by jazir5** [comment]
+1

**Comment by SuperstrongBE** [comment]
I'm f***ing upvote this ! +1

**Comment by Michaelgimii** [comment]
Hi elementor team!

Do you have any plans to add this feature? Maybe with the V2 editor.

I think about this feature every day. This is really great and very useful. Personally, I don't work with many Elementor widgets like Facebook widgets. I can disable them using this feature . This will clean the Elementor editor from useless widgets and most importantly, the speed of the editor will increase a lot.

**Comment by arielk** [comment]
Ref: https://github.com/orgs/elementor/discussions/21717

**Comment by nicholaszein** [comment]
Hey everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
