### ISSUE TITLE
Specify class for button element

### ISSUE THREAD

**Issue by leecollings** [elementor/elementor#9650]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have inserted a button and only have the five available styles to select from a dropdown (default, info, success, warning & danger). None of these fit the colour I have for primary, secondary, or other button styles used in Bootstrap. This is very limited.

**Describe the solution you'd like**
There is already an input field to set the button ID, there should be another input field to add extra classes to the button element. This would allow for endless styling and compatibility with Bootstrap.

**Describe alternatives you've considered**
I have considered entering an ID and creating my own styles to target this, but this means I have to do this for every button, even when they're the same style. It also doesn't let me take advantage of other classes I would like to add to the button within Bootstrap.

**Additional context**
None

**Comment by shilo-ey** [comment]
Hi @leecollings 

Thanks for your feedback,

We are currently working on a broader solution to this issue (to all links).

In the meanwhile try specifying CSS Class to the wrapper and target it accordingly.

Thanks

**Comment by TillVennemann-Lecturio** [comment]
Hey @shilo-ey do you have any news about this issue? I currently have the problem, that the class is added to the wrapper not the a element and therefore our tracking cannot be implemented correctl.y
