### ISSUE TITLE
Use Elementor Pro popup in Contact Form 'Terms and Conditions' Text

### ISSUE THREAD

**Issue by alohajoha** [elementor/elementor#9652]
I'm trying to create a popup for the terms and conditions in Contact Form 7 with Elementor Pro and I have put the code like this in the contact form code:

`<a href="#elementor-action%3Aaction%3Dpopup%3Aopen%20settings%3DeyJpZCI6IjY0IiwidG9nZ2xlIjpmYWxzZX0%3D">Datenschutzerklärung</a>`

It works, if I have a button assigned to it on the page, but not when I have linked it in the contact form 7 code. Can someone help me with this issue please?

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
