### ISSUE TITLE
background column width

### ISSUE THREAD

**Issue by jhweb2** [elementor/elementor#9654]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When u set a column width with a overlay opacity less than 1 a margin side appear and cant be eliminated, the overlay doesnt extend to the end o the container.

## Steps to reproduce

1 - Create a section
2 - Make 3 container
3 - On right side try to add a container with background overlay with 0.7 opacity for example (or see the image below)

![1](https://user-images.githubusercontent.com/53986027/69430356-2fc26f00-0d14-11ea-939d-d860cf10b6c4.png)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @jhweb2 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.** - Can't replicate using these steps. there's no such thing an overlay for columns.
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
