### ISSUE TITLE
Image Carousel Widget - Slides to Show option for Tablet breakpoint doesn't work

### ISSUE THREAD

**Issue by euene** [elementor/elementor#9659]
## Prerequisites

- [x] The issue still exists against the latest stable version of Elementor.

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

## Description

Create an image carousel widget. Go to "tablet" breakpoint view and adjust the "Slides to Show" option number - the result is that no matter what number is selected, only 1 slide will be shown always. The "Slides to Show" works as expected on desktop and mobile breakpoints - so it's only the Tablet breakpoint that doesn't work.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @euene 

We can't reproduce your issue,

Your issue occurs when the tablet is on landscape mode only, which is the expected behavior, as we use media queries to set the conditions based on screen resolution.

Thanks.

**Comment by euene** [comment]
The issue doesn't occur on tablet landscape only, it occurs at the exact tablet portrait breakpoint that's used by Elementor to preview the design in the Elementor editor, as well as on the front-end of the site.

The issue is extremely easy to reproduce - see an example where the desktop/mobile breakpoint apply the "Slides to Show" setting, but tablet doesn't apply it.

![elementor-bug](https://user-images.githubusercontent.com/6027160/69495529-99877800-0ed0-11ea-93eb-e8692565c95f.gif)

This can be reproduced every time, and has been happening for a long time now from many versions ago - but in this example, it's a fresh WordPress 5.3 install with only the latest versions of Elementor + Elementor Pro + Hello Elementor.

**Comment by euene** [comment]
Hi @shilo-ey 

The issue doesn't occur on tablet landscape only, it occurs at the exact tablet portrait breakpoint that's used by Elementor to preview the design in the Elementor editor, as well as on the front-end of the site.

The issue is extremely easy to reproduce - see an example where the desktop/mobile breakpoint apply the "Slides to Show" setting, but tablet doesn't apply it.

![elementor-bug-carousel](https://user-images.githubusercontent.com/6027160/69495567-0733a400-0ed1-11ea-9de1-5914daa56e6e.gif)

This can be reproduced every time, and has been happening for a long time now from many versions ago - but in this example, it's a fresh WordPress 5.3 install with only the latest versions of Elementor + Elementor Pro + Hello Elementor.

**Comment by vgstef** [comment]
I also have this issue. My plugins are up-to-date and I tried it on different websites.

What I see is the tablet option for "Slides to show" uses the mobile setting instead of the tablet settings. So the Tablet setting doesn't have any impact. If I change the mobile setting, the tablet design changes accordingly.

**Comment by vgstef** [comment]
Ok, the problem is only in the editor. On the Front-end, the tablet setting is taken into consideration.
