### ISSUE TITLE
latin-ext subset for Google Fonts in case of sk_SK (and others) locale

### ISSUE THREAD

**Issue by andrejm** [elementor/elementor#9660]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Some languages need special characters present in latin-ext subsets of Google Fonts. If the font is loaded without this subset, rendered page looks really nasty with missing letters shown in default font.

**Describe the solution you'd like**
Simply adding `'sk_SK' => 'latin-ext'` for Slovak locale in print_google_fonts() function in includes/frontend.php

**Describe alternatives you've considered**
A filter hook to set particular subset

**Additional context**
I think many others would like to see their languages added - see #1630 comments, #8186, #1915

**Comment by ogio** [comment]
Yes, we need this ASAP because Latin Extemded and Cyrillic subsets needs to be used for Eastern Europe and wider. Please, for now it will be helpful that we have some part of script that we can add on functions.php and enable google font subsets. Anybody knows how?

**Comment by andrejsrna** [comment]
Bump. Need this, please.

**Comment by MichaelDarko** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.0

Feel free to update

Thanks!

**Comment by mateitudor** [comment]
It just hasn't been completed for romanian.
