### ISSUE TITLE
Unable to delete element

### ISSUE THREAD

**Issue by CripyIce** [elementor/elementor#9661]
Hi there,
Started to use Elementor and realised i can't delete an element!
I'm not getting the "custom" context menu that I should.
I followed this guide https://docs.elementor.com/article/465-how-to-delete-a-widget, but it explains using the context menu which I don't have.

I'm using latest stable Mac OS and latest stable Chrome, but when using Safari I can see the context menu and delete an element.

Chrome:
<img width="394" alt="Screen Shot 2019-11-23 at 22 16 14" src="https://user-images.githubusercontent.com/26387823/69484686-eb7fbd80-0e3e-11ea-87d5-1f175e6a4b74.png">

Safari:
<img width="319" alt="Screen Shot 2019-11-23 at 22 15 50" src="https://user-images.githubusercontent.com/26387823/69484694-f0dd0800-0e3e-11ea-9884-d792fa1ec7dc.png">

> "delete" button doesn't work on both browsers.

**Comment by shilo-ey** [comment]
Hi @CripyIce 

Please make sure you don't have any console errors. if not, you can add editing handles.

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
