### ISSUE TITLE
Popup Counter

### ISSUE THREAD

**Issue by letterleben** [elementor/elementor#9673]
I'm missing a counter for popups with opening / closing statistics. Would be very interesting to analyse.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
