### ISSUE TITLE
Is this a bug? Missing publish button.

### ISSUE THREAD

**Issue by dastan4477** [elementor/elementor#9675]
I'm missing publish button after I updated plugin.
What can I do?

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
