### ISSUE TITLE
Post title over featured image in Posts

### ISSUE THREAD

**Issue by VK120** [elementor/elementor#9676]
Hello,

I need to move title, date and excerpt to the image above it. There is no function or margin with negative values to do this.

I can edit CSS myself (for example margin-top: -90px;) but if I code this, text goes under the image, not above it.

Any solution or function?

**Comment by shilo-ey** [comment]
Hi @VK120 

Try using `position: relative`

In addition, I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
