### ISSUE TITLE
Custom Font Display hook not working

### ISSUE THREAD

**Issue by MagnetBrains** [elementor/elementor#9677]
Hello, 

When we upload and use custom fonts via Elementor, the Google Page speed score drops.
The diagnostics mention that you should "Ensure that the font remain visible during webfont load".
To ensure the visibility, we have to font-display: swap property.
There is a filter provided in the Elementor Docs which can fix that. However, that filter does not work at all.
The link to that doc is here. https://developers.elementor.com/elementor-pro-2-7-custom-fonts-font-display-support/
I am not sure if it's an issue at my end or Is it a bug from Elementor's end.
My team sent an email to Elementor support but it's 2-3 days and we are yet to hear from them.
Has anyone tried that filter and did it work for you? Or how you are managing to resolve this issue.

**Comment by lubosmutny** [comment]
I have the same problem and no response from Elementor Technical Support? We've been waiting for it for six days ...

**Comment by shilo-ey** [comment]
ref: https://github.com/elementor/elementor/issues/5993#issuecomment-735295544
