### ISSUE TITLE
Displaying the name of the page

### ISSUE THREAD

**Issue by webstarspro** [elementor/elementor#9678]
- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

**What problem is your feature request going to solve? Please describe.**
Every time when I edit the page - I'm asking "what's the name of this page?"
If you are in editor - you can not see the name of the page you are editing at the moment.
If you are switching beetween many websites or pages you are confused many times.

**Describe the solution you'd like**
It would be usefull to display the name of the page somewhere here.
![image](https://user-images.githubusercontent.com/57489251/69539465-d8770580-0f84-11ea-92c6-50c13f7fddef.png)

**Comment by shilo-ey** [comment]
Hi @webstarspro 

Thanks for your feedback.

Click on the cog icon on the bottom-left corner of the panel and you'll see the title of the page.

Thanks

**Comment by webstarspro** [comment]
> Hi @webstarspro
> 
> Thanks for your feedback.
> 
> Click on the cog icon on the bottom-left corner of the panel and you'll see the title of the page.
> 
> Thanks

Don't close it.
THis is not the solution.

I can even close elementor editor and see the name.
Yes, I can.

The name should be displayed all the time without clicking anything.
If I switch between many pages I need to know the name all the time.
