### ISSUE TITLE
Responsive option for images.

### ISSUE THREAD

**Issue by myedgy** [elementor/elementor#9679]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Option to load different image sizes, now 1 image is loaded for mobile / tablet too. Most of the time this are images for desktop. 

**Describe the solution you'd like**
An option like text where you can set the responsiveness, to insert different images for mobile, tablet and desktop. This way the images are adaptive. Saves bandwidth and faster loading times for different image sizes.

**Describe alternatives you've considered**
Now I need to create multi blocks or 3 sliders one for desktop, one for tablet, one for phone so i'm sure the fastest and smallest image is loaded.

**Additional context**

**Comment by drawcard** [comment]
Are you referring to [srcset](https://html.com/attributes/img-srcset/)? I think WP / Elementor handles that already.  It appears to be auto-generated on the sites I build.

![image](https://user-images.githubusercontent.com/1435638/69897797-c3451100-13a0-11ea-9ff5-d2c50d4c86df.png)
