### ISSUE TITLE
Feature Request: Zoho CRM Integration

### ISSUE THREAD

**Issue by mfrapp20** [elementor/elementor#9684]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

This would make it easier to properly have form submissions using Elementor forms be captured in Zoho CRM without having to use webhooks. I currently am using webhooks to connect the two platforms, and it does work, but some data that would normally be available if I used Zoho CRM forms is missing (specifically visitor summary info). I think creating an integration would fix this issue too,

**Describe the solution you'd like**

Create an integration between Zoho CRM and Elementor which is similar to ActiveCampaign which allows you to map form fields to CRM fields and choose where form submissions go.

**Describe alternatives you've considered**

As mentioned above, I've used Zapier webhooks to connect Zoho CRM and Elementor, but some important data does not populate in Zoho CRM when I use this method over using Zoho CRM forms.

**Additional context**

**Comment by shilo-ey** [comment]
Hi @mfrapp20 

Thanks for your feedback,
I merged this issue with #9158, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by collizo4sky** [comment]
If you are using MailOptin, you can integrate Zoho CRM and Zoho Campaigns with your Elementor Forms.

See https://mailoptin.io/article/elementor-form-integration/

## Zoho CRM

![image](https://user-images.githubusercontent.com/4140659/72825305-15a2ff80-3c77-11ea-8907-58a5f5985e6a.png)

## Zoho Campaign Monitor
![image](https://user-images.githubusercontent.com/4140659/72825369-32d7ce00-3c77-11ea-9570-e81af42dff24.png)
