### ISSUE TITLE
Popups not editable

### ISSUE THREAD

**Issue by Jean-ClaudeVanRamme** [elementor/elementor#9691]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After updating wordpress to version 5.2.4 and elementor to version 2.7.5 the popups are uneditable. Elementor is stuck in the loading screen. 

![image](https://user-images.githubusercontent.com/58166948/69640646-016bc900-105f-11ea-8d67-4e5e5455a04a.png)

Everything else is perfectly editable with elementor. It is possible to create a new popup but if I try to edit it with elementor the same problem occurs.  And the popup IS working on the website. It is just not possible to edit it. 

I searched on some websites for error handling this problem:

[https://docs.elementor.com/article/184-cant-edit-with-elementor](https://docs.elementor.com/article/184-cant-edit-with-elementor)
[https://docs.elementor.com/article/481-safe-mode-didnt-solve-the-problem?utm_source=safe-mode&utm_medium=wp-dash&utm_campaign=learn](https://docs.elementor.com/article/481-safe-mode-didnt-solve-the-problem?utm_source=safe-mode&utm_medium=wp-dash&utm_campaign=learn)
[https://github.com/elementor/elementor/issues/9106](https://github.com/elementor/elementor/issues/9106)

To be more specific: 
- The error persists on different accounts
- The error persists on different browsers
- There is more than enough memory available
- The error persists while using safe mode
- Deleting cache had no impact
- Using the option switch front-end editor loader method had no impact

Through investigating with the debugging tools from chrome I got the following error message: 

![image](https://user-images.githubusercontent.com/58166948/69640617-ed27cc00-105e-11ea-8386-bbada74aa735.png)

## Steps to reproduce
Try to edit any popup with elementor

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

![image](https://user-images.githubusercontent.com/58166948/69641521-a509a900-1060-11ea-8141-e7bb8062c470.png)

					
![image](https://user-images.githubusercontent.com/58166948/69641167-fd8c7680-105f-11ea-99e7-db8eda19f10c.png)
				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @Jean-ClaudeVanRamme 

Thanks for reporting, this issue already been fixed in the latest versions of Elementor Pro.

Please update to the latest version in order to enjoy the full capabilies of Elementor without compatibility issues.

Thanks
