### ISSUE TITLE
Alert widget, add icon

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#9695]
Hello, would it be possible to add an icon next to the alert title on the alert widget? example:
![exemple](https://user-images.githubusercontent.com/56270626/69657353-5832cc00-107a-11ea-9d95-2fb1583a26e9.png)

**Comment by shilo-ey** [comment]
Hi @rodolphebertozzo 

Currently no, 
You can add it programmatically (use `span`/`i` or `:after` to add your icon) 

Thanks.
