### ISSUE TITLE
Popup cookie session / time

### ISSUE THREAD

**Issue by letterleben** [elementor/elementor#9697]
+ [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hi, 

I think there is missing the option to set a session cookie for popups. So that the counting of e.g. "show x times" will start again, when the user reopens the page after some time. 
Until now the cache has to be cleared or the browser needs to be closed completely to reactivate the counting again. 

I would prefere to have the options: 
- start counting / reopening the popups after xx hours
- start counting / reopening the popups per cookie session (delete cookie when leaving the page?)

I have many users that just browse around on the first time. Than they come back the day after, but they defenitely NOT clear the cache. When you use a Mac you know that most of the time you don't even close the browser... The popups will not show up again. That's not good!

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/8187 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
