### ISSUE TITLE
Popup counter

### ISSUE THREAD

**Issue by letterleben** [elementor/elementor#9698]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I'm missing the option to see how many times a popup was opened. 

In many popup plugins for wordpress there is a counter implemented, that shows how many times a popup was shown to users. That's a very interesting number if you want to analyse how helpful / successful your popup is.

**Comment by drawcard** [comment]
Would that be possible via Google Analytics tracking? The popup is like a page template  so you could theoretically track it that way.

**Comment by arielk** [comment]
Duplicate of #9234
