### ISSUE TITLE
Hide price until login

### ISSUE THREAD

**Issue by insight47** [elementor/elementor#9703]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Sometimes we'd like to hide our prices for certain WooCommerce products so competitors can't easily see them. We'd like to be able to hide prices sometimes until a visitor is logged into the website. Currently there is no way to do this with Elementor WooCommerce price modules.

**Describe the solution you'd like**
I think some code to use in functions.php that allows us to specify a WooCommerce category which we'd like to hide prices for until the visitor is logged in. [This code](https://wordpress.stackexchange.com/a/351812/147186) works with non-Elementor WooCommerce pages.

**Describe alternatives you've considered**
Only [the code listed above](https://wordpress.stackexchange.com/a/351812/147186).

**Additional context**
None.

**Comment by shilo-ey** [comment]
Hi @insight47 

If just hiding is what you want, you can do it by using simple CSS rule such as:
```CSS
.logged-in ul.products li.product .price {
    display: none;
}
```

I assume you want something more robust and not just hiding the price but disabling the functionality. 

In that term, Elementor currently doesn't handle or manipulate the WooCommerce options.

Thanks

**Comment by insight47** [comment]
I ended up using body:not(.logged-in) ...

Cheers.
