### ISSUE TITLE
✔️ 🚀 Feature Request: Implement column order

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#9705]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hey guys. I needed to make a swap between some Columns on tablet & mobile and i eventually developed an ordering control.

**Describe the solution you'd like**
To implement this control in the Column element:

```
$this->add_responsive_control(
    '_column_order',
    [
        'label' => __( 'Column Order', '@@textdomain' ),
        'type' => Controls_Manager::SELECT,
        'default' => '',
        'options' => [
            ''  => esc_html__( '- Default -', '@@textdomain' ),
            '-1'  => esc_html__( 'First', '@@textdomain' ),
            '1'  => esc_html__( '1', '@@textdomain' ),
            '2'  => esc_html__( '2', '@@textdomain' ),
            '3'  => esc_html__( '3', '@@textdomain' ),
            '4'  => esc_html__( '4', '@@textdomain' ),
            '5'  => esc_html__( '5', '@@textdomain' ),
            '6'  => esc_html__( '6', '@@textdomain' ),
            '7'  => esc_html__( '7', '@@textdomain' ),
            '8'  => esc_html__( '8', '@@textdomain' ),
            '9'  => esc_html__( '9', '@@textdomain' ),
            '10'  => esc_html__( '10', '@@textdomain' ),
            '999'  => esc_html__( 'Last', '@@textdomain' ),
        ],
        'selectors' => [
            '{{WRAPPER}}' => 'order: {{VALUE}};',
        ],
    ]
);
```

**Describe alternatives you've considered**
Doing my own control, but would happily deprecate it in favor of native Elementor control.

**Comment by drawcard** [comment]
I believe there is already column reordering in Advanced > Responsive settings, for the section widget.

**Comment by hogash** [comment]
Yes, i know but that only reverses the columns.

If i'd have say 3 columns, and on mobile/tablet i want the 2nd one to be first, the section's "Reverse columns" option is not useful.

With my proposed solution, to make the 2nd column first, i simply select First in the list.

**Comment by drawcard** [comment]
Oh I see. Yeah this is a nice idea :)

**Comment by drawcard** [comment]
I also run into this issue a lot when using columns to place items in nav menus.

```
Logo ------ Nav Item 1 - Nav Item 2 - Nav Item 3 --- Login Button - Register Button
```
Collapses to
```
Logo ------ Hamburger menu --- Login button - Register Button
```
Whereas the hamburger button would be better off on the other side of the buttons:

```
Logo ------ Login Button - Register Button --- Hamburger menu
```

**Comment by black-eye** [comment]
+1
Oh yes, this is such an easy update to do, but very handy. So it would be nice to have it in the core.

I'm using similar code in my child theme (with several other tweaks to make Elementor more powerful). In my case, I have there simple number input instead of dropdown select.

**Comment by numanzahid** [comment]
+1

this will be really helpful.

**Comment by numanzahid** [comment]
@hogash 

can you describe a little more how your solution works. I can use it until it is officially implemented.

**Comment by Webtica** [comment]
You can also do this with a bit of css: 

.elementor-13 .elementor-element.elementor-element-278741b {
    -webkit-order: 1;
    -ms-flex-order: 1;
    order: 1;
}
@media (max-width: 1024px)
.elementor-13 .elementor-element.elementor-element-278741b {
    -webkit-order: 1;
    -ms-flex-order: 1;
    order: 1;
}
.elementor-13 .elementor-element.elementor-element-38dc2c7 {
    -webkit-order: 2;
    -ms-flex-order: 2;
    order: 2;
}
@media (max-width: 1024px)
.elementor-13 .elementor-element.elementor-element-38dc2c7 {
    -webkit-order: 3;
    -ms-flex-order: 3;
    order: 3;
}
@media (max-width: 767px)
.elementor-13 .elementor-element.elementor-element-38dc2c7 {
    width: 50%;
    -webkit-order: 2;
    -ms-flex-order: 2;
    order: 2;
}
.elementor-13 .elementor-element.elementor-element-424378b {
    -webkit-order: 3;
    -ms-flex-order: 3;
    order: 3;
}
@media (max-width: 1024px)
.elementor-13 .elementor-element.elementor-element-424378b {
    -webkit-order: 2;
    -ms-flex-order: 2;
    order: 2;
}
@media (max-width: 767px)
.elementor-13 .elementor-element.elementor-element-424378b {
    -webkit-order: 3;
    -ms-flex-order: 3;
    order: 3;
}

IF they could make an control box in the advanced tab that would output this css of said column.

+1 For this feature

**Comment by drawcard** [comment]
Better yet, assign CSS or ID classnames to the elements you want to control via "Advanced" panel, so you don't need to target the randomised element classname :)

**Comment by black-eye** [comment]
Here's my approach. Add this to your functions.php or your child theme:

```
function bleye_add_responsive_column_order( $element, $args ) {
	$element->add_responsive_control(
		'responsive_column_order',
		[
			'label' => __( 'Responsive Column Order', 'elementor-extras-spevacek' ),
			'type' => \Elementor\Controls_Manager::NUMBER,
			'separator' => 'before',
			'selectors' => [
				'{{WRAPPER}}' => '-webkit-order: {{VALUE}}; -ms-flex-order: {{VALUE}}; order: {{VALUE}};',
			],
		]
	);
}
add_action( 'elementor/element/column/layout/before_section_end', 'bleye_add_responsive_column_order', 10, 2 );
```

It will add a new field to column settings:

![obrazek](https://user-images.githubusercontent.com/5634870/70955924-b39d1c00-2072-11ea-8389-e7bc7c824980.png)

Quite straightforward, right? How long would it take you to implement this, Elementor? 😉

**Comment by drawcard** [comment]
Not long I hope :) Excellent solution.

**Comment by drawcard** [comment]
@black-eye you should consider doing a PR so the Elementor team can merge it!

**Comment by black-eye** [comment]
@drawcard 
> @black-eye you should consider doing a PR so the Elementor team can merge it!

Well, I wouldn't call myself a big programmer/developer, and I have no experiences with adding PR's here on Github. Moreover, from what I've gathered from other issues here, Elementor's will for implementing such PRs is very limited. So I've decided to save my time a leave it as it is. ;-) But if someone else (or you) can add the PR, you're most welcome.

And besides that, in the code above there's already everything they need to implement it. ;-)

**Comment by drawcard** [comment]
I'll have a shot at doing a PR on your behalf - it's fairly easy within Github, you can fork the project, create a new branch and then pull that down to your local environment to do dev and testing. When finished, push back to the remote branch in your fork, and then submit your PR: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Aside from that, you want to test your changes in a clean Wordpress local environment (just a bare installation with Elementor + Elementor Pro active, and maybe Hello Elementor for the theme). https://localwp.com/ is a good option for this.

**Comment by wwdes** [comment]
+1
If they will implement CSS order property in to elementor, I imagine it should be controlled from a sections layout/responsive options with some sort of drag-and-drop list of all containing columns.

**Comment by tomas-eklund** [comment]
@black-eye 
> Here's my approach. Add this to your functions.php or your child theme:

Oh my, thank you so very much for this! 

Out of curiosity, what are your other "tweaks"? Anything you'd care to share?

**Comment by numanzahid** [comment]
@tomas-eklund yeah, good thinking.
@black-eye we want to know more tricks like that. Any blog or someplace where you share? 😄

**Comment by DorShahar** [comment]
This will be implemented as part of the "Container" feature.

Thanks

**Comment by nicholaszein** [comment]
Hello everybody!

We have great news! 🙌 

### 📢 We're happy to announce that you can now have full control over the order of the items inside a container with the <ins>stable</ins> version of the Flexbox Container experiment introduced in Elementor **v3.8**! 🥳 

You are invited to update Elementor to the latest version, activate the Flexbox Container experiment, and enjoy the full power of CSS Flexbox! 💪 

Cheers 🥂
