### ISSUE TITLE
Bug: array to string conversion

### ISSUE THREAD

**Issue by lonix1** [elementor/elementor#9709]
Sometimes elementor doesn't load. I get that little popup that tells me to show debug preview.

When I do that, it shows a blank page with:
> Array to string conversion

And in the console it shows this:

> ReferenceError: elementorModules is not defined         frontend.min.js:2:39695
    <anonymous> https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2
    __webpack_require__ https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2
    <anonymous> https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2
    __webpack_require__ https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2
    <anonymous> https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2
    __webpack_require__ https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2
    <anonymous> https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2

**Comment by drawcard** [comment]
Could be related to my issue: #9700

**Comment by shilo-ey** [comment]
Hi @lonix1 

This is not something we can debug with this info.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.


Next time, please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by lonix1** [comment]
For anyone else's benefit who stumbles on this poorly-worded error.

I increased the backend's memory limit to 512MB, and the problem seems to have gone away, for now.

This made me happy as I can carry on working, but it also makes me angry because that is an incredible amount of memory for a plugin to use - and I need that memory for other more important things. This plugin is obviously very inefficient. My firewall handles thousands of hack attempts every few minutes, and it does that in a *fraction* of the memory.

**Comment by lonix1** [comment]
Spoke too soon. That only worked for a while.

I disabled the plugin ["Redirection"](https://wordpress.org/plugins/redirection) and again Elementor is behaving.

Has anyone else had this problem? How can I have them both on at the same time?

Strange thing is they were working together for a long time, only now there is a problem.

**Comment by drawcard** [comment]
It could be that both plugins are competing for server resources that don't exist, or there are other JS conflicts. If you can share your server specs (Elementor > System Info) that may help.

The related error I reported came out of the blue with no warning, with a properly working setup. I resolved it after adjusting a few settings on the server (see my response in #9700).

**Comment by lonix1** [comment]
According to the [author of that plugin](https://github.com/johngodley/redirection/issues/2076#issuecomment-559427473), it's elementor that is probably misbehaving - and he's an automatic employee.

The problem was a redirection was confusing elementor when loading its UI. But apparently it shouldn't be working that way anyway.

That said, elementor would still fail to load from time to time, and your issue tipped me off about the memory pressure - so I bumped admin memory to 384MB and it seems to be working for now. I'm surprised at how much memory it needs.

**Comment by drawcard** [comment]
Good to know that. Maybe there's a recent update with Elementor that has required more memory to run - the docs say 256MB is required. But that would probably be a minimum requirement :)

It also depends a lot on other things like other plugins consuming memory, whether your server is restricted or not with resources, how much traffic you get to your site, etc. These days it's more common to have a server with at least 1GB to go around, to cater for it all.

If you have restricted memory resources you may be able to use other things like caching plugins to take the pressure off the site in other areas, and dedicate more to Elementor + Redirection.
