### ISSUE TITLE
Dynamic capabilities for Toggle widget

### ISSUE THREAD

**Issue by MjHead** [elementor/elementor#9710]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate (to be honest I found duplicates but these issues was closed because of incorrect description).
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In some cases could be very useful to has dynamic capabilities on a Toggle widget Title and Content (the same for Accordion and Tabs widgets). For example if I created single template for custom post type, lets say "Events". I have some custom fields for each event - detailed information, event schedule, venue etc. I can group these info on the single event page with Toggles and attach appropriate custom fields to required Toggles content - http://prntscr.com/q2u9nb.

**Describe the solution you'd like**
To make this happen we just need to add a dynamic capabilities for Toggle widget (and also will be great to do the same for Accordion and Tabs) - http://prntscr.com/q2u3b3

**Describe alternatives you've considered**
The same result could be retrieved if we create separate templates for each Toggle item, add Text Editor widget into these templates and use dynamic capabilities of Text Editor widget. But such structure will be much harder to maintain, also it will render template content inside each Toggle item and enqueue each template CSS files - this will have negative impact on performance score.

**Comment by DigitalBerry** [comment]
I would like this to be working too! Especially with Repeater regions in ACF.

There seem to be many "dynamic options" available on widgets, but not many of them work.

Come on team E sort it out ! :)

**Comment by elasticeye** [comment]
+1

**Comment by alammahbub2500** [comment]
I really need this. Seeking attention of the team here.

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
