### ISSUE TITLE
Not compatible with Classic Editor plugin

### ISSUE THREAD

**Issue by vladaman** [elementor/elementor#9715]
Trying Elementor and I found out that if I have plugin "Classic Editor" the Elementator doesn't work. We don't use standard Wordpress editor because it always screws up our designs. I would be nice if Elementor would work separately.

**Comment by shilo-ey** [comment]
Hi @vladaman 

Thanks for reporting,

We don't know about any familiar issues with this plugin.

We can't reproduce your issue.

Next time please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
