### ISSUE TITLE
[Feature Request] Margin in em or rem

### ISSUE THREAD

**Issue by lonix1** [elementor/elementor#9722]
In every element's "Advanced" section, we can set padding in em.

Please also add that for margin.

**Comment by numanzahid** [comment]
+1

**Comment by rodolphebertozzo** [comment]
Solve since release 3.0.0

@shilo-ey

**Comment by shilo-ey** [comment]
Thanks.

As @rodolphebertozzo mentioned, this feature is available in Elementor

Thanks
