### ISSUE TITLE
GLITCH in MEDIA CAROUSEL CUBE when...

### ISSUE THREAD

**Issue by Hoffkids** [elementor/elementor#9725]
Hi,
This is a clear bug that should not be hard to fix.

The plugin is MEDIA CAROUSEL and when you use the CUBE it glitches on iphones and in safari on computers.
There is a clear glitch with the CUBE carousel and ios.
This was tested by multiple people and even another person made a sample below to see.

What happens? when it spins to the next pic, the dots will dissapear and reapper and the arrows do the same at times.

See 2 examples below.

https://www.hoffkids.com/practice2/

https://www.spaandesign.nl/carousseltest/?fbclid=IwAR3xVGdkKNE8DIaRbvvfURu-LnaCuYKE1FAAv2nNx-GjaOXnmus60pv77Z4

Thanks for any quick attention to this BUG,

Barry

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by drawcard** [comment]
It looks like Safari is incorrectly clipping the 2d elements of the slideshow, when the 3d elements animate during transition. That might be an issue with [SwiperJS](https://swiperjs.com/) however so it may be worth reporting the issue to them.
