### ISSUE TITLE
[Vulnerability] Script Injecting with AdBlock Plus (Chrome) Installed

### ISSUE THREAD

**Issue by zeinnicholas** [elementor/elementor#9727]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello guys, I've detected a vulnerability with AdBlockPlus (3.7) in Chrome (78.0.3904.108) and tested in Elementor. I can confirm it affect any instance of the TinyMCE editor (WYSIWYG) inside Elementor.

The complete details of my findings and also steps to reproduce are registered here:
https://hackerone.com/reports/748841

Beware. If you have AdBlock Plus installed remove it immediately and check your installation and database.

## Steps to reproduce

See link above.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Unix) OpenSSL/1.1.1
	MySQL version: mariadb.org binary distribution v5.7.26
	PHP Version: 7.3.11
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 30720M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Astra Floww
	Version: 1.0.0
	Author: Nicholas Zein
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 2.1.3
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 2.7.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.3
		Author: Elementor.com
```
</details>

**Comment by bainternet** [comment]
@zeinnicholas 

We cant access the report,
> Oops! You can't access this report because it isn't public yet.

can you please contact our support at support@elementor.com, mention that you were directed by me and reference this issue and provide the report.

thanks.

**Comment by zeinnicholas** [comment]
Ooops... I guess it still needs approval.

No problema @bainternet, I'll do just that!

Thanks

**Comment by attritionorg** [comment]
@zeinnicholas @bainternet Can one of you provide an update on the disposition of this issue? Was it ultimately fixed? Thanks!

**Comment by zeinnicholas** [comment]
> @zeinnicholas @bainternet Can one of you provide an update on the disposition of this issue? Was it ultimately fixed? Thanks!

@attritionorg My findings were inconclusive. I couldn't verify with certainty if the extension in question was the root of the issue, and this was more of a TinyMCE problem than an Elementor problem.

I should disclose that at the time it was happening in a client website with a nulled/gpl plugin that I wasn't aware it was installed (the plugin in questions was Yith WooCommerce Wishlist Premium, installed by another person). I can't say if that played a role in allowing the script to be injected or not. Nonetheless, I had to run a complete scan and ended up uninstalling AdBlock Plus from the site as well.

What I can say is how to remove it successfully:

Disconnect every single user from the server. Clear all of the cookies from your browser. Do a search in the database for one of the strings the script injects, and make sure you delete all of those injections (tedious and dangerous job, make sure you backup your site). This is better done via phpMyAdmin. Then revisit one of the places you found the injected script and check if it appears again. If it doesn't, you've succeded in removing the threat. If it does, it could be something else.

**Comment by attritionorg** [comment]
@zeinnicholas Thanks for the detailed update, that is very helpful.
