### ISSUE TITLE
Option to open link in new tab has disappeared since last update 

### ISSUE THREAD

**Issue by brunocerq** [elementor/elementor#9735]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

When editing a link in text editor inside elementor, the option to open a link in a new tab has disappeared.

## Steps to reproduce

Go inside text editor, create a link, go to link options, there is no checkmark option to open the link in a new tab like there was before.
Attached is a picture showing the issue.
![Capture](https://user-images.githubusercontent.com/30045642/69917202-60fd1680-145b-11ea-8f16-acb8b325df64.JPG)

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.28
	PHP Version: 7.2.25
	PHP Max Input Vars: 100000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3
	Site URL: https://www.cryptocurrencyguide.org
	Home URL: https://www.cryptocurrencyguide.org
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Buzz
	Version: 5.1.0
	Author: Pojo Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.120 Safari/537.36

== Active Plugins ==
	ADS PRO – Multi-Purpose WordPress Ad Manager
		Version: 4.2.71
		Author: Scripteo

	Akismet Anti-Spam
		Version: 4.1.3
		Author: Automattic

	Code Snippets
		Version: 2.13.3
		Author: Shea Bunge

	Cool Tag Cloud
		Version: 2.18
		Author: WPKube

	Cryptocurrency Widgets PRO
		Version: 2.3.2
		Author: Cool Plugins

	Elementor
		Version: 2.8.0-beta1
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.3
		Author: Elementor.com

	Featured Images in RSS for Mailchimp & Other Email
		Version: 1.5.4
		Author: 5 Star Plugins

	GA Google Analytics
		Version: 20191109
		Author: Jeff Starr

	Google XML Sitemaps
		Version: 4.1.0
		Author: Arne Brachhold

	GTranslate
		Version: 2.8.50
		Author: Translate AI Multilingual Solutions

	Head, Footer and Post Injections
		Version: 3.1.3
		Author: Stefano Lissa

	OneSignal Push Notifications
		Version: 1.17.9
		Author: OneSignal

	Open Graph and Twitter Card Tags
		Version: 2.2.7.2
		Author: Webdados

	Pojo Custom Fonts
		Version: 1.0.5
		Author: Pojo Team

	Pojo Lightbox
		Version: 2.0.8
		Author: Pojo Team

	Pojo Sidebars
		Version: 1.0.3
		Author: Pojo Team

	Shortcode Widget
		Version: 1.5.2
		Author: Gagan Deep Singh

	Social Auto Poster
		Version: 3.0.3
		Author: WPWeb

	The SEO Framework
		Version: 4.0.4
		Author: The SEO Framework Team

	UpdraftPlus - Backup/Restore
		Version: 1.16.20
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.4.1
		Author: Wordfence

	WP-Sweep
		Version: 1.1.1
		Author: Lester 'GaMerZ' Chan

	WP Config File Editor
		Version: 1.6.7
		Author: AHMeD SAiD

	WP Maintenance Mode
		Version: 2.2.4
		Author: Designmodo

	WP Mega Menu Pro
		Version: 2.0.1
		Author: AccessPress Themes

	WP Rocket
		Version: 3.4.2.2
		Author: WP Media

	WP User Avatar
		Version: 2.2.4
		Author: flippercode

	WPWeb Updater
		Version: 1.1.0
		Author: WPWeb

== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		author-box : 1
		heading : 1
		html : 2
		sidebar : 2
		theme-archive-title : 1
	header : 1
		image : 1
		wp-widget-wpmegamenu_widget : 1
	page : 6
		archive-posts : 1
		author-box : 1
		heading : 1
		html : 2
		shortcode : 1
		sidebar : 1
		spacer : 3
	section : 26
		archive-posts : 1
		author-box : 2
		button : 1
		facebook-page : 1
		form : 1
		global : 3
		heading : 14
		html : 3
		icon : 1
		icon-list : 3
		image : 3
		posts : 5
		share-buttons : 2
		sidebar : 2
		tabs : 2
		text-editor : 7
		wp-widget-gtranslate : 1
	single : 3
		author-box : -4
		divider : 1
		heading : 3
		html : -2
		post-comments : 1
		post-info : 2
		post-navigation : 1
		search-form : 1
		share-buttons : 1
		sidebar : 1
		spacer : 2
		theme-post-content : 1
		theme-post-title : 1
	wp-post : 382
		author-box : 19
		button : 1
		global : 406
		heading : 293
		html : 3
		icon-list : 225
		image : 6
		shortcode : 1
		text-editor : 583
		video : 2
	wp-page : 13
		button : 2
		call-to-action : 1
		form : 4
		heading : 16
		html : 12
		icon-list : 1
		image : 10
		posts : 7
		shortcode : 1
		sidebar : 12
		text-editor : 10

== Log ==
	
PHP: showing 2 of 2PHP: 2019-11-07 06:06:26 [notice X 63444][/home/usitechp/cryptocurrencyguide.org/wp-content/plugins/elementor-pro/modules/library/wp-widgets/elementor-library.php::40] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-07 06:53:49 [notice X 1553][/home/usitechp/cryptocurrencyguide.org/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::1302] Undefined index: button_icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 1 of 12019-11-25 14:30:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.0-beta1',
)]

JS: showing 1 of 1JS: 2019-11-30 19:46:04 [error X 1][https://www.cryptocurrencyguide.org/wp-content/plugins/elementor/assets/js/editor.js?ver=2.8.0-beta1:21065:9] self.ui.form is undefined

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8

Feel free to update

Thanks!
