### ISSUE TITLE
Using Elementor without Gutenberg ?

### ISSUE THREAD

**Issue by JOduMonT** [elementor/elementor#9737]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor won't load if you desactive Gutenberg

In my case I was using a this code in function.php of my child theme (Astra 2.1.3
 and Page Builder Framework 2.1.2) since almost a month without issue

```
// disable for posts
add_filter('use_block_editor_for_post', '__return_false', 10);

// disable for post types
add_filter('use_block_editor_for_post_type', '__return_false', 10);
```

than this weekend Elementor was only loading on the old post, if I create a new post than fire Elementor, it's end into a never ending loading, unless I remove those 2 lines and try again.

## Steps to reproduce

To make the test more kosher, you could try with the plugin **Disable Gutenberg**, when this plugin is active, Elementor won't load.

## Isolating the problem

- [x] I'm using Elementor Pro, but pretty it's happen with Elementor too.
- [x] This bug happens with a Astra 2.1.3 and Page Builder Framework 2.1.2 WordPress theme.
- [x] As soon you disable Gutenberg, by any way (plugin or snippet) Elementor won't load.

## Expectation

I would love to run Elementor without Gutenberg dependancy, which was working before. If it's not possible I would like to be able to make Elementor as the default editor instead of always having two steps to edit a page/post.

## Related

- https://github.com/elementor/elementor/issues/4223

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
