### ISSUE TITLE
Pro Gallery bug - no navigation in lightbox

### ISSUE THREAD

**Issue by sf-steve** [elementor/elementor#9741]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Swapping a regular Elementor basic gallery for a pro gallery, the use is not able to navigated between opened images, as there are no backwards and forwards buttons.

## Steps to reproduce

Create a basic gallery, and a pro gallery with the same images. Clicking an image in the basic gallery will open a lightbox with back and forwards buttons, and a close button.
Doing the same with the pro gallery will open a lightbox with only a close buttton

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

Server Environment		
Operating System:	Linux							
Software:	Apache/2.4.18 (Ubuntu)							
MySQL version:	(Ubuntu) v5.7.28							
PHP Version:	7.1.26-1+ubuntu16.04.1+deb.sury.org+1							
PHP Max Input Vars:	1000							
PHP Max Post Size:	512M							
GD Installed:	Yes							
ZIP Installed:	No							
Write Permissions:	All right							
Elementor Library:	Connected							
WordPress Environment		
Version:	4.9.12							
Site URL:	https://REMOVED.lo.cal							
Home URL:	https://REMOVED.lo.cal							
WP Multisite:	No							
Max Upload Size:	512 MB							
Memory limit:	512M							
Permalink Structure:	/%postname%/							
Language:	en-GB							
Timezone:	Europe/London							
Admin Email:	steve@*******.co.uk							
Debug Mode:	Active							
Theme		
Name:								
Version:								
Author:								
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a child theme.						
User		
Role:	administrator							
WP Profile lang:	en_GB							
User Agent:	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36							
Active Plugins		

								Elementor - 2.7.5								
								By Elementor.com								

								Elementor Pro - 2.7.2								
								By Elementor.com								

								Post Duplicator - 2.20								
								By Metaphor Creations								

								SVG Support - 2.3.15								
								By Benbodhi								

								WordPress Importer - 0.6.4								
								By wordpressdotorg								

								Yoast SEO - 12.2								
								By Team Yoast
					
```
</details>

**Comment by shilo-ey** [comment]
Hi @sf-steve 

Thanks for your feedback.

Make sure your Pro plugin is updated, as for our inspection, we couldn't reproduce this issue.

Thanks

**Comment by birdbrainsolutions** [comment]
@shilo-ey Check the gallery navigation after logging out, the issue is still there
