### ISSUE TITLE
Fold Unfold height for Tablets and Smartphones not working

### ISSUE THREAD

**Issue by sonnesworld** [elementor/elementor#9752]
I use the unfold/fold function on a clients website. I really like it but I can't set the height for Tablets and Smartphones. When i change the size nothing happens … 
https://drive.google.com/file/d/1JYHR2LR4UZo4mN9-LBHNIo0P4O9733yY/view?usp=sharing

Here the page: https://teamwaerts.ch/verkaufsschulung-ostschweiz/

**Comment by shilo-ey** [comment]
Hi @sonnesworld 

This is not a native Elementor widget.

Please contact its authors.

Thanks
