### ISSUE TITLE
Description is not working in Heading Control

### ISSUE THREAD

**Issue by anikitas** [elementor/elementor#9755]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Hello,
Using Heading Control when you try to add a description as an argument, description is not visible. It seems that this is not working, even if it's defined in the documentation as a valid argument.
So either it's a small bug or possibly documentation is wrong.

https://developers.elementor.com/elementor-controls/heading-control/

Thanks
 
## Steps to reproduce

To reproduce just create a heading control with a descripton
e.g:
<pre>
$this->add_control(
	'more_options',
	[
		'label' => __( 'Additional Options', 'plugin-name' ),
		'type' => \Elementor\Controls_Manager::HEADING,
		'description' => __( 'Sample Description', 'plugin-name' ),
		'separator' => 'before',
	]
);	
</pre>
## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@anikitas 

This is the desired behavior. Heading control has only a label:
https://github.com/elementor/elementor/blob/7b86922eda1c664c7473c94d7e20e2295da5d5de/includes/controls/heading.php#L59-L65

If you need more then a simple heading, try using the `RAW_HTML` control
https://github.com/elementor/elementor/blob/7b86922eda1c664c7473c94d7e20e2295da5d5de/includes/controls/raw-html.php#L42-L49

thanks.

**Comment by anikitas** [comment]
No problem,

Then maybe you need to correct the documentation to avoid the confusion.


![Heading_Control_description_arg](https://user-images.githubusercontent.com/7165893/70139303-dd316d00-169a-11ea-82d7-63d4bc261f42.png)

Thanks in advance!
