### ISSUE TITLE
Add excerpt alignment

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#9757]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I'm using the post excerpt widget and I need to justify it the text. Other widget (i.e. title widget, featured image, author box) all have the alignment options. It should be in the excerpt widget too!

**Describe alternatives you've considered**

I'll have to use custom CSS, but that's not convenient.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
