### ISSUE TITLE
Elementor does not support 2-3-4 of addons

### ISSUE THREAD

**Issue by justdudeone** [elementor/elementor#9762]
Hello,

It's NOT just a support question - it's a **HUGE FUNDAMENTAL PROBLEM of Elementor!!!**
(I already try to resolve it via your Pro support - they can't handle with this, this problem must have a some in-Elementor new software solution!!!)

Long story short - after adding more Elementor addons-widgets as (even any 2-3 of them): [Elementor + Elementor Pro itself + Elementor Premium addons + Elementor Premium addons Pro + Namogo Elementor Extras + Element Pack Pro] to a one site (based on best of the best shared hosting with: 768Mb of php memory, 120sec of php timeout and CloudFlare) - Elementor widgets panel are hang out, freezes. I see all Elementor interface, upper and bottom buttons of Elementor panel works normally, but widgets list are freezes with loading circle. It happens on existed Elementor templates editing and on a new empty templates creating. Repeat - it happens when any 3 and more of those addons are activated at WP plugins list. If deactivate any of them - then Elementor works normally with any 1-2 of them.

**So this is obviously some kind of "site overloading" by too much Elementor addons-widgets.**
Firstly helps this solution: php.ini: max_input_vars = 10000 
But after adding 4-th addon it's not working.

Also I try without success:
wp-config.php: define('WP_MEMORY_LIMIT','300M');
wp-config.php: set_time_limit(300);

Unfortunately not your Elementor Pro support, not developers of all those addons, not hosting server support - can't resolve this problem.

**So seems that this problem can be resolved ONLY BY Elementor DEVELOPERS!
Please, add some kind of a "too much widgets overloading protection"!**
Maybe it can work by preliminary testing of current site resources and tune-up settings or widgets loading, or just add a "lazy-loading" to a widgets panel, or don't load widgets functionality before they chosen, etc something like that.

**Please, help to resolve it ASAP** because I can't use needed addons and this problem will arrive more and more with many users who bought 2-3-4 addons!

**Comment by Zexler** [comment]
Yes, this is a real problem. I have already come across it many times, because of which I have to choose which add-ons to install and which ones to do already with the help of a clean CSS. I think the developers will not answer your question, because this problem is caused by the imperfection of the architecture, and may require a lot of effort to fix it. No one expected the Elementor to be so popular. It still amazes me that there are many years of user requests that ask for things that are obvious to our time, such as ajax load more, etc.

**Comment by justdudeone** [comment]
I don't think that this is very complicated, because when widget panel are freezes - all other Elementor editor functionality still works normally - so widgets are isolated, so they are not a piece of an Elementor  deep architecture.

Also one very simple temporal solution - is just add to Elementor/Pro possibility to SWITCH OFF its own widgets one-by-one as is works at Premium addons / Namogo Extra / Element Pack Pro / etc. I need Elementor Pro for deep theme editing, therefore I need more functional elements than default Elementor/Pro - this function will give possibility to save theme-editing possibility with best widgets. (But repeat - this is are only a temporal solution, or just an another Elementor must-have option.)

**Comment by AbanobAkram** [comment]
Right, Elementor devs team needs to find a solution for this.

**Comment by justdudeone** [comment]
Also I want to assure Elementor developers that other addons are not really a competitors of your ElementorPro - because the most important improvement of ElementorPro against Elementor – are not widgets, but possibility to style WHOLE THEME! This possibility are lack at any other addons. So any other addons are NOT a really ElementorPro competitors and you must not afraid to resolve this problem for such reason.

But, as Elementor developers - you must resolve this fundamental problem fro your clients!

If you make it at ElementorPro only - it will definitely close all such questions and force users to buy your Pro version! ;)

**Comment by shilo-ey** [comment]
Hi @justdudeone 

Thanks for your feedback.

Elementor is a standalone plugin that has some minimum requirements.

If you use 3rd party plugins - we can't take responsibility for their performance. and on how they affect your server.

The more plugins you have equals more memory and CPU usage your site will need, therefore we recommend using our [Requirements](https://docs.elementor.com/article/38-requirements).

Out of the box, with a well-configured server - there is no reason (and we couldn't reproduce your issue) that this issue will occur or that your server will crash.

Thanks!

**Comment by justdudeone** [comment]
Hi, **shilo-ey**

All what you have wrote - is a lie and a total unprofessionalism and irresponsibility.

Elementor is not a standalone plugin - because Elementor create it's own ecosystem for a which reliable work now Elementor are responsible.

I use it on the best-of-the best shared hosting with tons of resources.

As I already write many times - this problem happen not because of any of 3-rd party plugins-addons, but with any addons because THIS IS A FUNDAMENTAL PROBLEM OF ELEMENTOR - how Elementor works/load widgets. 

As an obvious similar example - look at DSLR cameras ecosystems (Canon/Nikon/Sony/etc) - changing the original camera lenses from camera manufacturer to a 3rd party lenses (Sigma/Tamron/etc) - it's not a problem, all works fine. But at your Elementor and even payable ElementorPro it's impossible to change your widgets to another,

If you think a little - you will understand that Elementor developers MUST use one of solutions suggested by me for sure.

**Comment by Zexler** [comment]
I think the development team should not dismiss such problems, but solve it.

At a minimum, you yourself gave the other developers documentation that indicated how to connect new widgets. It turns out that the issue of connectivity and compatibility is on your side. And it’s one thing when I can’t load the page with third-party widgets, and another when I can’t start the editor itself!
