### ISSUE TITLE
Custom Query Filter - sorting by multiple fields

### ISSUE THREAD

**Issue by davidzack** [elementor/elementor#9770]
I'm trying to figure out if it's possible to write a custom query to sort a post module by multiple ACF fields. I have a CPT for PEOPLE, and I have ACF fields for first_name and last_name. I'd like to sort them alphabetically, which means by last name then first (in case two people have the same last name.)

Here's what I have so far:
```PHP
add_action( 'elementor/query/peopleorder', function( $query ) {
	// Set the query to fetch people ordered by Last Name, First Name

	$query->set( 'post_type', [ 'people' ] );
	$query->set('orderby', 'meta_value'); 
	$query->set( 'order', 'ASC' );
	$query->set('meta_key', array( 'last_name', 'first_name' ));

} );
```
The last line does not work. That array seems to only follow the last value. So I think this may require some sort of nested query. 

Is there a way to do a compound sort order?

Thanks

**Comment by bainternet** [comment]
@davidzack 

This is more of a WordPress question than an Elementor,
To order WP_Query by multiple meta keys you need define a named clause meta query and then you can use it in the `orderby` parameter something like this:

```PHP
add_action( 'elementor/query/peopleorder', function( $query ) {
	// Set the query to fetch people ordered by Last Name, First Name

	$query->set( 'post_type', [ 'people' ] );
	$query->set( 'meta_query' => [
        'relation' => 'AND',
        'last_name_clause' => [ // named clause
            'key' => 'last_name',
            'compare' => 'EXISTS',
        ],
        'first_name_clause' => [ // named clause
            'key' => 'first_name',
            'compare' => 'EXISTS',
        ], 
    ] );
	$query->set( 'orderby' => [
  	    'last_name_clause' => 'ASC',
        'first_name_clause' => 'ASC',
    ] );
} );
```

Hope this helps.

**Comment by davidzack** [comment]
Thanks!  That almost worked, but I had to change a couple of T_Double_Arrows.

Here's what worked for me:

`add_action( 'elementor/query/peopleorder', function( $query ) {
	$query->set( 'post_type', [ 'people' ] );
	$query->set( 'meta_query', [
        'relation' => 'AND',
        'last_name_clause' => [ // named clause
            'key' => 'last_name',
            'compare' => 'EXISTS',
        ],
        'first_name_clause' => [ // named clause
            'key' => 'first_name',
            'compare' => 'EXISTS',
        ], 
    ] );
	$query->set( 'orderby', [
  	    'last_name_clause' => 'ASC',
        'first_name_clause' => 'ASC',
    ] );
} );`

**Comment by godutchwine** [comment]
Thanks so much for this. However, somehow I have trouble ordering the posts.

I have a CPT with a numeric field (year) and an array of strings (names selected with a dropdown in ACF). I would like to order the posts by (1) year, descending and then (2) author, ascending. The sorting by year works fine, but whatever I try it won't correctly sort the author. It seems to sort by publication date instead and ignore the meta_value. Can anyone help?

This is what I have now:

`add_action( 'elementor/query/winebooksorder', function( $query ) {
	$query->set( 'post_type', [ 'winebooks' ] );
	$query->set( 'meta_query', [
        'relation' => 'AND',
        'wine_book_year_clause' => [ // named clause
            'key' => 'wine_book_year',
            'compare' => 'EXISTS',
        ],
        'wine_book_author_clause' => [ // named clause
            'key' => 'wine_book_author',
            'compare' => 'EXISTS',
        ], 
    ] );
	$query->set( 'orderby', [
  	    'wine_book_year_clause' => ['meta_value_num','DESC'],
        'wine_book_author_clause' => ['meta_value','ASC']
    ] );
} );`

**Comment by hellomahfuzpro** [comment]
> @davidzack
I have a custom post type called music, I want to sort the order of the music posts by a custom field called 'music_featured'. Also, I filtered music posts by custom taxonomies from the post widget. So far I've written this code for the sorting

`add_action( 'elementor/query/my_custom_music_feature_sorting', function( $query ) {
	
	$meta_query = $query->get( 'meta_query' );
	$query->set( 'meta_query', $meta_query );
	$query->set('orderby', 'meta_value'); 
	$query->set( 'order', 'ASC' );
	$query->set('meta_key', 'music_featured' );
} );`

But it seems it's not working. How do I get it working?
Thanks

**Comment by speedxcz** [comment]
Hi, I also solved this for a long time and finally I found that for dates, numeric data, you need to add the type NUMERIC. And for example, for time values, it is better to use CHAR:

```
add_action( 'elementor/query/winebooksorder', function( $query ) {
	$query->set( 'post_type', [ 'winebooks' ] );
	$query->set( 'meta_query', [
        'relation' => 'AND',
        'wine_book_year_clause' => [ // named clause
            'key' => 'wine_book_year',
            'type' => 'NUMERIC',
            'compare' => 'EXISTS',
        ],
        'wine_book_author_clause' => [ // named clause
            'key' => 'wine_book_author',
            'compare' => 'EXISTS',
        ], 
    ] );
	$query->set( 'orderby', [
  	    'wine_book_year_clause' => ['meta_value_num','DESC'],
        'wine_book_author_clause' => ['meta_value','ASC']
    ] );
} );
```


> Thanks so much for this. However, somehow I have trouble ordering the posts.
> 
> I have a CPT with a numeric field (year) and an array of strings (names selected with a dropdown in ACF). I would like to order the posts by (1) year, descending and then (2) author, ascending. The sorting by year works fine, but whatever I try it won't correctly sort the author. It seems to sort by publication date instead and ignore the meta_value. Can anyone help?
> 
> This is what I have now:
>
