### ISSUE TITLE
Slider with custom content/layout

### ISSUE THREAD

**Issue by pedrosromano** [elementor/elementor#9771]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Almost every project I develop needs a slider with custom content. For example, columns with text, icons and images, in each page of the slider. The built in elementor slider only allows for background images and text overlay with preset positions. I most projects, I end up developing a custom widget to achieve the design the client asked for.

**Describe the solution you'd like**
I think it would be a great feature to have a slider with an inner section for each slide, enabling me to fully customize the slider content.

**Describe alternatives you've considered**
I've considered external plugins and i've been developing custom widgets to achieve the custom sliders I need

**Comment by swinggraphics** [comment]
I agree that it should be built in. For now, you can hack it by initiating the slider on your own in JavaScript. This is how I threw it together on a previous project; probably could be improved, but it worked fine:

```JavaScript
/* Section slider */
var sliderSelector = 'body:not(.elementor-editor-active) .elementor-section-wrap > .elementor-section.slide-group';
var mythemeSliders = [];
var mythemeSliderWaypoints = [];
$(sliderSelector).each(function(){
	var $section = $(this);
	if( ! $section.is(sliderSelector) ) return;
	// Wrap slider sections in a group
	$section.nextAll(sliderSelector).addBack().addClass('swiper-slide')
	.wrapAll('<div class="mytheme swiper-container"/>')
	.wrapAll('<div class="swiper-wrapper"/>');
});
$('.mytheme.swiper-container').append('<div class="swiper-pagination" />');
$('.mytheme.swiper-container').each(function(i){
	$(this).append('<div class="swiper-pagination" />');
	mythemeSliders.push( new Swiper(this, {
		autoplay: false,
		loop: false,
		speed: 1000,
		effect: 'fade',
		fadeEffect: {crossFade: true},
		pagination: {
			el: '.swiper-pagination',
			type: 'bullets',
			clickable: true,
		},
		mousewheel: false
	}) );
	mythemeSliderWaypoints.push( new Waypoint({
		element: this,
		offset: 'bottom-in-view',
		handler: function(){
			mythemeSliderWaypoints[i].destroy();
			mythemeSliders[i].params.autoplay = {
				delay: 3000,
				disableOnInteraction: true
			};
			setTimeout(function(){
				mythemeSliders[i].slideNext();
				mythemeSliders[i].autoplay.start();
			}, 1500);
		}
	}) );
});
```
(Dependencies are `[ 'jquery', 'elementor-waypoints' ]`)

**Comment by pedrosromano** [comment]
Hi,
Thanks! How can i integrate that solution? I tried creating inner sections with each section being the slide-group, or using columns but none of them worked

**Comment by swinggraphics** [comment]
> Hi,
> Thanks! How can i integrate that solution? I tried creating inner sections with each section being the slide-group, or using columns but none of them worked

You can see it implemented here: https://itrigirls.org/. Each Section gets the "slide-group" class. In the editor, they will just look like normal sections.

**Comment by pedrosromano** [comment]
Got it! Any way of having multiple sliders in the same page?

**Comment by swinggraphics** [comment]
> Got it! Any way of having multiple sliders in the same page?

As long as something is between the groups, you can have multiple (unless I made a mistake in the code).

**Comment by vgstef** [comment]
swinggraphics, could you explain how and where to use your script?

**Comment by emeraldsama** [comment]
@vgstef

1. Enqueue the script in your theme or in a plugin. The simplest (though probably not best) way is in your (child or custom) theme's functions.php file. You need to include jQuery and elementor-waypoints as dependencies, meaning this custom script loads after.
`  function custom_ele_js() {
        wp_enqueue_script( 'slide_anything_ele', get_stylesheet_directory_uri() . '/assets/js/slide_anything_ele.js', ['jquery','elementor-waypoints'], null, true );
    }
add_action( 'wp_enqueue_scripts', 'custom_ele_js', 10 );`

2. Create the JS file (slide_anything_ele.js) with the script above.Save it to the file path location like shown (theme-folder/assets/js).

3. In the JS file, you may need to wrap the script in a document.ready() function. 
`jQuery(document).ready(function ($)
{ INSERT OPs CODE HERE
});`
4. Add the "slide-group" class to each Elementor Section to make it a slide.

**Comment by vgstef** [comment]
An idea. How about creating an Elementor slider widget that would use popups for slides. That would make it easy to create slides and the widget would simply need to let us choose popups and show them as slide instead of popups.

**Comment by swinggraphics** [comment]
@vgstef Good point. For that matter, a slider widget could use any template, and "Slider" could just be a new template category.

**Comment by swinggraphics** [comment]
@vgstef Good point. For that matter, a slider widget could use any template, and "Slider" could just be a new template category.

**Comment by shaneonabike** [comment]
This works super well and finally creates a solution for custom post types hooray! I'm just curious why you didn't use the autoplay that is setup with the actual Swiper @swinggraphics ?

**Comment by swinggraphics** [comment]
@shaneonabike What is "the autoplay that is setup with the actual Swiper"?

**Comment by shaneonabike** [comment]
It's based on https://swiperjs.com/api/#autoplay which I noticed you had set to false and then created your own system to autoplay. I just wanted to verify that wasn't some glitche you had noticed. Perhaps you just scraped the code from the Elementor widget that uses this?

**Comment by swinggraphics** [comment]
If autoplay were true, it would start while still off screen. The timout is because I'm waiting until the bottom is in view to start and the section is 100vh, the 3000 delay felt too long for the fist slide.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by shaneonabike** [comment]
Uhhh it's not really the same subject... the title of the other ticket doesn't refer to Slideshow at all but embed widgets into other widgets. I don't understand

**Comment by swinggraphics** [comment]
> Uhhh it's not really the same subject... the title of the other ticket doesn't refer to Slideshow at all but embed widgets into other widgets. I don't understand

It makes sense if their idea is to add a feature where any group of elements or a section can be turned into tabs, accordion, or slider. 🤞

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Carousel in Elementor Pro v3.14.0! 🥳 

You can now create slides with nested elements inside them and customize pretty much every aspect of your carousel.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
