### ISSUE TITLE
Support for dark mode (prefers-color-scheme) for Color Picker.

### ISSUE THREAD

**Issue by numanzahid** [elementor/elementor#9772]
There is similar request but that is only for elementor UI. https://github.com/elementor/elementor/issues/9263
I want to talk about dark mode in page design.

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Dark Mode is almost everywhere. but web designer using elementor only has ability to design only one mode. we can not define different colors for both modes.

some say that the dark mode is a health related issue. as you can see with https://github.com/elementor/elementor/issues/9263 
dark mode web design could also help with this issue.

**Describe the solution you'd like**
there should be an option to allow dark mode in elementor settings and with color picker. this setting will follow browser color scheme as defined `prefers-color-scheme`
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

switch on **Dark Mode Colors** option in elementor setting will enable an extra color picker for dark mode just like it does with responsive options. plus it will simulate how page will look in dark mode like it does with responsive options.

Please separate it from elementor editor UI. elemntor UI is just for the designer. there should be separate options for both **Dark Mode Colors** **Dark Mode Editor**

**Comment by shilo-ey** [comment]
I merged this issue with #9263 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

By the way, try out v2.8 beta.

Thanks for your feedback!

**Comment by numanzahid** [comment]
@shilo-ey  Can you please check. it is not same subject. the thread is only for elementor editor UI UX.

whereas I am talking about page design. it is not same.

**Comment by drawcard** [comment]
Copypasta: https://github.com/elementor/elementor/issues/9263#issuecomment-562490421

**Comment by drawcard** [comment]
(sorry deleted my other comment by accident)

Would like to see this feature +1. Perhaps it could be implemented as a Global Style setting in Section elements (where hyperlink / heading styles are currently)

**Comment by numanzahid** [comment]
If there is an option to enable dark mode color picker in the elementor settings (which can be off by default). and allow user to switch it on, this will make it less complicated for people who don't want to use it.

the color picker can fall right in the style of new responsive selector.

something like this:
![nightmode color selector (1)](https://user-images.githubusercontent.com/6734385/70410977-b2685f80-1a72-11ea-9543-965263c67935.png)

**Comment by drawcard** [comment]
Great idea, since that badge could just appear globally on every colour setting across Elementor!

**Comment by numanzahid** [comment]
do you have any idea how this topic can be open again and should not be mixed with https://github.com/elementor/elementor/issues/9263

because these are two different features and need to be addressed separately. I don't know why it was merged with dark mode of Elementor UI in the first place and closed.

**Comment by drawcard** [comment]
I would ask @shilo-ey or @bainternet what the specific rules are around re-opening old issues as new ones.

**Comment by jmzolezzi** [comment]
The solution proposed by @numanzahid looks really nice and should be lightweight.

Hopefully it's added to Elementor or Elementor Pro soon, and this issue reopened.
