### ISSUE TITLE
Add dynamic options to button inside slider widget

### ISSUE THREAD

**Issue by knireis** [elementor/elementor#9774]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I would like to add a popup to the button in the slider widget. This will not work without the dynamic option available.

**Comment by kassabulatova** [comment]
I support! The function is absolutely required to be

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
