### ISSUE TITLE
Conditional form actions

### ISSUE THREAD

**Issue by Talco100** [elementor/elementor#9790]
Today when a form is submitted - all actions run automatically.
BUT - many times we need only an action to run based on what the user did with the form.
i.e. 'subscribe to Getresponse' **ONLY IF** checkbox X was actually checked,
OR
Send a Webhook email only if field Y = Z.

**Comment by shilo-ey** [comment]
Duplicate of #2638

**Comment by Talco100** [comment]
Thanks Shilo
But as far as I understand - #2638 talk about the display of fields, and not about whether an action will be fired r not.
Did I get it right?

**Comment by dbjpanda** [comment]
@shilo-ey I think you should read the original issue again and reopen it.
