### ISSUE TITLE
Elementor Pro gallery widget not working in IE11

### ISSUE THREAD

**Issue by Netzlichter** [elementor/elementor#9791]
Hi there,

Im using the latest versions of Elementor and Elementor Pro.

The Pro gallery widget isnt loading images in IE11. And it is causing some javascript conflicts so some other elements are not working too (Elementor accordeon on the same site).

I know Internet Explorer 11 is a bad and old browser but there are 10% of people using it...

Big thanks in advance.

**Comment by filipe-q** [comment]
I had this exact issue (Elementor Pro Gallery and Accordion on same page). Here's how I fixed it:

.team-grid.elementor-widget-image-gallery.elementor-element {
    .gallery {
        margin-left: -15px;
        margin-right: -15px;
        width: calc(100% + 30px);

        @media (max-width: $mobile) {
            margin-left: -5px;
            margin-left: -5px;
            width: calc(100% + 10px);
        }
    }

    figure.gallery-item {
        margin: 15px;
        max-width: calc(16.666% - 30px);

        @media (min-width: $tablet-start) and (max-width: $tablet-end) {
            margin: 15px;
            max-width: calc(25% - 30px);
        }

        @media (max-width: $mobile) {
            margin: 5px;
            max-width: calc(50% - 10px);
        }
    }

    img {
        border-radius: 10px;
    }
}

.elementor-msie {
    .team-grid {
        .elementor-gallery__container {
            display: block;

            .e-gallery-item {
                float: left;
                width: calc(16.6666% - 20px);
                margin: 10px;
                height: 150px; // May have to be done inline with JS

                @media (min-width: $tablet-start) and (max-width: $tablet-end) {
                    width: calc(25% - 20px);
                }

                @media (max-width: $mobile) {
                    width: calc(50% - 20px);
                }

                .e-gallery-image {
                    width: 100%;
                    height: 100%;
                }
            }
        }
    }
}

The first part is what I wanted to do and then the second part is what I needed to do in order to get IE to look the same as on other browsers.

Then I had to use this JS
// Team Grid Img Height
teamImg = $('.team-grid img');
teamImgHeight = teamImg.width();
teamImg.css('height', teamImgHeight);

And you have to use a PolyFill in IE to have object-fit:cover
var someImages = document.querySelectorAll('.object-fit-cover img, .object-fit-contain img');
objectFitImages(someImages);
I'm using https://github.com/fregante/object-fit-images#readme

Sorry for the bad formatting but I don't know what is causing it.

**Comment by Netzlichter** [comment]
Hi filipe-q. Thank you for your answer and research. But I think I will wait for the Elementor team... BEcause this site is in development.

**Comment by filipe-q** [comment]
I agree that is the right thing to do but I'm pretty sure their answer is going to be this:
[https://docs.elementor.com/article/38-requirements](url) (See the paragraph about browsers)

**Comment by shilo-ey** [comment]
Hi @Netzlichter 

Thanks for your feedback, and @filipe-q for your research and contribution.

IE11 is an outdated browser and as mentioned in the link above, some features won't work properly in it. 

Thanks

**Comment by makuc** [comment]
I don't understand how can this issue be closed just like this. Where I'm from, a lot of computers used in shopping centers have outdated computers, hence they use IE. Sellers a lot of times open our company's website to show their costumers some information, which means I **have** to make websites IE compatible.

According to the link posted above: "Please note that you must use Chrome, Firefox, Safari, or Microsoft Edge version 79 or greater to **EDIT** pages with Elementor." Nowhere does it mention anything about NOT supporting IE, only limited support. Limited support doesn't mean broken functionality.

I'm not asking for perfect support in IE (for instance, `Call to Action` isn't displayed quite properly, it isn't functioning perfectly, but it is there and it is usable), but at least we could have the gallery properly displayed, even if its behavior is limited--Lightbox works just fine for a while now.
