### ISSUE TITLE
Get global settings/styles from elementor

### ISSUE THREAD

**Issue by Fr4nkHorr1gan** [elementor/elementor#9792]
Hi guys!
Please help me. How  get these values in the code?
For example, to set them to a variable, output them in a javascript, etc.
And also how can I add custom controls / sections there?
I tried to find something in the documentation, but nothing worked.

![image](https://user-images.githubusercontent.com/42470073/70347496-52529d00-1869-11ea-9081-bd501c02941a.png)
![image](https://user-images.githubusercontent.com/42470073/70324579-882b5d80-1838-11ea-88b7-93ec07311310.png)
![image](https://user-images.githubusercontent.com/42470073/70324857-43ec8d00-1839-11ea-8f59-124ccf83c15c.png)

Many thanks!

**Comment by shilo-ey** [comment]
You can access all the schemes settings by calling `elementor.schemes.getScheme`

For example, to get the value of the “Body Text” (the 3rd) typography, you can call
`elementor.schemes.getScheme('typography').items[3].value`

Read more here: https://developers.elementor.com/elementor-controls/color-control/

Thanks
