### ISSUE TITLE
Inconsistent - Misleading Option's Title: "CSS ID"

### ISSUE THREAD

**Issue by Ale-Digitale** [elementor/elementor#9799]
Inside the optional panel, where you have the chance to assign to your widget an ID,

it's titled: **CSS ID**

but... why ?

Shouldn't it be **HTML ID** or maybe just **ELEMENT ID**

since that ID is (correctly) assigned to the HTML ELEMENT's ID generated for your widget, it's NOT a CSS attribute.

The fact that those ID can be used by CSS Selectors ( but also Javascript's ) is another story !

**Comment by DorShahar** [comment]
Hi
Thank you for sharing your thoughts. 
The reason is since the main use is CSS/JS targeting. This is a common use for new users who need to use ID, and get this information just by learning CSS...

We will leave this option at the moment for backward compatibility. 

Thanks
