### ISSUE TITLE
Sharing Icons in posts widget

### ISSUE THREAD

**Issue by the-gap-decaders** [elementor/elementor#9806]
I would love people to be able to share my content to read later from the posts widget.  I typically share 50 words as an excerpt in the widget, enough for a reader to decide they want to share the post and read later.  Sharing icons in the widget for each post would enable the reader to do this.  The screenshot is an example with the blue line and dots showing where I would envisage the sharing buttons.  Thank you for considering! 
<img width="1439" alt="Screenshot 2019-12-09 at 09 52 04" src="https://user-images.githubusercontent.com/50086184/70421470-189cb480-1a6a-11ea-978a-1fb9a5ddf854.png">

**Comment by rodolphebertozzo** [comment]
+1

**Comment by shilo-ey** [comment]
I merged this issue with #4440 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
