### ISSUE TITLE
widgets and sections disappear when I try to edit saved template

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#9810]
when I try to edit saved templates, section and widget disappear, I tried to clear cache, disable plugins etc. still have same issue, how can I solve it?
![image](https://user-images.githubusercontent.com/2544046/70438896-e4dc8180-1a9f-11ea-8c8a-ba84590aa52a.png)

**Comment by shilo-ey** [comment]
Please update to the latest stable version.
Beta issues should be reported in the Beta thread only.

If this issue persists after updating, please open a new issue and follow the guidelines.

Thanks
