### ISSUE TITLE
Update from 2.7.5 to 2.7.6 causes fatal error

### ISSUE THREAD

**Issue by khag7** [elementor/elementor#9812]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Updated Elementor from within WordPress. Site immediately shows fatal error.

```
[10-Dec-2019 03:05:04 UTC] PHP Fatal error:  Uncaught Error: Call to a member function increase_times() on string in /home/public_html/wp-content/plugins/elementor/core/logger/loggers/db.php:21
Stack trace:
#0 /home/public_html/wp-content/plugins/elementor/core/logger/loggers/base.php(24): Elementor\Core\Logger\Loggers\Db->save_log(Object(Elementor\Core\Logger\Items\Base))
#1 /home/public_html/wp-content/plugins/elementor/core/logger/loggers/base.php(28): Elementor\Core\Logger\Loggers\Base->log(Object(Elementor\Core\Logger\Items\Base), 'info', Array)
#2 /home/public_html/wp-content/plugins/elementor/core/base/db-upgrades-manager.php(65): Elementor\Core\Logger\Loggers\Base->info('Elementor data ...', Array)
#3 /home/public_html/wp-content/plugins/elementor/core/base/db-upgrades-manager.php(115): Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete()
#4 /home/public_html/wp-content/plugins/elementor/core/base/db-upgrades-manager.php(182): Elementor\Core\Base\DB_Upgrades_M in /home/public_html/wp-content/plugins/elementor/core/logger/loggers/db.php on line 21
```

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

I have NOT tested this on a bare install with only Elementor activated, because I know that won't cause the error. If it did, you'd already be aware. I'm not going to waste my time or yours. I recognize this is an issue with either the theme (Page Builder) or a plugin.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.45
	PHP Version: 7.3.8
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3
	Site URL: https://`REMOVED`.com
	Home URL: https://`REMOVED`.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Page Builder Framework
	Version: 2.1.2
	Author: David Vongries
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

== Active Plugins ==

	Akismet Anti-Spam
		Version: 4.1.3
		Author: Automattic

	Better Notifications for WP
		Version: 1.7.5
		Author: Made with Fuel

	CartStack for WooCommerce
		Version: 1.1.1
		Author: CartStack

	Elementor
		Version: 2.7.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.3
		Author: Elementor.com

	Email Log
		Version: 2.3.1
		Author: Sudar

	Embed Plus for YouTube - Gallery, Channel, Playlist, Live Stream
		Version: 13.1.2.5
		Author: Embed Plus for YouTube Team

	Essential Addons for Elementor
		Version: 3.6.1
		Author: WPDeveloper

	Hide Title
		Version: 1.0.8
		Author: Dojo Digital

	HTTP/2 Server Push
		Version: 1.4
		Author: David Michael Ross

	Imagify
		Version: 1.9.8.1
		Author: WP Media

	Ivory Search
		Version: 4.4.2
		Author: Ivory Search

	Mailchimp for WooCommerce
		Version: 2.3
		Author: Mailchimp

	Members
		Version: 2.2.0
		Author: Justin Tadlock

	OMGF
		Version: 2.1.6
		Author: Daan van den Bergh

	Plugin Columns
		Version: 1.2.1
		Author: Roger Grimstad

	PWA
		Version: 0.3.0
		Author: PWA Plugin Contributors

	PW WooCommerce Bulk Edit Pro
		Version: 2.184
		Author: Pimwick, LLC

	PW WooCommerce Gift Cards Pro
		Version: 1.157
		Author: Pimwick, LLC

	Redirection
		Version: 4.5.1
		Author: John Godley

	Remove Howdy
		Version: 1.0
		Author: Nick Adams

	Simple History
		Version: 2.33
		Author: Pär Thernström

	Store Locator Plus®
		Version: 5.3
		Author: Store Locator Plus®

	UPS WooCommerce Shipping
		Version: 3.13.3
		Author: PluginHive

	User Switching
		Version: 1.5.3
		Author: John Blackbourn & contributors

	WooCommerce
		Version: 3.8.0
		Author: Automattic

	WooCommerce Admin
		Version: 0.22.0
		Author: WooCommerce

	WooCommerce Authorize.Net Premium
		Version: 10.8
		Author: Indatos Technologies

	WooCommerce Customer/Order/Coupon CSV Import Suite
		Version: 3.8.0
		Author: SkyVerge

	WooCommerce Google Analytics Pro
		Version: 1.8.6
		Author: SkyVerge

	WooCommerce Print Invoice & Delivery Note
		Version: 4.5.3
		Author: Tyche Softwares

	WooCommerce Refund & Exchange With RMA
		Version: 2.1.5
		Author: makewebbetter <webmaster@makewebbetter.com>

	WooCommerce Sequential Order Numbers
		Version: 1.9.2
		Author: SkyVerge

	WP CLI Login Command Server
		Version: 1.2
		Author: Evan Mattson

	WP External Links
		Version: 2.40
		Author: WebFactory Ltd

	WP LCache
		Version: 0.6.1
		Author: Pantheon, Daniel Bachhuber

	WP PHP Console
		Version: 1.5.4
		Author: Fulvio Notarstefano

	WP Rocket
		Version: 3.4.2.2
		Author: WP Media

	Yoast SEO
		Version: 12.6.2
		Author: Team Yoast

	Yoast SEO: WooCommerce (beta) | release/12.3 | 07-11-2019 10:11
		Version: 12.3-RC1
		Author: Team Yoast

	Zonos Checkout
		Version: 1.3.0
		Author: Zonos

== Log ==
	No entries to display

== Elements Usage ==
	
	footer
		form : 1
		global : 1
		heading : 6
		icon-list : 4
		share-buttons : 1
		theme-site-logo : 1
	header
		nav-menu : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 2
	section
		button : 15
		form : 1
		global : 2
		heading : 9
		icon-list : 4
		image : 14
		share-buttons : 1
		spacer : 20
		text-editor : 9
		theme-site-logo : 1
		video : 1
	wp-page
		button : -691
		form : -125
		global : -27
		google_maps : 12
		heading : -651
		icon : -1
		image : -440
		image-box : 4
		media-carousel : 1
		spacer : -979
		testimonial : 30
		text-editor : -234
		toggle : 1
		video : 1

</details>

**Comment by pako69** [comment]
Hi

Same here and my site is dead.

```
[12-Dec-2019 10:07:35 UTC] PHP Fatal error:  Uncaught Error: Call to a member function increase_times() on string in /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/loggers/db.php:21
Stack trace:
#0 /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/loggers/base.php(24): Elementor\Core\Logger\Loggers\Db->save_log(Object(Elementor\Core\Logger\Items\Base))
#1 /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/loggers/base.php(28): Elementor\Core\Logger\Loggers\Base->log(Object(Elementor\Core\Logger\Items\Base), 'info', Array)
#2 /home/gmao/my.domain.com/wp-content/plugins/elementor/core/base/db-upgrades-manager.php(65): Elementor\Core\Logger\Loggers\Base->info('Elementor data ...', Array)
#3 /home/gmao/my.domain.com/wp-content/plugins/elementor/core/base/db-upgrades-manager.php(115): Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete()
#4 /home/gmao/my.domain.com/wp-content/plugins/elementor/core/base/db-upgrades-manager.php(182): Elementor\Core\Base\DB_Upgrades_Manager->start_run( in /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/loggers/db.php on line 21
[12-Dec-2019 10:07:36 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/loggers/db.php on line 34
[12-Dec-2019 10:07:36 UTC] PHP Notice:  A non well formed numeric value encountered in /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/loggers/db.php on line 18
[12-Dec-2019 10:07:36 UTC] PHP Notice:  Array to string conversion in /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/items/base.php on line 43
[12-Dec-2019 10:07:36 UTC] PHP Notice:  A non well formed numeric value encountered in /home/gmao/my.domain.com/wp-content/plugins/elementor/core/logger/loggers/db.php on line 21
```

**Comment by pako69** [comment]
I found a workaround.

#1 delete Elementor plugin directory
#3 download the latest Elementor version on you computer
#4 edit the file /wp-content/plugins/elementor/core/logger/loggers/base.php
#5 in this file, comment out this line:
`// $this->save_log( $item );
`
#6 upload Elementor to /wp-content/plugins/
#7 check you are using the latest version, in wordpress go to /wp-admin/plugins.php
#8 re download the file /wp-content/plugins/elementor/core/logger/loggers/base.php and remove the php comment out
#9 reupload the this file at the same place
