### ISSUE TITLE
[Feature Request] Support for Woocommerce Membership Extension

### ISSUE THREAD

**Issue by kermit1973** [elementor/elementor#9813]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It is not possible to control the visibilty of Elementor widgets and sections for members / non-members when using the Woocommerce Membership extension.

**Describe the solution you'd like**
I would like to be able to control the visibilty of sections and widgets for members and non-members. 

**Describe alternatives you've considered**
The plugin itself offers member blocks for Gutenberg. 

**Additional context**
I hope to see this feature in a future update!

**Comment by bainternet** [comment]
@kermit1973 


Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
