### ISSUE TITLE
When ever i create a new section the elementor is adding too-many div tags for a single content why?

### ISSUE THREAD

**Issue by Hassanzafar107** [elementor/elementor#9814]
![divs](https://user-images.githubusercontent.com/34653540/70495651-0a18d080-1b30-11ea-8e65-208cd772cc36.PNG)
When ever i create a new section the elementor is adding too-many div tags for a single content why?
the url given below is an example
  | https://www.staging1.toycycle.co/test/
-- | --
 as if you inspect the top heading play more and pay less the number to div tags that are being created are too many.
please help me.

**Comment by Aviad-Herman** [comment]
Hi,
We recently released an experiment to optimize DOM.
Feel free to activate it in Elementor --> Settings --> Experiments
