### ISSUE TITLE
Social Icon Block & Icon Block - alignment is stuck on "left" on mobile view

### ISSUE THREAD

**Issue by mjmultimedia** [elementor/elementor#9822]
Social Icon Block & Icon Block - Alignment is stuck on "left" on mobile view. Even if I change it, it won't change on the mobile preview or show up different when viewing the website on mobile devices. I need to be able to align "right" or "center."

![Mobile Alignment Reference](https://user-images.githubusercontent.com/58740183/70543788-ff166e00-1b38-11ea-9b1a-2e96521b4ff8.png)

![Margin and Padding Reference](https://user-images.githubusercontent.com/58740183/70543787-ff166e00-1b38-11ea-8098-337923ee9c8f.png)

**Comment by shilo-ey** [comment]
Hi @mjmultimedia 

Thanks for sharing this info with us,

Unfortunately, we can't seem to reprocude this issue on our end.

According to the screenshot you shared you are using an outdated version of Elementor. Please upgrade and let us know if there issue persists.

Thanks
