### ISSUE TITLE
Dynamic Lightbox Captions

### ISSUE THREAD

**Issue by jamietreacy1** [elementor/elementor#9826]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need to be able to have captions showing on my dynamic lightbox after clicking on it from my image galleries.  This is an important feature for artists who use Elementor for their portfolio pages. 
**Describe the solution you'd like**
I would like to be able to click on any image in my gallery and have the lightbox pop up with the caption information below.  It would be great to have the option of where to position the text. I love how the gallery thumbnails let me choose where to pull the metadata from in order to form the caption information.  I would like to have this same option for the lightbox. 

**Describe alternatives you've considered**
I've been trying to get my portfolio galleries on my website the way I want them for years.  I settled on Elementor Pro, because I love that I can control the spacing between thumbnail images.  I've tried Envira Gallery and several other plugins, but Elementor is the closest to having everything a visual artist needs to create a stellar customized portfolio page with lightbox viewing environment.

**Additional context**
![image](https://user-images.githubusercontent.com/58745695/70556780-65e65800-1b36-11ea-926e-46b7990a0e08.png)
![image](https://user-images.githubusercontent.com/58745695/70557024-e016dc80-1b36-11ea-8b7b-c45a24f565b1.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!

**Comment by jamietreacy1** [comment]
Thank you so much! I will definitely post positive reviews and tell all my artist friends. The update is wonderful, and it feels so great to know my request was heard!

Have a great day,
Jamie
