### ISSUE TITLE
How to get new Elmentor editor UI color theme settings

### ISSUE THREAD

**Issue by webdevs-pro** [elementor/elementor#9827]
How can i get Elementor UI color theme settings on editor load and theme switch to apply proper css styles to my custom control? I found "onUIThemeChanged" in editor.js, how to use it?

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
