### ISSUE TITLE
Responsive visibility indication

### ISSUE THREAD

**Issue by DmitriyDSWEB** [elementor/elementor#9828]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DmitriyDSWEB** [comment]
You can return the icons as they were before, now it became inconvenient to click them twice to open and then select. Make them always visible, the activity is highlighted, not active, gray.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
