### ISSUE TITLE
[Dark Mode Bug] WordPress Widget settings unreadable

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#9829]
Just a quick bug report, on a fresh install of Elementor 2.8 + blank Wordpress website.

Wordpress widgets (eg the Categories widget) aren't inheriting dark mode styles and are unreadable:

![image](https://user-images.githubusercontent.com/1435638/70573834-ac00f180-1bf2-11ea-9e82-29ef577491f8.png)

**Comment by cirkut** [comment]
Would you mind also posting which browser and operating system you're using and having this issue on?

I haven't encountered this issue across any browsers on macOS.

**Comment by drawcard** [comment]
Sure, Chrome latest stable update, on MacOS Catalina latest update

**Comment by rodolphebertozzo** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8.1

Feel free to update

Thanks!
