### ISSUE TITLE
✅ 🚀 Feature Request: Let us choose the Source of Dynamic content for the Template widget

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#9830]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The Template Widget is only able to take the current post as source for Dynamic content.

**Describe the solution you'd like**

The Template Widget should have an Option to **select the source of the dynamic content**.
Like it is possible in the Preview when editing a Template.

![image](https://user-images.githubusercontent.com/52812059/70580644-79a1c500-1bef-11ea-9140-c358c6a00cc0.png)

This especially makes sense when

1. I want to show dynamic content in a global template
2. I want to separate content and design
3. I want to show Custom Post Types inside my post etc.

**Describe alternatives you've considered**
My current solution (which I think is too much effort for such a basic requirement of dynamic content):

- Use a 3rd party plugin "Elementor Custom Skin" to design a Loop Template for my Custom Post Type
- Use the Posts Widget to show exactly 1 post on 1 page
- Use "Manual Selection" for the Query to choose the Custom Post I want to display
- Elementor Custom Skin then allows to select the Loop Template to render the content in the Posts Widget

**Additional context**

**Comment by KoniKodes** [comment]
+1 - Yes. This is a lot of work for a simple "no-code drag&drop" page builder.

**Comment by nicholaszein** [comment]
Hello there!

### ✅ I believe the feature you requested has been solved by the introduction of the **`Loop Builder`** in **Elementor Pro version 3.8**.

You can learn more about this feature [here](https://elementor.com/help/loop-grid/).

Thank you for contributing and sharing your ideas! 🙏 

If you still think this should be an Elementor feature applied in another manner, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request) indicating exactly what you want, and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
