### ISSUE TITLE
🔗 🚀 Feature Request: Icon List Widget - Set text-indent spacing on the icon span (Related to #2167) - [ED-9757]

### ISSUE THREAD

**Issue by cirkut** [elementor/elementor#9831]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor.

### **What problem is your feature request going to solve? Please describe.**
When using the **Icon List** widget in inline layout mode, utilizing the _Text Indent_ option adds left padding to the `<span>` containing the list item's text. This is an issue when you're using the **Icon List** widget without an icon in list item. Using the _Text Indent_ control on an item without an icon will cause the clickable area/hitbox of the item to have the added padding. 

This can cause undesired spacing when mixing list items that have icons and list items that don't have icons. It's especially noticeable when using the divider functionality, or in the case of underlining the `<a>` tag using custom CSS (which is how I found the root of this issue).

_**Note:** This also happens when the widget is set to default layout mode, but the use-case of mixing icon'ed and non-icon'ed list items is far less common._

### **Describe the solution you'd like**
I would like to propose switching the application of the _Text Indent_ option to adding the padding to the right of the `<span>` that contains the icon, rather than the current implementation of adding left padding to the `<span> that contains the text.

Since the `<span>` that contains an icon does not output if there isn't an icon selected, the text-indent isn't applicable when 

### **Describe alternatives you've considered**
Alternatively, a class could be added to list items that have an icon or don't have an icon and can be used to selectively output the text-indent. The CSS that is output for the text indent could target only list items that have an icon.

### **Possible Related Issue**
#2167

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
