### ISSUE TITLE
[Dark Mode Bug] - Updated with the latest version 2.8.0

### ISSUE THREAD

**Issue by manoj-identixweb** [elementor/elementor#9833]
Hi Elementor,

I recently updated elementor version and experiencing an issue with that. I'm unable to duplicate or add a new column in the inner section. By default when drag and drop **Inner Section** widget to the section and going to duplicate the column, it doesn't allow to duplicate the column.

Also, it's not allowing to reposition the columns from left to right or right to left. When I swap the column, the column I swapped is deleted.

I'm attaching a link to the video screen record of those both issues I have faced with the latest update.
https://screencast-o-matic.com/watch/cqlXjcUSKs

I hope this been fixed shortly.

Thanks in advance!

**Comment by numanzahid** [comment]
+1

**Comment by rodolphebertozzo** [comment]
+1

**Comment by shilo-ey** [comment]
I merged this issue with #9824, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
