### ISSUE TITLE
More filters/actions in the upload file input in forms

### ISSUE THREAD

**Issue by faacsousa** [elementor/elementor#9859]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like to be able to customize the **upload input field** in forms. Today the filters and actions provided aren't enough (for my use case at least) or don't provide the parameters required to do some customization.

**Describe the solution you'd like**
At the moment I need 2 main changes.

* Pass the $record variable to the `elementor_pro/forms/upload_url` and `elementor_pro/forms/upload_path` filters. This would allow us to configure separate upload folders or urls for different forms which today is not possible using the stantard input component.

* Add a filter to change the resulting filename.
I'm aware that uploaded files have their name changed for security. In my use case I need the filenames to have a specific format. While this can be achieved by using the `elementor_pro/forms/process/upload` and renaming the files there. It would be much more intuitive to have a direct filter to customize that.

Also it would be nice if we could somehow access the Upload class (extended from Field_Base) from within the filters/actions so we can access the functions `get_upload_dir()` and `get_file_url()` so we don't have to rewrite code (or do some hack) to get those values.

**Describe alternatives you've considered**
At the moment i'm using the hook `elementor_pro/forms/process/upload` to recreate the paths used by elementor and then moving/renaming files.

The hook `elementor_pro/forms/process` can also be used to do some extra work at the end but I prefer to have each field logic appart.

**Additional context**
Nothing

**Comment by bainternet** [comment]
@faacsousa 

You can actually already achieve both with the provided action and filter hooks,

if you add your function to `elementor_pro/forms/process/upload` at an early priority, you can add your `elementor_pro/forms/upload_url` and `elementor_pro/forms/upload_path` filters only if the form is correct, ex:

```PHP
add_action( 'elementor_pro/forms/process/upload', function( $field, \ElementorPro\Modules\Forms\Classes\Form_Record $form_record, $ajax_handler ) {
	// check if its your form
	$form_name = $form_record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name['form_name'] ) {
		return;
	}
	//  Now that we can identify the for you can set your filter hooks for
	// `elementor_pro/forms/upload_url` and `elementor_pro/forms/upload_path`
	// and this can be set per form
	add_filter( 'elementor_pro/forms/upload_url', 'some_callback_to_modify_upload_url' );
	add_filter( 'elementor_pro/forms/upload_path', 'some_callback_to_modify_upload_path' );
}, 9, 2 );
```

As for filenames: We are passing the filename via wp_unique_filename() a WordPress native function that has a filter you can catch and alter the filename, ex:

```PHP
/**
 * @param string        $filename                 Unique file name.
 * @param string        $ext                      File extension, eg. ".png".
 * @param string        $dir                      Directory path.
 * @param callable|null $unique_filename_callback Callback function that generates the unique file name.
 */
add_filter( 'wp_unique_filename', function( $filename, $ext, $dir, $unique_filename_callback ) {
	static $file_count = 0; //used to get the current file when multiple uploads in a form

	// first make sure its an upload via elementor forms
	// or you can once again only add this filter hook if you know that this is
	// a desired form as in the above example
	if ( false === strpos( $dir, '/elementor/forms' ) ) {
		return $filename;
	}

	// get the original file name
	$path_parts = pathinfo( $_FILES['SET_FORM_FIELD_ID_HERE'][ $filename ] );
	// Bump counter for next file
	$file_count++;
	// Return your desired file name (original-unique_suffix.extension)
	return $path_parts['filename'] . '-' . $filename;

}, 10, 4 );
```

> Also it would be nice if we could somehow access the Upload class (extended from Field_Base) from within the filters/actions so we can access the functions get_upload_dir() and get_file_url() so we don't have to rewrite code (or do some hack) to get those values.

Not really sure what you mean beacuse you are awere of the `elementor_pro/forms/upload_url` and `elementor_pro/forms/upload_path` filter hooks so I really see no reason to rewrite/hack the code of Upload class. However if you still for some reason see the need to overwrite the code/behaviur of Upload class, you can always extend it and modify just the methods you need to even extend `ElementorPro\Modules\Forms\Fields\Field_Base` and create your own upload field.

Thanks.

**Comment by adofeg** [comment]
> ## Prerequisites
> * [x]  I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
> * [x]  The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )
> 
> **What problem is your feature request going to solve? Please describe.** I would like to be able to customize the **upload input field** in forms. Today the filters and actions provided aren't enough (for my use case at least) or don't provide the parameters required to do some customization.
> 
> **Describe the solution you'd like** At the moment I need 2 main changes.
> 
> * Pass the $record variable to the `elementor_pro/forms/upload_url` and `elementor_pro/forms/upload_path` filters. This would allow us to configure separate upload folders or urls for different forms which today is not possible using the stantard input component.
> * Add a filter to change the resulting filename.
>   I'm aware that uploaded files have their name changed for security. In my use case I need the filenames to have a specific format. While this can be achieved by using the `elementor_pro/forms/process/upload` and renaming the files there. It would be much more intuitive to have a direct filter to customize that.
> 
> Also it would be nice if we could somehow access the Upload class (extended from Field_Base) from within the filters/actions so we can access the functions `get_upload_dir()` and `get_file_url()` so we don't have to rewrite code (or do some hack) to get those values.
> 
> **Describe alternatives you've considered** At the moment i'm using the hook `elementor_pro/forms/process/upload` to recreate the paths used by elementor and then moving/renaming files.
> 
> The hook `elementor_pro/forms/process` can also be used to do some extra work at the end but I prefer to have each field logic appart.
> 
> **Additional context** Nothing

Hello, did you solve this issue?
