### ISSUE TITLE
Elementor Pro 2.8 Beta 2 Release

### ISSUE THREAD

**Issue by shilo-ey** [elementor/elementor#9861]
===========

# [Beta 2 UPDATED - PLEASE READ BELOW!](https://github.com/elementor/elementor/issues/9861#issuecomment-566681016)

===========

Elementor 2.8 Pro Beta is here and we would love to get feedback from you!
In Elementor 2.8 Pro, we are introducing important usability & SEO features, which will improve your site’s SEO score, performance, accessibility, and readability. 

**Meet the Table of Contents widget!**

Before installing, please make sure you are using:
- Elementor Core 2.8.1
- Elementor Pro 2.8 Beta 1

## Meet The New Table of Content Widget (#5171)

![TOC Beta](https://user-images.githubusercontent.com/45009641/70731434-5837fa80-1d0f-11ea-82e7-4380560555a1.png)

**“Content Is King”**
It seems like these days, if you want to get substantial traffic from Google, you have to create long-form content.

Today, Elementor is adding a crucial tool to make your long-form content more successful and readable by readers and search engines alike. 

Introducing the Table of Contents widget, a great way to improve accessibility, boost SEO and get those precious featured snippets on Google 💪.

It’s not just another SEO widget, it’s actually the most customizable TOC widget available to date. Moreover, if you use it in conjunction with Elementor’s Theme Builder, you can add it to all your site posts with one swoop, thus instantly improving your site SEO.

Here’s what the TOC widget includes, in terms of customization:

- Level of mapped heading tags
- Set the container the mapping will affect on
- Allow advanced styling customization
- Exclude tags by selector
- Collapsed / Expanded state
- Use this widget as any other widget, control weather it’s sticky or fixed
- Allow better accessibility in your page by linking directly to the headings you wish

**Test flow:**

1. Create a new page and insert a predesigned template into it (to insert heading tags quickly)
2. Drag in Table of Contents widget
3. Include or exclude the heading tags you wish to show in the ToC
4. Style the widget and specify per device settings
5. Make sure everything works as expected in both the Editor and on Frontend.
6. For our MOST HELPFUL beta testers, please add the table of content to a single template, and set it to sticky. Then — publish it and notice how all the posts in your site include the Table of Contents widget.

## Improved Site Performance: Gallery Lazy Load, Optimization & Random Order (#9763, #9269)
In Pro v2.7, we introduced the Pro Gallery widget. Now, we have improved the Gallery’s load time and added two important functions: Lazy Load & random ordering of images.

In order to improve your site performance, and make the images load MUCH faster, Elementor Gallery widget now includes lazy load by default. We’ve also optimized the code that loads images and improved image transitions.

Besides Lazy Load, you can now choose between default and random image order. Choose ‘Random’, and the images will shuffle, in single and multiple galleries and across layouts. 

**Test flow:**

**A:**
1. Create a new page and insert “Gallery” widget to it
2. Insert large amount of images using the Gallery control
3. Make sure “Lazy Load” switcher is on
4. Make sure everything works as expected in both the Editor and on Frontend
5. In frontend, open the Developer Tools > Network tab and make sure the images load asynchronously while scrolling down the page and revealing more images

**B:**
1. Create a new page and insert “Gallery” widget to it
2. Insert images using the Gallery control
3. Select “Random” in Order control and see the images shuffle
4. Make sure everything works as expected in both the Editor and on Frontend

 
## Make Your Site’s Icons Unique: Font Awesome 5 Pro Improvements

![FA-Color](https://user-images.githubusercontent.com/45009641/70731389-49514800-1d0f-11ea-9148-da673b32baf4.png)

You know how everyone uses the same icons? With this version, you can create unique pages with duotone icons, that will surely make your websites stand out.

A few months ago, in version 2.6, Elementor upgraded its icon library to Font Awesome 5. Font Awesome 5 is the largest and most popular icon library. It’s a bit like Elementor and wine, it keeps improving over time.

The new version adds a lot of value to Font Awesome Pro subscribers. Those users now have the ability to use 300+ new icons, plus 1700+ duotone icons, which are icons that comprise of 2 different shades (adds an original look & feel to icons).
 
**Test flow:**

1. In your dashboard go to Elementor > Settings > Integrations tab.
2. Scroll to the Font Awesome Pro row, fill in your Font Awesome Pro Kit ID and click “Validate Kit ID”
3. After receiving confirmation click on “Save Changes” button
4. Create a new page and insert any widget uses an icon
5. Browse throughout the new icon families added and insert one of the new icons (`film-canister` for example)
6. Add another icon and select Duotone icon
7. Specify it’s color and make sure it applies correctly
8. Make sure everything works as expected in both the Editor and on Frontend.

## Improved Accessibility
We improved the Nav Menu widget accessibility properties, as well as the Flip Box & Call to Action widgets HTML semantics. All these changes will improve how screen readers read the elements on the page.

**Test flow:**

1. Make sure you previously created a Menu in your website
2. Create a new page and insert “Nav Menu” widget to it
3. Go to frontend and inspect the Nav Menu widget and search for ‘tabindex’, ‘aria-expanded’, ‘aria-hidden’ and ‘role="navigation"’ accessibility attributes added to it
4. Use screen reader utility to hear how users will navigate using this element
5. Drag in Flip Box and Call to Action widgets and redo steps 3 and 4

----------
## More Improvements

- Tweak: Updated Font Awesome Pro to v5.11.2 (#9578)
- Tweak: Added preselect support for multiple default select values in Forms Widget (#9324)
- Tweak: Avoid duplicate queries for Custom Icons (#9579)
- Tweak: Major performance improvements to Gallery widget
- Tweak: Avoid non-existing images in Gallery widget
- Tweak: Added ‘tabindex’, ‘aria-expanded’, ‘aria-hidden’ and ‘role="navigation"’ accessibility attributes to Nav Menu widget
- Tweak: Changed button HTML tag from `button` to `span` in Call to Action and Flip Box widgets for better W3C compliance and accessibility
- Tweak: Removed Google+ from default networks in Share Buttons widget 
- Tweak: Added compatibility for Library Connect
- Tweak: Added i18n to Toolset date dynamic tag
- Tweak: Added external link support to Gallery widget
- Tweak: Changed the link external attributes implementation to use `add_link_attributes()` in Gallery widget
- Tweak: Updated references to the new Schemes system location
- Tweak: Avoid running Gallery handler when the gallery is empty
- Tweak: UI Tweaks in Editor Panel
- Tweak: Added responsive capabilities to Pointer Width control in Nav Menu widget
- Tweak: Added mobile support for responsive controls in Nav Menu widget
- Fix: Removed “Date” query from Products widget
- Fix: ACF URL “undefined Index” notice (#7646)
- Fix: WooCommerce Mini-Cart widget causes fatal error in edge cases (#9304)
- Fix: Avoid empty spaces in Post info widget
- Tweak: Always show “Custom label” control in Login widget
- Fix: Nav Menu item typography selector in Nav Menu widget
- Fix: Facebook Like Button widget causes flickering
- Fix: Woocommerce mini-cart behaviour when using `plain` permalinks format
- Fix: Avoid running Popup triggers when set without conditions
- Fix: Slides widget when used as a Shortcode and is hidden
- Fix: Custom URL being accessed on swipe in Media Carousel
- Fix: Media Carousel widget Cube effect glitch
- Fix: Lightbox shows images from multiple Gallery widgets in the same page
- Fix: Image `alt` Text not displayed on overlay in Gallery widget
- Fix: Gallery widget not visible in Posts widget Full Content skin
- Fix: Woocommerce mini-cart remove unnecessary hooks registration when WooCommerce integration set to `Disable`
- Fix: Slides widget button wrapping breaks in mobile view
- Fix: Dynamic capabilities with the Reviews widget
- Fix: Disabling autoplay doesn't work in Slides widget
- Fix: Posts widget Full Content skin not working on Single template
- Fix: Autocomplete not working for “By Author” condition in Display Conditions screen

--------
## How to Install the Beta Version
If you still haven't enabled beta testing in Elementor, please follow these steps:

- Go to Elementor > Tools > Versions
- Enable the beta tester feature
- Go to Dashboard > Updates and update to the latest beta version.

This will get you set up to test the new Elementor Pro 2.8 Beta.

-------
## Notes
For bugs and remarks, please reply with a comment on the specific issue here on GitHub.

Please keep this related to the Current beta Only! Any other issue or feature request, feel free to open a new issue.

Designated time for release: `December 18, 2019` (Estimated)
 
**Many thanks for your support and help!**
The Elementor Team

**Comment by zeinnicholas** [comment]
I'm testing it. Will relay back soon. ;)

> 
> Designated time for release: `December 18, 2019` (Estimated)
> 

I think it's too soon to release considering the amount of bugs people have been reporting here and in FB about the free version 2.8. Just my opinion...

**Comment by oceandiveloper** [comment]
Awesome functionality for the Pro 2.8 release. Makes me all very happy. 

I just tested the TOC and have to say it works really nicely. I just noticed one thing: There is some not so great looking inner whitespace at the bottom of the TOC created by an empty <p></p> tag. I guess this can be removed...

<img width="1002" alt="Screen Shot 2019-12-14 at 08 00 40" src="https://user-images.githubusercontent.com/43462095/70839514-f333f000-1e47-11ea-80ed-8ff666958640.png">

**Comment by shilo-ey** [comment]
[**@oceandiveloper**](https://github.com/oceandiveloper) commented on [Dec 14, 2019, 2:03 AM GMT+2](https://github.com/elementor/elementor/issues/9861#issuecomment-565655182 "2019-12-14T00:03:59Z - Replied by Github Reply Comments"):
> Awesome functionality for the Pro 2.8 release. Makes me all very happy. 
> 
> I just tested the TOC and have to say it works really nicely. I just noticed one thing: There is some not so great looking whitespace at the bottom of the TOC created by two empty `<p></p>` tag. Since these don't serve any semantic purpose I guess those could be removed...

Hi, can you please share a JSON export of the widget you placed on your site? can't manage to reproduce this case.

Thanks

**Comment by sermalefico** [comment]
Pro Gallery widget does not create images with custom size option in dynamic mode, only return full-size images.

**Comment by carmeliy** [comment]
> Pro Gallery widget does not create images with custom size option in dynamic mode, only return full-size images.

Hi, sorry but I received the mail to test TOC but I don't know how to download Elementor Pro 2.8 Beta 1¿Can you hep me? Thanks in advance

**Comment by fabianenzensperger** [comment]
Cool update, but first I thougt we became the Awesome 5 Pro for free with  Elementor Pro. :D

**Comment by taminoferrari** [comment]
Very nice new feature. @shilo-ey I have a fixed navigation on my website. When I jump to the anchors my navigation is overlapping the subtitle. It would be nice if you could add the option to add an offset setting to avoid that.

**Comment by oceandiveloper** [comment]
> [**@oceandiveloper**](https://github.com/oceandiveloper) commented on [Dec 14, 2019, 2:03 AM GMT+2](https://github.com/elementor/elementor/issues/9861#issuecomment-565655182):
> 
> > Awesome functionality for the Pro 2.8 release. Makes me all very happy.
> > I just tested the TOC and have to say it works really nicely. I just noticed one thing: There is some not so great looking whitespace at the bottom of the TOC created by two empty `<p></p>` tag. Since these don't serve any semantic purpose I guess those could be removed...
> 
> Hi, can you please share a JSON export of the widget you placed on your site? can't manage to reproduce this case.
> 
> Thanks

Here you go. 

> Hi, can you please share a JSON export of the widget you placed on your site? can't manage to reproduce this case.

Here is the JSON export of the entire section. The content (privacy policy) on this page is dynamically created by another plugin via shortcode.

[elementor-395-2019-12-16.json.zip](https://github.com/elementor/elementor/files/3966066/elementor-395-2019-12-16.json.zip)

**Comment by shilo-ey** [comment]
[**@oceandiveloper**](https://github.com/oceandiveloper) commented on [Dec 16, 2019, 6:25 AM GMT+2](https://github.com/elementor/elementor/issues/9861#issuecomment-565899658 "2019-12-16T04:25:55Z - Replied by Github Reply Comments"):
> > Hi, can you please share a JSON export of the widget you placed on your site? can't manage to reproduce this case.
> 
> @shilo-ey  Here is the JSON export of the entire section. The content (privacy policy) on this page is dynamically created by another plugin via shortcode.
> 
> [elementor-395-2019-12-16.json.zip](https://github.com/elementor/elementor/files/3966066/elementor-395-2019-12-16.json.zip)

It seems like you have another code injecting that redundant `<p></p>` tag:
![image](https://user-images.githubusercontent.com/45009641/70890679-4ba4f200-1fee-11ea-910a-3d5c919881f2.png)

Try deactivating your plugins, switch to "Hello theme" and let me know if the issue persists.


[**@sermalefico**](https://github.com/sermalefico) commented on [Dec 15, 2019, 5:49 PM GMT+2](https://github.com/elementor/elementor/issues/9861#issuecomment-565821253 "2019-12-15T15:49:15Z - Replied by Github Reply Comments"):
> Pro Gallery widget does not create images with custom size option in dynamic mode, only return full-size images.

Not related to beta, but from what I've inspected, the thumbnail returned are in the right size (the full image though is the full size as should be).


Thanks again to everyone.

**Comment by fabianenzensperger** [comment]
For me, the beta is unfortunately not displayed. Beta tester und tools has been active since last night. Elementor 2.8.1 is installed. Someone an idea why?

**Comment by shilo-ey** [comment]
@fabianenzensperger 
> For me, the beta is unfortunately not displayed. Beta tester und tools has been active since last night. Elementor 2.8.1 is installed. Someone an idea why?

Go to Dashboard > Updates and click "Check Again"
If that didn't work, go to Plugins, deactivate and reactivate Elementor Pro and see if there's an update.

Thanks

**Comment by fabianenzensperger** [comment]
> @fabianenzensperger
> 
> > For me, the beta is unfortunately not displayed. Beta tester und tools has been active since last night. Elementor 2.8.1 is installed. Someone an idea why?
> 
> Go to Dashboard > Updates and click "Check Again"
> If that didn't work, go to Plugins, deactivate and reactivate Elementor Pro and see if there's an update.
> 
> Thanks

Both suggestions didn't work.

**Comment by Jordidriesen** [comment]
I've noticed that the table of contents doesn't get the titles from an ACF wysiwig field. I'm using only elementor and elementor pro, in the editor it doesn't show any values for the titles and on the frontend I get a loading animation within the toc.

**Comment by nickdgreen** [comment]
With the TOC widget the Anchor by type is just a series of boxes with no descriptor. The only way to see which levels have been set is to hover over each one. The parameters need to contain their values H1, H2 etc.
![TOC feedback](https://user-images.githubusercontent.com/22448787/70917291-f4fede80-2014-11ea-908d-256c95038a39.png)

**Comment by parfilov** [comment]
Underline for normal state works different in different themes.

- Hello — doesn't work
- Twenty Nineteen — shows by default and cannot be disable (on hover is disabled by default and cannot be enabled)
- Twenty Seventeen — doesn't work
- Astra — doesn't work

**Comment by parfilov** [comment]
Add different paddings for TOC header and list blocks please.

**Comment by oceandiveloper** [comment]
> It seems like you have another code injecting that redundant `<p></p>` tag:

So you're right in that some code is injecting empty <p></p> tags all over the page. But I still think this is related to Elementor Pro 2.8 beta. Please have a look at [this video](https://www.youtube.com/watch?v=1YGs361uhuc) where I reproduce the issue by updating Elementor Pro to 2.8.0 beta with Hello theme and no other plugin installed.

**Comment by SniffleValve** [comment]
> > @fabianenzensperger
> > > For me, the beta is unfortunately not displayed. Beta tester und tools has been active since last night. Elementor 2.8.1 is installed. Someone an idea why?
> > 
> > 
> > Go to Dashboard > Updates and click "Check Again"
> > If that didn't work, go to Plugins, deactivate and reactivate Elementor Pro and see if there's an update.
> > Thanks
> 
> Both suggestions didn't work.

If the update to beta still is not displaying, then use the manual method :) 
- log into your Elementor account
- click Purchases
- click 'View Details and Downloads'
- scroll to the bottom and in Products, click elementor-pro2.8.0-beta1 to download

Then either delete your existing E Pro and install the downloaded beta or install and activate the Easy Themes and Plugins Update plugin (in the WP plugin repo) which lets you upload a new version over an existing one (I use this all the time ... so handy for testing :) )

Cheers!
Lyle

**Comment by Grassmedia** [comment]
So, I'm playing with ToC in a single post archive which has an Elementor Header & Footer.  There are two H2 tags in the footer which ToC picks up BUT clicking on the link doesn't take me there.  Example on sandbox site https://ancientgeekery.com/acf-gallery-post/

**Comment by shilo-ey** [comment]
We just released a new beta version, please update your version to v2.8 Pro Beta 2.

This beta release includes:

- Tweak: Rearranged controls and settings in Table of Contents widget
- Tweak: Improved Table of Contents performance
- Tweak: Added Icon controls for Minimized state in Table of Contents widget
- Tweak: Refactor `register_controls()` method in Posts widget skin trait
- Fix: Posts widget alignment issue
- Fix: `PHP Notice: Undefined index` display for Author query (#9864)
- Fix: Added compatibility for Button widget placed inside Swiper carousel ([Topic](https://wordpress.org/support/topic/broken-buttons-since-elementor-2-8/))
- Fix: Product Variations Clear button not working in edge cases
- Fix: Styling issues in Form widget submit button

This Beta is our RC for 2.8 Pro


Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.

Thanks again to everyone.

**Comment by Kpudlo** [comment]
Love the table of contents! That's going to help on one of the websites I've been working on. One concern I noticed is that specifying a container seems hard, as I'm not sure what to put there. 

I was able to get results with `section`, but that was the same as default. I couldn't get `section.post-content` or `section-post-content` or anything of that sort to work. 

![example](https://user-images.githubusercontent.com/4432822/71024282-8f712780-20d2-11ea-9612-3f94a3b493f8.gif)




I was able to exclude the area I didn't want by excluding by selector for now at least.

**Comment by shilo-ey** [comment]
[**@Kpudlo**](https://github.com/Kpudlo) commented on [Dec 17, 2019, 8:39 PM GMT+2](https://github.com/elementor/elementor/issues/9861#issuecomment-566693465 "2019-12-17T18:39:18Z - Replied by Github Reply Comments"):
> Love the table of contents! That's going to help on one of the websites I've been working on. One concern I noticed is that specifying a container seems hard, as I'm not sure what to put there. 
> 
> I was able to get results with `section`, but that was the same as default. I couldn't get `section.post-content` or `section-post-content` or anything of that sort to work. 
> 
> 
> I was able to exclude the area I didn't want by excluding by selector for now at least.

Thanks, 
By default, the content area is the entire document besides Elementor made header & footer.
The Container control replaces that area to the container/s (comma separated) you wish to include.

For example, if my content area is wrapped by `<main>` tag and my footer with `<footer>` tag, you'll need to specify `main,footer` to display headings from this area.

If you want, you can even use HTML selectors to specify it (`.show-in-toc` for example) and apply that selector to the places you want to show.

Thanks

**Comment by shilo-ey** [comment]
Elementor Pro v2.8.1 is now available, Feel free to update.

**Thank you all again for your feedback!**

**Comment by fabianenzensperger** [comment]
And what is with Pro 2.8.0? What is change with .1? And why a .1 so fast?

**Comment by shilo-ey** [comment]
[**@fabianenzensperger**](https://github.com/fabianenzensperger) commented on [Dec 18, 2019, 8:06 PM GMT+2](https://github.com/elementor/elementor/issues/9861#issuecomment-567145634 "2019-12-18T18:06:25Z - Replied by Github Reply Comments"):
> And what is with Pro 2.8.0? What is change with .1? And why a .1 so fast?

Two hotfixes you reported, and we decided to release right after releasing Elementor Pro v2.8.0. See the changelog for more details.

**Comment by oceandiveloper** [comment]
@shilo-ey what happened to my reported problem? You never got back to me in the last two days.

**Comment by kratex19** [comment]
I can install elementor 2.8 but it causes my mega menu to open and stays open when trying to edit also when it is published and online in desktop, tablet and mobile .

**Comment by Kishorchandth** [comment]
Table of Contents (TOC) is great to have on any blog post that have huge content. but there is tiny problem RankMath is not detecting TOC is there any way to fixed  this issue ?

**Comment by kratex19** [comment]
Try this , Let me know if it works , My Problem with TOC is in my megamenu js most likely . I am going to look at a No- Conflict for js which i have used on other js related problems in the past ...
 TOC Pack - Table of contents for Elementor » Rank Math Compatibility

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
TOC Pack - Table of contents for Elementor » Rank Math Compatibility

TOC Pack is a Wordpress Elementor plugin which provides two must need SEO widgets. One is TOC headings which aut...
 |

 |

 |




Thank You. 
Gary Brown

 

    On Saturday, December 21, 2019, 10:05:31 PM CST, Kishorchand <notifications@github.com> wrote:  
 
 
Table of Contents (TOC) is great to have on any blog post that have huge content. but there is tiny problem RankMath is not detecting TOC is there any way to fixed this issue ?

**Comment by rootmegusta** [comment]
The custom breakpoints resolution plugin for Elemntor is online! If you use it, please send me your feedback, it would be useful for me 🤞
https://wepixel.ro/custom-breakpoints-plugin-for-wordpress-elementor/
