### ISSUE TITLE
✅ 🐞 Bug Report: New color picker issues

### ISSUE THREAD

**Issue by avermat** [elementor/elementor#9862]
**Can't save column color**
When I click "edit column" and try to save the column background color (by clicking the "+" button) it saves #000000 and not the color shown in the color picker.

**Transparency bar can't switch to RGBA**
When I adjust the transparency bar for a hex color, it doesn't change the color to RGBA... instead it's stuck on hex and uses an 8-digit hex code. So now there's no way for me to use the correct RGBA number (eg .25).

![image](https://user-images.githubusercontent.com/29379115/70738837-67488980-1cca-11ea-9073-926fb5bed0d5.png)

Also, in the image above, why is the transparency bar black, and not blue?

**Transparency bar can't switch to Hex**
If I'm using an RGBA color, and want to set it to 1 (no transparency), it doesn't go back to hex. I'm stuck on RGBA.

**My Setup**
Elementor (latest 2.8.1)
Elementor Pro (latest)
Astra (latest)
No other plugins

**Comment by black-eye** [comment]
+1 For the rgba format when transparecy is used. It's much more understandable.
Or give us at least some indicator of what's the exact transparency as number, I'm not using transparency much, but when I do, I want to set it by exact number, not a random guess.

**Comment by black-eye** [comment]
Also try to edit the hex code manually. I goes absolutely funky, random numbers are addet, you absolutely loose control of your output. Yes I know, I can put it back to rails by clicking the clear button, but com on... this should work right from the start.

**Comment by zeinnicholas** [comment]
Choosing HEXA was bound to be problematic... I can't understand why they choose to use it... Not intuitive at all...

The last two digits translate to the opacity of the color, but they are also calculated in hexadecimal code, so if the opacity is 100%, it translates to FF, if the opacity is 0%, it translates to 00... It goes from 0 to F... The problem with this is that you cannot define a specific amount of opacity using HEXA without having to translate what those two last alpha-numbers mean... And the slider itself also doesn't show a percentage. It is fine if you know from the top of your head, but if you don't, you end up without any clue on what percentage it is...

I find this choice really odd, since now we have much space to see the entire rgba string (something that was often cut-off in the old color picker). For me this shows a lack of care and polish, and a clear will to rush things off... Elementor never did this before, not this way. The last update was a disaster.

I lost my trust on the software. 

@black-eye to input manual numbers, you have to do like you did before, remove the entire string including the '#' then write whatever you want. If you keep the '#' the color picker will try to guess what color you're imputing. This behavior remains unchanged from the previous versions.

**Comment by avermat** [comment]
@shilo-ey Any chance we can get the column color bug fixed? I'm still seeing it in 2.8.2.
_When I click "edit column" and try to save the column background color (by clicking the "+" button) it saves #000000 and not the color shown in the color picker._

**Comment by Worldwebscapes** [comment]
I am having difficulties in selecting black from the chosen color picker in general. It seems to only fill in #0 at the bottom rather than #000000. Other colors seem ok for me. I have to hit the clear button in order to choose black though.

**Comment by webcolor-in** [comment]
I am same issues in saving color which is confirmed by Elementor support team as well, please fix this. I also did not like this layout of color palette and input box instead recommend to follow what other popular software are doing than reinventing the wheel. 

This has clear cut entry option which I can notice in first instance and color change scroll bars are vertical ones than horizontal because vertical scrolls are easier than horizontal ones. Can this same layout be adopted in Elementor color picker please?


<img width="409" alt="Screenshot 2019-12-21 at 10 26 04 AM" src="https://user-images.githubusercontent.com/55145799/71303290-bda97c80-23dc-11ea-96c7-f78eaea484f2.png">

**Comment by Clavinia** [comment]
I totally agree with @zeinnicholas regarding the last update. I've been using Elementor for some years already and I am really bothered with this new color picker. I am a designer and like to have a full control of the alpha in terms of percentage, therefore I usually work with RBGa accross all platforms. Having to change my workflow to HEXA is not in my plans and has really become a problem for me. I would really like Elementor to at least give the users the choice to revert to the previous colour picker, and, in the meanwhile, work in @webcolor-in 's suggestion and take inspiration in Adobe XD's one.

**Comment by realstephenzhao** [comment]
I am frustrated with this 8 digit #rgba hex color too.

**Comment by team-webstudio** [comment]
Same here, it so counter intuitive as most web design uses rgba for transparency. And even the responsive icons to toggle the element's media query properties now take a couple of clicks, where as they use to be already in display and you just have to click them, now they're hidden and so small for click accuracy.

**Comment by brenda-malone** [comment]
This is an awful experience within Elementor. PLEASE correct the color picker issue. It wastes a ton of time every single time.

**Comment by ianstudio** [comment]
8-Digit Hex could be an option but should not be the default and only option.

PS: A complete color picker would look more like this:
https://www.google.com/search?en&q=HEX+color&ie=UTF-8&oe=UTF-8
https://color.adobe.com/create

**Comment by ianstudio** [comment]
It shows me 8-Digit Hex when setting background color, RGBA when setting a shadow, it's hard grasping if those behavior are "features" or bugs.. if they are features they sure don't feel like an upgrade.

PS: A complete color picker would look more like this, giving us options that WE decide match our workflow:
https://www.google.com/search?en&q=HEX+color&ie=UTF-8&oe=UTF-8
https://color.adobe.com/create

**Comment by ianstudio** [comment]
It shows me 8-Digit Hex when setting background color, RGBA when setting a shadow, it's hard grasping if those behaviors are "features" or bugs.. if they are features they sure don't feel like an upgrade.

PS: A complete color picker would look more like this, giving us options that WE decide match our workflow..
https://www.google.com/search?en&q=HEX+color&ie=UTF-8&oe=UTF-8
https://color.adobe.com/create

For instance I like to be able to set a color from any starting point, even CMYK - I use external color tools for that but still, if those could be integrated why not..

The ultimate on Mac would be to be able to invoke the Apple Color Picker... one can dream or the even the OpenColor app http://opencolor.tools

**Comment by ianstudio** [comment]
It shows me 8-Digit Hex when setting background color, RGBA when setting a shadow, it's hard grasping if those behaviors are "features" or bugs.. if they are features they sure don't feel like an upgrade.

PS: A complete color picker would look more like this, giving us options that WE decide match our workflow..
https://www.google.com/search?en&q=HEX+color&ie=UTF-8&oe=UTF-8
https://color.adobe.com/create

For instance I like to be able to set a color from any starting point, even CMYK - I use external color tools for that but still, if those could be integrated why not..

The ultimate on Mac would be to be able to invoke the Apple Color Picker... one can dream or even the OpenColor app http://opencolor.tools

**Comment by webcolor-in** [comment]
The moment I start typing colors it will auto fill with junk values so the only option left is I paste color here and type somewhere else, that's not good.

**Comment by maxwellhibbert** [comment]
Need a dedicated alpha input! 🤦‍♂

**Comment by lelas** [comment]
I am experiencing a related issue. I can't paste or enter rgba values. Maximum input: "rgba(0," (if I try to paste more, the field turns red).

Perhaps not fully related, but as of a recent update, I can't change background colours on existing elements either -- that is, without moving the slider back and forth. When I move the slider, the change goes into effect, never before.

**Comment by lior-sh** [comment]
Hi @avermat,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by lelas** [comment]
I have the same issue. Changing a color via the color doesn't work **unless** I move one of the sliders back and forth. It's been there for a while, not the latest release, for sure.

**Comment by lelas** [comment]
@lior-sh I can record a video of this, if that would be helpful.

**Comment by lior-sh** [comment]
@lelas Yes it will help, thanks!

**Comment by captaincoo1** [comment]
Any way to show RGBA instead of HEXA yet?

**Comment by joehdevwp** [comment]
I am frustrated with this 8 digit #rgba hex color too.

**Comment by moonbeetle** [comment]
#HEXA as output in the color field is just a very bad UI decision. A little annoyance that grows with the time. Unintuitive, counterproductive. It's almost like using unix timestamp for mm/dd/yyyy ;-)

**Comment by MichaelDarko** [comment]
Using #HEXA format and not giving us any way to control transparency in percentages is a great descision if you want to drive people nuts. In webdesign, you need to set exact % transparency all the time. This is driving me mad about 20 times a day.

They've revamped the color picker a few times and it's still useless. :-/

I've started a specific feature request for this: #12772

**Comment by ianstudio** [comment]
+1
Again an issue that the Elementor team in some ways insults its users with by playing deaf.

**Comment by JoeHana** [comment]
Just a little tip - it shouldn't be the longterm solution but it has helped me quite a bit.

* Rightclick on the transparency bar and inspect it in the browser console
* Just drag the slider and keep an eye on how the value in the console changes. The correct RGBA value is visible there.

That way I can see it more precisely without any kind of color code translations. Still it would be helpful to have a more user-friendly solution.

**Comment by mark2090** [comment]
I concur with avermat, the author of this issue. 

I see this current design for the opacity of a color hard to use when I am trying to match opacity between colors. 

The use of a percentage or use of RGBA (where opacity is designated by a decimal and a number) are the best ways to use opacity controls of color. 

I have no objections to the HEX code, **so long** as Elementor also provides either the percentage scale or RGBA scale also. 
Not everyone needs to use the HEX scale, neither does everyone like it either. 

So to provide a more global usage, please include the percentage or RGBA scale for color opacity. 

PS: in fact, I am sure that coding for Elementor can replace the visible HEX number with a percentage number, but the color tool still uses the HEX code anyway. Visually, this would resolve usability issues.  

Thanks.

**Comment by MichaelDarko** [comment]
How many millions of users do you need before you let us control the transparency in percentages? So frustrating.

**Comment by jeffreysfridge** [comment]
I would like Elementor 4 to come out immediately and the only new feature is an alpha percentage in the color picker.

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the option to choose other colors in the color picker is now live in the latest v3.13-Beta release!

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that you can now use RGBA and HSLA colors with the Elementor Color Picker since **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
