### ISSUE TITLE
Query Control: filter by Author caused php warning.

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#9864]
Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello great team,

I've just found 2 issues with Query Control of Posts widget.

![download (1)](https://user-images.githubusercontent.com/7134267/70782414-840fba80-1db9-11ea-82cf-02726768a67b.png)

Whenever i filter posts by author then debug.log will show php warning:

PHP Notice:  Undefined index: display in /Volumes/DATA/steve/test/wp-content/plugins/elementor-pro/modules/query-control/module.php on line 290

The other issue, I can't search author by Nick Name.
It will be better when user can search by Nick Name instead of Username only, right?

Could you check & improve it? please

## Environment
Elementor Pro 2.7.3
Hello Elementor theme

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.1

Feel free to update

Thanks!
