### ISSUE TITLE
Using Responsive Control values in another Control

### ISSUE THREAD

**Issue by nnnswordfish** [elementor/elementor#9866]
Is there a way to use Responsive Control values in another control?

**avatar_size.VALUE** is a responsive control value, but it only returns desktop value.

<pre>
$this->add_responsive_control(
	'avatar_gutter',
	[
		'label' => esc_html__( 'Gutter', 'abc' ),
		'type' => Controls_Manager::SLIDER,
		'size_units' => ['px'],
		'range' => [
			'px' => [
				'min' => 0,
				'max' => 50,
			],
		],				
		'default' => [
			'unit' => 'px',
			'size' => 20,
		],
		'selectors' => [
			'{{WRAPPER}} .abc-comment-meta' => 'margin-left: calc({{avatar_size.VALUE}}px + {{SIZE}}{{UNIT}});',
		],
	]
);
);
</pre>

**Comment by nnnswordfish** [comment]
anybody here?

**Comment by nnnswordfish** [comment]
@bainternet alive?

**Comment by rami-elementor** [comment]
Hi @nnnswordfish 

This is a bad practice, we don't allow using one control values in other control selectors.

It can return JS errors and in some cases break sites.
