### ISSUE TITLE
Anchor Widget Not Working After 2.8.0 and 2.8.1 update

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#9868]
Anchor widghet inside the elementor does not work correctly anymore when you have a sticky widget on the top. When creating a menu for the page with anchors before the update it scrolled down to the right place (which is of course after the sticky widget). Now when klicking on the menu it scrolls down and stops under the sticky widget. The sticky widget on top is in other words covering everything. Hope you understand what I mean....This happened after updating from 2.7.6.

You can no longer have a functional meny on the page itself if you have a stycky widget on top thanks to the new update. When will this be fixed?

**Comment by vgstef** [comment]
I also have this issue. 

When I reach the anchor on a page from another page, the sticky menu covers the sections.

It seems like the scroll down to the anchor doesn't take into consideration the height on the sticky menu.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
