### ISSUE TITLE
Button for reset all parameters styles by click?

### ISSUE THREAD

**Issue by Grafs** [elementor/elementor#9870]
How to show Reset button in Styles tab and create event reset all styles on javascript?

**Comment by zeinnicholas** [comment]
Right click to reset individual elements styles.

I don't know if there is a hook to reset everything globally, but you can look for it in here:

https://code.elementor.com/js-hooks/

**Comment by Grafs** [comment]
@zeinnicholas Thanks!
I watched it hooks but could not find the solution

**Comment by shilo-ey** [comment]
Hi @Grafs 

In the latest versions of Elementor, we are constantly working on improving our API to support this kind of functionality.

For now you can try adding the following functions, and then use the following code snippet to reset by ID:
```JS
function findViewRecursive( parent, key, value, multiple = true ) {
    let found = [];
    for ( const x in parent._views ) {
        const view = parent._views[ x ];

        if ( value === view.model.get( key ) ) {
            found.push( view );
            if ( ! multiple ) {
                return found;
            }
        }

        if ( view.children ) {
            const views = findViewRecursive( view.children, key, value, multiple );
            if ( views.length ) {
                found = found.concat( views );
                if ( ! multiple ) {
                    return found;
                }
            }
        }
    }

    return found;
}

function findViewById( id ) {
    const elements = findViewRecursive(
        elementor.getPreviewView().children,
        'id',
        id,
        false
    );

    return elements ? elements[ 0 ] : false;
}

```

And then:

```$e.run('document/elements/reset-style',{container: findViewById('YOUR_ELEMENT_ID').getContainer() })```

Replace `YOUR_ELEMENT_ID` with your elements ID.

Thanks
