### ISSUE TITLE
✅ Carousel with self-hosted video

### ISSUE THREAD

**Issue by etishberg** [elementor/elementor#9871]
Currently, the carousel only supports YouTube and Vimeo, but I host all my videos on my site.

While there is nothing wrong with YouTube or Vimeo the ability to use self hosted videos is an important one. It should be one of the choices on the pulldown menu.

It would also be much 'safer' and easier to use an Elementor plug-in than a 3rd party one.

Thanks...eli

**Comment by inspiredearth** [comment]
I would also like to see a "Self-hosted" option. 
Is anything being done about this feature?

**Comment by ligne13** [comment]
+1

**Comment by cesarlucian** [comment]
+1

**Comment by Fitia** [comment]
+1

**Comment by nimeshpatel20** [comment]
+1

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was fulfilled with the introduction of the new nested Carousel in Elementor Pro v3.14! 🥳 

With the new Nested Carousel, you have much more control over the styling of the carousel itself and its functionalities, and you can use whatever widget you want inside each carousel item, which means being able to add Video widgets and display them exactly the same way you would by using the (now legacy) Media Carousel. To learn more about how to use the Carousel widget, check this article: https://elementor.com/help/carousel-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
