### ISSUE TITLE
Woo commerce elementor 

### ISSUE THREAD

**Issue by Geekwp** [elementor/elementor#9873]
Hi every one i try to do a woocommerce boutique but i have a big problem on my website. So far everything worked but i tried to put product image and product price it doesn't work. Elementor give me this message : "The style of this widget is often affected by your theme and plugins. If you experience any such issue, try to switch to a basic theme and deactivate related plugins."

So i try to change my theme for a default theme and still doesn't work. I disable all the plugins and just let active elementor and woocommerce and still doesn't work. I try to uninstall woocommerce and install it again and the same thing happens.

Who can help me ? I am blocked and i lost time for my website !

**Comment by SC36DC** [comment]
Have you tried clearing your cache and checking again? Check it on a different browser?

**Comment by shilo-ey** [comment]
Hi @Geekwp 

Please contact our support for better debugging of this issue.

Thanks

**Comment by Geekwp** [comment]
Hi SC36DC ! How i can clear the cache ? I will check it on a different browser ;) 

Hi Shilo-ey ! I have contacted the support but i just have a ticket and i wait but no answer...
