### ISSUE TITLE
[Feature request] Image widget custom size cropping focus point/control

### ISSUE THREAD

**Issue by gTaylorRokk** [elementor/elementor#9875]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
At the moment with the image widget you can use one of the Wordpress image size presets or use the custom image size to create a crop which is great. However I think this could be improved and be even more useful by giving us better to control over the actual cropping of the image. At the moment you input the desired size and it is just cropped automatically from the sides and the top and bottom so depending on the subject position you can get undesired results. 

**Describe the solution you'd like**
It would be nice to have more control of the cropping directly in the image widget controls to either set a focus point of the custom image size crop to keep the subject central or have some additional cropping controls (similar to WP's own media one) so we can better control how the image crops the custom size. 

**Describe alternatives you've considered**
I appreciate this could be managed outside of Elementor with the media library tools or there's plugins for setting focus point for cropping etc, but as we are able to create custom image sizes from within Elementor's image widget settings (non destructively from the original) it would make a lot of sense to me and in my opinion provide a much better/smoother custom image sizing workflow to have it available natively as part of Elementor image settings.

**Comment by black-eye** [comment]
+1
Oh yes - just like in the example below. Gues where it came from... 😉 

![zoom-focus](https://user-images.githubusercontent.com/5634870/70855543-beb64780-1ecc-11ea-9144-4d406dc3e474.gif)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11513, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by black-eye** [comment]
@shilo-ey 
> Merged issue
> 
> I merged this issue with #11513, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> Thanks for your feedback!

Well, I'm not quite sure why you've chosen newer issue with worse description over this one, but never mind, I'll add mine comment and image there as well...
