### ISSUE TITLE
Show Popups based on Keyword in URL or UTM Parameters

### ISSUE THREAD

**Issue by yanissi** [elementor/elementor#9876]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
At the moment, it is impossible to target users coming from a redirected website as Google Analytics does not register 301 redirects as referrers but as direct traffic source. the idea here would be to add a new advanced rule in popups conditions that would look for UTM Parameters or a string contained in the URL of the website.

**Describe the solution you'd like**
Advanced Rules - Show if URL Contains : (Regex/Keyword) : Input Text

**Additional context**
This feature Request come after me writing an article on how to target referral traffic with your popups on Wordpress : https://martechwithme.com/show-popups-to-users-from-referral-url/

I then received an email from a reader asking if there was any way to target users coming from 301 redirects and i realized this was not an option despite being a feature in other Popups Builder (Namely "WP Popups Lite" by timersys to name one). I directed my reader to this plugin for the time being and thought it would be good to request this feature as Elementor is in its own league regarding the building interface and ease of use and I definitely think Elementor could benefit from such a feature.

**Comment by shilo-ey** [comment]
Hi @yanissi 

Thanks for your feedback.

You can use the advanced rule "When arriving from specific URL" and place the parameter you wish to include.

Read more here: https://docs.elementor.com/article/472-popups

Thanks

**Comment by yanissi** [comment]
No, it does not work like this, this is not what I meant... Neither related to the feature I suggested.

Let's say you have domain.com that redirects (301 Permanent) to domain2.com. If you create a popup on domain2.com that triggers when the user comes from domain.com, **it does not work** because a **301 redirect** is not the same as a link to domain.com and not treated as referral. And this is not a bug, 301 redirects are just not considered referral traffic. I'm already using "Show popups when coming from URL" and it did not work for this case. Hence my post here.

Now, what I suggested is a new Advanced Rule that looks at the URL a user is currently in on domain2.com. So that popups would show if a keyword, let's say "utm_source=301redirect" is in the URL of domain2.com. This way, that would allow people that are dealing with 301 redirects to show popups to users that are coming from 301 Redirects as long as the admin create the proper redirect.

Does that make sense @shilo-ey ? Do you think it would be possible to reopen this issue and discuss it further ?

**Comment by eknown** [comment]
@yanissi I'm looking to solve the same problem right now. Did you ever find a working solution?

**Comment by eknown** [comment]
For anyone looking for a temporary solution (since this feature has yet to be implemented), you can add the following into `functions.php` to manually trigger a popup based on URL parameters.

Using @yanissi's example where we're checking if `utm_source=301redirect` is part of the URL:
```
jQuery(document).ready(function() {
    if (window.location.href.indexOf("utm_source=301redirect") > -1) {
      jQuery('body').append('<a id="popup_trigger" href="#elementor-action%3Aaction%3Dpopup%3Aopen%26settings%3INSERT_POPUP_ID_HERE"></a>');
      jQuery('#popup_trigger')[0].click();
    }
});
```

You'll need to replace `utm_source=301redirect` with whatever parameter you're looking for, and replace `INSERT_POPUP_ID_HERE` with your elementor popup's unique ID.

To get the elementor popup ID, create a button with its link set to open the desired popup, and inspect the output from where you can simply copy the button's `href` value.

**Comment by fabienlege** [comment]
+1 Always no simple solution to do this in 2021 ?!

**Comment by Dadparvar** [comment]
This really is super handy. There are many cases where this can be a big help.

For example, we want to display a specific popup only if the URL contains a specific parameter (in our case, it's: clear-cart). We reload the page after the cart is emptied and the reloaded page has ?clear-cart added to its URL. (@eknown 's solution may help in come cases, but having a built-in option would help a lot and would make things easier)

If it was possible to check the URL for certain keywords this would let us use popups much more in our project.
