### ISSUE TITLE
Where do I save my custom action for forms?

### ISSUE THREAD

**Issue by salgados** [elementor/elementor#9877]
I was told by Elementor support that my question was more appropriate for the development team.

I am trying to follow the following tutorial to add a custom form action the Form widget:
https://developers.elementor.com/forms-api/custom-form-action/

What's not clear to me is where do I save my php file?

**Comment by shilo-ey** [comment]
Hi @salgados 

You can add the code anywhere that loads, in a custom plugin or in your theme's `functions.php` file.

Thanks
