### ISSUE TITLE
Image Carousel widget if remove Navigation - space remains below

### ISSUE THREAD

**Issue by zimmiel** [elementor/elementor#9878]
In Image Carousel widget if remove Navigation (img 1), or Dots inside (img 2) - space remains below (not like the top). There is still space.
I already wrote in support. Support recommended use Custom CSS (img 3)
I got the answer "We are aware of the issue and it will be resolved in a future update of Elementor. Currently, we would really recommend using the workaround provided by Cesar."
There have already been updates, but no change. I decided to open Bug report.
![img 1](https://user-images.githubusercontent.com/42843497/70852896-7177ad00-1eaf-11ea-8ad2-50d2e44f1610.png)
![img 2](https://user-images.githubusercontent.com/42843497/70852897-72104380-1eaf-11ea-80dc-05d339935a2f.png)
![img 3](https://user-images.githubusercontent.com/42843497/70852898-72104380-1eaf-11ea-90e4-c00ca33c31af.png)

**Comment by lior-sh** [comment]
Hi @zimmiel,

Thanks for reporting, we couldn't reproduce the issue. It seems to be fixed.
Thanks.

**Comment by zimmiel** [comment]
Hi @lior-sh 
Sorry for the late answer/question.
Space remains below not fixed. Only if insert Custom CSS.
I can not understand it difficult to fix in Elementor, so don’t have to add custom css?
it's a bug why Elementor won't fix it?
