### ISSUE TITLE
Fullscreen mobile popup cant be closed

### ISSUE THREAD

**Issue by Asicreativedude** [elementor/elementor#9880]
When making a fullscreen popup, it cant be closed with the close button / custom button as long as there are entrance / exit animations. 

Once they are changed to default everything works great.

**Comment by lior-sh** [comment]
Hi @Asicreativedude,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
