### ISSUE TITLE
Advanced Query Control - child categorie - no good hierarchy

### ISSUE THREAD

**Issue by NAROLLES** [elementor/elementor#9884]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I noticed a difference between the hierarchy of my child categories of wordpress and the hierarchy that appears in query control
of the post widget in elementor library
here is confusion between the child categories between term_taxonomy_id and term_id and parent
in the sql database - Table: wp_term_taxonomy

## Steps to reproduce

if i take the example category "term id 29041 audio format" its parent category is "term id 29040"
BUT
elementor in "query control" the category "term id 29041 audio format" has for "parent category"
the !!! **term_taxonomy_id** !!! 29040 Univers Jardinerie

of course the confusion depends on the existence of the same id number between the column "term id" and "term ttaxonomy id"
if there is not the same id number the problem is not seen

the problem is also visible in the display conditions of model library

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.21
	PHP Version: 7.3.12
	PHP Max Input Vars: 1000
	PHP Max Post Size: 24M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.1
	Site URL: https://www.jardinerie-animalerie-fleuriste.fr
	Home URL: https://www.jardinerie-animalerie-fleuriste.fr
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/%post_id%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

== Active Plugins ==
	.TUBE Video Curator
		Version: 1.1.9
		Author: .TUBE gTLD

	ACF Content Analysis for Yoast SEO
		Version: 2.3.0
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Admin Columns
		Version: 3.4.8
		Author: AdminColumns.com

	AdRotate Professional
		Version: 5.6.4
		Author: Arnan de Gans

	Advanced Custom Fields
		Version: 5.8.7
		Author: Elliot Condon

	Akismet Anti-Spam
		Version: 4.1.3
		Author: Automattic

	AMP
		Version: 1.4.1
		Author: AMP Project Contributors

	Async JavaScript
		Version: 2.19.07.14
		Author: Frank Goossens (futtta)

	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	BuddyPress
		Version: 5.1.0
		Author: The BuddyPress Community

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Classic Editor Addon
		Version: 2.6.0
		Author: <a href="https://so-wp.com">Pieter Bos</a>, <a href="https://gschoppe.com">Greg Schoppe</a>

	Default featured image
		Version: 1.6.1
		Author: Jan Willem Oostendorp

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Elementor
		Version: 2.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.3
		Author: Elementor.com

	Enable Media Replace
		Version: 3.3.7
		Author: ShortPixel

	Glue for Yoast SEO & AMP
		Version: 0.5
		Author: Joost de Valk

	Google Doc Embedder
		Version: 2.6.4
		Author: Kevin Davis, Dan Lester

	Imagify
		Version: 1.9.8.1
		Author: WP Media

	Login LockDown
		Version: v1.8.1
		Author: Michael VanDeMar

	MailPoet 3 (New)
		Version: 3.41.1
		Author: MailPoet

	MailPoet 3 Premium (New)
		Version: 3.0.75
		Author: MailPoet

	OneSignal Push Notifications
		Version: 1.17.9
		Author: OneSignal

	Public Post Preview
		Version: 2.9.0
		Author: Dominik Schilling

	Redirection
		Version: 4.5.1
		Author: John Godley

	Regenerate Thumbnails
		Version: 3.1.2
		Author: Alex Mills (Viper007Bond)

	TinyMCE Advanced
		Version: 5.3.0
		Author: Andrew Ozz

	WordPress Editorial Calendar
		Version: 3.7.5
		Author: Colin Vernon, Justin Evans, Joachim Kudish, Mary Vogt, and Zack Grossbart

	WordPress Popular Posts
		Version: 5.0.1
		Author: Hector Cabrera

	WP-Optimize - Clean, Compress, Cache
		Version: 3.0.14
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP-Polls
		Version: 2.75.3
		Author: Lester 'GaMerZ' Chan

	Yoast SEO
		Version: 12.7.1
		Author: Team Yoast

== Elements Usage ==
	
	archive : 7
		archive-posts : 1
		button : -49
		gallery : 1
		heading : -29
		nav-menu : -87
		posts : -30
		shortcode : 1
		tabs : 1
		template : -73
		text-editor : 1
		theme-archive-title : 1
		wp-widget-ajdg_bnnrwidgets : 1
		wp-widget-ajdg_grpwidgets : -174
	footer : 1
		heading : 1
		text-editor : 3
		theme-site-title : 1
	header : 2
		button : 1
		countdown : 1
		heading : 2
		nav-menu : 1
		search-form : 1
		theme-site-logo : 1
		theme-site-title : 1
	popup : 4
		button : 1
		heading : -11
		icon : 16
		image : 1
		nav-menu : 1
		posts : 1
		text-editor : 3
		theme-site-logo : 1
		toggle : 14
	section : 27
		animated-headline : 1
		author-box : 1
		button : -33
		call-to-action : 1
		divider : 2
		heading : -131
		image : 3
		nav-menu : 2
		post-info : 1
		posts : -37
		social-icons : 1
		tabs : 1
		text-editor : -116
	single : 8
		author-box : -13
		breadcrumbs : 1
		heading : -181
		menu-anchor : 1
		nav-menu : -75
		post-comments : 1
		post-info : -93
		posts : 1
		share-buttons : 1
		shortcode : -91
		spacer : 1
		template : -108
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 2
		wp-widget-ajdg_bnnrwidgets : -49
		wp-widget-ajdg_grpwidgets : -245
	wp-post : 139
		button : 10
		gallery : -19
		heading : 29
		image : 34
		image-gallery : 134
		menu-anchor : 1
		text-editor : 40
	wp-page : 24
		button : -942
		counter : 2
		flip-box : -79
		form : 1
		google_maps : 1
		heading : -160
		html : 2
		icon-box : 3
		icon-list : 1
		image : -1
		image-gallery : 6
		media-carousel : 1
		menu-anchor : -173
		nav-menu : -21
		posts : -344
		price-table : 3
		shortcode : 1
		slides : 2
		social-icons : 1
		testimonial-carousel : 1
		text-editor : 27
		toggle : 4
		video : 2
		wp-widget-ajdg_grpwidgets : -48

== Log ==
	
Log: showing 19 of 192019-09-16 11:32:17 [info] elementor::elementor_updater Started 
2019-09-16 11:32:17 [notice] Could not find Elementor/Upgrades - _v_2_7_0_rename_document_types_to_wp callback 
2019-09-16 11:32:17 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-16 11:32:17 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-16 11:32:17 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-16 11:32:17 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data callback needs to run again 
2019-09-16 11:32:17 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start (x2) 
2019-09-16 11:32:18 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-16 11:32:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.1',
  'to' => '2.7.2',
)]
2019-09-24 16:18:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-09-24 16:18:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.5',
  'to' => '2.7.0',
)]
2019-09-26 19:53:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.0',
  'to' => '2.7.1',
)]
2019-10-06 23:00:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.3',
  'to' => '2.7.4',
)]
2019-10-06 23:00:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.1',
  'to' => '2.7.2',
)]
2019-10-28 22:00:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-10-28 22:00:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-12-08 18:59:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.7.6',
)]
2019-12-10 09:27:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.6',
  'to' => '2.8.0',
)]
2019-12-11 23:44:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.0',
  'to' => '2.8.1',
)]

PHP: showing 8 of 8PHP: 2019-09-26 19:53:35 [warning X 1][/home/jardinerieanimal/public_html/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/home/jardinerieanimal/public_html/wp-content/uploads/elementor/css/post-461562.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-10 09:44:00 [notice X 88][/home/jardinerieanimal/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::384] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-22 16:12:53 [notice X 57][/home/jardinerieanimal/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::738] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-31 17:22:00 [notice X 101][/home/jardinerieanimal/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::841] Undefined property: WP_Error::$parent [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-01 19:17:22 [notice X 48][/home/jardinerieanimal/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-09 11:05:24 [notice X 11][/home/jardinerieanimal/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::727] Undefined index: filter_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-22 14:31:15 [notice X 1][/home/jardinerieanimal/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::688] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-11 23:52:21 [notice X 2565][/home/jardinerieanimal/public_html/wp-content/plugins/elementor/core/dynamic-tags/tag.php::45] Undefined index: after [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 15 of 15JS: 2019-10-04 07:18:32 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.3:32:132313] Cannot read property \'html\' of undefined 
JS: 2019-10-07 22:42:53 [error X 3][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:32:64106] this.ui.apply.add is not a function 
JS: 2019-10-13 10:58:12 [error X 41][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:2:46150] Cannot read property \'select2\' of undefined 
JS: 2019-10-13 10:58:13 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view107459\") has already been destroyed and cannot be used. 
JS: 2019-10-13 11:15:53 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view142259\") has already been destroyed and cannot be used. 
JS: 2019-10-13 11:16:16 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view143228\") has already been destroyed and cannot be used. 
JS: 2019-10-13 11:30:43 [error X 2][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:7:50317] Blocked a frame with origin \"https://www.jardinerie-animalerie-fleuriste.fr\" from accessing a cross-origin frame. 
JS: 2019-11-15 00:30:00 [error X 39][https://www.jardinerie-animalerie-fleuriste.fr/wp-includes/js/backbone.min.js?ver=1.4.0:1:3793] Cannot convert undefined or null to object 
JS: 2019-11-16 16:33:46 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view100561\") has already been destroyed and cannot be used. 
JS: 2019-11-17 12:35:35 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3288\") has already been destroyed and cannot be used. 
JS: 2019-11-17 13:45:24 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3213\") has already been destroyed and cannot be used. 
JS: 2019-11-18 11:32:03 [error X 8][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.7.3:2:45763] Cannot read property \'elementSettingsModel\' of undefined 
JS: 2019-11-19 19:27:50 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3777\") has already been destroyed and cannot be used. 
JS: 2019-11-19 19:38:14 [error X 1][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13031\") has already been destroyed and cannot be used. 
JS: 2019-11-28 11:36:07 [error X 3][https://www.jardinerie-animalerie-fleuriste.fr/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.5:2:39895] n.attributes[e.name].each is not a function

**Comment by NAROLLES** [comment]
@KingYes

**Comment by NAROLLES** [comment]
@danielkatz

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
