### ISSUE TITLE
🔗 🔃  🚀 Feature Request: Add Flip "Vertical" option to the Shape Divider options (Merged with #2729)

### ISSUE THREAD

**Issue by ScottKemp** [elementor/elementor#9887]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Sometimes a shape divider will look better with flipped vertically (Especially with Custom Shapes).

**Describe the solution you'd like**
I would like instead of just a Flip option (which is essentially a "Flip Horizontally") a "Flip Vertically" option as well.  Divi has this option and it is nice.

**Describe alternatives you've considered**
Custom CSS

**Additional context**

**Comment by glanglois** [comment]
I agree with Scott. 

Adding a "flip" tick box to change a horizontal divider to a vertical divider would be a great feature.

**Comment by shilo-ey** [comment]
I merged this issue with #2729, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
