### ISSUE TITLE
playsinline for videos still not there.

### ISSUE THREAD

**Issue by swatsqad** [elementor/elementor#9892]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
(marked as solved, however no)
- [X] The issue still exists against the latest stable version of Elementor.

The video element does not add the playsinline tag, and there is no option to add it. This breaks iOS autoplay on muted self-hosted videos.

## Steps to reproduce

1) add a muted and autoplaying video
2) notice how on iOS is big broken.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!
