### ISSUE TITLE
Global widgets are reverting to a default text in page edit mode

### ISSUE THREAD

**Issue by Tiffer777** [elementor/elementor#9895]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Hi, I was told this was a bug and to post in here.  I'm using Elementor Pro & OceanWP. When I logged in and went to edit a page. It seems all of my saved global widgets have reverted to a default. As an example, here is my heading, the image, and both headers don't show up. However, when I click to 'edit global widget' the real text is there. Right now when I view my live page, everything looks fine. However, since this just happened, I'm scared to save any new updates and don't want to continue to work in here until I know it's safe to save. Also, all of my WP, theme and plugins are all updated. Thanks for helping.

Screenshots:

This is what my header is suppose to look like: https://www.screencast.com/t/ye0jGi6tRe

This is what it actually looks like in the Elementor editor: https://www.screencast.com/t/WsiTW2QU

This is what my footer is suppose to look like: https://www.screencast.com/t/EfU3KfPMXVG

This is what it actually looks like in the editor: https://www.screencast.com/t/Kdwx6AwjgT

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.1.24
	PHP Max Input Vars: 1000
	PHP Max Post Size: 260M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.1
	Site URL: http://2019.riverscoalition.org
	Home URL: http://2019.riverscoalition.org
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.7.3
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

== Active Plugins ==
	Admin Columns
		Version: 3.4.8
		Author: AdminColumns.com

	Akismet Anti-Spam
		Version: 4.1.3
		Author: Automattic

	Download Manager
		Version: 3.0.5
		Author: W3 Eden

	Duplicate Page
		Version: 4.0
		Author: mndpsingh287

	Elementor
		Version: 2.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.3
		Author: Elementor.com

	Element Pack
		Version: 4.2.0
		Author: BdThemes

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	Ocean Extra
		Version: 1.5.19
		Author: OceanWP

	TablePress
		Version: 1.10
		Author: Tobias Bäthge

	WPForms Lite
		Version: 1.5.7
		Author: WPForms

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 1.5
		Author: Mike Hansen

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		global : 23
		heading : 1
		sidebar : 1
	section : 5
		global : -10
	single : 1
		divider : 1
		global : 23
		heading : 2
		post-info : 2
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-title : 1
	wp-post : 24
		accordion : 1
		animated-headline : 1
		bdt-advanced-button : 2
		bdt-advanced-heading : 1
		bdt-advanced-icon-box : 4
		bdt-animated-heading : 1
		bdt-document-viewer : 1
		bdt-flip-box : -1
		bdt-timeline : 1
		bdt-wp-forms : 1
		blockquote : 1
		divider : 2
		facebook-page : 2
		global : -256
		heading : -52
		icon : 1
		icon-list : -12
		image : 5
		image-box : 7
		nav-menu : 2
		posts : 1
		shortcode : 1
		sidebar : 1
		spacer : 7
		text-editor : 2
		video : 2

== Log ==
	
Log: showing 20 of 362019-07-29 12:28:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.6',
)]
2019-07-29 12:28:24 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-29 12:28:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.6',
)]
2019-07-29 12:28:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.11',
  'to' => '2.6.1',
)]
2019-08-08 22:01:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.6',
  'to' => '2.6.8',
)]
2019-08-08 22:02:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.1',
  'to' => '2.6.2',
)]
2019-08-22 01:14:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.2',
  'to' => '2.6.4',
)]
2019-09-17 12:52:40 [info] elementor::elementor_updater Started 
2019-09-17 12:52:40 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-17 12:52:40 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-17 12:52:40 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-17 12:52:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-09-17 12:52:41 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-17 12:52:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-09-17 12:55:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.4',
  'to' => '2.6.5',
)]
2019-10-15 21:48:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.2',
  'to' => '2.7.4',
)]
2019-10-15 21:49:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.5',
  'to' => '2.7.2',
)]
2019-10-31 20:41:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-10-31 20:42:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-12-15 11:56:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.1',
)]

JS: showing 5 of 5JS: 2019-06-27 14:52:41 [error X 1][http://2019.riverscoalition.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:83489] Cannot set property \'controls\' of undefined 
JS: 2019-06-30 13:10:16 [error X 2][http://2019.riverscoalition.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1857\") has already been destroyed and cannot be used. 
JS: 2019-07-02 17:12:23 [error X 6][http://2019.riverscoalition.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4679\") has already been destroyed and cannot be used. 
JS: 2019-07-02 19:47:23 [error X 1][http://2019.riverscoalition.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view961\") has already been destroyed and cannot be used. 
JS: 2019-11-07 14:20:36 [error X 3][http://2019.riverscoalition.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1994\") has already been destroyed and cannot be used. 

PHP: showing 2 of 2PHP: 2019-07-02 00:24:46 [notice X 4619][/home/riversco/2019.riverscoalition.org/wp-content/plugins/elementor-pro/plugin.php::332] Undefined property: Elementor\Editor::$notice_bar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-17 12:52:41 [warning X 4][/home2/riversco/2019.riverscoalition.org/wp-content/plugins/elementor/modules/usage/module.php::481] Division by zero [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by mohammadr3z** [comment]
Same Problem

**Comment by Tiffer777** [comment]
This was fixed with the last update for Elementor 2.8.2  
Yay!!!

**Comment by sabuz** [comment]
Same problem in custom widget, Elementor version is 2.9.7

**Comment by LeonSkrilec** [comment]
Same problem with Elementor 3.0.9. Custom global widget content is not rendering correctly in page preview view.

**Comment by Aviad-Herman** [comment]
Hello,
Is this still an issue or has it been solved in the latest versions of Elementor?

If the bug persists, we recently updated the infrastructure behind Global Widgets. The update is currently only available on Elementor's developer edition releases (https://elementor.com/blog/introducing-beta-developer-edition/). Could you see if the bug still happens on the developer release?

Important note: the developer releases should not be used on live sites

**Comment by Tiffer777** [comment]
Hi, problem is persisting. Just updated to latest Elementor 3.4.3 and Pro 3.4.1 and WP is also up to date.  This is what my global widgets look like on every one of my pages: https://www.screencast.com/t/ydkmokx696
If I click on one of them and simply select "edit" global widget button, then the content suddenly appears, so I click on "edit" for each one of them.  Save my page and close it.  I open it again and see the same thing, nothing there.

**Comment by Aviad-Herman** [comment]
I'm sorry to hear that.
Do you have any staging environment you can test if the next elementor developer release solves your problem?
You can also install it on the live site but that's a bit risky :-)

**Comment by Tiffer777** [comment]
Hi, I don't have any kind of staging environment setup. I'm just hoping at some point it gets resolved. It's pretty frustrating.  If you have any other ideas, post 'em!!  =) Thanks so much! Tiff

**Comment by havn** [comment]
Had this issue a few times in the past, yet today it suddenlu popped up again :(
Elementor Version 3.6.6, Elementor Pro Version 3.7.2.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
