### ISSUE TITLE
Allow for elements to be tied to the color picker list, to allow for more site-wide color changes.

### ISSUE THREAD

**Issue by FreerkLap** [elementor/elementor#9899]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The new color picker is amazing. Thank you for building software that changes an industry :)

**What problem is your feature request going to solve? Please describe.**
One thing I would love, is to have more choice in site-wide colors. Right now, we can choose 4 colors which are tied to things like buttons, titles, etc. But I would like more flexibility. It feels like the new color picker would be a great tool to add this to.

**Describe the solution you'd like**
Allow for the colors of elements to be 'locked' to a specific color slot in the Color Picker. For ex. if we had a bar of 10 colors (almost like a hotbar in roleplaying games, where you select spells, attacks, etc). Then, allow an element's color to be tied to one of these hotbar functions. This would make it possible to change the colors sidewide, and keep it all in unison.

**Describe alternatives you've considered**
I know I'm discribing what is basicly CSS without coding. But I believe this is exactly the point of Elementor. To make the most amazing UX in the webdesign world. So far, you guys have nailed it. It can only grow from here.

I look forward to hearing opinions. And apologies if this has come up before. I tried searching for it, but found null.

Rick

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
