### ISSUE TITLE
Not obvious how to delete or re-order saved colors

### ISSUE THREAD

**Issue by nepa** [elementor/elementor#9900]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The color picker allows users to save certain colors for later use. There is a plus button to add new colors. However, to delete or re-order existing colors, drag and drop has to be used. But this is not obvious, because there is no hint or tooltip.

**Describe the solution you'd like**
Add a small descriptive text or tooltip that explains, that there is a drag and drop action to delete or re-order colors.

**Describe alternatives you've considered**
Show a delete button permanently next to the plus button and enable it, as soon as a stored color has been selected. However, this still leaves re-ordering by drag and drop unobvious.

**Additional context**
![image](https://user-images.githubusercontent.com/772192/70982030-94c07900-20b6-11ea-96d4-a67454577145.png)

**Comment by shilo-ey** [comment]
Hi @nepa 

Thanks for your valuable feedback.

This feature was released after a long period of versions and usability tests. 
In the selected version, when you open the color picker for the first time, you will see the Delete area expanded by default, with the description "Drag to Delete"

After that, we don't want to waste precious area from the picker itself.

thanks
