### ISSUE TITLE
Amp

### ISSUE THREAD

**Issue by garteth** [elementor/elementor#9903]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The ability to have posts created using Elementor to utilize the AMP technology.

**Describe the solution you'd like**
Integrate AMP capabilities into Elementor.

**Describe alternatives you've considered**
None because none work.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
