### ISSUE TITLE
Copy and Paste Style Does not show in Editor in Elementor V2.8.2

### ISSUE THREAD

**Issue by sprad001** [elementor/elementor#9904]
This problem carries over from the Elementor V2.8. betas
 and V2.8.1.
When copying the attributes of a widget and pasting it into another one, the values get pasted but the change is not reflected on the widget in the editor, but when initiating a preview the change can be seen in the preview. See recording https://www.screencast.com/t/uROtZ5QB.
This test was done in Firefox but previously I have experienced the same in Chrome.
Also noticed some icon hover issue as in the video.
Prior to this test, I cleared the browser cache, rebuilt all the CSS where I could do that and did a hard browser reload.
[system-info-1.txt](https://github.com/elementor/elementor/files/3973263/system-info-1.txt)

**Comment by black-eye** [comment]
Had a similar problem - see my coments on the referenced thread.

**Comment by shilo-ey** [comment]
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

**Comment by sprad001** [comment]
Well, looks like it is a plugin that causes the problem in my case and that is the _Piotnet Addons For Elementor Pro_. The free version of it working fine but the paid pro version causes this Paste Style issue. The pro version need to use the free version in conjunction like with many other pro plugins.

**Comment by sprad001** [comment]
@webfocusdesign, I agree with you on its usefulness. I had to reactivate it because it is essential on the site I am working on.

**Comment by shilo-ey** [comment]
Thanks for your input, as for now I'm closing this issue.

If you encounter any other issue please feel free to open a new thread.

Thanks

**Comment by sprad001** [comment]
@webfocusdesign, the **_Piotnet Addons For Elementor Pro_** plugin developer contacted me and advised to disable **Custom Media Query Breakpoints** feature in its Settings Page.
Once disabled the Paste Style worked correctly. Obviously this is only a temporary measure and will have a permanent fix.

**Comment by sprad001** [comment]
I got a message from the _**Piotnet Addons For Elementor Pro**_ plugin developer and advised me to download from the member area the updated plugin and install it. It should be **V5.16.16 after installation**. You can reactivate the **Custom Media Query Breakpoints** feature in its Settings Page of the plugin if you disabled it before. The Copy and Paste Style will work now.
