### ISSUE TITLE
[Bug] Listen for Elementor form widget submissions?

### ISSUE THREAD

**Issue by leosolid** [elementor/elementor#9912]
Hi, the Elementor ticket email told me to post this here.

I have some JS that I want to execute after an Elementor form on the same page has  been submitted successfully.

To elaborate, I want the page to redirect after my script has executed and after the form is submitted to WP. If I add a redirect 'action after submit' then sometimes the page redirects before my script finishes running. On the other hand, if I redirect after my custom script using an 'onsubmit' listener, then sometimes the page redirects before the form is actually submitted to the WP server (especially on slow connections). If I can listen for when the form is actually sent to WP, then I can execute my script serially, ensuring both things happen before the redirect.

How can I listen for when the form was successfully submitted to WP?

**Comment by shilo-ey** [comment]
@tomaswisten 

The Elementor Pro form triggers a custom JavaScript event named `submit_success` so you can to your tracking or anything else you want on that event
```JS
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		// form has been submitted do your thing
	});
});
```

In addition, you can manually create your redirect in a new tab and trigger other JS actions:

```JS
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( '#FORM_ID_HERE' ).on('submit_success', function(){
		// form has been submitted
		window.open('YOUR URL', '_blank');
	});
});
``` 

Thanks.
