### ISSUE TITLE
Color picker - Saved colors not applying

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#9913]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I'm having problems with saved colors not applying when selected. Unfortunately i can't really describe the steps to reproduce this, because it's only happening from time to time.

When i select one of my saved colors, the color picker is indicating that the color is selected, but the color is not actually applied to the element. I need to click into the color spectrum and then reselect the saved color to get it working.

Again, it's only happening sometimes (but quite often) and i unfortunately can't pinpoint the steps to reproduce this, but there is definitely a bug somewhere. 

If someone is experiencing the same issue and knows how to consistently reproduce it, feel free to contribute.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] can reproduce this bug consistently using the steps above.

**Comment by jazir5** [comment]
I have had this same issue actually, i would save a color and then try to insert it, only for it to insert a different color

**Comment by shilo-ey** [comment]
It seems like you are experiencing JS errors that conflict with Elementor.

Check your console and create a detailed issue report (follow the guidelines please).

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists

Thanks
