### ISSUE TITLE
Feature Request: More Spacer Options

### ISSUE THREAD

**Issue by mskks64** [elementor/elementor#9914]
Really simple but should be easy request. Right now the spacer only does pixels. Vertical height and percentage would be a nice addition.  I typically use the custom css to do this but being built in would be nice!

**Comment by KoniKodes** [comment]
+1 - I too would love to see this.

**Comment by trickymast3r** [comment]
+1 for adding more units like rem em

**Comment by arielk** [comment]
Adding % unit to height will not work in most browsers so I am closing this issue.

Thanks
