### ISSUE TITLE
Feature Request: +/- on text blocks to increase/decrease text size.

### ISSUE THREAD

**Issue by puterdude** [elementor/elementor#9916]
**+/-** on text blocks to increase/decrease text size. 

**An increasing number of elderly people need larger text sizes.**

The font size change could only last while the text (block) was displayed.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
