### ISSUE TITLE
[Bug] New gallery widget style is broken since 2.8 update.

### ISSUE THREAD

**Issue by asafmoraz** [elementor/elementor#9925]
The new gallery widget "Aligned sideways" is broken after 2.8 update.

This is how it looks like after the update:

![Bug](https://user-images.githubusercontent.com/59032032/71121533-48c12180-21e7-11ea-9eef-ecb1151ceadf.JPG)

And this is how it looks like on version 2.7.6:

![Good](https://user-images.githubusercontent.com/59032032/71121572-60000f00-21e7-11ea-8f7c-7ec4d3f2eb6f.JPG)

Hope you can fix it asap.

Thanks.

**Comment by formulaclick** [comment]
Same problem here. Please fix it!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.2

Feel free to update

Thanks!

**Comment by asafmoraz** [comment]
Hi.

I don't have an update of Elementor Pro to 2.8.2 only for Elementor free version to 2.8.2 and if i update them both, i still suffer from this issue 😕

![Screenshot_20191222-111706](https://user-images.githubusercontent.com/59032032/71319902-03ce1100-24ad-11ea-9499-a5817b4e84da.png)

**Comment by asafmoraz** [comment]
Just checked again on elementor 2.8.2 and on elementor pro 2.8.2 and the issue hasn't been fixed 😬

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by asafmoraz** [comment]
Ok, i will do it.

Thanks.

**Comment by asafmoraz** [comment]
Hi.

Just letting you know that the problem has been solved. 
Apparently i had to delete all of the cache and for some reason my chrome browser history also.

formulaclick: i guess that it will solve your issue as well.

Thanks for your support.
