### ISSUE TITLE
Elementor Pro Popup Animation

### ISSUE THREAD

**Issue by Mululu** [elementor/elementor#9926]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

## Description

With the initial animation of a popup, the popup appears again very briefly at the end of the animation. It flashes again briefly before it finally disappears.

## Steps to reproduce

Popup mit einer Ausgangsanimation erstellen zum Beispiel Fade Out with 1 sec.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.15
	PHP Version: 7.3.12-1+0~20191128.49+debian9~1.gbp24559b
	PHP Max Input Vars: 1776
	PHP Max Post Size: 150M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.1
	Site URL: https://baam-bud.de
	Home URL: http://baam-bud.de
	WP Multisite: No
	Max Upload Size: 150 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Elementor
		Version: 2.8.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.3
		Author: Elementor.com

	Wetterwarner
		Version: 2.3.3
		Author: Tim Knigge

== Elements Usage ==
	
	header : 6
		nav-menu : 3
		theme-site-logo : 1
	popup : 1
		wp-widget-wetterwarner_widget : 1

**Comment by lior-sh** [comment]
@Mululu 
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
