### ISSUE TITLE
Error ACF URL Dynamic field » Notice: Undefined index: return_format in ../elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 56

### ISSUE THREAD

**Issue by gpmxman** [elementor/elementor#9929]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by iceflow19** [comment]
I've came across this bug several times too. To patch, I currently just move line 56 down into the file case in the switch case, since that's the only place that line is being used at.

**Comment by Dreamsreal7** [comment]
> I've came across this bug several times too. To patch, I currently just move line 56 down into the file case in the switch case, since that's the only place that line is being used at.

Could you kindly clarify the patch? I too have unfortunately ran into this error and a temporary fix would be ideal. Thanks in advance.

**Comment by manoj-identixweb** [comment]
This issue is showing to me also. Kindly suggest the temporary fix for this. I hope we got this issue resolved in the next update of Elementor.

**Comment by amindiary** [comment]
I have same issue
