### ISSUE TITLE
Give an example code to add skins to the elementor-hello-world widget

### ISSUE THREAD

**Issue by vovagabel** [elementor/elementor#9930]
The description on this page (https://code.elementor.com/methods/elementor-widget_base-_register_skins/) is not enough to understand.

There are no problems with adding controls and no other functions. I couldn't add skins, I couldn't find any detailed examples.

**Comment by shilo-ey** [comment]
Hi @vovagabel 

You mentioned our code referance site, you should use our developers site, with great docs and useful blog posts.

see here: https://developers.elementor.com/creating-a-new-widget/

thanks
