### ISSUE TITLE
[Feature request] option : Minimize TOC on Desktop by Default  too (not just Tablet/mobile)

### ISSUE THREAD

**Issue by OCpublishing** [elementor/elementor#9933]
Well I think the title is clear enough.
That would be very helpfull to have a TOC minimized BY DEFAULT on desktop too. If I understood right this is possible for tablet or mobile but not for desktop. Some users (as I do) will probably use it inside the content area.
So an option to have this TOC widget minimized on all viewport including desktop **by default** would be nice.

Thank you

**Comment by btward79** [comment]
I cannot agree more. One of the reasons we went with Elementor was this widget actually. Only to find out it’s not for desktop. Many of our pages have long table of contents, so we cannot use it as is. Elementor folks, please implement this one. Thank you.

**Comment by bstreet123456789** [comment]
+1

**Comment by mootyb** [comment]
+1

**Comment by joelcunha** [comment]
+1

**Comment by myBCN** [comment]
+1  It's been a year and a new major release. Cannot belive not more people are asking for this improvement. Are people not using this widget?

**Comment by danielelbar** [comment]
+1

**Comment by l3enito** [comment]
+1

**Comment by d19dotca** [comment]
Seems so strange that desktop isn't an option to minimize it on, almost like a total oversight on design of the widget. Hoping that's added soon. Should be an easy one.

**Comment by Noob86** [comment]
+1 👍🏼 for this request. Has anyone found a work around for this? Perhaps with PHP? Can’t believe that it’s still not implemented.

**Comment by Maxican** [comment]
+1
Yes please.

**Comment by TheRashad** [comment]
Add a HTML Element anywhere on the actual site. Paste in this code:

```
<script> 
jQuery(document).ready(function($) { 
var delay = 100; setTimeout(function() { 
$('.elementor-widget-table-of-contents').addClass('elementor-toc--collapsed');
 $('.elementor-toc__body').css('display', 'none'); }, delay); 
}); 
</script>
```

and you are fine! Works for me, so I hope it works for you too.

**Comment by Maxican** [comment]
@TheRashad Thank you very much, sir. Works like a charm. 👌🏽

**Comment by arnolduspt** [comment]
> 
> 
> Add a HTML Element anywhere on the actual site. Paste in this code:
> 
> ```
> <script> 
> jQuery(document).ready(function($) { 
> var delay = 100; setTimeout(function() { 
> $('.elementor-widget-table-of-contents').addClass('elementor-toc--collapsed');
>  $('.elementor-toc__body').css('display', 'none'); }, delay); 
> }); 
> </script>
> ```
> 
> and you are fine! Works for me, so I hope it works for you too.

Thankyou verry much:)

**Comment by Roro88** [comment]
awesom! works like a charm

**Comment by OCpublishing** [comment]
Well. 2 years soon and still unable to have minimized TOC on desktop too without user workaround...

Is it THAT difficult?

Please do something about it guys

Thanks in advance

**Comment by yswisa** [comment]
Please add me to the request, its very simple to do Elementor dev team

**Comment by aatu86** [comment]
Yes, it is crazy that Elementor hasn't addressed this yet, it would take them 10 minutes to fix it. The crude jQuery 'fix' above is not an ideal workaround, and presumably has a negative affect on CLS as well! As a temporary measure, you can use the TOC widget PowerPack (https://powerpackelements.com/elementor-widgets/table-of-content/), but that costs additional money and add even more codebase. It functions almost exactly the same as Elementor's built-in widget, it just has a desktop minimization setting.

**Comment by Januuus** [comment]
The table of content from Ultimate addons can be collapsed on desktop !

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!

**Comment by aatu86** [comment]
Glad this was finally addressed, but it still needs work.
- Most importantly, the TOC initially loads expanded then closes afterward. You can watch it happen, which can't be good for CLS. In comparison, the PowerPark TOC Widget (see my previous comment) loads closed and doesn't shift the lower elements around.
- At least in my case, the Header Title is now centered instead of left justified for some reason
- To expand the TOC, you have to click on the icon itself versus the entire header width

**Comment by aatu86** [comment]
@avivu @shilo-ey Any update on this? Is there another feature request thread where this was continued?

**Comment by nicholaszein** [comment]
Hello @aatu86,

thanks for the feedback! 🙏 

This issue was already closed. Please, submit a new [🚀 Feature Request](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=feature_request.yml), or a [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) so we can help you better. 

Thank you!
