### ISSUE TITLE
Help with Archive Posts Elementor

### ISSUE THREAD

**Issue by Ruben2600** [elementor/elementor#9934]
Hello ,

Can someone send a code for elementor **archive posts,** now many posts among each other, I want only 6 to be next to each other and no more

Can someone send me a CSS so that I can paste it into the code?

Thank you :)

**Comment by shilo-ey** [comment]
Hi @Ruben2600 

You don't need to use external code to do so, just use the Query control to select how many posts will be shown. see more here: https://docs.elementor.com/article/101-posts

or here: 
https://elementor.com/blog/introducing-advanced-query-control/

Thanks
