### ISSUE TITLE
Elementor outputs too much DIVs. Please make it cleaner

### ISSUE THREAD

**Issue by beposss** [elementor/elementor#9935]
Are all those DIVs really needed? Why other products can make the same thing with a cleaner code?

A large DOM tree can harm your page performance in multiple ways.

https://developers.google.com/web/tools/lighthouse/audits/dom-size

I really like your product. But while/instead of adding new features, please think also about make it clean, lean, and bloat free.

**Comment by shilo-ey** [comment]
I merged this issue with  #7351 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
