### ISSUE TITLE
[bug] post widget query - no manual selection of cpt and posts possible -> URGENT!

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#9936]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue especially exists against the latest stable version of Elementor.

lately having buildt up some complex sort of showing posts of cpts -> there i made use of manual selection of single dedicated posts within the query. THIS IS NO LONGER POSSIBLE!
interestingly nothing is broken so far, the former choosen posts still staying where they are ...
but there are no changes or new instances possible -> the 'manual selection' option within the query only shows pages, no posts, no cpts ...!

this must have been occured with 2.8 updates obviously, as the sites were produced and (one) went online shortly before.

sadly enough once again theres no chance for a roll back to pre 2.8 versions due to dependencies ... grrr.

## Steps to reproduce

try to find blog posts or cpts when choosing 'manual selection' within query options for posts widget ... ?????

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

<details>
<summary>System Info</summary>
not needed this time, as it worked a few days ago under exact same circumstances - the only change actually was the elementor update(s) !!!!!!!!!

</details>

**Comment by dasigna** [comment]
EDIT:
finally i managed to revert on site back zu pre 2.8 ... and astonishingly it doesnt work eighter any more.
a site with pre 2.8 i didnt update until now works as expected.

so obviously there are some changes to the database too with 2.8??

this is frustrating :(

**Comment by shilo-ey** [comment]
Hi @dasigna 
Thanks for reporting,

No DB changes were made in v2.8+, and no changes were made to the Query control.

It seems like other conflict you have with your custom code/other plugin

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to Hello theme (or other default WordPress theme).

And see if the issue still persists.

If this issue persists please contact our support for better troubleshooting.

thanks
