### ISSUE TITLE
[BUG] Link button on text editor

### ISSUE THREAD

**Issue by Zabriskie1973** [elementor/elementor#9937]
Hello,

The link button on text editor does not work anymore.
When we select a text to link, the little field under the text does not appears.
![Capture d’écran 2019-12-19 à 19 41 31](https://user-images.githubusercontent.com/59064963/71200092-ae6ce680-2297-11ea-97e6-e6be723a90a3.png)

**Comment by shilo-ey** [comment]
Hi @Zabriskie1973 

It seems like you altered the default TinyMCE editor with 3rd party addon which probably not supported.

If you'll disable it you will see that this works perfectly.

Other than that, next time please follow the guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without it we simply can't help.

Thanks.
