### ISSUE TITLE
Why you guys added static font size for Testimonial widget description text

### ISSUE THREAD

**Issue by Swapnildhanrale** [elementor/elementor#9939]
We need to check the issue with testimonial content font size default value issues shown in the screenshot below.
Screenshot Url - https://share.getcloudapp.com/kpudj70q

**Comment by shilo-ey** [comment]
Hi @Swapnildhanrale 

No one changed this property for over 3 years: https://github.com/elementor/elementor/blob/05f04fcac5c1c957f89c315988661125badd552b/assets/dev/scss/frontend/widgets/testimonial.scss#L9

If you don't want this size simply change it.

Thanks
