### ISSUE TITLE
Php code 

### ISSUE THREAD

**Issue by AbanobA** [elementor/elementor#9941]
Hi,  I am a developer and I love you’re plug-in I was looking for a way to put a php code in my page but haven’t found a way to do so on you’re plug-in widget please let me know if you have that feature or if you can add it to a later updates, thanks

**Comment by shilo-ey** [comment]
Hi @AbanobA 

Thanks for your feedback

You cannot add PHP code to Elementor, since this would pose a security risk for websites. You can create shortcodes that run PHP and add the shortcode to Elementor.

Other than that, you can use 3rd party plugin at your own risk.

Thanks
