### ISSUE TITLE
Time zone widget showing multiple times at different time zones

### ISSUE THREAD

**Issue by goodhead168** [elementor/elementor#9942]
Can anyone make a widget that enables user to show multiple times at different time zones in places like footer...
![times](https://user-images.githubusercontent.com/58589147/71238127-4c1af100-233e-11ea-8dfb-4103f06a0d6e.JPG)

**Comment by shilo-ey** [comment]
Hi @goodhead168 

Thanks for your feedback,

Elementor provides a well-documented API for this case.

You can use it to extend an existing widget or alternatively[ create a new one](https://developers.elementor.com/creating-a-new-widget/) with this functionality.

Other than that, you can use 3rd party plugins in this case.

Thanks
