### ISSUE TITLE
Disabling Resizable, Sortable and Draggable instances instead of Destroying them on editor mode switch

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#9944]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

All the resizable, sortable and draggable instances on the elements should ideally be disabled and re-enabled instead of destroying and re-initializing them every time the editor mode is switched to preview and back to edit. This would improve performance by quite a margin I believe.

Was there any specific intention behind the current approach of destroying them on editor mode switch instead of just disabling them?

**Comment by shilo-ey** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. 

If you, however, decide to write a patch for it, we'll gladly include it after some code review.

Thanks
