### ISSUE TITLE
[FEATURE REQUEST] Enable the Table of content widget to be minimized at page load for mobile and/or tablet and/or desktop

### ISSUE THREAD

**Issue by JohnMulderFrance** [elementor/elementor#9946]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Expand the useability of the new TOC widget:
Currently you are only able to minimize the widget on either mobile of tablet. I would really like it when i, am able to minimize it on mobile and/or tablet and/or desktop. This will add some more design opportunities.

**Comment by OCpublishing** [comment]
#9933 
Same

**Comment by AkhilAniyan** [comment]
I was also looking for the same. I'm using TOC within the content top position. It is good to make it minimized on desktop too!

**Comment by mononox** [comment]
+1

**Comment by markwalker92** [comment]
+1

**Comment by shilo-ey** [comment]
I merged this issue with #9933, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by wordxpression** [comment]
+ 1 Another vote for 'minimize on all devices'

**Comment by joelcunha** [comment]
+1

**Comment by l3enito** [comment]
+1

**Comment by kvh21** [comment]
+1
