### ISSUE TITLE
Nav Menu Widget Dropdown styling lost after Elementor Pro 2.8 upgrading [video link inside]

### ISSUE THREAD

**Issue by formulaclick** [elementor/elementor#9948]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After upgrading to Elementor Pro 2.8, Dropdown and Toggle Button related styles are lost if Breakpoint is selected as "none". Also on Style tab, "Dropdown" and "Toggle Button" sections are gone. Styles are back only if yo select Mobile or Tablet breakpoint.

**VIDEO LINK HERE**
https://streamable.com/n93ym

## Steps to reproduce

- Insert Nav Widget and select a menu that contains some submenus
- Select Mobile or Tablet Breakpoint
- Make some design for Dropdown and Toggle button under styles tab
- Select "None" as breakpoint
- Styles are gone and under styles tab related blocks are also gone

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/w4xq8dGR

**Comment by freelancesam** [comment]
I've found similar issues surrounding the nav widget

**Comment by riveso** [comment]
Hello. I also have the same problem, worse is that had this menu enabled on various sites and now I can not update.
Returning to version 2.7.3 the error does not occur.
Moving on to version 2.8.2 the burger menu disappears and everything is extended.
I have already moved on to support Elementor but they cannot reproduce there.

**Comment by formulaclick** [comment]
> Hello. I also have the same problem, worse is that had this menu enabled on various sites and now I can not update.
> Returning to version 2.7.3 the error does not occur.
> Moving on to version 2.8.2 the burger menu disappears and everything is extended.
> I have already moved on to support Elementor but they cannot reproduce there.

Exactly same here. And tested on other websites also. Please check attached video link @shilo-ey https://streamable.com/n93ym

**Comment by formulaclick** [comment]
@shilo-ey are you working on this? Any updates? Is the bug isolated? I have many websites using still 2.7 due to this issue

**Comment by oooh-boi** [comment]
Oh, that's interesting, it's a bug. Here's what shilo-ey replied to me 10 days before this issue is actually classified as a bug:

https://github.com/elementor/elementor/issues/10043

So, people who work with Elementor on a daily basis and "intercept" issues in the real case scenario should be treated like ignorants first until there's some sort of a critical mass created that makes you actually convinced about the problem. That's sooo lame guys in charge... shame on you.

**Comment by formulaclick** [comment]
This is no doubt a bug, and there is not a clear answer about it...
I have some websites with 2.8 and still problem persists. 

Example: I can't style this submenu because I don't want to have a breakpoint: https://pasteboard.co/IQZ5zbc.png

Please at least tell us you are working on it @shilo-ey...

**Comment by mice777** [comment]
I add my report to this bug (just was ahead to send new bug report, but discovered this issue).
I can style dropdown menu only if "mobile breakpoint" != "none". If it's set to "none", the dropdown submenu is drawn in plain white (ignoring my styling), even on desktop browser.
What's the logic here?

I want to set it to "none", show full menu even on mobile, and still want to style it.
Some developer screwed things pretty much, please try it and recover to working state.
Thanks. I pay you for support.


![image](https://user-images.githubusercontent.com/3145438/72839604-dda9b580-3c92-11ea-98a1-498f78a3993c.png)
This disappears and is ignored when above is set to none.
![image](https://user-images.githubusercontent.com/3145438/72839554-c7035e80-3c92-11ea-99b3-fe86fa6a66d4.png)

**Comment by notechup** [comment]
Still have this problem in Ele Pro 2.8.3...

**Comment by nickejp** [comment]
Same problem here.

**Comment by squadcar** [comment]
Was going to post a new issue, but I think it might be related to this. When using dropdown nav widget, if "primary headline" font-family has been set globally, it overrides the typography font-family at the widget level.
