### ISSUE TITLE
[BUG]Bullet Points Spacing Issue

### ISSUE THREAD

**Issue by 2b75e9u92b** [elementor/elementor#9949]
https://i.imgur.com/sP8ErZj.png
left use hello elementor theme , right use generatepress theme

**Comment by 2b75e9u92b** [comment]
Is anyone here?
hello elementor 1.0 themes no problem
hello elementor 2.2.1 something wrong
i don't know how solve the problem
help me...

**Comment by lior-sh** [comment]
Hi @2b75e9u92b,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
