### ISSUE TITLE
embed new color picker

### ISSUE THREAD

**Issue by franzarmas** [elementor/elementor#9953]
Hello, amazing Elementor team.

I am a Web developer a member of Elementor PRO and I have created many plugins and themes for elementor and I have seen that they have launched a new color picker recently, please I would like to indicate how to embed that color picker in the different parts of WordPress for example in the color fields within the WP Customizer and in the WP-Admin Metabox.

We want to replace the WP default color widget, with its Color Picker.

I look forward to technical, thank you very much.

**Comment by arielk** [comment]
The new color picker is based on this library, but cannot be expanded out of the box: https://github.com/Simonwep/pickr

If you want to extend it to an entire WP admin you need to develop some code for it.
