### ISSUE TITLE
A way to separate *products search results* and *posts/pages search results* in the Archive Template. 

### ISSUE THREAD

**Issue by purpleglow** [elementor/elementor#9956]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
You have a website with products and pages/posts. You search for "big". Archive Post widget returns both products and pages/posts in the same layout, all mixed. Products don't have an add to cart button and look like pages. 

**Describe the solution you'd like**
A way to separate products from pages/posts. For example, at a section at the top show only the products, and a section on the bottom show only the pages/posts. Products at the top can have the add to cart button, and pages can be nicely formatted too. 

**Describe alternatives you've considered**
At the moment you either have a) get only products in the search results, or b) settle for products + pages/posts being all mixed up. Yuck!

**Additional context**
Not needed. 

Thanks for considering.

**Comment by marceloaof** [comment]
Allowing the user to filter search results with dropdowns "products" and "pages/posts" on the search box is another absence on this area.

**Comment by KoniKodes** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/6226 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
