### ISSUE TITLE
Color picker bug even if color is set null/transparent. 

### ISSUE THREAD

**Issue by webangon** [elementor/elementor#9958]
Hi
I think previous color picker is better than new one. If color picker is transparent or not set updated value is set . Its always grey which is confusing . 

![Annotation 2019-12-21 104417](https://user-images.githubusercontent.com/7946657/71303158-eb8fc080-23de-11ea-9b98-22e1f7c458be.png)

**Comment by Creativenauts** [comment]
i cannot manually add a color to the picker

**Comment by lior-sh** [comment]
Hi @webangon,

Thanks for reporting, it's not a bug Color Picker is always set to the default color until you change. 
In addition, The icon of the Color picker always appears as transparent until you change it.
Thanks.
