### ISSUE TITLE
Thumbnails in Posts widget ignores WP SmartCrop focalpoint hinting

### ISSUE THREAD

**Issue by boabjohn** [elementor/elementor#9960]
(re-posted from the chat support: the problem is that Elementor Images respects SmartCrop focal point info, but the Elementor Posts widget does not)

The Elementor Posts widget is a way to view some selection of posts. The display of information from each post is configured in the widget. This includes the ability to include an image, set to a given size (several prebuilt options are provided, plus a custom option). This image cropping will be applied identically. The Posts widget merely grabs whatever featured image is
available and displays it according to those settings.

Of course this is good for some images, but not good for others. The featured image in each post is specific to the content...some content is best in portrait, some in landscape. The single global crop set in the Posts widget is certain to make some thumbnails look good while others do not.

The solution to this problem is to allow content editors to specify the focal point *on each image*, thus giving specific cropping hints to whatever presentation widget is actually rendering the image.

So, I have done this on our site. I used the tool called WP SmartCrop.

SmartCrop provides information on the desired cropping and passes this along to whatever process is going to render an image to the browser.

Your Image widget respects the SmartCrop hinting on the main post page
(see the automatic cropping at:
http://www.jamarr.org.au/storytree-gains-funding/ )

But the front page of the site (http://www.jamarr.org.au) shows the thumbnail cropped straight out of the middle.

/*Can you please check to see what is going on with the Posts Widget?
Why is it not reading the SmartCrop focal point info when it produces
thumbnails?*/

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
