### ISSUE TITLE
🔗 🚀 Feature Request: Addition of table creation widget in Elementer pro (Duplicate of #1342)

### ISSUE THREAD

**Issue by PrakashKumar0143** [elementor/elementor#9961]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.*when i am creating any website and using elementer pro to create any page or post for any blogger, they expect always how to add any table and which can be editable easily as the table feature is available. Since this feature is not there i need to install an extra plugin which my clients are getting frustrated for slowdown*

**Describe the solution you'd like*please add a table widget which can be also add or delete any number of row or column even sometime in any row might be number of columns can be varied which is possible later for user or editors or admin*

**Describe alternatives you've considered*I think this is the best solution*

**Additional context**

**Comment by PrakashKumar0143** [comment]
Hi support,
I have checked with somany website that after installation of elementer pro plugin the website is somewhat getting slow and now a days everyone need table widget to explain anything instead of an image. Due to this heavy load nobody getting interested to install an extra plugin for a single table design work. So my kind request you to add this feature in Elementer pro.

**Comment by rodolphebertozzo** [comment]
+1

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1342, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
