### ISSUE TITLE
A way to add a Search Bar (widget) to the Nav Menu widget. Showing a search bar on the mobile menu is essential. 

### ISSUE THREAD

**Issue by purpleglow** [elementor/elementor#9964]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A way to add a search field to the nav menu. We often have to rely on another plugin for the mobile menu because they offer a search bar option, and Elementor doesn't. 

**Describe the solution you'd like**
An option to add a search field to the Nav Menu. This is important for the mobile menu, but it would also be useful for desktop. 

**Describe alternatives you've considered**
We have to use other plugins for mobile menus since Elementor doesn't support that. 

**Additional context**
N/a.

**Comment by simonclay** [comment]
1+ Would very much like this option. 

I can add columns in nav or position the Search Widget inline, but what to do when responsive gets to mobile?

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/3275 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by romans1995** [comment]
is there any solution?

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
