### ISSUE TITLE
SEARCH FORM ELEMENT HAS A 1.618 EM MARGIN-BOTTOM

### ISSUE THREAD

**Issue by Javier-vega** [elementor/elementor#9969]
Hi!

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Using Storefront theme, it seems that the element Search Form has a 1.618 em margin-bottom, so I can not get it centered vertically as the rest of elements. There is no problem with Twenty Sixteen theme, or Twenty Twenty, only with Storefront

## Steps to reproduce

Just create a search form using Storefront theme

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.28
	PHP Version: 7.3.12
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://casita2.lacasitademimbre.com
	Home URL: https://casita2.lacasitademimbre.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Storefront Child
	Version: 1.0.0
	Author: Drimway
	Child Theme: Yes
	Parent Theme Name: Storefront
	Parent Theme Version: 2.5.3
	Parent Theme Author: Automattic

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

== Active Plugins ==
	Additional Variation Images Gallery for WooCommerce
		Version: 1.1.34
		Author: Emran Ahmed

	Booster for WooCommerce
		Version: 4.6.1
		Author: Algoritmika Ltd

	CMP - Coming Soon & Maintenance Plugin
		Version: 3.6.8
		Author: NiteoThemes

	Elementor
		Version: 2.8.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.1
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 1.9.15
		Author: Facebook

	Limit Login Attempts Reloaded
		Version: 2.10.0
		Author: WPChef

	LitExtension Customer Password Plugin
		Version: 1.0.0
		Author: LitExtension

	Mailchimp for WooCommerce
		Version: 2.3
		Author: Mailchimp

	Perfect WooCommerce Brands
		Version: 1.7.7
		Author: Alberto de Vera Sevilla

	Product Variation Swatches for Woocommerce
		Version: 1.0.4
		Author: ThemeHigh

	TI WooCommerce Wishlist Plugin
		Version: 1.15.4
		Author: TemplateInvaders

	WC - APG NIF/CIF/NIE Field
		Version: 1.4.0.1
		Author: Art Project Group

	WooCommerce
		Version: 3.8.1
		Author: Automattic

	WooCommerce Admin
		Version: 0.23.2
		Author: WooCommerce

	WooCommerce Multiple Customer Addresses
		Version: 16.3
		Author: Lagudi Domenico

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.18
		Author: WooCommerce

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.4.2
		Author: Ewout Fernhout

	WooCommerce Services
		Version: 1.22.2
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.3.1
		Author: WooCommerce

	Yoast SEO
		Version: 12.7.1
		Author: Team Yoast

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Elements Usage ==
	
	archive : 2
		archive-posts : 1
		breadcrumbs : 1
		heading : 1
	footer : 1
		form : 1
		global : 1
		heading : 2
		html : 1
		icon-list : 3
		image : 2
	header : 1
		button : 5
		global : 1
		icon-list : 1
		image : 1
		nav-menu : 1
		search-form : 1
		woocommerce-menu-cart : 1
	popup : 1
		heading : 1
		login : 1
		spacer : 1
	product : 1
		button : 1
		heading : 1
		share-buttons : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-product-upsell : 1
	section : 1
		form : 1
		global : 1
		heading : 6
		icon-box : 1
	wp-page : 6
		divider : 2
		form : 1
		heading : -63
		icon-box : 1
		image : 2
		image-carousel : 1
		image-gallery : 1
		shortcode : 2
		social-icons : 1
		testimonial-carousel : 1
		text-editor : 2
		wc-categories : 1
		woocommerce-menu-cart : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-products : 1
		wp-widget-media_gallery : 1
	product-archive : 1
		wc-archive-products : 1

== Log ==
	
JS: showing 12 of 12JS: 2019-12-07 13:32:25 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.7.5:2:46224] Cannot read property \'attributes\' of undefined 
JS: 2019-12-07 15:14:30 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view977\") has already been destroyed and cannot be used. 
JS: 2019-12-07 15:27:15 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view543\") has already been destroyed and cannot be used. 
JS: 2019-12-07 15:29:06 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view523\") has already been destroyed and cannot be used. 
JS: 2019-12-07 15:30:48 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view608\") has already been destroyed and cannot be used. 
JS: 2019-12-07 20:13:46 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view567\") has already been destroyed and cannot be used. 
JS: 2019-12-07 20:22:56 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view575\") has already been destroyed and cannot be used. 
JS: 2019-12-07 20:23:34 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view601\") has already been destroyed and cannot be used. 
JS: 2019-12-07 21:04:40 [error X 4][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view11399\") has already been destroyed and cannot be used. 
JS: 2019-12-08 18:08:20 [error X 4][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:64106] this.ui.apply.add is not a function 
JS: 2019-12-08 18:09:25 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:36787] Cannot read property \'0\' of undefined 
JS: 2019-12-17 12:15:54 [error X 1][https://casita2.lacasitademimbre.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.8.2:2:156871] Cannot read property \'map\' of undefined 

PHP: showing 3 of 3PHP: 2019-12-07 15:56:08 [notice X 1][/home/drimway/casita2.lacasitademimbre.com/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-07 21:37:31 [notice X 2][/home/drimway/casita2.lacasitademimbre.com/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::139] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-11 20:55:09 [notice X 53][/home/drimway/casita2.lacasitademimbre.com/wp-content/plugins/elementor/core/dynamic-tags/tag.php::45] Undefined index: after [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52019-12-09 19:09:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.7.6',
)]
2019-12-10 18:48:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.6',
  'to' => '2.8.0',
)]
2019-12-11 17:47:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.0',
  'to' => '2.8.1',
)]
2019-12-17 13:10:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2019-12-19 12:40:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.1',
)]
				
</details>
![margin-bottom](https://user-images.githubusercontent.com/59137766/71321431-7644ee00-24b9-11ea-860b-14d325730f06.png)

**Comment by shilo-ey** [comment]
Hi @Javier-vega 

This property is not related to Elementor, but to all of the `form` tags in Storefront theme.

You can override it by using:
```CSS
form.elementor-search-form {
    margin-bottom: 0;
}
```

Thanks
