### ISSUE TITLE
Icon Store bug

### ISSUE THREAD

**Issue by handrasl** [elementor/elementor#9970]
Hi!

When I use the icon store. I don't see icons. It isn't font awesome 4 issue. The icons are there, but not showing.
I think, a wrong css value is the problem.
The height of icon's container is 0 and overflow of icon's container is hidden.
When I change height value, the icons is showing.

I attached two images. 
[wrong](https://drive.google.com/open?id=196bvT2vDZT40tboo198nW2cblK-xCzXh)  | [good](https://drive.google.com/open?id=1qrsGUzQPwFV4wKXzSy27yuzbzVpef1qS)

Elementor version: 2.8.2 (free)
Wordperss version: 5.3.2

Best Regards: András

**Comment by bainternet** [comment]
@handrasl 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
