### ISSUE TITLE
Font Display Swap

### ISSUE THREAD

**Issue by JDSTIGER** [elementor/elementor#9982]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
PageSpeed Insights "Ensure text remains visible during webfont load" Fonts being loaded by Elementor such as the icons are causing a 1-second delay in load time.

**Describe the solution you'd like**
Adding `font-display: swap;` into the font calls.

**Describe alternatives you've considered**
I have added the code in myself but they were removed after the update. I don't want to keep manually adding the font display.

**Additional context**

**Comment by shilo-ey** [comment]
If you are using a custom font - you can do it yourself with Elementor: 
https://developers.elementor.com/elementor-pro-2-7-custom-fonts-font-display-support/

It doesn't have to be deleted on every update

Thanks

**Comment by JDSTIGER** [comment]
> If you are using a custom font - you can do it yourself with Elementor:
> https://developers.elementor.com/elementor-pro-2-7-custom-fonts-font-display-support/
> 
> It doesn't have to be deleted on every update
> 
> Thanks

I am not referring to custom fonts from Elementer Pro, I am referring to the bundled icons/fonts with Elementor, paths such as:

```
/elem/assets/lib/font-awesome/webfonts/fa-solid-900.woff2
/elem/assets/lib/eicons/fonts/eicons.woff2?5.5.0
```

**Comment by brandondithberry** [comment]
I also am wondering how to add font display values to the Elementor bundled icons.

**Comment by brandondithberry** [comment]
> If you are using a custom font - you can do it yourself with Elementor:
> https://developers.elementor.com/elementor-pro-2-7-custom-fonts-font-display-support/
> 
> It doesn't have to be deleted on every update
> 
> Thanks

You didn't answer the question then closed the issue before resolving it.

**Comment by jonathansoltero** [comment]
@brandondithberry I don't know why they closed it but I reopened one after talking with the support team about this being closed & the new one remains open: https://github.com/elementor/elementor/issues/10095

**Comment by sepidev** [comment]
This code may help. Provided by elementor.
```
add_action(‘elementor/frontend/after_register_styles’,function() {
foreach( [ ‘solid’, ‘regular’, ‘brands’ ] as $style ) {
wp_deregister_style( ‘elementor-icons-fa-‘ . $style );
}
}, 20 );
```
