### ISSUE TITLE
[Bug] - Elementor - Gallery Widget and Basic Gallery Widget isn't sliding the images

### ISSUE THREAD

**Issue by manoj-identixweb** [elementor/elementor#9989]
## Prerequisites

- [✓] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [✓] The issue still exists against the latest stable version of Elementor.

## Description
- I have found an issue with **Basic Gallery** and **Gallery** both widget is functioning the same but not sliding when clicking on navigation.
- When click on any image from the gallery listed, the first one image is opening only also when click on any images the first image is showing in the lightbox.
- I checked my console for an error and seen that the jQuery of elementor is conflicting.
- Here is the link to the screenshot of the error getting in the console. https://prnt.sc/qfgw8j

## Steps to reproduce
- Drag and drop the **Gallery** or **Basic Gallery** widget to the section.
- Enable lightbox option and link to the media.
- Reach to the page of front where this executing and click on the image. After clicking, get an image in popup. Then click on the navigation icon for navigate image.
- Click on the new image, it'll also show the first image.

## Isolating the problem

- [✓] This bug happens with only Elementor plugin active (and Elementor Pro).
- [✓] This bug happens with a default WordPress theme active.
- [✓] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* **Isolating the problem.**
* **System info.**
* **One issue per thread**

Without it we simply can't help.

We can't reproduce this issue.
In your case, it seems like a conflict with your theme/custom code/plugin.

Thanks.

**Comment by manoj-identixweb** [comment]
You can generate the issue by simply adding the **Basic Gallery** Widget.

**Comment by manoj-identixweb** [comment]
Hi Shilo,
Hope you are well.
I am getting the below error in console while testing with Inspect Element feature today.
https://prnt.sc/qkb737
Please take a look and let me know why gallery and basic gallery widgets are not working for me.
Looking forward to hearing your response.
Thanks in advance,
