### ISSUE TITLE
Add gradient to widgets

### ISSUE THREAD

**Issue by TheRollingPanda** [elementor/elementor#9995]
Hi guys,

Elementor allows us to use gradient on background, but not on the main widget, spacer or header for example, which allow us to use only one color.

I think it wouldn't be too complicated for the team to add gradient with 3 or 4 different color.

So far I've found a solution only for the header, and it needs the use of CSS code.

Hope I'm not the only one who wishes to add gradient color to the design of my website.

Cheers

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3142, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
